package com.guudint.clickargo.clictruck.jobupload.dto;

import java.util.Date;
import java.util.HashMap;

import org.apache.commons.lang3.StringUtils;
import org.apache.log4j.Logger;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.guudint.clickargo.clictruck.jobupload.model.TCkJobUpload;
import com.vcc.camelone.common.dto.AbstractDTO;

/**
 * TCkJobUpload generated by hbm2java
 */

public class CkJobUpload extends AbstractDTO<CkJobUpload, TCkJobUpload> {

	private static Logger log = Logger.getLogger(CkJobUpload.class);

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 1L;

	// Attributes
	/////////////
	private String upId;
	private String upAccnId;
	private String upFileName;
	private String upFilePath;
	private Integer upFileSize;
	private Integer upTotalLines;
	private String upSuccessJobIds;
	private String upFailLines;
	private String upRemark;
	private Character upStatus;
	private Date upDtCreate;
	private String upUidCreate;
	private Date upDtLupd;
	private String upUidLupd;
	
	@JsonIgnore
	ObjectMapper objectMapper = new ObjectMapper();

	public CkJobUpload() {
	}

	public CkJobUpload(String upId) {
		this.upId = upId;
	}

	public CkJobUpload(TCkJobUpload entity) {
		super(entity);
	}

	// Override Methods
	///////////////////

	@Override
	public int compareTo(CkJobUpload o) {
		return 0;
	}

	@Override
	public void init() {
	}

	// //////
	public int getTotalSuccessJobIds() {
		try {
			if (StringUtils.isNotBlank(upSuccessJobIds)) {
				@SuppressWarnings("unchecked")
				HashMap<String, String> successMap = objectMapper.readValue(upSuccessJobIds, HashMap.class);
				return successMap.size();
			}
		} catch (Exception e) {
			log.error(e.getMessage());
		}
		return 0;
	}
	public int getTotalFailJobIds() {
		try {
			if (StringUtils.isNotBlank(upFailLines)) {
				@SuppressWarnings("unchecked")
				HashMap<String, String> failMap = objectMapper.readValue(upFailLines, HashMap.class);
				return failMap.size();
			}
		} catch (Exception e) {
			log.error(e.getMessage());
		}
		return 0;
	}
	// //////

	public String getUpId() {
		return this.upId;
	}

	public void setUpId(String upId) {
		this.upId = upId;
	}

	public String getUpAccnId() {
		return this.upAccnId;
	}

	public void setUpAccnId(String upAccnId) {
		this.upAccnId = upAccnId;
	}

	public String getUpFileName() {
		return this.upFileName;
	}

	public void setUpFileName(String upFileName) {
		this.upFileName = upFileName;
	}

	public String getUpFilePath() {
		return this.upFilePath;
	}

	public void setUpFilePath(String upFilePath) {
		this.upFilePath = upFilePath;
	}

	public Integer getUpFileSize() {
		return this.upFileSize;
	}

	public void setUpFileSize(Integer upFileSize) {
		this.upFileSize = upFileSize;
	}

	public Integer getUpTotalLines() {
		return this.upTotalLines;
	}

	public void setUpTotalLines(Integer upTotalLines) {
		this.upTotalLines = upTotalLines;
	}

	public String getUpSuccessJobIds() {
		return this.upSuccessJobIds;
	}

	public void setUpSuccessJobIds(String upSuccessJobIds) {
		this.upSuccessJobIds = upSuccessJobIds;
	}

	public String getUpFailLines() {
		return this.upFailLines;
	}

	public void setUpFailLines(String upFailLines) {
		this.upFailLines = upFailLines;
	}

	public String getUpRemark() {
		return this.upRemark;
	}

	public void setUpRemark(String upRemark) {
		this.upRemark = upRemark;
	}

	public Character getUpStatus() {
		return this.upStatus;
	}

	public void setUpStatus(Character upStatus) {
		this.upStatus = upStatus;
	}

	public Date getUpDtCreate() {
		return this.upDtCreate;
	}

	public void setUpDtCreate(Date upDtCreate) {
		this.upDtCreate = upDtCreate;
	}

	public String getUpUidCreate() {
		return this.upUidCreate;
	}

	public void setUpUidCreate(String upUidCreate) {
		this.upUidCreate = upUidCreate;
	}

	public Date getUpDtLupd() {
		return this.upDtLupd;
	}

	public void setUpDtLupd(Date upDtLupd) {
		this.upDtLupd = upDtLupd;
	}

	public String getUpUidLupd() {
		return this.upUidLupd;
	}

	public void setUpUidLupd(String upUidLupd) {
		this.upUidLupd = upUidLupd;
	}

}
