//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.16 at 09:09:51 AM SGT 
//


package com.dsv.edi.xml.DSV_ShipmentMessage_v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DangerousGoodsDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DangerousGoodsDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DangerousGoods" type="{http://edi.dsv.com/XML/SharedElements_v1.xsd}DangerousGoods" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DangerousGoodsDetail", namespace = "http://edi.dsv.com/XML/Order_v1.xsd", propOrder = {
    "dangerousGoods"
})
public class DangerousGoodsDetail2 {

    @XmlElement(name = "DangerousGoods")
    protected DangerousGoods dangerousGoods;

    /**
     * Gets the value of the dangerousGoods property.
     * 
     * @return
     *     possible object is
     *     {@link DangerousGoods }
     *     
     */
    public DangerousGoods getDangerousGoods() {
        return dangerousGoods;
    }

    /**
     * Sets the value of the dangerousGoods property.
     * 
     * @param value
     *     allowed object is
     *     {@link DangerousGoods }
     *     
     */
    public void setDangerousGoods(DangerousGoods value) {
        this.dangerousGoods = value;
    }

}
