//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.16 at 09:09:51 AM SGT 
//


package com.dsv.edi.xml.DSV_ShipmentMessage_v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FreeText complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FreeText">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DescriptionCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TextLine1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TextLine2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TextLine3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TextLine4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TextLine5" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FreeText", propOrder = {
    "descriptionCode",
    "textLine1",
    "textLine2",
    "textLine3",
    "textLine4",
    "textLine5"
})
public class FreeText {

    @XmlElement(name = "DescriptionCode")
    protected String descriptionCode;
    @XmlElement(name = "TextLine1")
    protected String textLine1;
    @XmlElement(name = "TextLine2")
    protected String textLine2;
    @XmlElement(name = "TextLine3")
    protected String textLine3;
    @XmlElement(name = "TextLine4")
    protected String textLine4;
    @XmlElement(name = "TextLine5")
    protected String textLine5;
    @XmlAttribute(name = "Type", required = true)
    protected String type;

    /**
     * Gets the value of the descriptionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescriptionCode() {
        return descriptionCode;
    }

    /**
     * Sets the value of the descriptionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescriptionCode(String value) {
        this.descriptionCode = value;
    }

    /**
     * Gets the value of the textLine1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextLine1() {
        return textLine1;
    }

    /**
     * Sets the value of the textLine1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextLine1(String value) {
        this.textLine1 = value;
    }

    /**
     * Gets the value of the textLine2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextLine2() {
        return textLine2;
    }

    /**
     * Sets the value of the textLine2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextLine2(String value) {
        this.textLine2 = value;
    }

    /**
     * Gets the value of the textLine3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextLine3() {
        return textLine3;
    }

    /**
     * Sets the value of the textLine3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextLine3(String value) {
        this.textLine3 = value;
    }

    /**
     * Gets the value of the textLine4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextLine4() {
        return textLine4;
    }

    /**
     * Sets the value of the textLine4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextLine4(String value) {
        this.textLine4 = value;
    }

    /**
     * Gets the value of the textLine5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextLine5() {
        return textLine5;
    }

    /**
     * Sets the value of the textLine5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextLine5(String value) {
        this.textLine5 = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
