//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.16 at 09:09:51 AM SGT 
//


package com.dsv.edi.xml.DSV_ShipmentMessage_v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GoodsItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GoodsItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Item" type="{http://edi.dsv.com/XML/SharedElements_v1.xsd}Item" minOccurs="0"/>
 *         &lt;element name="HandlingInstructions" type="{http://edi.dsv.com/XML/Shipment_v1.xsd}HandlingInstructions" minOccurs="0"/>
 *         &lt;element name="TemperatureControl" type="{http://edi.dsv.com/XML/SharedElements_v1.xsd}TemperatureControl" minOccurs="0"/>
 *         &lt;element name="RangeDetails" type="{http://edi.dsv.com/XML/SharedElements_v1.xsd}RangeDetails" minOccurs="0"/>
 *         &lt;element name="Locations" type="{http://edi.dsv.com/XML/Shipment_v1.xsd}LocationList" minOccurs="0"/>
 *         &lt;element name="MonetaryAmounts" type="{http://edi.dsv.com/XML/Shipment_v1.xsd}MonetaryAmountList" minOccurs="0"/>
 *         &lt;element name="ProductIds" type="{http://edi.dsv.com/XML/Shipment_v1.xsd}ProductIdsList" minOccurs="0"/>
 *         &lt;element name="FreeTextData" type="{http://edi.dsv.com/XML/Shipment_v1.xsd}FreeTextList" minOccurs="0"/>
 *         &lt;element name="Measurements" type="{http://edi.dsv.com/XML/Shipment_v1.xsd}MeasurementsList" minOccurs="0"/>
 *         &lt;element name="Dimensions" type="{http://edi.dsv.com/XML/Shipment_v1.xsd}DimensionsList" minOccurs="0"/>
 *         &lt;element name="References" type="{http://edi.dsv.com/XML/Shipment_v1.xsd}ReferenceGroupList" minOccurs="0"/>
 *         &lt;element name="PackageIds" type="{http://edi.dsv.com/XML/Shipment_v1.xsd}PackageIds" minOccurs="0"/>
 *         &lt;element name="GoodsPlacementIds" type="{http://edi.dsv.com/XML/SharedElements_v1.xsd}GoodsPlacementIds" minOccurs="0"/>
 *         &lt;element name="DangerousGoodsDetails" type="{http://edi.dsv.com/XML/Shipment_v1.xsd}DangerousGoodsDetailList" minOccurs="0"/>
 *         &lt;element name="ContainerNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GoodsItem", namespace = "http://edi.dsv.com/XML/Shipment_v1.xsd", propOrder = {
    "item",
    "handlingInstructions",
    "temperatureControl",
    "rangeDetails",
    "locations",
    "monetaryAmounts",
    "productIds",
    "freeTextData",
    "measurements",
    "dimensions",
    "references",
    "packageIds",
    "goodsPlacementIds",
    "dangerousGoodsDetails",
    "containerNumber"
})
public class GoodsItem {

    @XmlElement(name = "Item")
    protected Item item;
    @XmlElement(name = "HandlingInstructions")
    protected HandlingInstructions handlingInstructions;
    @XmlElement(name = "TemperatureControl")
    protected TemperatureControl temperatureControl;
    @XmlElement(name = "RangeDetails")
    protected RangeDetails rangeDetails;
    @XmlElement(name = "Locations")
    protected LocationList locations;
    @XmlElement(name = "MonetaryAmounts")
    protected MonetaryAmountList monetaryAmounts;
    @XmlElement(name = "ProductIds")
    protected ProductIdsList productIds;
    @XmlElement(name = "FreeTextData")
    protected FreeTextList freeTextData;
    @XmlElement(name = "Measurements")
    protected MeasurementsList measurements;
    @XmlElement(name = "Dimensions")
    protected DimensionsList dimensions;
    @XmlElement(name = "References")
    protected ReferenceGroupList references;
    @XmlElement(name = "PackageIds")
    protected PackageIds packageIds;
    @XmlElement(name = "GoodsPlacementIds")
    protected GoodsPlacementIds goodsPlacementIds;
    @XmlElement(name = "DangerousGoodsDetails")
    protected DangerousGoodsDetailList dangerousGoodsDetails;
    @XmlElement(name = "ContainerNumber")
    protected String containerNumber;

    /**
     * Gets the value of the item property.
     * 
     * @return
     *     possible object is
     *     {@link Item }
     *     
     */
    public Item getItem() {
        return item;
    }

    /**
     * Sets the value of the item property.
     * 
     * @param value
     *     allowed object is
     *     {@link Item }
     *     
     */
    public void setItem(Item value) {
        this.item = value;
    }

    /**
     * Gets the value of the handlingInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link HandlingInstructions }
     *     
     */
    public HandlingInstructions getHandlingInstructions() {
        return handlingInstructions;
    }

    /**
     * Sets the value of the handlingInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link HandlingInstructions }
     *     
     */
    public void setHandlingInstructions(HandlingInstructions value) {
        this.handlingInstructions = value;
    }

    /**
     * Gets the value of the temperatureControl property.
     * 
     * @return
     *     possible object is
     *     {@link TemperatureControl }
     *     
     */
    public TemperatureControl getTemperatureControl() {
        return temperatureControl;
    }

    /**
     * Sets the value of the temperatureControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemperatureControl }
     *     
     */
    public void setTemperatureControl(TemperatureControl value) {
        this.temperatureControl = value;
    }

    /**
     * Gets the value of the rangeDetails property.
     * 
     * @return
     *     possible object is
     *     {@link RangeDetails }
     *     
     */
    public RangeDetails getRangeDetails() {
        return rangeDetails;
    }

    /**
     * Sets the value of the rangeDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link RangeDetails }
     *     
     */
    public void setRangeDetails(RangeDetails value) {
        this.rangeDetails = value;
    }

    /**
     * Gets the value of the locations property.
     * 
     * @return
     *     possible object is
     *     {@link LocationList }
     *     
     */
    public LocationList getLocations() {
        return locations;
    }

    /**
     * Sets the value of the locations property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationList }
     *     
     */
    public void setLocations(LocationList value) {
        this.locations = value;
    }

    /**
     * Gets the value of the monetaryAmounts property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryAmountList }
     *     
     */
    public MonetaryAmountList getMonetaryAmounts() {
        return monetaryAmounts;
    }

    /**
     * Sets the value of the monetaryAmounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryAmountList }
     *     
     */
    public void setMonetaryAmounts(MonetaryAmountList value) {
        this.monetaryAmounts = value;
    }

    /**
     * Gets the value of the productIds property.
     * 
     * @return
     *     possible object is
     *     {@link ProductIdsList }
     *     
     */
    public ProductIdsList getProductIds() {
        return productIds;
    }

    /**
     * Sets the value of the productIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductIdsList }
     *     
     */
    public void setProductIds(ProductIdsList value) {
        this.productIds = value;
    }

    /**
     * Gets the value of the freeTextData property.
     * 
     * @return
     *     possible object is
     *     {@link FreeTextList }
     *     
     */
    public FreeTextList getFreeTextData() {
        return freeTextData;
    }

    /**
     * Sets the value of the freeTextData property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreeTextList }
     *     
     */
    public void setFreeTextData(FreeTextList value) {
        this.freeTextData = value;
    }

    /**
     * Gets the value of the measurements property.
     * 
     * @return
     *     possible object is
     *     {@link MeasurementsList }
     *     
     */
    public MeasurementsList getMeasurements() {
        return measurements;
    }

    /**
     * Sets the value of the measurements property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasurementsList }
     *     
     */
    public void setMeasurements(MeasurementsList value) {
        this.measurements = value;
    }

    /**
     * Gets the value of the dimensions property.
     * 
     * @return
     *     possible object is
     *     {@link DimensionsList }
     *     
     */
    public DimensionsList getDimensions() {
        return dimensions;
    }

    /**
     * Sets the value of the dimensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link DimensionsList }
     *     
     */
    public void setDimensions(DimensionsList value) {
        this.dimensions = value;
    }

    /**
     * Gets the value of the references property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceGroupList }
     *     
     */
    public ReferenceGroupList getReferences() {
        return references;
    }

    /**
     * Sets the value of the references property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceGroupList }
     *     
     */
    public void setReferences(ReferenceGroupList value) {
        this.references = value;
    }

    /**
     * Gets the value of the packageIds property.
     * 
     * @return
     *     possible object is
     *     {@link PackageIds }
     *     
     */
    public PackageIds getPackageIds() {
        return packageIds;
    }

    /**
     * Sets the value of the packageIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackageIds }
     *     
     */
    public void setPackageIds(PackageIds value) {
        this.packageIds = value;
    }

    /**
     * Gets the value of the goodsPlacementIds property.
     * 
     * @return
     *     possible object is
     *     {@link GoodsPlacementIds }
     *     
     */
    public GoodsPlacementIds getGoodsPlacementIds() {
        return goodsPlacementIds;
    }

    /**
     * Sets the value of the goodsPlacementIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link GoodsPlacementIds }
     *     
     */
    public void setGoodsPlacementIds(GoodsPlacementIds value) {
        this.goodsPlacementIds = value;
    }

    /**
     * Gets the value of the dangerousGoodsDetails property.
     * 
     * @return
     *     possible object is
     *     {@link DangerousGoodsDetailList }
     *     
     */
    public DangerousGoodsDetailList getDangerousGoodsDetails() {
        return dangerousGoodsDetails;
    }

    /**
     * Sets the value of the dangerousGoodsDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link DangerousGoodsDetailList }
     *     
     */
    public void setDangerousGoodsDetails(DangerousGoodsDetailList value) {
        this.dangerousGoodsDetails = value;
    }

    /**
     * Gets the value of the containerNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContainerNumber() {
        return containerNumber;
    }

    /**
     * Sets the value of the containerNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContainerNumber(String value) {
        this.containerNumber = value;
    }

}
