//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.16 at 09:09:51 AM SGT 
//


package com.dsv.edi.xml.DSV_ShipmentMessage_v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GoodsItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GoodsItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Item" type="{http://edi.dsv.com/XML/SharedElements_v1.xsd}Item" minOccurs="0"/>
 *         &lt;element name="Measurements" type="{http://edi.dsv.com/XML/Order_v1.xsd}MeasurementsList" minOccurs="0"/>
 *         &lt;element name="Dimensions" type="{http://edi.dsv.com/XML/Order_v1.xsd}DimensionsList" minOccurs="0"/>
 *         &lt;element name="HandlingInstructions" type="{http://edi.dsv.com/XML/Order_v1.xsd}HandlingInstructions" minOccurs="0"/>
 *         &lt;element name="References" type="{http://edi.dsv.com/XML/Order_v1.xsd}ReferenceGroupList" minOccurs="0"/>
 *         &lt;element name="PackageIds" type="{http://edi.dsv.com/XML/Order_v1.xsd}PackageIds" minOccurs="0"/>
 *         &lt;element name="ContainerNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreeTextData" type="{http://edi.dsv.com/XML/Order_v1.xsd}FreeTextList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GoodsItem", namespace = "http://edi.dsv.com/XML/Order_v1.xsd", propOrder = {
    "item",
    "measurements",
    "dimensions",
    "handlingInstructions",
    "references",
    "packageIds",
    "containerNumber",
    "freeTextData"
})
public class GoodsItem2 {

    @XmlElement(name = "Item")
    protected Item item;
    @XmlElement(name = "Measurements")
    protected MeasurementsList2 measurements;
    @XmlElement(name = "Dimensions")
    protected DimensionsList2 dimensions;
    @XmlElement(name = "HandlingInstructions")
    protected HandlingInstructions2 handlingInstructions;
    @XmlElement(name = "References")
    protected ReferenceGroupList2 references;
    @XmlElement(name = "PackageIds")
    protected PackageIds2 packageIds;
    @XmlElement(name = "ContainerNumber")
    protected String containerNumber;
    @XmlElement(name = "FreeTextData")
    protected FreeTextList2 freeTextData;

    /**
     * Gets the value of the item property.
     * 
     * @return
     *     possible object is
     *     {@link Item }
     *     
     */
    public Item getItem() {
        return item;
    }

    /**
     * Sets the value of the item property.
     * 
     * @param value
     *     allowed object is
     *     {@link Item }
     *     
     */
    public void setItem(Item value) {
        this.item = value;
    }

    /**
     * Gets the value of the measurements property.
     * 
     * @return
     *     possible object is
     *     {@link MeasurementsList2 }
     *     
     */
    public MeasurementsList2 getMeasurements() {
        return measurements;
    }

    /**
     * Sets the value of the measurements property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasurementsList2 }
     *     
     */
    public void setMeasurements(MeasurementsList2 value) {
        this.measurements = value;
    }

    /**
     * Gets the value of the dimensions property.
     * 
     * @return
     *     possible object is
     *     {@link DimensionsList2 }
     *     
     */
    public DimensionsList2 getDimensions() {
        return dimensions;
    }

    /**
     * Sets the value of the dimensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link DimensionsList2 }
     *     
     */
    public void setDimensions(DimensionsList2 value) {
        this.dimensions = value;
    }

    /**
     * Gets the value of the handlingInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link HandlingInstructions2 }
     *     
     */
    public HandlingInstructions2 getHandlingInstructions() {
        return handlingInstructions;
    }

    /**
     * Sets the value of the handlingInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link HandlingInstructions2 }
     *     
     */
    public void setHandlingInstructions(HandlingInstructions2 value) {
        this.handlingInstructions = value;
    }

    /**
     * Gets the value of the references property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceGroupList2 }
     *     
     */
    public ReferenceGroupList2 getReferences() {
        return references;
    }

    /**
     * Sets the value of the references property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceGroupList2 }
     *     
     */
    public void setReferences(ReferenceGroupList2 value) {
        this.references = value;
    }

    /**
     * Gets the value of the packageIds property.
     * 
     * @return
     *     possible object is
     *     {@link PackageIds2 }
     *     
     */
    public PackageIds2 getPackageIds() {
        return packageIds;
    }

    /**
     * Sets the value of the packageIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackageIds2 }
     *     
     */
    public void setPackageIds(PackageIds2 value) {
        this.packageIds = value;
    }

    /**
     * Gets the value of the containerNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContainerNumber() {
        return containerNumber;
    }

    /**
     * Sets the value of the containerNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContainerNumber(String value) {
        this.containerNumber = value;
    }

    /**
     * Gets the value of the freeTextData property.
     * 
     * @return
     *     possible object is
     *     {@link FreeTextList2 }
     *     
     */
    public FreeTextList2 getFreeTextData() {
        return freeTextData;
    }

    /**
     * Sets the value of the freeTextData property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreeTextList2 }
     *     
     */
    public void setFreeTextData(FreeTextList2 value) {
        this.freeTextData = value;
    }

}
