//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.16 at 09:09:51 AM SGT 
//


package com.dsv.edi.xml.DSV_ShipmentMessage_v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PackageIds complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PackageIds">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PackageId" type="{http://edi.dsv.com/XML/SharedElements_v1.xsd}PackageId" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="References" type="{http://edi.dsv.com/XML/Shipment_v1.xsd}ReferenceGroupList" minOccurs="0"/>
 *         &lt;element name="Dates" type="{http://edi.dsv.com/XML/Shipment_v1.xsd}DateList" minOccurs="0"/>
 *         &lt;element name="GoodsIdentities" type="{http://edi.dsv.com/XML/SharedElements_v1.xsd}GoodsIdentity" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PackageIds", namespace = "http://edi.dsv.com/XML/Shipment_v1.xsd", propOrder = {
    "packageId",
    "references",
    "dates",
    "goodsIdentities"
})
public class PackageIds {

    @XmlElement(name = "PackageId")
    protected List<PackageId> packageId;
    @XmlElement(name = "References")
    protected ReferenceGroupList references;
    @XmlElement(name = "Dates")
    protected DateList dates;
    @XmlElement(name = "GoodsIdentities")
    protected List<GoodsIdentity> goodsIdentities;

    /**
     * Gets the value of the packageId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the packageId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPackageId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PackageId }
     * 
     * 
     */
    public List<PackageId> getPackageId() {
        if (packageId == null) {
            packageId = new ArrayList<PackageId>();
        }
        return this.packageId;
    }

    /**
     * Gets the value of the references property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceGroupList }
     *     
     */
    public ReferenceGroupList getReferences() {
        return references;
    }

    /**
     * Sets the value of the references property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceGroupList }
     *     
     */
    public void setReferences(ReferenceGroupList value) {
        this.references = value;
    }

    /**
     * Gets the value of the dates property.
     * 
     * @return
     *     possible object is
     *     {@link DateList }
     *     
     */
    public DateList getDates() {
        return dates;
    }

    /**
     * Sets the value of the dates property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateList }
     *     
     */
    public void setDates(DateList value) {
        this.dates = value;
    }

    /**
     * Gets the value of the goodsIdentities property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the goodsIdentities property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGoodsIdentities().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GoodsIdentity }
     * 
     * 
     */
    public List<GoodsIdentity> getGoodsIdentities() {
        if (goodsIdentities == null) {
            goodsIdentities = new ArrayList<GoodsIdentity>();
        }
        return this.goodsIdentities;
    }

}
