//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.16 at 09:09:51 AM SGT 
//


package com.dsv.edi.xml.DSV_ShipmentMessage_v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Seal complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Seal">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SealId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SealParty" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Seal", propOrder = {
    "sealId",
    "sealParty"
})
public class Seal {

    @XmlElement(name = "SealId")
    protected String sealId;
    @XmlElement(name = "SealParty")
    protected String sealParty;

    /**
     * Gets the value of the sealId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSealId() {
        return sealId;
    }

    /**
     * Sets the value of the sealId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSealId(String value) {
        this.sealId = value;
    }

    /**
     * Gets the value of the sealParty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSealParty() {
        return sealParty;
    }

    /**
     * Sets the value of the sealParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSealParty(String value) {
        this.sealParty = value;
    }

}
