//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.16 at 09:09:51 AM SGT 
//


package com.dsv.edi.xml.DSV_ShipmentMessage_v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransportStage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransportStage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Stage" type="{http://edi.dsv.com/XML/SharedElements_v1.xsd}Stage" minOccurs="0"/>
 *         &lt;element name="Dates" type="{http://edi.dsv.com/XML/Shipment_v1.xsd}DateList" minOccurs="0"/>
 *         &lt;element name="Locations" type="{http://edi.dsv.com/XML/Shipment_v1.xsd}LocationList" minOccurs="0"/>
 *         &lt;element name="References" type="{http://edi.dsv.com/XML/Shipment_v1.xsd}ReferenceGroupList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransportStage", namespace = "http://edi.dsv.com/XML/Shipment_v1.xsd", propOrder = {
    "stage",
    "dates",
    "locations",
    "references"
})
public class TransportStage {

    @XmlElement(name = "Stage")
    protected Stage stage;
    @XmlElement(name = "Dates")
    protected DateList dates;
    @XmlElement(name = "Locations")
    protected LocationList locations;
    @XmlElement(name = "References")
    protected ReferenceGroupList references;

    /**
     * Gets the value of the stage property.
     * 
     * @return
     *     possible object is
     *     {@link Stage }
     *     
     */
    public Stage getStage() {
        return stage;
    }

    /**
     * Sets the value of the stage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stage }
     *     
     */
    public void setStage(Stage value) {
        this.stage = value;
    }

    /**
     * Gets the value of the dates property.
     * 
     * @return
     *     possible object is
     *     {@link DateList }
     *     
     */
    public DateList getDates() {
        return dates;
    }

    /**
     * Sets the value of the dates property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateList }
     *     
     */
    public void setDates(DateList value) {
        this.dates = value;
    }

    /**
     * Gets the value of the locations property.
     * 
     * @return
     *     possible object is
     *     {@link LocationList }
     *     
     */
    public LocationList getLocations() {
        return locations;
    }

    /**
     * Sets the value of the locations property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationList }
     *     
     */
    public void setLocations(LocationList value) {
        this.locations = value;
    }

    /**
     * Gets the value of the references property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceGroupList }
     *     
     */
    public ReferenceGroupList getReferences() {
        return references;
    }

    /**
     * Sets the value of the references property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceGroupList }
     *     
     */
    public void setReferences(ReferenceGroupList value) {
        this.references = value;
    }

}
