package com.guudint.clickargo.clictruck.sage.model;
// Generated 16 Jun 2023, 11:42:54 am by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtSageTax generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_SAGE_TAX")
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
public class TCkCtSageTax extends COAbstractEntity<TCkCtSageTax> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -1L;

	// Attributes
	/////////////
	private String stId;
	private String stPrefix;
	private long stRangeBegin;
	private long stRangeEnd;
	private long stRangeCurrent;
	private String stRangeFormat;
	private Character stStatus; // E: expired, A: active
	private Date stDtCreate;
	private String stUidCreate;
	private Date stDtLupd;
	private String stUidLupd;

	// Constructors
	///////////////
	public TCkCtSageTax() {
	}

	public TCkCtSageTax(String stId, String stPrefix, long stRangeBegin, long stRangeEnd, long stRangeCurrent) {
		this.stId = stId;
		this.stPrefix = stPrefix;
		this.stRangeBegin = stRangeBegin;
		this.stRangeEnd = stRangeEnd;
		this.stRangeCurrent = stRangeCurrent;
	}

	public TCkCtSageTax(String stId, String stPrefix, long stRangeBegin, long stRangeEnd, long stRangeCurrent,
			Character stStatus, Date stDtCreate, String stUidCreate, Date stDtLupd, String stUidLupd) {
		this.stId = stId;
		this.stPrefix = stPrefix;
		this.stRangeBegin = stRangeBegin;
		this.stRangeEnd = stRangeEnd;
		this.stRangeCurrent = stRangeCurrent;
		this.stStatus = stStatus;
		this.stDtCreate = stDtCreate;
		this.stUidCreate = stUidCreate;
		this.stDtLupd = stDtLupd;
		this.stUidLupd = stUidLupd;
	}



	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkCtSageTax arg0) {
		return 0;
	}

	@Override
	public void init() {

	}
	@Id

	@Column(name = "ST_ID", unique = true, nullable = false, length = 35)
	public String getStId() {
		return this.stId;
	}

	public void setStId(String stId) {
		this.stId = stId;
	}

	@Column(name = "ST_PREFIX", nullable = false, length = 35)
	public String getStPrefix() {
		return this.stPrefix;
	}

	public void setStPrefix(String stPrefix) {
		this.stPrefix = stPrefix;
	}

	@Column(name = "ST_RANGE_BEGIN", nullable = false)
	public long getStRangeBegin() {
		return this.stRangeBegin;
	}

	public void setStRangeBegin(long stRangeBegin) {
		this.stRangeBegin = stRangeBegin;
	}

	@Column(name = "ST_RANGE_END", nullable = false)
	public long getStRangeEnd() {
		return this.stRangeEnd;
	}

	public void setStRangeEnd(long stRangeEnd) {
		this.stRangeEnd = stRangeEnd;
	}

	@Column(name = "ST_RANGE_CURRENT", nullable = false)
	public long getStRangeCurrent() {
		return this.stRangeCurrent;
	}

	public void setStRangeCurrent(long stRangeCurrent) {
		this.stRangeCurrent = stRangeCurrent;
	}

	@Column(name = "ST_RANGE_FORMAT", nullable = false)
	public String getStRangeFormat() {
		return this.stRangeFormat;
	}

	public void setStRangeFormat(String stRangeFormat) {
		this.stRangeFormat = stRangeFormat;
	}

	@Column(name = "ST_STATUS", length = 1)
	public Character getStStatus() {
		return this.stStatus;
	}

	public void setStStatus(Character stStatus) {
		this.stStatus = stStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ST_DT_CREATE", length = 19)
	public Date getStDtCreate() {
		return this.stDtCreate;
	}

	public void setStDtCreate(Date stDtCreate) {
		this.stDtCreate = stDtCreate;
	}

	@Column(name = "ST_UID_CREATE", length = 35)
	public String getStUidCreate() {
		return this.stUidCreate;
	}

	public void setStUidCreate(String stUidCreate) {
		this.stUidCreate = stUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ST_DT_LUPD", length = 19)
	public Date getStDtLupd() {
		return this.stDtLupd;
	}

	public void setStDtLupd(Date stDtLupd) {
		this.stDtLupd = stDtLupd;
	}

	@Column(name = "ST_UID_LUPD", length = 35)
	public String getStUidLupd() {
		return this.stUidLupd;
	}

	public void setStUidLupd(String stUidLupd) {
		this.stUidLupd = stUidLupd;
	}

	@Override
	public boolean equals(Object obj) {
		if(obj == null) {
			return false;
		}
		TCkCtSageTax tCkCtSageTax = (TCkCtSageTax) obj;
		return tCkCtSageTax.getStId().equals(this.getStId());
	}
}
