package com.guudint.clickargo.clictruck.sage.model;
// Generated 15 Jun 2023, 4:49:30 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtSage generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_SAGE")
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
public class TCkCtSage extends COAbstractEntity<TCkCtSage> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -1L;
	public static final String PREFIX_ID = "SAGE";

	// Attributes
	/////////////

	private String sageId;
	private String sageBatchNo;
	private String sageFileLoc;
	private Date sageDtStart;
	private Date sageDtEnd;

	private Character sageStatus; 
	private Date sageDtCreate;
	private String sageUidCreate;
	private Date sageDtLupd;
	private String sageUidLupd;


	// Constructors
	///////////////
	public TCkCtSage() {
	}

	public TCkCtSage(String sageId, String sageBatchNo, String sageFileLoc, Date sageDtStart, Date sageDtEnd) {
		this.sageId = sageId;
		this.sageBatchNo = sageBatchNo;
		this.sageFileLoc = sageFileLoc;
		this.sageDtStart = sageDtStart;
		this.sageDtEnd = sageDtEnd;
	}


	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkCtSage arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

	@Id

	@Column(name = "SAGE_ID", unique = true, nullable = false, length = 35)
	public String getSageId() {
		return this.sageId;
	}

	public void setSageId(String sageId) {
		this.sageId = sageId;
	}

	@Column(name = "SAGE_BATCH_NO", nullable = false, length = 19)
	public String getSageBatchNo() {
		return this.sageBatchNo;
	}

	public void setSageBatchNo(String sageBatchNo) {
		this.sageBatchNo = sageBatchNo;
	}

	@Column(name = "SAGE_FILE_LOC", nullable = false, length = 19)
	public String getSageFileLoc() {
		return this.sageFileLoc;
	}

	public void setSageFileLoc(String sageFileLoc) {
		this.sageFileLoc = sageFileLoc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SAGE_DT_START", nullable = false, length = 19)
	public Date getSageDtStart() {
		return this.sageDtStart;
	}

	public void setSageDtStart(Date sageDtStart) {
		this.sageDtStart = sageDtStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SAGE_DT_END", nullable = false, length = 19)
	public Date getSageDtEnd() {
		return this.sageDtEnd;
	}

	public void setSageDtEnd(Date sageDtEnd) {
		this.sageDtEnd = sageDtEnd;
	}


	@Column(name = "SAGE_STATUS", length = 1)
	public Character getSageStatus() {
		return sageStatus;
	}

	public void setSageStatus(Character sageStatus) {
		this.sageStatus = sageStatus;
	}
	

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SAGE_DT_CREATE", length = 19)
	public Date getSageDtCreate() {
		return this.sageDtCreate;
	}

	public void setSageDtCreate(Date sageDtCreate) {
		this.sageDtCreate = sageDtCreate;
	}

	@Column(name = "SAGE_UID_CREATE", length = 35)
	public String getSageUidCreate() {
		return this.sageUidCreate;
	}

	public void setSageUidCreate(String sageUidCreate) {
		this.sageUidCreate = sageUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SAGE_DT_LUPD", length = 19)
	public Date getSageDtLupd() {
		return this.sageDtLupd;
	}

	public void setSageDtLupd(Date sageDtLupd) {
		this.sageDtLupd = sageDtLupd;
	}

	@Column(name = "SAGE_UID_LUPD", length = 35)
	public String getSageUidLupd() {
		return this.sageUidLupd;
	}

	public void setSageUidLupd(String sageUidLupd) {
		this.sageUidLupd = sageUidLupd;
	}

}
