package com.guudint.clickargo.clictruck.sage.model;
// Generated 3 Aug 2023, 7:23:57 pm by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VSageBookingId generated by hbm2java
 */
@Embeddable
public class VCkSageBookingId implements java.io.Serializable {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -1L;
	
	private String typeId;
	private String sageId;
	private String docNo;

	public VCkSageBookingId() {
	}



	@Column(name = "TYPE_ID", nullable = false, length = 8)
	public String getTypeId() {
		return this.typeId;
	}

	public void setTypeId(String typeId) {
		this.typeId = typeId;
	}

	@Column(name = "SAGE_ID", length = 256)
	public String getSageId() {
		return this.sageId;
	}

	public void setSageId(String sageId) {
		this.sageId = sageId;
	}

	@Column(name = "DOC_NO", nullable = false, length = 256)
	public String getDocNo() {
		return this.docNo;
	}

	public void setDocNo(String docNo) {
		this.docNo = docNo;
	}

}
