package com.guudint.clickargo.clictruck.sage.model;
// Generated 3 Aug 2023, 7:23:57 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * VSageBooking generated by hbm2java
 */
@Entity
@Table(name = "V_CK_SAGE_BOOKING")
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
public class VCkSageBooking extends COAbstractEntity<VCkSageBooking> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -1L;

	private VCkSageBookingId id;
	
	private String service;
	private String sageType;
	private String reference;
	private String datetime;
	//private String typeId;
	//private String sageId;
	private String tranType;
	//private String docNo;
	private String issuedDate;
	private String ccy;
	private Long amount;
	private Long vat;
	private Long duty;
	private String terms;
	private String taxNo;
	private Long total;
	private Date rcdDtBillApproved;


	// Constructors
	///////////////
	public VCkSageBooking() {
	}

	
	// Override Methods
	///////////////////
	@Override
	public int compareTo(VCkSageBooking arg0) {
		return 0;
	}

	@Override
	public void init() {

	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "typeId", column = @Column(name = "TYPE_ID", nullable = false, length = 8)),
			@AttributeOverride(name = "sageId", column = @Column(name = "SAGE_ID", length = 256)),
			@AttributeOverride(name = "docNo", column = @Column(name = "DOC_NO", nullable = false, length = 256))})
	public VCkSageBookingId getId() {
		return this.id;
	}

	public void setId(VCkSageBookingId id) {
		this.id = id;
	}

	
	@Column(name = "SERVICE", nullable = false, length = 9)
	public String getService() {
		return this.service;
	}

	public void setService(String service) {
		this.service = service;
	}

	@Column(name = "SAGE_TYPE", nullable = false, length = 4)
	public String getSageType() {
		return this.sageType;
	}

	public void setSageType(String sageType) {
		this.sageType = sageType;
	}

	@Column(name = "REFERENCE", nullable = false, length = 35)
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	@Column(name = "DATETIME", length = 19)
	public String getDatetime() {
		return this.datetime;
	}

	public void setDatetime(String datetime) {
		this.datetime = datetime;
	}

	@Column(name = "TRAN_TYPE", nullable = false, length = 9)
	public String getTranType() {
		return this.tranType;
	}

	public void setTranType(String tranType) {
		this.tranType = tranType;
	}

	@Column(name = "ISSUED_DATE", length = 10)
	public String getIssuedDate() {
		return this.issuedDate;
	}

	public void setIssuedDate(String issuedDate) {
		this.issuedDate = issuedDate;
	}

	@Column(name = "CCY", nullable = false, length = 3)
	public String getCcy() {
		return this.ccy;
	}

	public void setCcy(String ccy) {
		this.ccy = ccy;
	}

	@Column(name = "AMOUNT", precision = 14, scale = 0)
	public Long getAmount() {
		return this.amount;
	}

	public void setAmount(Long amount) {
		this.amount = amount;
	}

	@Column(name = "VAT", precision = 14, scale = 0)
	public Long getVat() {
		return this.vat;
	}

	public void setVat(Long vat) {
		this.vat = vat;
	}

	@Column(name = "DUTY", precision = 14, scale = 0)
	public Long getDuty() {
		return this.duty;
	}

	public void setDuty(Long duty) {
		this.duty = duty;
	}

	@Column(name = "TERMS", length = 10)
	public String getTerms() {
		return this.terms;
	}

	public void setTerms(String terms) {
		this.terms = terms;
	}

	@Column(name = "TAX_NO", length = 35)
	public String getTaxNo() {
		return this.taxNo;
	}

	public void setTaxNo(String taxNo) {
		this.taxNo = taxNo;
	}

	@Column(name = "TOTAL", precision = 14, scale = 0)
	public Long getTotal() {
		return this.total;
	}

	public void setTotal(Long total) {
		this.total = total;
	}

	@Column(name = "RCD_DT_BILL_APPROVED", length = 19)
	public Date getRcdDtBillApproved() {
		return this.rcdDtBillApproved;
	}

	public void setRcdDtBillApproved(Date rcdDtBillApproved) {
		this.rcdDtBillApproved = rcdDtBillApproved;
	}

}
