package com.guudint.clickargo.clictruck.planexec.trip.model;
// Generated 9 May, 2023 2:31:30 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.guudint.clickargo.clictruck.planexec.job.model.TCkJobTruck;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtTrip generated by hbm2java
 */
@Entity
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
@Table(name = "T_CK_CT_TRIP")
public class TCkCtTrip extends COAbstractEntity<TCkCtTrip> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 2450495691572981653L;
	
	// Attributes
	/////////////
	private String trId;
	private TCkCtTripCharge TCkCtTripCharge;
	private TCkCtTripLocation TCkCtTripLocationByTrTo;
	private TCkCtTripLocation TCkCtTripLocationByTrFrom;
	private TCkCtTripLocation TCkCtTripLocationByTrDepot;
	private TCkJobTruck TCkJobTruck;
	private String trFromAddr;
	private String trToAddr;
	private String trDepoAddr;
	private Character trChargeOpen;
	private Integer trSeq = 0; // default = 0
	
	private Character trStatus;
	private Date trDtCreate;
	private String trUidCreate;
	private Date trDtLupd;
	private String trUidLupd;
	
	@Transient
	List<TCkCtTripCargoFm> fmCargoList;
	@Transient
	List<TCkCtTripCargoMm> mmCargoList; 

	// Constructors
	///////////////
	public TCkCtTrip() {
	}

	public TCkCtTrip(String trId) {
		this.trId = trId;
	}

	public TCkCtTrip(String trId, TCkCtTripCharge TCkCtTripCharge, TCkCtTripLocation TCkCtTripLocationByTrTo,
			TCkCtTripLocation TCkCtTripLocationByTrFrom, TCkCtTripLocation TCkCtTripLocationByTrDepot,
			TCkJobTruck TCkJobTruck,String trFromAddr, String trToAddr, String trDepoAddr, Character trChargeOpen,
			Character trStatus, Date trDtCreate, String trUidCreate, Date trDtLupd, String trUidLupd) {
		this.trId = trId;
		this.TCkCtTripCharge = TCkCtTripCharge;
		this.TCkCtTripLocationByTrTo = TCkCtTripLocationByTrTo;
		this.TCkCtTripLocationByTrFrom = TCkCtTripLocationByTrFrom;
		this.TCkCtTripLocationByTrDepot = TCkCtTripLocationByTrDepot;
		this.TCkJobTruck = TCkJobTruck;
		this.trFromAddr = trFromAddr;
		this.trToAddr = trToAddr;
		this.trDepoAddr = trDepoAddr;
		this.trChargeOpen = trChargeOpen;
		this.trStatus = trStatus;
		this.trDtCreate = trDtCreate;
		this.trUidCreate = trUidCreate;
		this.trDtLupd = trDtLupd;
		this.trUidLupd = trUidLupd;
	}


	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkCtTrip o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
	
	// Properties
	/////////////
	@Id
	@Column(name = "TR_ID", unique = true, nullable = false, length = 35)
	public String getTrId() {
		return this.trId;
	}

	public void setTrId(String trId) {
		this.trId = trId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "TR_CHARGE")
	public TCkCtTripCharge getTCkCtTripCharge() {
		return this.TCkCtTripCharge;
	}

	public void setTCkCtTripCharge(TCkCtTripCharge TCkCtTripCharge) {
		this.TCkCtTripCharge = TCkCtTripCharge;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "TR_TO")
	public TCkCtTripLocation getTCkCtTripLocationByTrTo() {
		return this.TCkCtTripLocationByTrTo;
	}

	public void setTCkCtTripLocationByTrTo(TCkCtTripLocation TCkCtTripLocationByTrTo) {
		this.TCkCtTripLocationByTrTo = TCkCtTripLocationByTrTo;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "TR_FROM")
	public TCkCtTripLocation getTCkCtTripLocationByTrFrom() {
		return this.TCkCtTripLocationByTrFrom;
	}

	public void setTCkCtTripLocationByTrFrom(TCkCtTripLocation TCkCtTripLocationByTrFrom) {
		this.TCkCtTripLocationByTrFrom = TCkCtTripLocationByTrFrom;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "TR_DEPO")
	public TCkCtTripLocation getTCkCtTripLocationByTrDepot() {
		return this.TCkCtTripLocationByTrDepot;
	}

	public void setTCkCtTripLocationByTrDepot(TCkCtTripLocation tCkCtTripLocationByTrDepot) {
		this.TCkCtTripLocationByTrDepot = tCkCtTripLocationByTrDepot;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "TR_JOB")
	@JsonIgnore
	public TCkJobTruck getTCkJobTruck() {
		return this.TCkJobTruck;
	}

	public void setTCkJobTruck(TCkJobTruck TCkJobTruck) {
		this.TCkJobTruck = TCkJobTruck;
	}

	@Column(name = "TR_FROM_ADDR", length = 1024)
	public String getTrFromAddr() {
		return trFromAddr;
	}

	public void setTrFromAddr(String trFromAddr) {
		this.trFromAddr = trFromAddr;
	}

	@Column(name = "TR_TO_ADDR", length = 1024)
	public String getTrToAddr() {
		return trToAddr;
	}

	public void setTrToAddr(String trToAddr) {
		this.trToAddr = trToAddr;
	}

	@Column(name = "TR_DEPO_ADDR", length = 1024)
	public String getTrDepoAddr() {
		return trDepoAddr;
	}

	public void setTrDepoAddr(String trDepoAddr) {
		this.trDepoAddr = trDepoAddr;
	}

	@Column(name = "TR_CHARGE_OPEN", length = 1)
	public Character getTrChargeOpen() {
		return trChargeOpen;
	}

	public void setTrChargeOpen(Character trChargeOpen) {
		this.trChargeOpen = trChargeOpen;
	}

	@Column(name = "TR_STATUS", length = 1)
	public Character getTrStatus() {
		return this.trStatus;
	}

	public void setTrStatus(Character trStatus) {
		this.trStatus = trStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TR_DT_CREATE", length = 19)
	@CreationTimestamp
	public Date getTrDtCreate() {
		return this.trDtCreate;
	}

	public void setTrDtCreate(Date trDtCreate) {
		this.trDtCreate = trDtCreate;
	}

	@Column(name = "TR_UID_CREATE", length = 35)
	public String getTrUidCreate() {
		return this.trUidCreate;
	}

	public void setTrUidCreate(String trUidCreate) {
		this.trUidCreate = trUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TR_DT_LUPD", length = 19)
	@UpdateTimestamp
	public Date getTrDtLupd() {
		return this.trDtLupd;
	}

	public void setTrDtLupd(Date trDtLupd) {
		this.trDtLupd = trDtLupd;
	}

	@Column(name = "TR_UID_LUPD", length = 35)
	public String getTrUidLupd() {
		return this.trUidLupd;
	}

	public void setTrUidLupd(String trUidLupd) {
		this.trUidLupd = trUidLupd;
	}

	@Column(name = "TR_SEQ")
	public Integer getTrSeq() {
		return this.trSeq;
	}

	public void setTrSeq(Integer trSeq) {
		this.trSeq = trSeq;
	}


	@Transient
	public List<TCkCtTripCargoFm> getFmCargoList() {
		return fmCargoList;
	}

	public void setFmCargoList(List<TCkCtTripCargoFm> fmCargoList) {
		this.fmCargoList = fmCargoList;
	}

	@Transient
	public List<TCkCtTripCargoMm> getMmCargoList() {
		return mmCargoList;
	}

	public void setMmCargoList(List<TCkCtTripCargoMm> mmCargoList) {
		this.mmCargoList = mmCargoList;
	}
}
