package com.guudint.clickargo.clictruck.planexec.trip.model;
// Generated 9 May, 2023 2:31:30 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.guudint.clickargo.clictruck.master.model.TCkCtMstCargoType;
import com.guudint.clickargo.master.model.TCkMstCntType;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtTripCargoFm generated by hbm2java
 */
@Entity
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
@Table(name = "T_CK_CT_TRIP_CARGO_FM")
public class TCkCtTripCargoFm extends COAbstractEntity<TCkCtTripCargoFm> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 325677479049919636L;
	
	// Attributes
	/////////////
	private String cgId;
	private TCkCtMstCargoType TCkCtMstCargoType;
	private TCkCtTrip TCkCtTrip;
	private TCkMstCntType TCkMstCntType;
	private String cgCntNo;
	private String cgCntSealNo;
	private Character cgCntFullLoad;
	private String cgCargoDesc;
	private String cgCargoSpecialInstn;
	private Character cgStatus;
	private Date cgDtCreate;
	private String cgUidCreate;
	private Date cgDtLupd;
	private String cgUidLupd;

	// Constructors
	///////////////
	public TCkCtTripCargoFm() {
	}

	public TCkCtTripCargoFm(String cgId, TCkCtTrip TCkCtTrip) {
		this.cgId = cgId;
		this.TCkCtTrip = TCkCtTrip;
	}

	public TCkCtTripCargoFm(String cgId, TCkCtMstCargoType TCkCtMstCargoType, TCkCtTrip TCkCtTrip,
			TCkMstCntType TCkMstCntType, String cgCntNo, String cgCntSealNo, Character cgCntFullLoad,
			String cgCargoDesc, String cgCargoSpecialInstn, Character cgStatus, Date cgDtCreate, String cgUidCreate,
			Date cgDtLupd, String cgUidLupd) {
		this.cgId = cgId;
		this.TCkCtMstCargoType = TCkCtMstCargoType;
		this.TCkCtTrip = TCkCtTrip;
		this.TCkMstCntType = TCkMstCntType;
		this.cgCntNo = cgCntNo;
		this.cgCntSealNo = cgCntSealNo;
		this.cgCntFullLoad = cgCntFullLoad;
		this.cgCargoDesc = cgCargoDesc;
		this.cgCargoSpecialInstn = cgCargoSpecialInstn;
		this.cgStatus = cgStatus;
		this.cgDtCreate = cgDtCreate;
		this.cgUidCreate = cgUidCreate;
		this.cgDtLupd = cgDtLupd;
		this.cgUidLupd = cgUidLupd;
	}

	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}

	// Properties
	/////////////
	@Id
	@Column(name = "CG_ID", unique = true, nullable = false, length = 35)
	public String getCgId() {
		return this.cgId;
	}

	public void setCgId(String cgId) {
		this.cgId = cgId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CG_CARGO_TYPE")
	public TCkCtMstCargoType getTCkCtMstCargoType() {
		return this.TCkCtMstCargoType;
	}

	public void setTCkCtMstCargoType(TCkCtMstCargoType TCkCtMstCargoType) {
		this.TCkCtMstCargoType = TCkCtMstCargoType;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CG_TRIP", nullable = false)
	public TCkCtTrip getTCkCtTrip() {
		return this.TCkCtTrip;
	}

	public void setTCkCtTrip(TCkCtTrip TCkCtTrip) {
		this.TCkCtTrip = TCkCtTrip;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CG_CNT_TYPE")
	public TCkMstCntType getTCkMstCntType() {
		return this.TCkMstCntType;
	}

	public void setTCkMstCntType(TCkMstCntType TCkMstCntType) {
		this.TCkMstCntType = TCkMstCntType;
	}

	@Column(name = "CG_CNT_NO", length = 256)
	public String getCgCntNo() {
		return this.cgCntNo;
	}

	public void setCgCntNo(String cgCntNo) {
		this.cgCntNo = cgCntNo;
	}

	@Column(name = "CG_CNT_SEAL_NO", length = 256)
	public String getCgCntSealNo() {
		return this.cgCntSealNo;
	}

	public void setCgCntSealNo(String cgCntSealNo) {
		this.cgCntSealNo = cgCntSealNo;
	}

	@Column(name = "CG_CNT_FULL_LOAD", length = 1)
	public Character getCgCntFullLoad() {
		return this.cgCntFullLoad;
	}

	public void setCgCntFullLoad(Character cgCntFullLoad) {
		this.cgCntFullLoad = cgCntFullLoad;
	}

	@Column(name = "CG_CARGO_DESC", length = 16777215)
	public String getCgCargoDesc() {
		return this.cgCargoDesc;
	}

	public void setCgCargoDesc(String cgCargoDesc) {
		this.cgCargoDesc = cgCargoDesc;
	}

	@Column(name = "CG_CARGO_SPECIAL_INSTN", length = 16777215)
	public String getCgCargoSpecialInstn() {
		return this.cgCargoSpecialInstn;
	}

	public void setCgCargoSpecialInstn(String cgCargoSpecialInstn) {
		this.cgCargoSpecialInstn = cgCargoSpecialInstn;
	}

	@Column(name = "CG_STATUS", length = 1)
	public Character getCgStatus() {
		return this.cgStatus;
	}

	public void setCgStatus(Character cgStatus) {
		this.cgStatus = cgStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CG_DT_CREATE", length = 19)
	@CreationTimestamp
	public Date getCgDtCreate() {
		return this.cgDtCreate;
	}

	public void setCgDtCreate(Date cgDtCreate) {
		this.cgDtCreate = cgDtCreate;
	}

	@Column(name = "CG_UID_CREATE", length = 35)
	public String getCgUidCreate() {
		return this.cgUidCreate;
	}

	public void setCgUidCreate(String cgUidCreate) {
		this.cgUidCreate = cgUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CG_DT_LUPD", length = 19)
	@UpdateTimestamp
	public Date getCgDtLupd() {
		return this.cgDtLupd;
	}

	public void setCgDtLupd(Date cgDtLupd) {
		this.cgDtLupd = cgDtLupd;
	}

	@Column(name = "CG_UID_LUPD", length = 35)
	public String getCgUidLupd() {
		return this.cgUidLupd;
	}

	public void setCgUidLupd(String cgUidLupd) {
		this.cgUidLupd = cgUidLupd;
	}

	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkCtTripCargoFm o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

}
