package com.guudint.clickargo.clictruck.planexec.trip.model;
// Generated 05 15, 23 10:36:37 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtTripDo generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_TRIP_DO")
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
public class TCkCtTripDo extends COAbstractEntity<TCkCtTripDo> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -8923339442936602965L;
	
	// Attributes
	/////////////
	private String doId;
	private TCkCtTrip TCkCtTrip;
	private String doNo;
	private String doUnsigned;
	private String doSigned;
	private String doRemarks;
	private Character doStatus;
	private Date doDtCreate;
	private String doUidCreate;
	private Date doDtLupd;
	private String doUidLupd;

	// Constructors
	///////////////
	public TCkCtTripDo() {
	}

	public TCkCtTripDo(String doId, TCkCtTrip TCkCtTrip) {
		this.doId = doId;
		this.TCkCtTrip = TCkCtTrip;
	}

	public TCkCtTripDo(String doId, TCkCtTrip TCkCtTrip, String doNo, String doUnsigned, String doSigned,
			String doRemarks, Character doStatus, Date doDtCreate, String doUidCreate, Date doDtLupd,
			String doUidLupd) {
		this.doId = doId;
		this.TCkCtTrip = TCkCtTrip;
		this.doNo = doNo;
		this.doUnsigned = doUnsigned;
		this.doSigned = doSigned;
		this.doRemarks = doRemarks;
		this.doStatus = doStatus;
		this.doDtCreate = doDtCreate;
		this.doUidCreate = doUidCreate;
		this.doDtLupd = doDtLupd;
		this.doUidLupd = doUidLupd;
	}

	// Properties
	/////////////
	@Id
	@Column(name = "DO_ID", unique = true, nullable = false, length = 35)
	public String getDoId() {
		return this.doId;
	}

	public void setDoId(String doId) {
		this.doId = doId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "DO_TRIP", nullable = false)
	public TCkCtTrip getTCkCtTrip() {
		return this.TCkCtTrip;
	}

	public void setTCkCtTrip(TCkCtTrip TCkCtTrip) {
		this.TCkCtTrip = TCkCtTrip;
	}

	@Column(name = "DO_NO", length = 256)
	public String getDoNo() {
		return this.doNo;
	}

	public void setDoNo(String doNo) {
		this.doNo = doNo;
	}

	@Column(name = "DO_UNSIGNED", length = 1024)
	public String getDoUnsigned() {
		return this.doUnsigned;
	}

	public void setDoUnsigned(String doUnsigned) {
		this.doUnsigned = doUnsigned;
	}

	@Column(name = "DO_SIGNED", length = 1024)
	public String getDoSigned() {
		return this.doSigned;
	}

	public void setDoSigned(String doSigned) {
		this.doSigned = doSigned;
	}

	@Column(name = "DO_REMARKS", length = 16777215)
	public String getDoRemarks() {
		return this.doRemarks;
	}

	public void setDoRemarks(String doRemarks) {
		this.doRemarks = doRemarks;
	}

	@Column(name = "DO_STATUS", length = 1)
	public Character getDoStatus() {
		return this.doStatus;
	}

	public void setDoStatus(Character doStatus) {
		this.doStatus = doStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DO_DT_CREATE", length = 19)
	@CreationTimestamp
	public Date getDoDtCreate() {
		return this.doDtCreate;
	}

	public void setDoDtCreate(Date doDtCreate) {
		this.doDtCreate = doDtCreate;
	}

	@Column(name = "DO_UID_CREATE", length = 35)
	public String getDoUidCreate() {
		return this.doUidCreate;
	}

	public void setDoUidCreate(String doUidCreate) {
		this.doUidCreate = doUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DO_DT_LUPD", length = 19)
	@UpdateTimestamp
	public Date getDoDtLupd() {
		return this.doDtLupd;
	}

	public void setDoDtLupd(Date doDtLupd) {
		this.doDtLupd = doDtLupd;
	}

	@Column(name = "DO_UID_LUPD", length = 35)
	public String getDoUidLupd() {
		return this.doUidLupd;
	}

	public void setDoUidLupd(String doUidLupd) {
		this.doUidLupd = doUidLupd;
	}

	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkCtTripDo o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

}
