package com.guudint.clickargo.clictruck.planexec.trip.model;
// Generated 05 15, 23 10:36:37 PM by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.guudint.clickargo.clictruck.master.model.TCkCtMstToInvoiceState;
import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtPlatformInvoice generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_PLATFORM_INVOICE")
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
public class TCkCtPlatformInvoice extends COAbstractEntity<TCkCtPlatformInvoice> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -5091117510008805562L;

	// Attributes
	/////////////
	private String invId;
	private TCkCtMstToInvoiceState TCkCtMstToInvoiceState;
	private TCkCtTrip TCkCtTrip;
	private TCoreAccn TCoreAccnByInvTo;
	private TCoreAccn TCoreAccnByInvFrom;
	private String invJobId;
	private String invNo;
	private String invPaymentTxnRef;
	private BigDecimal invAmt;
	private BigDecimal invVat;
	private BigDecimal invStampDuty;
	private BigDecimal invTotal;
	private String invSageTaxNo;
	private Date invDtIssue;
	private Date invDtDue;
	private Date invDtPaid;
	private String invName;
	private String invLoc;
	private String invInvocierComment;
	private String invInvocieeRemarks;
	private Short invRefresh;
	private Character invStatus;
	private Date invDtCreate;
	private String invUidCreate;
	private Date invDtLupd;
	private String invUidLupd;

	// Constructors
	///////////////
	public TCkCtPlatformInvoice() {
	}

	/**
	 * 
	 * @param invId
	 * @param TCkCtMstToInvoiceState
	 * @param invNo
	 */
	public TCkCtPlatformInvoice(String invId, TCkCtMstToInvoiceState TCkCtMstToInvoiceState, String invNo) {
		this.invId = invId;
		this.TCkCtMstToInvoiceState = TCkCtMstToInvoiceState;
		this.invNo = invNo;
	}

	/**
	 * 
	 * @param invId
	 * @param invPaymentTxnRef
	 * @param TCkCtMstToInvoiceState
	 * @param TCkCtTrip
	 * @param TCoreAccnByInvTo
	 * @param TCoreAccnByInvFrom
	 * @param invJobId
	 * @param invNo
	 * @param invDtIssue
	 * @param invDtDue
	 * @param invDtPaid
	 * @param invName
	 * @param invLoc
	 * @param invInvocierComment
	 * @param invInvocieeRemarks
	 * @param invStatus
	 * @param invDtCreate
	 * @param invUidCreate
	 * @param invDtLupd
	 * @param invUidLupd
	 */
	public TCkCtPlatformInvoice(String invId, TCkCtMstToInvoiceState TCkCtMstToInvoiceState, TCkCtTrip TCkCtTrip,
			TCoreAccn TCoreAccnByInvTo, TCoreAccn TCoreAccnByInvFrom, String invJobId, String invNo,
			String invPaymentTxnRef, Date invDtIssue, Date invDtDue, Date invDtPaid, String invName, String invLoc,
			String invInvocierComment, String invInvocieeRemarks, Character invStatus, Date invDtCreate,
			String invUidCreate, Date invDtLupd, String invUidLupd) {
		this.invId = invId;
		this.TCkCtMstToInvoiceState = TCkCtMstToInvoiceState;
		this.TCkCtTrip = TCkCtTrip;
		this.TCoreAccnByInvTo = TCoreAccnByInvTo;
		this.TCoreAccnByInvFrom = TCoreAccnByInvFrom;
		this.invJobId = invJobId;
		this.invNo = invNo;
		this.invPaymentTxnRef = invPaymentTxnRef;
		this.invDtIssue = invDtIssue;
		this.invDtDue = invDtDue;
		this.invDtPaid = invDtPaid;
		this.invName = invName;
		this.invLoc = invLoc;
		this.invInvocierComment = invInvocierComment;
		this.invInvocieeRemarks = invInvocieeRemarks;
		this.invStatus = invStatus;
		this.invDtCreate = invDtCreate;
		this.invUidCreate = invUidCreate;
		this.invDtLupd = invDtLupd;
		this.invUidLupd = invUidLupd;
	}

	// Properties
	/////////////
	@Id
	@Column(name = "INV_ID", unique = true, nullable = false, length = 35)
	public String getInvId() {
		return this.invId;
	}

	public void setInvId(String invId) {
		this.invId = invId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "INV_STATE", nullable = false)
	public TCkCtMstToInvoiceState getTCkCtMstToInvoiceState() {
		return this.TCkCtMstToInvoiceState;
	}

	public void setTCkCtMstToInvoiceState(TCkCtMstToInvoiceState TCkCtMstToInvoiceState) {
		this.TCkCtMstToInvoiceState = TCkCtMstToInvoiceState;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "INV_TRIP")
	public TCkCtTrip getTCkCtTrip() {
		return this.TCkCtTrip;
	}

	public void setTCkCtTrip(TCkCtTrip TCkCtTrip) {
		this.TCkCtTrip = TCkCtTrip;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "INV_TO")
	public TCoreAccn getTCoreAccnByInvTo() {
		return this.TCoreAccnByInvTo;
	}

	public void setTCoreAccnByInvTo(TCoreAccn TCoreAccnByInvTo) {
		this.TCoreAccnByInvTo = TCoreAccnByInvTo;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "INV_FROM")
	public TCoreAccn getTCoreAccnByInvFrom() {
		return this.TCoreAccnByInvFrom;
	}

	public void setTCoreAccnByInvFrom(TCoreAccn TCoreAccnByInvFrom) {
		this.TCoreAccnByInvFrom = TCoreAccnByInvFrom;
	}

	@Column(name = "INV_JOB_ID", length = 35)
	public String getInvJobId() {
		return this.invJobId;
	}

	public void setInvJobId(String invJobId) {
		this.invJobId = invJobId;
	}

	@Column(name = "INV_NO", nullable = false, length = 256)
	public String getInvNo() {
		return this.invNo;
	}

	public void setInvNo(String invNo) {
		this.invNo = invNo;
	}
	
	@Column(name = "INV_PAYMENT_TXN_REF", length = 35)
	public String getInvPaymentTxnRef() {
		return this.invPaymentTxnRef;
	}

	public void setInvPaymentTxnRef(String invPaymentTxnRef) {
		this.invPaymentTxnRef = invPaymentTxnRef;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INV_DT_ISSUE", length = 19)
	public Date getInvDtIssue() {
		return this.invDtIssue;
	}

	public void setInvDtIssue(Date invDtIssue) {
		this.invDtIssue = invDtIssue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INV_DT_DUE", length = 19)
	public Date getInvDtDue() {
		return this.invDtDue;
	}

	public void setInvDtDue(Date invDtDue) {
		this.invDtDue = invDtDue;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INV_DT_PAID", length = 19)
	public Date getInvDtPaid() {
		return this.invDtPaid;
	}

	public void setInvDtPaid(Date invDtPaid) {
		this.invDtPaid = invDtPaid;
	}

	@Column(name = "INV_NAME", length = 256)
	public String getInvName() {
		return this.invName;
	}

	public void setInvName(String invName) {
		this.invName = invName;
	}

	@Column(name = "INV_LOC", length = 1024)
	public String getInvLoc() {
		return this.invLoc;
	}

	public void setInvLoc(String invLoc) {
		this.invLoc = invLoc;
	}

	@Column(name = "INV_INVOCIER_COMMENT", length = 16777215)
	public String getInvInvocierComment() {
		return this.invInvocierComment;
	}

	public void setInvInvocierComment(String invInvocierComment) {
		this.invInvocierComment = invInvocierComment;
	}

	@Column(name = "INV_INVOCIEE_REMARKS", length = 16777215)
	public String getInvInvocieeRemarks() {
		return this.invInvocieeRemarks;
	}

	public void setInvInvocieeRemarks(String invInvocieeRemarks) {
		this.invInvocieeRemarks = invInvocieeRemarks;
	}

	@Column(name = "INV_STATUS", length = 1)
	public Character getInvStatus() {
		return this.invStatus;
	}

	public void setInvStatus(Character invStatus) {
		this.invStatus = invStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INV_DT_CREATE", length = 19)
	@CreationTimestamp
	public Date getInvDtCreate() {
		return this.invDtCreate;
	}

	public void setInvDtCreate(Date invDtCreate) {
		this.invDtCreate = invDtCreate;
	}

	@Column(name = "INV_UID_CREATE", length = 35)
	public String getInvUidCreate() {
		return this.invUidCreate;
	}

	public void setInvUidCreate(String invUidCreate) {
		this.invUidCreate = invUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INV_DT_LUPD", length = 19)
	@UpdateTimestamp
	public Date getInvDtLupd() {
		return this.invDtLupd;
	}

	public void setInvDtLupd(Date invDtLupd) {
		this.invDtLupd = invDtLupd;
	}

	@Column(name = "INV_UID_LUPD", length = 35)
	public String getInvUidLupd() {
		return this.invUidLupd;
	}

	public void setInvUidLupd(String invUidLupd) {
		this.invUidLupd = invUidLupd;
	}

	@Column(name = "INV_AMT", precision = 15)
	public BigDecimal getInvAmt() {
		return invAmt;
	}

	public void setInvAmt(BigDecimal invAmt) {
		this.invAmt = invAmt;
	}

	@Column(name = "INV_VAT", precision = 15)
	public BigDecimal getInvVat() {
		return invVat;
	}

	public void setInvVat(BigDecimal invVat) {
		this.invVat = invVat;
	}

	@Column(name = "INV_STAMP_DUTY", precision = 15)
	public BigDecimal getInvStampDuty() {
		return invStampDuty;
	}

	public void setInvStampDuty(BigDecimal invStampDuty) {
		this.invStampDuty = invStampDuty;
	}

	@Column(name = "INV_TOTAL", precision = 15)
	public BigDecimal getInvTotal() {
		return invTotal;
	}

	public void setInvTotal(BigDecimal invTotal) {
		this.invTotal = invTotal;
	}

	@Column(name = "INV_SAGE_TAX_NO", length = 35)
	public String getInvSageTaxNo() {
		return this.invSageTaxNo;
	}

	public void setInvSageTaxNo(String invSageTaxNo) {
		this.invSageTaxNo = invSageTaxNo;
	}

	@Column(name = "INV_REFRESH")
	public Short getInvRefresh() {
		return invRefresh;
	}

	public void setInvRefresh(Short invRefresh) {
		this.invRefresh = invRefresh;
	}

	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkCtPlatformInvoice o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
