package com.guudint.clickargo.clictruck.planexec.trip.model;
// Generated 9 May, 2023 2:31:30 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.guudint.clickargo.clictruck.common.model.TCkCtLocation;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtTripLocation generated by hbm2java
 */
@Entity
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
@Table(name = "T_CK_CT_TRIP_LOCATION")
public class TCkCtTripLocation extends COAbstractEntity<TCkCtTripLocation> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -7167951670584324701L;

	// Attributes
	/////////////
	private String tlocId;
	private TCkCtLocation TCkCtLocation;
	private String tlocLocName;
	private String tlocLocAddress;
	private String tlocLocGps;
	private Date tlocDtLoc;
	private String tlocRemarks;
	private String tlocCargoRec;
	private String tlocMobileNo;
	private String tlocSpecialInstn;
	private String tlocComment;
	private Date tlocDtStart;
	private Date tlocDtReach;
	private Date tlocDtEnd;
	private Character tlocIsDeviated;
	private String tlocDeviationComment;
	private Character tlocStatus;
	private String tlocName;
	private Date tlocDtCreate;
	private String tlocUidCreate;
	private Date tlocDtLupd;
	private String tlocUidLupd;

	// Constructors
	///////////////
	public TCkCtTripLocation() {
	}

	public TCkCtTripLocation(String tlocId) {
		this.tlocId = tlocId;
	}

	public TCkCtTripLocation(String tlocId, TCkCtLocation TCkCtLocation, String tlocLocName, String tlocLocAddress,
			String tlocLocGps, Date tlocDtLoc, String tlocRemarks, String tlocCargoRec, String tlocMobileNo, Character tlocStatus, String tlocName, Date tlocDtCreate,
			String tlocUidCreate, Date tlocDtLupd, String tlocUidLupd) {
		this.tlocId = tlocId;
		this.TCkCtLocation = TCkCtLocation;
		this.tlocLocName = tlocLocName;
		this.tlocLocAddress = tlocLocAddress;
		this.tlocLocGps = tlocLocGps;
		this.tlocDtLoc = tlocDtLoc;
		this.tlocRemarks = tlocRemarks;
		this.tlocCargoRec = tlocCargoRec;
		this.tlocMobileNo = tlocMobileNo;
		this.tlocStatus = tlocStatus;
		this.tlocName = tlocName;
		this.tlocDtCreate = tlocDtCreate;
		this.tlocUidCreate = tlocUidCreate;
		this.tlocDtLupd = tlocDtLupd;
		this.tlocUidLupd = tlocUidLupd;
	}

	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkCtTripLocation o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
	
	////
	@Transient
	public boolean isDiferentNameWithLocation() {
		if(TCkCtLocation != null && TCkCtLocation.getLocName() != null )
			return ! TCkCtLocation.getLocName().equalsIgnoreCase(tlocLocName);
		// default is same name
		return false;
	}

	@Transient
	public boolean isDiferentAddressWithLocation() {

		if(TCkCtLocation != null && TCkCtLocation.getLocAddress() != null )
			return ! TCkCtLocation.getLocAddress().equalsIgnoreCase(tlocLocAddress);
		// default is same address
		return false;
	}
	

	// Properties
	/////////////
	@Id
	@Column(name = "TLOC_ID", unique = true, nullable = false, length = 35)
	public String getTlocId() {
		return this.tlocId;
	}

	public void setTlocId(String tlocId) {
		this.tlocId = tlocId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TLOC_LOC")
	public TCkCtLocation getTCkCtLocation() {
		return this.TCkCtLocation;
	}

	public void setTCkCtLocation(TCkCtLocation TCkCtLocation) {
		this.TCkCtLocation = TCkCtLocation;
	}

	@Column(name = "TLOC_LOC_NAME", length = 1024)
	public String getTlocLocName() {
		return this.tlocLocName;
	}

	public void setTlocLocName(String tlocLocName) {
		this.tlocLocName = tlocLocName;
	}

	@Column(name = "TLOC_LOC_ADDRESS", length = 65535)
	public String getTlocLocAddress() {
		return this.tlocLocAddress;
	}

	public void setTlocLocAddress(String tlocLocAddress) {
		this.tlocLocAddress = tlocLocAddress;
	}

	@Column(name = "TLOC_LOC_GPS", length = 1024)
	public String getTlocLocGps() {
		return this.tlocLocGps;
	}

	public void setTlocLocGps(String tlocLocGps) {
		this.tlocLocGps = tlocLocGps;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TLOC_DT_LOC", length = 19)
	public Date getTlocDtLoc() {
		return this.tlocDtLoc;
	}

	public void setTlocDtLoc(Date tlocDtLoc) {
		this.tlocDtLoc = tlocDtLoc;
	}

	@Column(name = "TLOC_REMARKS", length = 16777215)
	public String getTlocRemarks() {
		return this.tlocRemarks;
	}

	public void setTlocRemarks(String tlocRemarks) {
		this.tlocRemarks = tlocRemarks;
	}

	@Column(name = "TLOC_CARGO_REC", length = 255)
	public String getTlocCargoRec() {
		return tlocCargoRec;
	}

	public void setTlocCargoRec(String tlocCargoRec) {
		this.tlocCargoRec = tlocCargoRec;
	}

	@Column(name = "TLOC_MOBILE_NO", length = 45)
	public String getTlocMobileNo() {
		return this.tlocMobileNo;
	}

	public void setTlocMobileNo(String tlocMobileNo) {
		this.tlocMobileNo = tlocMobileNo;
	}

	@Column(name = "TLOC_STATUS", length = 1)
	public Character getTlocStatus() {
		return this.tlocStatus;
	}

	public void setTlocStatus(Character tlocStatus) {
		this.tlocStatus = tlocStatus;
	}
	
	@Column(name = "TLOC_NAME", length = 1)
	public String getTlocName() {
		return this.tlocName;
	}

	public void setTlocName(String tlocName) {
		this.tlocName = tlocName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TLOC_DT_CREATE", length = 19)
	@CreationTimestamp
	public Date getTlocDtCreate() {
		return this.tlocDtCreate;
	}

	public void setTlocDtCreate(Date tlocDtCreate) {
		this.tlocDtCreate = tlocDtCreate;
	}

	@Column(name = "TLOC_UID_CREATE", length = 35)
	public String getTlocUidCreate() {
		return this.tlocUidCreate;
	}

	public void setTlocUidCreate(String tlocUidCreate) {
		this.tlocUidCreate = tlocUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TLOC_DT_LUPD", length = 19)
	@UpdateTimestamp
	public Date getTlocDtLupd() {
		return this.tlocDtLupd;
	}

	public void setTlocDtLupd(Date tlocDtLupd) {
		this.tlocDtLupd = tlocDtLupd;
	}

	@Column(name = "TLOC_UID_LUPD", length = 35)
	public String getTlocUidLupd() {
		return this.tlocUidLupd;
	}

	public void setTlocUidLupd(String tlocUidLupd) {
		this.tlocUidLupd = tlocUidLupd;
	}

	@Column(name = "TLOC_SPECIAL_INSTN", length = 16777215)
	public String getTlocSpecialInstn() {
		return this.tlocSpecialInstn;
	}

	public void setTlocSpecialInstn(String tlocSpecialInstn) {
		this.tlocSpecialInstn = tlocSpecialInstn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TLOC_DT_START", length = 19)
	public Date getTlocDtStart() {
		return this.tlocDtStart;
	}

	public void setTlocDtStart(Date tlocDtStart) {
		this.tlocDtStart = tlocDtStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TLOC_DT_REACH", length = 19)
	public Date getTlocDtReach() {
		return this.tlocDtReach;
	}

	public void setTlocDtReach(Date tlocDtReach) {
		this.tlocDtReach = tlocDtReach;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TLOC_DT_END", length = 19)
	public Date getTlocDtEnd() {
		return this.tlocDtEnd;
	}

	public void setTlocDtEnd(Date tlocDtEnd) {
		this.tlocDtEnd = tlocDtEnd;
	}

	@Column(name = "TLOC_COMMENT", length = 16777215)
	public String getTlocComment() {
		return this.tlocComment;
	}

	public void setTlocComment(String tlocComment) {
		this.tlocComment = tlocComment;
	}
	
	@Column(name = "TLOC_IS_DEVIATED", length = 1)
	public Character getTlocIsDeviated() {
		return this.tlocIsDeviated;
	}

	public void setTlocIsDeviated(Character tlocIsDeviated) {
		this.tlocIsDeviated = tlocIsDeviated;
	}

	@Column(name = "TLOC_DEVIATION_COMMENT", length = 16777215)
	public String getTlocDeviationComment() {
		return this.tlocDeviationComment;
	}

	public void setTlocDeviationComment(String tlocDeviationComment) {
		this.tlocDeviationComment = tlocDeviationComment;
	}

}
