package com.guudint.clickargo.clictruck.planexec.trip.model;
// Generated 20 Oct 2023, 12:24:55 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.guudint.clickargo.clictruck.master.model.TCkCtMstTripAttachType;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtTripAttach generated by hbm2java
 */
@Entity
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
@Table(name = "T_CK_CT_TRIP_ATTACH")
public class TCkCtTripAttach extends COAbstractEntity<TCkCtTripAttach> {

	private static final long serialVersionUID = 3805800850422702834L;
	private String atId;
	private TCkCtMstTripAttachType TCkCtMstTripAttachType;
	private TCkCtTrip TCkCtTrip;
	private String atName;
	private String atLoc;
	private String atSource;
	private Character atStatus;
	private Date atDtCreate;
	private String atUidCreate;
	private Date atDtLupd;
	private String atUidLupd;

	public TCkCtTripAttach() {
	}

	public TCkCtTripAttach(String atId) {
		this.atId = atId;
	}

	public TCkCtTripAttach(String atId, TCkCtMstTripAttachType TCkCtMstTripAttachType,
			TCkCtTrip TCkCtTrip, String atName, String atLoc, Character atStatus, Date atDtCreate,
			String atUidCreate, Date atDtLupd, String atUidLupd) {
		this.atId = atId;
		this.TCkCtMstTripAttachType = TCkCtMstTripAttachType;
		this.TCkCtTrip = TCkCtTrip;
		this.atName = atName;
		this.atLoc = atLoc;
		this.atStatus = atStatus;
		this.atDtCreate = atDtCreate;
		this.atUidCreate = atUidCreate;
		this.atDtLupd = atDtLupd;
		this.atUidLupd = atUidLupd;
	}

	@Id

	@Column(name = "AT_ID", unique = true, nullable = false, length = 35)
	public String getAtId() {
		return this.atId;
	}

	public void setAtId(String atId) {
		this.atId = atId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AT_TYPE")
	public TCkCtMstTripAttachType getTCkCtMstTripAttachType() {
		return this.TCkCtMstTripAttachType;
	}

	public void setTCkCtMstTripAttachType(TCkCtMstTripAttachType TCkCtMstTripAttachType) {
		this.TCkCtMstTripAttachType = TCkCtMstTripAttachType;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AT_TRIP")
	public TCkCtTrip getTCkCtTrip() {
		return TCkCtTrip;
	}

	public void setTCkCtTrip(TCkCtTrip tCkCtTrip) {
		TCkCtTrip = tCkCtTrip;
	}

	@Column(name = "AT_NAME", length = 256)
	public String getAtName() {
		return this.atName;
	}

	
	public void setAtName(String atName) {
		this.atName = atName;
	}

	@Column(name = "AT_LOC", length = 1024)
	public String getAtLoc() {
		return this.atLoc;
	}

	public void setAtLoc(String atLoc) {
		this.atLoc = atLoc;
	}

	@Column(name = "AT_SOURCE", length = 45)
	public String getAtSource() {
		return this.atSource;
	}

	public void setAtSource(String atSource) {
		this.atSource = atSource;
	}

	@Column(name = "AT_STATUS", length = 1)
	public Character getAtStatus() {
		return this.atStatus;
	}

	public void setAtStatus(Character atStatus) {
		this.atStatus = atStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AT_DT_CREATE", length = 19)
	public Date getAtDtCreate() {
		return this.atDtCreate;
	}

	public void setAtDtCreate(Date atDtCreate) {
		this.atDtCreate = atDtCreate;
	}

	@Column(name = "AT_UID_CREATE", length = 35)
	public String getAtUidCreate() {
		return this.atUidCreate;
	}

	public void setAtUidCreate(String atUidCreate) {
		this.atUidCreate = atUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AT_DT_LUPD", length = 19)
	public Date getAtDtLupd() {
		return this.atDtLupd;
	}

	public void setAtDtLupd(Date atDtLupd) {
		this.atDtLupd = atDtLupd;
	}

	@Column(name = "AT_UID_LUPD", length = 35)
	public String getAtUidLupd() {
		return this.atUidLupd;
	}

	public void setAtUidLupd(String atUidLupd) {
		this.atUidLupd = atUidLupd;
	}

	@Override
	public int compareTo(TCkCtTripAttach o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
