package com.guudint.clickargo.clictruck.planexec.trip.model;
// Generated 9 May, 2023 2:31:30 PM by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtTripCharge generated by hbm2java
 */
@Entity
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
@Table(name = "T_CK_CT_TRIP_CHARGE")
public class TCkCtTripCharge extends COAbstractEntity<TCkCtTripCharge> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 5663308730375526397L;
	
	// Attributes
	/////////////
	private String tcId;
	private char tcIsOpen;
	private BigDecimal tcPrice;
	private BigDecimal tcPlatformFee;
	private BigDecimal tcGovtTax;
	private BigDecimal tcWitholdTax;
	private Character tcStatus;
	private Date tcDtCreate;
	private String tcUidCreate;
	private Date tcDtLupd;
	private String tcUidLupd;

	// Constructors
	///////////////
	public TCkCtTripCharge() {
	}

	public TCkCtTripCharge(String tcId, char tcIsOpen) {
		this.tcId = tcId;
		this.tcIsOpen = tcIsOpen;
	}

	public TCkCtTripCharge(String tcId, char tcIsOpen, BigDecimal tcPrice, BigDecimal tcPlatformFee,
			BigDecimal tcGovtTax, BigDecimal tcWitholdTax, Character tcStatus, Date tcDtCreate, String tcUidCreate,
			Date tcDtLupd, String tcUidLupd) {
		this.tcId = tcId;
		this.tcIsOpen = tcIsOpen;
		this.tcPrice = tcPrice;
		this.tcPlatformFee = tcPlatformFee;
		this.tcGovtTax = tcGovtTax;
		this.tcWitholdTax = tcWitholdTax;
		this.tcStatus = tcStatus;
		this.tcDtCreate = tcDtCreate;
		this.tcUidCreate = tcUidCreate;
		this.tcDtLupd = tcDtLupd;
		this.tcUidLupd = tcUidLupd;
	}

	
	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkCtTripCharge o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
	
	// Properties
	/////////////
	@Id
	@Column(name = "TC_ID", unique = true, nullable = false, length = 35)
	public String getTcId() {
		return this.tcId;
	}

	public void setTcId(String tcId) {
		this.tcId = tcId;
	}

	@Column(name = "TC_IS_OPEN", nullable = false, length = 1)
	public char getTcIsOpen() {
		return this.tcIsOpen;
	}

	public void setTcIsOpen(char tcIsOpen) {
		this.tcIsOpen = tcIsOpen;
	}

	@Column(name = "TC_PRICE", precision = 15)
	public BigDecimal getTcPrice() {
		return this.tcPrice;
	}

	public void setTcPrice(BigDecimal tcPrice) {
		this.tcPrice = tcPrice;
	}

	@Column(name = "TC_PLATFORM_FEE", precision = 15)
	public BigDecimal getTcPlatformFee() {
		return this.tcPlatformFee;
	}

	public void setTcPlatformFee(BigDecimal tcPlatformFee) {
		this.tcPlatformFee = tcPlatformFee;
	}

	@Column(name = "TC_GOVT_TAX", precision = 15)
	public BigDecimal getTcGovtTax() {
		return this.tcGovtTax;
	}

	public void setTcGovtTax(BigDecimal tcGovtTax) {
		this.tcGovtTax = tcGovtTax;
	}

	@Column(name = "TC_WITHOLD_TAX", precision = 15)
	public BigDecimal getTcWitholdTax() {
		return this.tcWitholdTax;
	}

	public void setTcWitholdTax(BigDecimal tcWitholdTax) {
		this.tcWitholdTax = tcWitholdTax;
	}

	@Column(name = "TC_STATUS", length = 1)
	public Character getTcStatus() {
		return this.tcStatus;
	}

	public void setTcStatus(Character tcStatus) {
		this.tcStatus = tcStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TC_DT_CREATE", length = 19)
	@CreationTimestamp
	public Date getTcDtCreate() {
		return this.tcDtCreate;
	}

	public void setTcDtCreate(Date tcDtCreate) {
		this.tcDtCreate = tcDtCreate;
	}

	@Column(name = "TC_UID_CREATE", length = 35)
	public String getTcUidCreate() {
		return this.tcUidCreate;
	}

	public void setTcUidCreate(String tcUidCreate) {
		this.tcUidCreate = tcUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TC_DT_LUPD", length = 19)
	@UpdateTimestamp
	public Date getTcDtLupd() {
		return this.tcDtLupd;
	}

	public void setTcDtLupd(Date tcDtLupd) {
		this.tcDtLupd = tcDtLupd;
	}

	@Column(name = "TC_UID_LUPD", length = 35)
	public String getTcUidLupd() {
		return this.tcUidLupd;
	}

	public void setTcUidLupd(String tcUidLupd) {
		this.tcUidLupd = tcUidLupd;
	}

}
