package com.guudint.clickargo.clictruck.planexec.trip.model;
// Generated 9 May, 2023 2:31:30 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.guudint.clickargo.clictruck.master.model.TCkCtMstCargoType;
import com.vcc.camelone.common.COAbstractEntity;
import com.guudint.clickargo.clictruck.master.model.TCkCtMstUomSize;
import com.guudint.clickargo.clictruck.master.model.TCkCtMstUomVolume;
import com.guudint.clickargo.clictruck.master.model.TCkCtMstUomWeight;

/**
 * TCkCtTripCargoMm generated by hbm2java
 */
@Entity
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
@Table(name = "T_CK_CT_TRIP_CARGO_MM")
public class TCkCtTripCargoMm extends COAbstractEntity<TCkCtTripCargoMm> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -5671442306630895646L;
	
	// Attributes
	/////////////
	private String cgId;
	private TCkCtMstCargoType TCkCtMstCargoType;
	private TCkCtMstUomWeight TCkCtMstUomWeight;
	private TCkCtMstUomVolume TCkCtMstUomVolume;
	private TCkCtMstUomSize TCkCtMstUomSize;
	private TCkCtTrip TCkCtTrip;
	private String cgCargoDesc;
	private String cgCargoSpecialInstn;
	private Double cgCargoQty;
	private String cgCargoMarksNo;
	private Double cgCargoLength;
	private Double cgCargoWidth;
	private Double cgCargoHeight;
	private Double cgCargoWeight;
	private Double cgCargoVolume;
	private String cgCargoQtyUom;
	private Character cgStatus;
	private Character cgPickupStatus;
	private Character cgDropOffStatus;
	private Date cgDtCreate;
	private String cgUidCreate;
	private Date cgDtLupd;
	private String cgUidLupd;

	// Constructors
	///////////////
	public TCkCtTripCargoMm() {
	}

	public TCkCtTripCargoMm(String cgId, TCkCtTrip TCkCtTrip) {
		this.cgId = cgId;
		this.TCkCtTrip = TCkCtTrip;
	}

	public TCkCtTripCargoMm(String cgId, TCkCtMstCargoType TCkCtMstCargoType, TCkCtTrip TCkCtTrip, String cgCargoDesc,
			String cgCargoSpecialInstn, Double cgCargoQty, String cgCargoMarksNo, Double cgCargoLength,
							Double cgCargoWidth, Double cgCargoHeight, Double cgCargoWeight, Double cgCargoVolume, Character cgStatus,
			Date cgDtCreate, String cgUidCreate, Date cgDtLupd, String cgUidLupd, Character cgPickupStatus, Character cgDropOffStatus) {
		this.cgId = cgId;
		this.TCkCtMstCargoType = TCkCtMstCargoType;
		this.TCkCtTrip = TCkCtTrip;
		this.cgCargoDesc = cgCargoDesc;
		this.cgCargoSpecialInstn = cgCargoSpecialInstn;
		this.cgCargoQty = cgCargoQty;
		this.cgCargoMarksNo = cgCargoMarksNo;
		this.cgCargoLength = cgCargoLength;
		this.cgCargoWidth = cgCargoWidth;
		this.cgCargoHeight = cgCargoHeight;
		this.cgCargoWeight = cgCargoWeight;
		this.cgCargoVolume = cgCargoVolume;
		this.cgStatus = cgStatus;
		this.cgPickupStatus = cgPickupStatus;
		this.cgDropOffStatus = cgDropOffStatus;
		this.cgDtCreate = cgDtCreate;
		this.cgUidCreate = cgUidCreate;
		this.cgDtLupd = cgDtLupd;
		this.cgUidLupd = cgUidLupd;
	}

	public TCkCtTripCargoMm(com.guudint.clickargo.clictruck.master.model.TCkCtMstUomWeight TCkCtMstUomWeight, com.guudint.clickargo.clictruck.master.model.TCkCtMstUomVolume TCkCtMstUomVolume, com.guudint.clickargo.clictruck.master.model.TCkCtMstUomSize TCkCtMstUomSize, String cgCargoQtyUom) {
		this.TCkCtMstUomWeight = TCkCtMstUomWeight;
		this.TCkCtMstUomVolume = TCkCtMstUomVolume;
		this.TCkCtMstUomSize = TCkCtMstUomSize;
		this.cgCargoQtyUom = cgCargoQtyUom;
	}

	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
	
	// Properties
	/////////////
	@Id
	@Column(name = "CG_ID", unique = true, nullable = false, length = 35)
	public String getCgId() {
		return this.cgId;
	}

	public void setCgId(String cgId) {
		this.cgId = cgId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CG_CARGO_TYPE")
	public TCkCtMstCargoType getTCkCtMstCargoType() {
		return this.TCkCtMstCargoType;
	}

	public void setTCkCtMstCargoType(TCkCtMstCargoType TCkCtMstCargoType) {
		this.TCkCtMstCargoType = TCkCtMstCargoType;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CG_CARGO_UOM_WEIGHT")
	public TCkCtMstUomWeight getTCkCtMstUomWeight() {
		return TCkCtMstUomWeight;
	}

	public void setTCkCtMstUomWeight(TCkCtMstUomWeight TCkCtMstUomWeight) {
		this.TCkCtMstUomWeight = TCkCtMstUomWeight;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CG_CARGO_UOM_VOLUME")
	public TCkCtMstUomVolume getTCkCtMstUomVolume() {
		return TCkCtMstUomVolume;
	}

	public void setTCkCtMstUomVolume(TCkCtMstUomVolume TCkCtMstUomVolume) {
		this.TCkCtMstUomVolume = TCkCtMstUomVolume;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CG_CARGO_UOM_SIZE")
	public TCkCtMstUomSize getTCkCtMstUomSize() {
		return TCkCtMstUomSize;
	}

	public void setTCkCtMstUomSize(TCkCtMstUomSize TCkCtMstUomSize) {
		this.TCkCtMstUomSize = TCkCtMstUomSize;
	}
	@Column(name = "CG_CARGO_UOM_QTY")
	public String getCgCargoQtyUom() {
		return cgCargoQtyUom;
	}

	public void setCgCargoQtyUom(String cgCargoQtyUom) {
		this.cgCargoQtyUom = cgCargoQtyUom;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CG_TRIP", nullable = false)
	public TCkCtTrip getTCkCtTrip() {
		return this.TCkCtTrip;
	}

	public void setTCkCtTrip(TCkCtTrip TCkCtTrip) {
		this.TCkCtTrip = TCkCtTrip;
	}

	@Column(name = "CG_CARGO_DESC", length = 16777215)
	public String getCgCargoDesc() {
		return this.cgCargoDesc;
	}

	public void setCgCargoDesc(String cgCargoDesc) {
		this.cgCargoDesc = cgCargoDesc;
	}

	@Column(name = "CG_CARGO_SPECIAL_INSTN", length = 16777215)
	public String getCgCargoSpecialInstn() {
		return this.cgCargoSpecialInstn;
	}

	public void setCgCargoSpecialInstn(String cgCargoSpecialInstn) {
		this.cgCargoSpecialInstn = cgCargoSpecialInstn;
	}

	@Column(name = "CG_CARGO_QTY")
	public Double getCgCargoQty() {
		return this.cgCargoQty;
	}

	public void setCgCargoQty(Double cgCargoQty) {
		this.cgCargoQty = cgCargoQty;
	}

	@Column(name = "CG_CARGO_MARKS_NO", length = 65535)
	public String getCgCargoMarksNo() {
		return this.cgCargoMarksNo;
	}

	public void setCgCargoMarksNo(String cgCargoMarksNo) {
		this.cgCargoMarksNo = cgCargoMarksNo;
	}

	@Column(name = "CG_CARGO_LENGTH")
	public Double getCgCargoLength() {
		return this.cgCargoLength;
	}

	public void setCgCargoLength(Double cgCargoLength) {
		this.cgCargoLength = cgCargoLength;
	}

	@Column(name = "CG_CARGO_WIDTH")
	public Double getCgCargoWidth() {
		return this.cgCargoWidth;
	}

	public void setCgCargoWidth(Double cgCargoWidth) {
		this.cgCargoWidth = cgCargoWidth;
	}

	@Column(name = "CG_CARGO_HEIGHT")
	public Double getCgCargoHeight() {
		return this.cgCargoHeight;
	}

	public void setCgCargoHeight(Double cgCargoHeight) {
		this.cgCargoHeight = cgCargoHeight;
	}

	@Column(name = "CG_CARGO_WEIGHT")
	public Double getCgCargoWeight() {
		return this.cgCargoWeight;
	}

	public void setCgCargoWeight(Double cgCargoWeight) {
		this.cgCargoWeight = cgCargoWeight;
	}

	@Column(name = "CG_CARGO_VOLUME")
	public Double getCgCargoVolume() {
		return this.cgCargoVolume;
	}

	public void setCgCargoVolume(Double cgCargoVolume) {
		this.cgCargoVolume = cgCargoVolume;
	}

	@Column(name = "CG_STATUS", length = 1)
	public Character getCgStatus() {
		return this.cgStatus;
	}

	public void setCgStatus(Character cgStatus) {
		this.cgStatus = cgStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CG_DT_CREATE", length = 19)
	@CreationTimestamp
	public Date getCgDtCreate() {
		return this.cgDtCreate;
	}

	public void setCgDtCreate(Date cgDtCreate) {
		this.cgDtCreate = cgDtCreate;
	}

	@Column(name = "CG_UID_CREATE", length = 35)
	public String getCgUidCreate() {
		return this.cgUidCreate;
	}

	public void setCgUidCreate(String cgUidCreate) {
		this.cgUidCreate = cgUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CG_DT_LUPD", length = 19)
	@UpdateTimestamp
	public Date getCgDtLupd() {
		return this.cgDtLupd;
	}

	public void setCgDtLupd(Date cgDtLupd) {
		this.cgDtLupd = cgDtLupd;
	}

	@Column(name = "CG_UID_LUPD", length = 35)
	public String getCgUidLupd() {
		return this.cgUidLupd;
	}

	public void setCgUidLupd(String cgUidLupd) {
		this.cgUidLupd = cgUidLupd;
	}

	@Column(name = "CG_PICKUP_STATUS", length = 1)
	public Character getCgPickupStatus() {
		return cgPickupStatus;
	}

	public void setCgPickupStatus(Character cgPickupStatus) {
		this.cgPickupStatus = cgPickupStatus;
	}


	@Column(name = "CG_DROPOFF_STATUS", length = 1)
	public Character getCgDropOffStatus() {
		return cgDropOffStatus;
	}

	public void setCgDropOffStatus(Character cgDropOffStatus) {
		this.cgDropOffStatus = cgDropOffStatus;
	}

	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkCtTripCargoMm o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

}
