package com.guudint.clickargo.clictruck.planexec.trip.model;
// Generated 9 May, 2023 2:31:30 PM by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import org.springframework.beans.BeanUtils;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.guudint.clickargo.clictruck.master.model.TCkCtMstReimbursementType;
import com.guudint.clickargo.clictruck.planexec.trip.dto.CkCtTripReimbursement;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtTripReimbursement generated by hbm2java
 */
@Entity
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
@Table(name = "T_CK_CT_TRIP_REIMBURSEMENT")
public class TCkCtTripReimbursement extends COAbstractEntity<TCkCtTripReimbursement> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 3885571606328962869L;

	// Attributes
	/////////////
	private String trId;
	private TCkCtMstReimbursementType TCkCtMstReimbursementType;
	private TCkCtTrip TCkCtTrip;
	private String trReceiptName;
	private String trReceiptLoc;
	private String trRemarks;
	private BigDecimal trPrice;
	private BigDecimal trTax;
	private BigDecimal trTotal;
	private Character trStatus;
	private Date trDtCreate;
	private String trUidCreate;
	private Date trDtLupd;
	private String trUidLupd;

	// Constructors
	///////////////
	public TCkCtTripReimbursement() {
	}

	public TCkCtTripReimbursement(String trId, TCkCtMstReimbursementType TCkCtMstReimbursementType,
			TCkCtTrip TCkCtTrip) {
		this.trId = trId;
		this.TCkCtMstReimbursementType = TCkCtMstReimbursementType;
		this.TCkCtTrip = TCkCtTrip;
	}

	public TCkCtTripReimbursement(CkCtTripReimbursement ckCtTripReimbursement) {
		BeanUtils.copyProperties(ckCtTripReimbursement, this, "base64File");
	}

	public TCkCtTripReimbursement(String trId, TCkCtMstReimbursementType TCkCtMstReimbursementType, TCkCtTrip TCkCtTrip,
			String trReceiptName, String trReceiptLoc, String trRemarks, BigDecimal trPrice, BigDecimal trTax,
			BigDecimal trTotal, Character trStatus, Date trDtCreate, String trUidCreate, Date trDtLupd,
			String trUidLupd) {
		this.trId = trId;
		this.TCkCtMstReimbursementType = TCkCtMstReimbursementType;
		this.TCkCtTrip = TCkCtTrip;
		this.trReceiptName = trReceiptName;
		this.trReceiptLoc = trReceiptLoc;
		this.trRemarks = trRemarks;
		this.trPrice = trPrice;
		this.trTax = trTax;
		this.trTotal = trTotal;
		this.trStatus = trStatus;
		this.trDtCreate = trDtCreate;
		this.trUidCreate = trUidCreate;
		this.trDtLupd = trDtLupd;
		this.trUidLupd = trUidLupd;
	}

	// Properties
	/////////////
	@Id
	@Column(name = "TR_ID", unique = true, nullable = false, length = 35)
	public String getTrId() {
		return this.trId;
	}

	public void setTrId(String trId) {
		this.trId = trId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TR_TYPE", nullable = false)
	public TCkCtMstReimbursementType getTCkCtMstReimbursementType() {
		return this.TCkCtMstReimbursementType;
	}

	public void setTCkCtMstReimbursementType(TCkCtMstReimbursementType TCkCtMstReimbursementType) {
		this.TCkCtMstReimbursementType = TCkCtMstReimbursementType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TR_TRIP", nullable = false)
	public TCkCtTrip getTCkCtTrip() {
		return this.TCkCtTrip;
	}

	public void setTCkCtTrip(TCkCtTrip TCkCtTrip) {
		this.TCkCtTrip = TCkCtTrip;
	}

	@Column(name = "TR_RECEIPT_NAME", length = 256)
	public String getTrReceiptName() {
		return this.trReceiptName;
	}

	public void setTrReceiptName(String trReceiptName) {
		this.trReceiptName = trReceiptName;
	}

	@Column(name = "TR_RECEIPT_LOC", length = 1024)
	public String getTrReceiptLoc() {
		return this.trReceiptLoc;
	}

	public void setTrReceiptLoc(String trReceiptLoc) {
		this.trReceiptLoc = trReceiptLoc;
	}

	@Column(name = "TR_REMARKS", length = 16777215)
	public String getTrRemarks() {
		return this.trRemarks;
	}

	public void setTrRemarks(String trRemarks) {
		this.trRemarks = trRemarks;
	}

	@Column(name = "TR_PRICE", precision = 15)
	public BigDecimal getTrPrice() {
		return this.trPrice;
	}

	public void setTrPrice(BigDecimal trPrice) {
		this.trPrice = trPrice;
	}

	@Column(name = "TR_TAX", precision = 15)
	public BigDecimal getTrTax() {
		return this.trTax;
	}

	public void setTrTax(BigDecimal trTax) {
		this.trTax = trTax;
	}

	@Column(name = "TR_TOTAL", precision = 15)
	public BigDecimal getTrTotal() {
		return this.trTotal;
	}

	public void setTrTotal(BigDecimal trTotal) {
		this.trTotal = trTotal;
	}

	@Column(name = "TR_STATUS", length = 1)
	public Character getTrStatus() {
		return this.trStatus;
	}

	public void setTrStatus(Character trStatus) {
		this.trStatus = trStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TR_DT_CREATE", length = 19)
	@CreationTimestamp
	public Date getTrDtCreate() {
		return this.trDtCreate;
	}

	public void setTrDtCreate(Date trDtCreate) {
		this.trDtCreate = trDtCreate;
	}

	@Column(name = "TR_UID_CREATE", length = 35)
	public String getTrUidCreate() {
		return this.trUidCreate;
	}

	public void setTrUidCreate(String trUidCreate) {
		this.trUidCreate = trUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TR_DT_LUPD", length = 19)
	@UpdateTimestamp
	public Date getTrDtLupd() {
		return this.trDtLupd;
	}

	public void setTrDtLupd(Date trDtLupd) {
		this.trDtLupd = trDtLupd;
	}

	@Column(name = "TR_UID_LUPD", length = 35)
	public String getTrUidLupd() {
		return this.trUidLupd;
	}

	public void setTrUidLupd(String trUidLupd) {
		this.trUidLupd = trUidLupd;
	}

	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkCtTripReimbursement o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}
}
