package com.guudint.clickargo.clictruck.planexec.trip.model;
// Generated 05 15, 23 10:36:37 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtTripDoAttach generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_TRIP_DO_ATTACH")
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
public class TCkCtTripDoAttach extends COAbstractEntity<TCkCtTripDoAttach> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 6555098932886946733L;
	
	// Attributes
	/////////////
	private String doaId;
	private TCkCtTrip TCkCtTrip;
	private String doaName;
	private String doaLoc;
	private String doaSource;
	private Character doaStatus;
	private Date doaDtCreate;
	private String doaUidCreate;
	private Date doaDtLupd;
	private String doaUidLupd;

	// Constructors
	///////////////
	public TCkCtTripDoAttach() {
	}

	public TCkCtTripDoAttach(String doaId, TCkCtTrip TCkCtTrip) {
		this.doaId = doaId;
		this.TCkCtTrip = TCkCtTrip;
	}

	public TCkCtTripDoAttach(String doaId, TCkCtTrip TCkCtTrip, String doaName, String doaLoc, Character doaStatus,
			Date doaDtCreate, String doaUidCreate, Date doaDtLupd, String doaUidLupd) {
		this.doaId = doaId;
		this.TCkCtTrip = TCkCtTrip;
		this.doaName = doaName;
		this.doaLoc = doaLoc;
		this.doaStatus = doaStatus;
		this.doaDtCreate = doaDtCreate;
		this.doaUidCreate = doaUidCreate;
		this.doaDtLupd = doaDtLupd;
		this.doaUidLupd = doaUidLupd;
	}

	// Properties
	/////////////
	@Id
	@Column(name = "DOA_ID", unique = true, nullable = false, length = 35)
	public String getDoaId() {
		return this.doaId;
	}

	public void setDoaId(String doaId) {
		this.doaId = doaId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "DOA_TRIP", nullable = false)
	public TCkCtTrip getTCkCtTrip() {
		return this.TCkCtTrip;
	}

	public void setTCkCtTrip(TCkCtTrip TCkCtTrip) {
		this.TCkCtTrip = TCkCtTrip;
	}

	@Column(name = "DOA_NAME", length = 256)
	public String getDoaName() {
		return this.doaName;
	}

	public void setDoaName(String doaName) {
		this.doaName = doaName;
	}

	@Column(name = "DOA_LOC", length = 1024)
	public String getDoaLoc() {
		return this.doaLoc;
	}

	public void setDoaLoc(String doaLoc) {
		this.doaLoc = doaLoc;
	}

	@Column(name = "DOA_SOURCE", length = 45)
	public String getDoaSource() {
		return this.doaSource;
	}

	public void setDoaSource(String doaSource) {
		this.doaSource = doaSource;
	}

	@Column(name = "DOA_STATUS", length = 1)
	public Character getDoaStatus() {
		return this.doaStatus;
	}

	public void setDoaStatus(Character doaStatus) {
		this.doaStatus = doaStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DOA_DT_CREATE", length = 19)
	@CreationTimestamp
	public Date getDoaDtCreate() {
		return this.doaDtCreate;
	}

	public void setDoaDtCreate(Date doaDtCreate) {
		this.doaDtCreate = doaDtCreate;
	}

	@Column(name = "DOA_UID_CREATE", length = 35)
	public String getDoaUidCreate() {
		return this.doaUidCreate;
	}

	public void setDoaUidCreate(String doaUidCreate) {
		this.doaUidCreate = doaUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DOA_DT_LUPD", length = 19)
	@UpdateTimestamp
	public Date getDoaDtLupd() {
		return this.doaDtLupd;
	}

	public void setDoaDtLupd(Date doaDtLupd) {
		this.doaDtLupd = doaDtLupd;
	}

	@Column(name = "DOA_UID_LUPD", length = 35)
	public String getDoaUidLupd() {
		return this.doaUidLupd;
	}

	public void setDoaUidLupd(String doaUidLupd) {
		this.doaUidLupd = doaUidLupd;
	}

	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkCtTripDoAttach o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

}
