import Mock from "../../../mock";

const data = {
  "iTotalRecords": 1,
  "iTotalDisplayRecords": 1,
  "aaData": [
      {
          "otherLangDesc": null,
          "coreMstLocale": null,
          "vhId": "CKCTVEH2023032958275",
          "vhPlateNo": "83738",
          "vhClass": 2,
          "vhPhotoName": null,
          "vhPhotoLoc": null,
          "vhLength": 20,
          "vhWidth": 230,
          "vhHeight": 30,
          "vhWeight": 30,
          "vhVolume": 30,
          "vhChassisNo": "9373837",
          "vhIsMaintenance": "N",
          "vhRemarks": "reay",
          "vhGpsImei": "334343",
          "vhStatus": "A",
          "vhDtCreate": 1680081299000,
          "vhUidCreate": "ALKNAR_U001",
          "vhDtLupd": 1680081509000,
          "vhUidLupd": "ALKNAR_U001",
          "tckCtMstVehState": null,
          "tckCtMstChassisType": {
              "otherLangDesc": null,
              "coreMstLocale": null,
              "chtyId": "20FT",
              "chtyName": "20FT CHASSIS",
              "chtyDesc": "20FT CHASSIS",
              "chtyDescOth": "20FT CHASSIS",
              "chtyStatus": "A",
              "chtyDtCreate": 1601485200000,
              "chtyUidCreate": "SYS",
              "chtyDtLupd": 1601485200000,
              "chtyUidLupd": "SYS",
              "tckCtVehs": []
          },
          "tckCtMstVehType": {
              "otherLangDesc": null,
              "coreMstLocale": null,
              "vhtyId": "CONTAINER 40FT",
              "vhtyName": "CONTAINER 40FT",
              "vhtyDesc": "CONTAINER 40FT",
              "vhtyDescOth": "CONTAINER 40FT",
              "vhtyStatus": "A",
              "vhtyDtCreate": 1601485200000,
              "vhtyUidCreate": "SYS",
              "vhtyDtLupd": 1601485200000,
              "vhtyUidLupd": "SYS",
              "ckCtTripRates": [],
              "ckCtRentalVehs": [],
              "ckCtVehs": []
          },
          "tcoreAccn": {
              "otherLangDesc": null,
              "coreMstLocale": null,
              "accnId": "ALKNAR",
              "accnStatus": "A",
              "accnName": "Alkindo Naratama",
              "accnNameOth": "Alkindo Naratama",
              "accnCoyRegn": "21",
              "accnPassNid": null,
              "accnNationality": "Indonesia",
              "accnVatFlag": null,
              "accnVatNo": null,
              "accnAddr": null,
              "accnContact": null,
              "accnDtAgree": null,
              "accnDtReg": 1664557200000,
              "accnDtDereg": null,
              "accnDtRereg": null,
              "accnDtSusp": null,
              "accnDtReins": null,
              "accnDtCreate": 1664557200000,
              "accnUidCreate": "SYS",
              "accnDtLupd": 1664557200000,
              "accnUidLupd": "SYS",
              "accnBusinessAct": null,
              "accnOwnerNationality": null,
              "accnOwnerName": null,
              "cityCode": "23",
              "coreLocale": null,
              "TMstAccnType": null
          }
      },
      {
        "otherLangDesc": null,
        "coreMstLocale": null,
        "vhId": "CKCTVEH2023032958277",
        "vhPlateNo": "83738",
        "vhClass": 2,
        "vhPhotoName": null,
        "vhPhotoLoc": null,
        "vhLength": 20,
        "vhWidth": 230,
        "vhHeight": 30,
        "vhWeight": 30,
        "vhVolume": 30,
        "vhChassisNo": "9373837",
        "vhIsMaintenance": "N",
        "vhRemarks": "reay",
        "vhGpsImei": "334343",
        "vhStatus": "I",
        "vhDtCreate": 1680081299000,
        "vhUidCreate": "ALKNAR_U001",
        "vhDtLupd": 1680081509000,
        "vhUidLupd": "ALKNAR_U001",
        "tckCtMstVehState": null,
        "tckCtMstChassisType": {
            "otherLangDesc": null,
            "coreMstLocale": null,
            "chtyId": "20FT",
            "chtyName": "20FT CHASSIS",
            "chtyDesc": "20FT CHASSIS",
            "chtyDescOth": "20FT CHASSIS",
            "chtyStatus": "A",
            "chtyDtCreate": 1601485200000,
            "chtyUidCreate": "SYS",
            "chtyDtLupd": 1601485200000,
            "chtyUidLupd": "SYS",
            "tckCtVehs": []
        },
        "tckCtMstVehType": {
            "otherLangDesc": null,
            "coreMstLocale": null,
            "vhtyId": "CONTAINER 40FT",
            "vhtyName": "CONTAINER 40FT",
            "vhtyDesc": "CONTAINER 40FT",
            "vhtyDescOth": "CONTAINER 40FT",
            "vhtyStatus": "A",
            "vhtyDtCreate": 1601485200000,
            "vhtyUidCreate": "SYS",
            "vhtyDtLupd": 1601485200000,
            "vhtyUidLupd": "SYS",
            "ckCtTripRates": [],
            "ckCtRentalVehs": [],
            "ckCtVehs": []
        },
        "tcoreAccn": {
            "otherLangDesc": null,
            "coreMstLocale": null,
            "accnId": "ALKNAR",
            "accnStatus": "A",
            "accnName": "Alkindo Naratama",
            "accnNameOth": "Alkindo Naratama",
            "accnCoyRegn": "21",
            "accnPassNid": null,
            "accnNationality": "Indonesia",
            "accnVatFlag": null,
            "accnVatNo": null,
            "accnAddr": null,
            "accnContact": null,
            "accnDtAgree": null,
            "accnDtReg": 1664557200000,
            "accnDtDereg": null,
            "accnDtRereg": null,
            "accnDtSusp": null,
            "accnDtReins": null,
            "accnDtCreate": 1664557200000,
            "accnUidCreate": "SYS",
            "accnDtLupd": 1664557200000,
            "accnUidLupd": "SYS",
            "accnBusinessAct": null,
            "accnOwnerNationality": null,
            "accnOwnerName": null,
            "cityCode": "23",
            "coreLocale": null,
            "TMstAccnType": null
        }
    }
  ]
}

  Mock.onGet(/api\/v1\/clickargo\/clictruck\/administrator\/vehicle\/list\/?.*/).reply((config) => {
    return [200, data];
  });


  Mock.onGet(/api\/v1\/clickargo\/clictruck\/job\/truck\/list\/?.*/).reply((config) => {
    return [200, data];
  });