package com.guudint.clickargo.clictruck.sage.dto;


import java.util.Date;

import com.guudint.clickargo.clictruck.sage.model.VCkSageBooking;
import com.vcc.camelone.common.dto.AbstractDTO;

/**
 * VSageBooking generated by hbm2java
 */

public class CkSageBooking extends AbstractDTO<CkSageBooking, VCkSageBooking> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -1L;
	
	private String service;
	private String sageType;
	private String reference;
	private String datetime;
	private String typeId;
	private String sageId;
	private String tranType;
	private String docNo;
	private String issuedDate;
	private String ccy;
	private Long amount;
	private Long vat;
	private Long duty;
	private String terms;
	private String taxNo;
	private Long total;
	private Date rcdDtBillApproved;


	// Constructors
	///////////////
	public CkSageBooking() {
		
	}
	
	public CkSageBooking(VCkSageBooking entity) {
		
		super(entity);
		
		this.typeId = entity.getId().getTypeId();
		this.sageId = entity.getId().getSageId();
		this.docNo = entity.getId().getDocNo();
	}

	
	// Override Methods
	///////////////////
	@Override
	public int compareTo(CkSageBooking arg0) {
		return 0;
	}

	@Override
	public void init() {

	}

	public String getService() {
		return this.service;
	}

	public void setService(String service) {
		this.service = service;
	}

	public String getSageType() {
		return this.sageType;
	}

	public void setSageType(String sageType) {
		this.sageType = sageType;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public String getDatetime() {
		return this.datetime;
	}

	public void setDatetime(String datetime) {
		this.datetime = datetime;
	}

	public String getTypeId() {
		return this.typeId;
	}

	public void setTypeId(String typeId) {
		this.typeId = typeId;
	}

	public String getSageId() {
		return this.sageId;
	}

	public void setSageId(String sageId) {
		this.sageId = sageId;
	}

	public String getTranType() {
		return this.tranType;
	}

	public void setTranType(String tranType) {
		this.tranType = tranType;
	}

	public String getDocNo() {
		return this.docNo;
	}

	public void setDocNo(String docNo) {
		this.docNo = docNo;
	}

	public String getIssuedDate() {
		return this.issuedDate;
	}

	public void setIssuedDate(String issuedDate) {
		this.issuedDate = issuedDate;
	}

	public String getCcy() {
		return this.ccy;
	}

	public void setCcy(String ccy) {
		this.ccy = ccy;
	}

	public Long getAmount() {
		return this.amount;
	}

	public void setAmount(Long amount) {
		this.amount = amount;
	}

	public Long getVat() {
		return this.vat;
	}

	public void setVat(Long vat) {
		this.vat = vat;
	}

	public Long getDuty() {
		return this.duty;
	}

	public void setDuty(Long duty) {
		this.duty = duty;
	}

	public String getTerms() {
		return this.terms;
	}

	public void setTerms(String terms) {
		this.terms = terms;
	}

	public String getTaxNo() {
		return this.taxNo;
	}

	public void setTaxNo(String taxNo) {
		this.taxNo = taxNo;
	}

	public Long getTotal() {
		return this.total;
	}

	public void setTotal(Long total) {
		this.total = total;
	}

	public Date getRcdDtBillApproved() {
		return this.rcdDtBillApproved;
	}

	public void setRcdDtBillApproved(Date rcdDtBillApproved) {
		this.rcdDtBillApproved = rcdDtBillApproved;
	}

}
