package com.guudint.clickargo.clictruck.admin.ratetable.model;
// Generated 14 Sep 2023, 6:32:21 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtRateTableRemark generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_RATE_TABLE_REMARK")
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
public class TCkCtRateTableRemark extends COAbstractEntity<TCkCtRateTableRemark> {

	private static final long serialVersionUID = 4833919978245007184L;
	private String rtrId;
	private TCkCtRateTable TCkCtRateTable;
	private char rtrType;
	private String rtrComment;
	private Character rtrStatus;
	private Date rtrDtCreate;
	private String rtrUidCreate;
	private Date rtrDtLupd;
	private String rtrUidLupd;

	public TCkCtRateTableRemark() {
	}

	public TCkCtRateTableRemark(String rtrId, TCkCtRateTable TCkCtRateTable, char rtrType) {
		this.rtrId = rtrId;
		this.TCkCtRateTable = TCkCtRateTable;
		this.rtrType = rtrType;
	}

	public TCkCtRateTableRemark(String rtrId, TCkCtRateTable TCkCtRateTable, char rtrType, String rtrComment,
			Character rtrStatus, Date rtrDtCreate, String rtrUidCreate, Date rtrDtLupd, String rtrUidLupd) {
		this.rtrId = rtrId;
		this.TCkCtRateTable = TCkCtRateTable;
		this.rtrType = rtrType;
		this.rtrComment = rtrComment;
		this.rtrStatus = rtrStatus;
		this.rtrDtCreate = rtrDtCreate;
		this.rtrUidCreate = rtrUidCreate;
		this.rtrDtLupd = rtrDtLupd;
		this.rtrUidLupd = rtrUidLupd;
	}

	@Id

	@Column(name = "RTR_ID", unique = true, nullable = false, length = 35)
	public String getRtrId() {
		return this.rtrId;
	}

	public void setRtrId(String rtrId) {
		this.rtrId = rtrId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "RTR_RATE_TABLE", nullable = false)
	public TCkCtRateTable getTCkCtRateTable() {
		return this.TCkCtRateTable;
	}

	public void setTCkCtRateTable(TCkCtRateTable TCkCtRateTable) {
		this.TCkCtRateTable = TCkCtRateTable;
	}

	@Column(name = "RTR_TYPE", nullable = false, length = 1)
	public char getRtrType() {
		return this.rtrType;
	}

	public void setRtrType(char rtrType) {
		this.rtrType = rtrType;
	}

	@Column(name = "RTR_COMMENT", length = 16777215)
	public String getRtrComment() {
		return this.rtrComment;
	}

	public void setRtrComment(String rtrComment) {
		this.rtrComment = rtrComment;
	}

	@Column(name = "RTR_STATUS", length = 1)
	public Character getRtrStatus() {
		return this.rtrStatus;
	}

	public void setRtrStatus(Character rtrStatus) {
		this.rtrStatus = rtrStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RTR_DT_CREATE", length = 19)
	public Date getRtrDtCreate() {
		return this.rtrDtCreate;
	}

	public void setRtrDtCreate(Date rtrDtCreate) {
		this.rtrDtCreate = rtrDtCreate;
	}

	@Column(name = "RTR_UID_CREATE", length = 35)
	public String getRtrUidCreate() {
		return this.rtrUidCreate;
	}

	public void setRtrUidCreate(String rtrUidCreate) {
		this.rtrUidCreate = rtrUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RTR_DT_LUPD", length = 19)
	public Date getRtrDtLupd() {
		return this.rtrDtLupd;
	}

	public void setRtrDtLupd(Date rtrDtLupd) {
		this.rtrDtLupd = rtrDtLupd;
	}

	@Column(name = "RTR_UID_LUPD", length = 35)
	public String getRtrUidLupd() {
		return this.rtrUidLupd;
	}

	public void setRtrUidLupd(String rtrUidLupd) {
		this.rtrUidLupd = rtrUidLupd;
	}

	@Override
	public int compareTo(TCkCtRateTableRemark o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
