package com.guudint.clickargo.clictruck.admin.ratetable.model;
// Generated 21 Feb, 2023 3:06:01 PM by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.guudint.clickargo.clictruck.common.model.TCkCtLocation;
import com.guudint.clickargo.clictruck.master.model.TCkCtMstVehType;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtTripRate generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_TRIP_RATE")
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
public class TCkCtTripRate extends COAbstractEntity<TCkCtTripRate> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -1655963418878177294L;

	// Attributes
	/////////////
	private String trId;
	private TCkCtLocation TCkCtLocationByTrLocTo;
	private TCkCtLocation TCkCtLocationByTrLocFrom;
	private TCkCtMstVehType TCkCtMstVehType;
	private TCkCtRateTable TCkCtRateTable;
	private BigDecimal trCharge;
	private Character trStatus;
	private Date trDtCreate;
	private String trUidCreate;
	private Date trDtLupd;
	private String trUidLupd;
	
	private TCkCtTripRate TCkCtTripRate;
	private String trType;
	private Integer trSeq;
	private List<TCkCtTripRate> TCkCtTripRates = new ArrayList<TCkCtTripRate>(0);

	public TCkCtTripRate() {
	}

	public TCkCtTripRate(String trId, TCkCtRateTable TCkCtRateTable) {
		this.trId = trId;
		this.TCkCtRateTable = TCkCtRateTable;
	}

	public TCkCtTripRate(String trId, TCkCtLocation TCkCtLocationByTrLocTo, TCkCtLocation TCkCtLocationByTrLocFrom,
			TCkCtMstVehType TCkCtMstVehType, TCkCtRateTable TCkCtRateTable, BigDecimal trCharge, Character trStatus,
			Date trDtCreate, String trUidCreate, Date trDtLupd, String trUidLupd) {
		this.trId = trId;
		this.TCkCtLocationByTrLocTo = TCkCtLocationByTrLocTo;
		this.TCkCtLocationByTrLocFrom = TCkCtLocationByTrLocFrom;
		this.TCkCtMstVehType = TCkCtMstVehType;
		this.TCkCtRateTable = TCkCtRateTable;
		this.trCharge = trCharge;
		this.trStatus = trStatus;
		this.trDtCreate = trDtCreate;
		this.trUidCreate = trUidCreate;
		this.trDtLupd = trDtLupd;
		this.trUidLupd = trUidLupd;
	}


	@Override
	public int compareTo(TCkCtTripRate o) {
		return 0;
	}

	@Override
	public void init() {

	}
	
	@Id

	@Column(name = "TR_ID", unique = true, nullable = false, length = 35)
	public String getTrId() {
		return this.trId;
	}

	public void setTrId(String trId) {
		this.trId = trId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "TR_LOC_TO")
	public TCkCtLocation getTCkCtLocationByTrLocTo() {
		return this.TCkCtLocationByTrLocTo;
	}

	public void setTCkCtLocationByTrLocTo(TCkCtLocation TCkCtLocationByTrLocTo) {
		this.TCkCtLocationByTrLocTo = TCkCtLocationByTrLocTo;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "TR_LOC_FROM")
	public TCkCtLocation getTCkCtLocationByTrLocFrom() {
		return this.TCkCtLocationByTrLocFrom;
	}

	public void setTCkCtLocationByTrLocFrom(TCkCtLocation TCkCtLocationByTrLocFrom) {
		this.TCkCtLocationByTrLocFrom = TCkCtLocationByTrLocFrom;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "TR_VEH_TYPE")
	public TCkCtMstVehType getTCkCtMstVehType() {
		return this.TCkCtMstVehType;
	}

	public void setTCkCtMstVehType(TCkCtMstVehType TCkCtMstVehType) {
		this.TCkCtMstVehType = TCkCtMstVehType;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "TR_RATE_TABLE", nullable = false)
	public TCkCtRateTable getTCkCtRateTable() {
		return this.TCkCtRateTable;
	}

	public void setTCkCtRateTable(TCkCtRateTable TCkCtRateTable) {
		this.TCkCtRateTable = TCkCtRateTable;
	}

	@Column(name = "TR_CHARGE", precision = 15)
	public BigDecimal getTrCharge() {
		return this.trCharge;
	}

	public void setTrCharge(BigDecimal trCharge) {
		this.trCharge = trCharge;
	}

	@Column(name = "TR_STATUS", length = 1)
	public Character getTrStatus() {
		return this.trStatus;
	}

	public void setTrStatus(Character trStatus) {
		this.trStatus = trStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TR_DT_CREATE", length = 19)
	public Date getTrDtCreate() {
		return this.trDtCreate;
	}

	public void setTrDtCreate(Date trDtCreate) {
		this.trDtCreate = trDtCreate;
	}

	@Column(name = "TR_UID_CREATE", length = 35)
	public String getTrUidCreate() {
		return this.trUidCreate;
	}

	public void setTrUidCreate(String trUidCreate) {
		this.trUidCreate = trUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TR_DT_LUPD", length = 19)
	public Date getTrDtLupd() {
		return this.trDtLupd;
	}

	public void setTrDtLupd(Date trDtLupd) {
		this.trDtLupd = trDtLupd;
	}

	@Column(name = "TR_UID_LUPD", length = 35)
	public String getTrUidLupd() {
		return this.trUidLupd;
	}

	public void setTrUidLupd(String trUidLupd) {
		this.trUidLupd = trUidLupd;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TR_PARENT")
	public TCkCtTripRate getTCkCtTripRate() {
		return this.TCkCtTripRate;
	}

	public void setTCkCtTripRate(TCkCtTripRate TCkCtTripRate) {
		this.TCkCtTripRate = TCkCtTripRate;
	}

	@Column(name = "TR_TYPE", length = 1)
	public String getTrType() {
		return this.trType;
	}

	public void setTrType(String trType) {
		this.trType = trType;
	}

	@Column(name = "TR_SEQ")
	public Integer getTrSeq() {
		return this.trSeq;
	}

	public void setTrSeq(Integer trSeq) {
		this.trSeq = trSeq;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCkCtTripRate")
	public List<TCkCtTripRate> getTCkCtTripRates() {
		return this.TCkCtTripRates;
	}

	public void setTCkCtTripRates(List<TCkCtTripRate> TCkCtTripRates) {
		this.TCkCtTripRates = TCkCtTripRates;
	}

}
