package com.guudint.clickargo.clictruck.admin.rental.model;
// Generated 21 Feb, 2023 3:06:01 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;
import com.vcc.camelone.master.model.TMstCurrency;

/**
 * TCkCtRentalTable generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_RENTAL_TABLE")
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
public class TCkCtRentalTable  extends COAbstractEntity<TCkCtRentalTable> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -2653749103802105371L;
	
	// Attributes
	/////////////
	private String rtId;
	private TCoreAccn TCoreAccnByRtCompany;
	private TCoreAccn TCoreAccnByRtCoFf;
	private TMstCurrency TMstCurrency;
	private String rtName;
	private String rtDescription;
	private Date rtDtStart;
	private Date rtDtEnd;
	private String rtRemarks;
	private Character rtStatus;
	private Date rtDtCreate;
	private String rtUidCreate;
	private Date rtDtLupd;
	private String rtUidLupd;

	// Constructors
	///////////////
	public TCkCtRentalTable() {
	}

	public TCkCtRentalTable(String rtId) {
		this.rtId = rtId;
	}

	public TCkCtRentalTable(String rtId, TCoreAccn TCoreAccnByRtCompany, TCoreAccn TCoreAccnByRtCoFf,
			TMstCurrency TMstCurrency, String rtName, String rtDescription, Date rtDtStart, Date rtDtEnd,
			String rtRemarks, Character rtStatus, Date rtDtCreate, String rtUidCreate, Date rtDtLupd, String rtUidLupd) {
		this.rtId = rtId;
		this.TCoreAccnByRtCompany = TCoreAccnByRtCompany;
		this.TCoreAccnByRtCoFf = TCoreAccnByRtCoFf;
		this.TMstCurrency = TMstCurrency;
		this.rtName = rtName;
		this.rtDescription = rtDescription;
		this.rtDtStart = rtDtStart;
		this.rtDtEnd = rtDtEnd;
		this.rtRemarks = rtRemarks;
		this.rtStatus = rtStatus;
		this.rtDtCreate = rtDtCreate;
		this.rtUidCreate = rtUidCreate;
		this.rtDtLupd = rtDtLupd;
		this.rtUidLupd = rtUidLupd;
	}

	// Properties
	/////////////
	@Id
	@Column(name = "RT_ID", unique = true, nullable = false, length = 35)
	public String getRtId() {
		return this.rtId;
	}

	public void setRtId(String rtId) {
		this.rtId = rtId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "RT_COMPANY")
	public TCoreAccn getTCoreAccnByRtCompany() {
		return this.TCoreAccnByRtCompany;
	}

	public void setTCoreAccnByRtCompany(TCoreAccn TCoreAccnByRtCompany) {
		this.TCoreAccnByRtCompany = TCoreAccnByRtCompany;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "RT_CO_FF")
	public TCoreAccn getTCoreAccnByRtCoFf() {
		return this.TCoreAccnByRtCoFf;
	}

	public void setTCoreAccnByRtCoFf(TCoreAccn TCoreAccnByRtCoFf) {
		this.TCoreAccnByRtCoFf = TCoreAccnByRtCoFf;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "RT_CCY")
	public TMstCurrency getTMstCurrency() {
		return this.TMstCurrency;
	}

	public void setTMstCurrency(TMstCurrency TMstCurrency) {
		this.TMstCurrency = TMstCurrency;
	}

	@Column(name = "RT_NAME", length = 1024)
	public String getRtName() {
		return this.rtName;
	}

	public void setRtName(String rtName) {
		this.rtName = rtName;
	}

	@Column(name = "RT_DESCRIPTION", length = 16777215)
	public String getRtDescription() {
		return this.rtDescription;
	}

	public void setRtDescription(String rtDescription) {
		this.rtDescription = rtDescription;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RT_DT_START", length = 19)
	public Date getRtDtStart() {
		return this.rtDtStart;
	}

	public void setRtDtStart(Date rtDtStart) {
		this.rtDtStart = rtDtStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RT_DT_END", length = 19)
	public Date getRtDtEnd() {
		return this.rtDtEnd;
	}

	public void setRtDtEnd(Date rtDtEnd) {
		this.rtDtEnd = rtDtEnd;
	}

	@Column(name = "RT_REMARKS", length = 65535)
	public String getRtRemarks() {
		return this.rtRemarks;
	}

	public void setRtRemarks(String rtRemarks) {
		this.rtRemarks = rtRemarks;
	}

	@Column(name = "RT_STATUS", length = 1)
	public Character getRtStatus() {
		return this.rtStatus;
	}

	public void setRtStatus(Character rtStatus) {
		this.rtStatus = rtStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RT_DT_CREATE", length = 19)
	@CreationTimestamp
	public Date getRtDtCreate() {
		return this.rtDtCreate;
	}

	public void setRtDtCreate(Date rtDtCreate) {
		this.rtDtCreate = rtDtCreate;
	}

	@Column(name = "RT_UID_CREATE", length = 35)
	public String getRtUidCreate() {
		return this.rtUidCreate;
	}

	public void setRtUidCreate(String rtUidCreate) {
		this.rtUidCreate = rtUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RT_DT_LUPD", length = 19)
	@UpdateTimestamp
	public Date getRtDtLupd() {
		return this.rtDtLupd;
	}

	public void setRtDtLupd(Date rtDtLupd) {
		this.rtDtLupd = rtDtLupd;
	}

	@Column(name = "RT_UID_LUPD", length = 35)
	public String getRtUidLupd() {
		return this.rtUidLupd;
	}

	public void setRtUidLupd(String rtUidLupd) {
		this.rtUidLupd = rtUidLupd;
	}

	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkCtRentalTable o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

}
