package com.guudint.clickargo.clictruck.common.model;
// Generated 21 Feb, 2023 3:06:01 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import org.springframework.beans.BeanUtils;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.guudint.clickargo.clictruck.common.dto.CkCtDrv;
import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtDrv generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_DRV")
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
public class TCkCtDrv extends COAbstractEntity<TCkCtDrv> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 8191831755093035598L;
	
	// Attributes
	/////////////
	private String drvId;
	private TCoreAccn TCoreAccn;
	private String drvName;
	private String drvState;
	private String drvLicenseNo;
	private Date drvLicenseExpiry;
	private String drvLicensePhotoName;
	private String drvLicensePhotoLoc;
	private String drvEmail;
	private String drvPhone;
	private String drvMobileId;
	private String drvMobilePassword;
	private int drvLoginFailure;
	private String drvMobileLang;
	private Character drvStatus;
	private Date drvDtCreate;
	private String drvUidCreate;
	private Date drvDtLupd;
	private String drvUidLupd;

	// Constructors
	///////////////
	public TCkCtDrv() {
	}

	public TCkCtDrv(String drvId) {
		this.drvId = drvId;
	}

	public TCkCtDrv(CkCtDrv ckCtDrv){
		BeanUtils.copyProperties(ckCtDrv, this, "base64File");
	}

	public TCkCtDrv(String drvId, TCoreAccn TCoreAccn, String drvName, String drvLicenseNo,
			Date drvLicenseExpiry, String drvLicensePhotoName, String drvLicensePhotoLoc, String drvEmail,
			String drvPhone, String drvMobileId, String drvMobilePassword, Character drvStatus, Date drvDtCreate,
			String drvUidCreate, Date drvDtLupd, String drvUidLupd) {
		this.drvId = drvId;
		this.TCoreAccn = TCoreAccn;
		this.drvName = drvName;
		this.drvLicenseNo = drvLicenseNo;
		this.drvLicenseExpiry = drvLicenseExpiry;
		this.drvLicensePhotoName = drvLicensePhotoName;
		this.drvLicensePhotoLoc = drvLicensePhotoLoc;
		this.drvEmail = drvEmail;
		this.drvPhone = drvPhone;
		this.drvMobileId = drvMobileId;
		this.drvMobilePassword = drvMobilePassword;
		this.drvStatus = drvStatus;
		this.drvDtCreate = drvDtCreate;
		this.drvUidCreate = drvUidCreate;
		this.drvDtLupd = drvDtLupd;
		this.drvUidLupd = drvUidLupd;
	}

	// Properties
	/////////////
	@Id
	@Column(name = "DRV_ID", unique = true, nullable = false, length = 35)
	public String getDrvId() {
		return this.drvId;
	}

	public void setDrvId(String drvId) {
		this.drvId = drvId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "DRV_COMPANY")
	public TCoreAccn getTCoreAccn() {
		return this.TCoreAccn;
	}

	public void setTCoreAccn(TCoreAccn TCoreAccn) {
		this.TCoreAccn = TCoreAccn;
	}

	@Column(name = "DRV_NAME", length = 256)
	public String getDrvName() {
		return this.drvName;
	}

	public void setDrvName(String drvName) {
		this.drvName = drvName;
	}

	@Column(name = "DRV_LICENSE_NO", length = 256)
	public String getDrvLicenseNo() {
		return this.drvLicenseNo;
	}

	public void setDrvLicenseNo(String drvLicenseNo) {
		this.drvLicenseNo = drvLicenseNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DRV_LICENSE_EXPIRY", length = 19)
	public Date getDrvLicenseExpiry() {
		return this.drvLicenseExpiry;
	}

	public void setDrvLicenseExpiry(Date drvLicenseExpiry) {
		this.drvLicenseExpiry = drvLicenseExpiry;
	}

	@Column(name = "DRV_LICENSE_PHOTO_NAME", length = 256)
	public String getDrvLicensePhotoName() {
		return this.drvLicensePhotoName;
	}

	public void setDrvLicensePhotoName(String drvLicensePhotoName) {
		this.drvLicensePhotoName = drvLicensePhotoName;
	}

	@Column(name = "DRV_LICENSE_PHOTO_LOC", length = 1024)
	public String getDrvLicensePhotoLoc() {
		return this.drvLicensePhotoLoc;
	}

	public void setDrvLicensePhotoLoc(String drvLicensePhotoLoc) {
		this.drvLicensePhotoLoc = drvLicensePhotoLoc;
	}

	@Column(name = "DRV_EMAIL", length = 128)
	public String getDrvEmail() {
		return this.drvEmail;
	}

	public void setDrvEmail(String drvEmail) {
		this.drvEmail = drvEmail;
	}

	@Column(name = "DRV_PHONE", length = 1024)
	public String getDrvPhone() {
		return this.drvPhone;
	}

	public void setDrvPhone(String drvPhone) {
		this.drvPhone = drvPhone;
	}

	@Column(name = "DRV_MOBILE_ID", length = 256)
	public String getDrvMobileId() {
		return this.drvMobileId;
	}

	public void setDrvMobileId(String drvMobileId) {
		this.drvMobileId = drvMobileId;
	}

	@Column(name = "DRV_MOBILE_PASSWORD", length = 256)
	public String getDrvMobilePassword() {
		return this.drvMobilePassword;
	}

	public void setDrvMobilePassword(String drvMobilePassword) {
		this.drvMobilePassword = drvMobilePassword;
	}

	@Column(name = "DRV_LOGIN_FAILURE")
	public int getDrvLoginFailure() {
		return this.drvLoginFailure;
	}

	public void setDrvLoginFailure(int drvLoginFailure) {
		this.drvLoginFailure = drvLoginFailure;
	}

	@Column(name = "DRV_STATUS", length = 1)
	public Character getDrvStatus() {
		return this.drvStatus;
	}

	public void setDrvStatus(Character drvStatus) {
		this.drvStatus = drvStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DRV_DT_CREATE", length = 19)
	@CreationTimestamp
	public Date getDrvDtCreate() {
		return this.drvDtCreate;
	}

	public void setDrvDtCreate(Date drvDtCreate) {
		this.drvDtCreate = drvDtCreate;
	}

	@Column(name = "DRV_UID_CREATE", length = 35)
	public String getDrvUidCreate() {
		return this.drvUidCreate;
	}

	public void setDrvUidCreate(String drvUidCreate) {
		this.drvUidCreate = drvUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DRV_DT_LUPD", length = 19)
	@UpdateTimestamp
	public Date getDrvDtLupd() {
		return this.drvDtLupd;
	}

	public void setDrvDtLupd(Date drvDtLupd) {
		this.drvDtLupd = drvDtLupd;
	}

	@Column(name = "DRV_UID_LUPD", length = 35)
	public String getDrvUidLupd() {
		return this.drvUidLupd;
	}

	public void setDrvUidLupd(String drvUidLupd) {
		this.drvUidLupd = drvUidLupd;
	}
	
	
	@Column(name = "DRV_STATE", length = 35)
	public String getDrvState() {
		return drvState;
	}

	public void setDrvState(String drvState) {
		this.drvState = drvState;
	}

	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkCtDrv o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}
	
	@Column(name = "DRV_MOBILE_LANG", length = 3)
	public String getDrvMobileLang() {
		return this.drvMobileLang;
	}

	public void setDrvMobileLang(String drvMobileLang) {
		this.drvMobileLang = drvMobileLang;
	}

}
