package com.guudint.clickargo.clictruck.common.model;
// Generated 29 Aug 2023, 4:49:59 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.beans.BeanUtils;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.guudint.clickargo.clictruck.common.dto.CkCtTrackDevice;
import com.guudint.clickargo.clictruck.master.model.TCkCtMstTrackDeviceState;
import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;
import com.vcc.camelone.master.model.TMstAccnType;

/**
 * TCkCtTrackDevice generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_TRACK_DEVICE")
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
public class TCkCtTrackDevice extends COAbstractEntity<TCkCtTrackDevice> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -1L;
	public static final String PREFIX_ID = "TD";
	
	private String tdId;
	private TCkCtMstTrackDeviceState TCkCtMstTrackDeviceState;
	private TCkCtVeh TCkCtVeh;
	private TCoreAccn TCoreAccn;
	private TMstAccnType TMstAccnType;
	private String tdVehPlateNo;
	private String tdGpsImei;
	private Date tdDtActivattion;
	private Date tdDtActivate;
	private Date tdDtDeactivate;
	private String tdUidActivate;
	private String tdUidDeactivate;
	private Character tdStatus;
	private Date tdDtCreate;
	private String tdUidCreate;
	private Date tdDtLupd;
	private String tdUidLupd;

	public TCkCtTrackDevice() {
	}

	public TCkCtTrackDevice(String tdId, TCkCtMstTrackDeviceState TCkCtMstTrackDeviceState) {
		this.tdId = tdId;
		this.TCkCtMstTrackDeviceState = TCkCtMstTrackDeviceState;
	}


	// Override Methods
	///////////////////
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	 */
	@Override
	public int compareTo(TCkCtTrackDevice o) {
		return 0;
	}

	public TCkCtTrackDevice(CkCtTrackDevice ckCtTrackDevice){
		BeanUtils.copyProperties(ckCtTrackDevice, this );
	}
	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 * 
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}
	
	@Id

	@Column(name = "TD_ID", unique = true, nullable = false, length = 35)
	public String getTdId() {
		return this.tdId;
	}

	public void setTdId(String tdId) {
		this.tdId = tdId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "TD_STATE", nullable = false)
	public TCkCtMstTrackDeviceState getTCkCtMstTrackDeviceState() {
		return this.TCkCtMstTrackDeviceState;
	}

	public void setTCkCtMstTrackDeviceState(TCkCtMstTrackDeviceState TCkCtMstTrackDeviceState) {
		this.TCkCtMstTrackDeviceState = TCkCtMstTrackDeviceState;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TD_VEH_ID")
	public TCkCtVeh getTCkCtVeh() {
		return this.TCkCtVeh;
	}

	public void setTCkCtVeh(TCkCtVeh TCkCtVeh) {
		this.TCkCtVeh = TCkCtVeh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TD_COMPANY")
	public TCoreAccn getTCoreAccn() {
		return this.TCoreAccn;
	}

	public void setTCoreAccn(TCoreAccn TCoreAccn) {
		this.TCoreAccn = TCoreAccn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TD_COMPANY_TYPE")
	public TMstAccnType getTMstAccnType() {
		return this.TMstAccnType;
	}

	public void setTMstAccnType(TMstAccnType TMstAccnType) {
		this.TMstAccnType = TMstAccnType;
	}

	@Column(name = "TD_VEH_PLATE_NO", length = 256)
	public String getTdVehPlateNo() {
		return this.tdVehPlateNo;
	}

	public void setTdVehPlateNo(String tdVehPlateNo) {
		this.tdVehPlateNo = tdVehPlateNo;
	}

	@Column(name = "TD_GPS_IMEI", length = 1024)
	public String getTdGpsImei() {
		return this.tdGpsImei;
	}

	public void setTdGpsImei(String tdGpsImei) {
		this.tdGpsImei = tdGpsImei;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TD_DT_ACTIVATTION", length = 19)
	public Date getTdDtActivattion() {
		return this.tdDtActivattion;
	}

	public void setTdDtActivattion(Date tdDtActivattion) {
		this.tdDtActivattion = tdDtActivattion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TD_DT_ACTIVATE", length = 19)
	public Date getTdDtActivate() {
		return this.tdDtActivate;
	}

	public void setTdDtActivate(Date tdDtActivate) {
		this.tdDtActivate = tdDtActivate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TD_DT_DEACTIVATE", length = 19)
	public Date getTdDtDeactivate() {
		return this.tdDtDeactivate;
	}

	public void setTdDtDeactivate(Date tdDtDeactivate) {
		this.tdDtDeactivate = tdDtDeactivate;
	}

	@Column(name = "TD_UID_ACTIVATE", length = 35)
	public String getTdUidActivate() {
		return this.tdUidActivate;
	}

	public void setTdUidActivate(String tdUidActivate) {
		this.tdUidActivate = tdUidActivate;
	}

	@Column(name = "TD_UID_DEACTIVATE", length = 35)
	public String getTdUidDeactivate() {
		return this.tdUidDeactivate;
	}

	public void setTdUidDeactivate(String tdUidDeactivate) {
		this.tdUidDeactivate = tdUidDeactivate;
	}

	@Column(name = "TD_STATUS", length = 1)
	public Character getTdStatus() {
		return this.tdStatus;
	}

	public void setTdStatus(Character tdStatus) {
		this.tdStatus = tdStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TD_DT_CREATE", length = 19)
	public Date getTdDtCreate() {
		return this.tdDtCreate;
	}

	public void setTdDtCreate(Date tdDtCreate) {
		this.tdDtCreate = tdDtCreate;
	}

	@Column(name = "TD_UID_CREATE", length = 35)
	public String getTdUidCreate() {
		return this.tdUidCreate;
	}

	public void setTdUidCreate(String tdUidCreate) {
		this.tdUidCreate = tdUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TD_DT_LUPD", length = 19)
	public Date getTdDtLupd() {
		return this.tdDtLupd;
	}

	public void setTdDtLupd(Date tdDtLupd) {
		this.tdDtLupd = tdDtLupd;
	}

	@Column(name = "TD_UID_LUPD", length = 35)
	public String getTdUidLupd() {
		return this.tdUidLupd;
	}

	public void setTdUidLupd(String tdUidLupd) {
		this.tdUidLupd = tdUidLupd;
	}

}
