package com.guudint.clickargo.clictruck.common.model;
// Generated 5 Apr 2024, 2:35:22 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.ccm.model.TCoreUsr;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtAccnInqReq generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_ACCN_INQ_REQ")
public class TCkCtAccnInqReq extends COAbstractEntity<TCkCtAccnInqReq> {

	private static final long serialVersionUID = -4171653960511893098L;
	private String airId;
	private TCoreAccn TCoreAccn;
	private TCoreUsr TCoreUsr;
	private String airEmailReq;
	private String airReqState;
	private String airRemarks;
	private Date airDtProcessed;
	private Character airStatus;
	private Date airDtCreate;
	private String airUidCreate;
	private Date airDtLupd;
	private String airUidLupd;

	public TCkCtAccnInqReq() {
	}

	public TCkCtAccnInqReq(String airId, String airEmailReq) {
		this.airId = airId;
		this.airEmailReq = airEmailReq;
	}

	public TCkCtAccnInqReq(String airId, TCoreAccn TCoreAccn, TCoreUsr TCoreUsr, String airEmailReq, String airReqState,
			Character airStatus, Date airDtCreate, String airUidCreate, Date airDtLupd, String airUidLupd) {
		this.airId = airId;
		this.TCoreAccn = TCoreAccn;
		this.TCoreUsr = TCoreUsr;
		this.airEmailReq = airEmailReq;
		this.airReqState = airReqState;
		this.airStatus = airStatus;
		this.airDtCreate = airDtCreate;
		this.airUidCreate = airUidCreate;
		this.airDtLupd = airDtLupd;
		this.airUidLupd = airUidLupd;
	}

	@Id

	@Column(name = "AIR_ID", unique = true, nullable = false, length = 35)
	public String getAirId() {
		return this.airId;
	}

	public void setAirId(String airId) {
		this.airId = airId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AIR_ACCN_ID")
	public TCoreAccn getTCoreAccn() {
		return this.TCoreAccn;
	}

	public void setTCoreAccn(TCoreAccn TCoreAccn) {
		this.TCoreAccn = TCoreAccn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AIR_PROCESS_BY")
	public TCoreUsr getTCoreUsr() {
		return this.TCoreUsr;
	}

	public void setTCoreUsr(TCoreUsr TCoreUsr) {
		this.TCoreUsr = TCoreUsr;
	}

	@Column(name = "AIR_EMAIL_REQ", nullable = false, length = 128)
	public String getAirEmailReq() {
		return this.airEmailReq;
	}

	public void setAirEmailReq(String airEmailReq) {
		this.airEmailReq = airEmailReq;
	}

	@Column(name = "AIR_REQ_STATE", length = 35)
	public String getAirReqState() {
		return this.airReqState;
	}

	public void setAirReqState(String airReqState) {
		this.airReqState = airReqState;
	}

	@Column(name = "AIR_STATUS", length = 1)
	public Character getAirStatus() {
		return this.airStatus;
	}

	public void setAirStatus(Character airStatus) {
		this.airStatus = airStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AIR_DT_CREATE", length = 19)
	public Date getAirDtCreate() {
		return this.airDtCreate;
	}

	public void setAirDtCreate(Date airDtCreate) {
		this.airDtCreate = airDtCreate;
	}

	@Column(name = "AIR_UID_CREATE", length = 35)
	public String getAirUidCreate() {
		return this.airUidCreate;
	}

	public void setAirUidCreate(String airUidCreate) {
		this.airUidCreate = airUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AIR_DT_LUPD", length = 19)
	public Date getAirDtLupd() {
		return this.airDtLupd;
	}

	public void setAirDtLupd(Date airDtLupd) {
		this.airDtLupd = airDtLupd;
	}

	@Column(name = "AIR_UID_LUPD", length = 35)
	public String getAirUidLupd() {
		return this.airUidLupd;
	}

	public void setAirUidLupd(String airUidLupd) {
		this.airUidLupd = airUidLupd;
	}

	@Column(name = "AIR_REMARKS")
	public String getAirRemarks() {
		return airRemarks;
	}

	public void setAirRemarks(String airRemarks) {
		this.airRemarks = airRemarks;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AIR_DT_PROCESSED", length = 19)
	public Date getAirDtProcessed() {
		return airDtProcessed;
	}

	public void setAirDtProcessed(Date airDtProcessed) {
		this.airDtProcessed = airDtProcessed;
	}

	@Override
	public int compareTo(TCkCtAccnInqReq o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
