package com.guudint.clickargo.clictruck.common.model;
// Generated 29 Apr 2024, 12:17:56 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtDeptVeh generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_DEPT_VEH")
public class TCkCtDeptVeh extends COAbstractEntity<TCkCtDeptVeh> {

	private static final long serialVersionUID = -1204487013883913708L;
	private String dvId;
	private TCkCtDept TCkCtDept;
	private TCkCtVeh TCkCtVeh;
	private Character dvStatus;
	private Date dvDtCreate;
	private String dvUidCreate;
	private Date dvDtLupd;
	private String dvUidLupd;

	public TCkCtDeptVeh() {
	}

	public TCkCtDeptVeh(String dvId) {
		this.dvId = dvId;
	}

	public TCkCtDeptVeh(String dvId, TCkCtDept TCkCtDept, TCkCtVeh TCkCtVeh, Character dvStatus, Date dvDtCreate,
			String dvUidCreate, Date dvDtLupd, String dvUidLupd) {
		this.dvId = dvId;
		this.TCkCtDept = TCkCtDept;
		this.TCkCtVeh = TCkCtVeh;
		this.dvStatus = dvStatus;
		this.dvDtCreate = dvDtCreate;
		this.dvUidCreate = dvUidCreate;
		this.dvDtLupd = dvDtLupd;
		this.dvUidLupd = dvUidLupd;
	}

	@Id

	@Column(name = "DV_ID", unique = true, nullable = false, length = 35)
	public String getDvId() {
		return this.dvId;
	}

	public void setDvId(String dvId) {
		this.dvId = dvId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DV_DEPT")
	public TCkCtDept getTCkCtDept() {
		return this.TCkCtDept;
	}

	public void setTCkCtDept(TCkCtDept TCkCtDept) {
		this.TCkCtDept = TCkCtDept;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DV_VEH")
	public TCkCtVeh getTCkCtVeh() {
		return this.TCkCtVeh;
	}

	public void setTCkCtVeh(TCkCtVeh TCkCtVeh) {
		this.TCkCtVeh = TCkCtVeh;
	}

	@Column(name = "DV_STATUS", length = 1)
	public Character getDvStatus() {
		return this.dvStatus;
	}

	public void setDvStatus(Character dvStatus) {
		this.dvStatus = dvStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DV_DT_CREATE", length = 19)
	public Date getDvDtCreate() {
		return this.dvDtCreate;
	}

	public void setDvDtCreate(Date dvDtCreate) {
		this.dvDtCreate = dvDtCreate;
	}

	@Column(name = "DV_UID_CREATE", length = 35)
	public String getDvUidCreate() {
		return this.dvUidCreate;
	}

	public void setDvUidCreate(String dvUidCreate) {
		this.dvUidCreate = dvUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DV_DT_LUPD", length = 19)
	public Date getDvDtLupd() {
		return this.dvDtLupd;
	}

	public void setDvDtLupd(Date dvDtLupd) {
		this.dvDtLupd = dvDtLupd;
	}

	@Column(name = "DV_UID_LUPD", length = 35)
	public String getDvUidLupd() {
		return this.dvUidLupd;
	}

	public void setDvUidLupd(String dvUidLupd) {
		this.dvUidLupd = dvUidLupd;
	}

	@Override
	public int compareTo(TCkCtDeptVeh o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
