package com.guudint.clickargo.clictruck.common.model;
// Generated 29 Apr 2024, 11:43:46 am by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtCo2x generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_CO2X")
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
public class TCkCtCo2x extends COAbstractEntity<TCkCtCo2x> {

	private static final long serialVersionUID = 7607150371266291081L;
	private String co2xId;
	private TCoreAccn TCoreAccn;
	private String co2xAccnName;
	private String co2xCoyId;
	private Date co2xDtExpiry;
	private String co2xUid;
	private String co2xPwd;
	private Character co2xStatus;
	private Date co2xDtCreate;
	private String co2xUidCreate;
	private Date co2xDtLupd;
	private String co2xUidLupd;

	public TCkCtCo2x() {
	}

	public TCkCtCo2x(String co2xId) {
		this.co2xId = co2xId;
	}

	public TCkCtCo2x(String co2xId, TCoreAccn TCoreAccn, String co2xAccnName, String co2xCoyId, Date co2xDtExpiry,
			String co2xUid, String co2xPwd, Character co2xStatus, Date co2xDtCreate, String co2xUidCreate,
			Date co2xDtLupd, String co2xUidLupd) {
		this.co2xId = co2xId;
		this.TCoreAccn = TCoreAccn;
		this.co2xAccnName = co2xAccnName;
		this.co2xCoyId = co2xCoyId;
		this.co2xDtExpiry = co2xDtExpiry;
		this.co2xUid = co2xUid;
		this.co2xPwd = co2xPwd;
		this.co2xStatus = co2xStatus;
		this.co2xDtCreate = co2xDtCreate;
		this.co2xUidCreate = co2xUidCreate;
		this.co2xDtLupd = co2xDtLupd;
		this.co2xUidLupd = co2xUidLupd;
	}

	@Id

	@Column(name = "CO2X_ID", unique = true, nullable = false, length = 35)
	public String getCo2xId() {
		return this.co2xId;
	}

	public void setCo2xId(String co2xId) {
		this.co2xId = co2xId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CO2X_ACCN")
	public TCoreAccn getTCoreAccn() {
		return this.TCoreAccn;
	}

	public void setTCoreAccn(TCoreAccn TCoreAccn) {
		this.TCoreAccn = TCoreAccn;
	}

	@Column(name = "CO2X_ACCN_NAME", length = 1024)
	public String getCo2xAccnName() {
		return this.co2xAccnName;
	}

	public void setCo2xAccnName(String co2xAccnName) {
		this.co2xAccnName = co2xAccnName;
	}

	@Column(name = "CO2X_COY_ID", length = 1024)
	public String getCo2xCoyId() {
		return this.co2xCoyId;
	}

	public void setCo2xCoyId(String co2xCoyId) {
		this.co2xCoyId = co2xCoyId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CO2X_DT_EXPIRY", length = 19)
	public Date getCo2xDtExpiry() {
		return this.co2xDtExpiry;
	}

	public void setCo2xDtExpiry(Date co2xDtExpiry) {
		this.co2xDtExpiry = co2xDtExpiry;
	}

	@Column(name = "CO2X_UID", length = 256)
	public String getCo2xUid() {
		return this.co2xUid;
	}

	public void setCo2xUid(String co2xUid) {
		this.co2xUid = co2xUid;
	}

	@Column(name = "CO2X_PWD", length = 256)
	public String getCo2xPwd() {
		return this.co2xPwd;
	}

	public void setCo2xPwd(String co2xPwd) {
		this.co2xPwd = co2xPwd;
	}

	@Column(name = "CO2X_STATUS", length = 1)
	public Character getCo2xStatus() {
		return this.co2xStatus;
	}

	public void setCo2xStatus(Character co2xStatus) {
		this.co2xStatus = co2xStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CO2X_DT_CREATE", length = 19)
	public Date getCo2xDtCreate() {
		return this.co2xDtCreate;
	}

	public void setCo2xDtCreate(Date co2xDtCreate) {
		this.co2xDtCreate = co2xDtCreate;
	}

	@Column(name = "CO2X_UID_CREATE", length = 35)
	public String getCo2xUidCreate() {
		return this.co2xUidCreate;
	}

	public void setCo2xUidCreate(String co2xUidCreate) {
		this.co2xUidCreate = co2xUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CO2X_DT_LUPD", length = 19)
	public Date getCo2xDtLupd() {
		return this.co2xDtLupd;
	}

	public void setCo2xDtLupd(Date co2xDtLupd) {
		this.co2xDtLupd = co2xDtLupd;
	}

	@Column(name = "CO2X_UID_LUPD", length = 35)
	public String getCo2xUidLupd() {
		return this.co2xUidLupd;
	}

	public void setCo2xUidLupd(String co2xUidLupd) {
		this.co2xUidLupd = co2xUidLupd;
	}

	@Override
	public int compareTo(TCkCtCo2x o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

}
