package com.guudint.clickargo.clictruck.common.model;
// Generated 29 Apr 2024, 12:17:56 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.ccm.model.TCoreUsr;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtDeptUsr generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_DEPT_USR")
public class TCkCtDeptUsr extends COAbstractEntity<TCkCtDeptUsr> {

	private static final long serialVersionUID = 4906900165626520810L;
	private String duId;
	private TCkCtDept TCkCtDept;
	private TCoreUsr TCoreUsr;
	private Character duStatus;
	private Date duDtCreate;
	private String duUidCreate;
	private Date duDtLupd;
	private String duUidLupd;

	public TCkCtDeptUsr() {
	}

	public TCkCtDeptUsr(String duId) {
		this.duId = duId;
	}

	public TCkCtDeptUsr(String duId, TCkCtDept TCkCtDept, TCoreUsr TCoreUsr, Character duStatus, Date duDtCreate,
			String duUidCreate, Date duDtLupd, String duUidLupd) {
		this.duId = duId;
		this.TCkCtDept = TCkCtDept;
		this.TCoreUsr = TCoreUsr;
		this.duStatus = duStatus;
		this.duDtCreate = duDtCreate;
		this.duUidCreate = duUidCreate;
		this.duDtLupd = duDtLupd;
		this.duUidLupd = duUidLupd;
	}

	@Id

	@Column(name = "DU_ID", unique = true, nullable = false, length = 35)
	public String getDuId() {
		return this.duId;
	}

	public void setDuId(String duId) {
		this.duId = duId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DU_DEPT")
	public TCkCtDept getTCkCtDept() {
		return this.TCkCtDept;
	}

	public void setTCkCtDept(TCkCtDept TCkCtDept) {
		this.TCkCtDept = TCkCtDept;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DU_USR")
	public TCoreUsr getTCoreUsr() {
		return this.TCoreUsr;
	}

	public void setTCoreUsr(TCoreUsr TCoreUsr) {
		this.TCoreUsr = TCoreUsr;
	}

	@Column(name = "DU_STATUS", length = 1)
	public Character getDuStatus() {
		return this.duStatus;
	}

	public void setDuStatus(Character duStatus) {
		this.duStatus = duStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DU_DT_CREATE", length = 19)
	public Date getDuDtCreate() {
		return this.duDtCreate;
	}

	public void setDuDtCreate(Date duDtCreate) {
		this.duDtCreate = duDtCreate;
	}

	@Column(name = "DU_UID_CREATE", length = 35)
	public String getDuUidCreate() {
		return this.duUidCreate;
	}

	public void setDuUidCreate(String duUidCreate) {
		this.duUidCreate = duUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DU_DT_LUPD", length = 19)
	public Date getDuDtLupd() {
		return this.duDtLupd;
	}

	public void setDuDtLupd(Date duDtLupd) {
		this.duDtLupd = duDtLupd;
	}

	@Column(name = "DU_UID_LUPD", length = 35)
	public String getDuUidLupd() {
		return this.duUidLupd;
	}

	public void setDuUidLupd(String duUidLupd) {
		this.duUidLupd = duUidLupd;
	}

	@Override
	public int compareTo(TCkCtDeptUsr o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
