package com.guudint.clickargo.clictruck.common.model;
// Generated 29 Apr 2024, 12:17:56 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtDept generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_DEPT")
public class TCkCtDept extends COAbstractEntity<TCkCtDept> {

	private static final long serialVersionUID = -6481365185363638329L;
	private String deptId;
	private TCoreAccn TCoreAccn;
	private String deptName;
	private String deptDesc;
	private Character deptColor;
	private Character deptStatus;
	private Date deptDtCreate;
	private String deptUidCreate;
	private Date deptDtLupd;
	private String deptUidLupd;

	public TCkCtDept() {
	}

	public TCkCtDept(String deptId) {
		this.deptId = deptId;
	}

	public TCkCtDept(String deptId, TCoreAccn TCoreAccn, String deptName, String deptDesc, Character deptColor,
			Character deptStatus, Date deptDtCreate, String deptUidCreate, Date deptDtLupd, String deptUidLupd) {
		this.deptId = deptId;
		this.TCoreAccn = TCoreAccn;
		this.deptName = deptName;
		this.deptDesc = deptDesc;
		this.deptColor = deptColor;
		this.deptStatus = deptStatus;
		this.deptDtCreate = deptDtCreate;
		this.deptUidCreate = deptUidCreate;
		this.deptDtLupd = deptDtLupd;
		this.deptUidLupd = deptUidLupd;
	}

	@Id

	@Column(name = "DEPT_ID", unique = true, nullable = false, length = 35)
	public String getDeptId() {
		return this.deptId;
	}

	public void setDeptId(String deptId) {
		this.deptId = deptId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEPT_ACCN")
	public TCoreAccn getTCoreAccn() {
		return this.TCoreAccn;
	}

	public void setTCoreAccn(TCoreAccn TCoreAccn) {
		this.TCoreAccn = TCoreAccn;
	}

	@Column(name = "DEPT_NAME", length = 256)
	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	@Column(name = "DEPT_DESC", length = 1024)
	public String getDeptDesc() {
		return this.deptDesc;
	}

	public void setDeptDesc(String deptDesc) {
		this.deptDesc = deptDesc;
	}

	@Column(name = "DEPT_COLOR", length = 1)
	public Character getDeptColor() {
		return this.deptColor;
	}

	public void setDeptColor(Character deptColor) {
		this.deptColor = deptColor;
	}

	@Column(name = "DEPT_STATUS", length = 1)
	public Character getDeptStatus() {
		return this.deptStatus;
	}

	public void setDeptStatus(Character deptStatus) {
		this.deptStatus = deptStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DEPT_DT_CREATE", length = 19)
	public Date getDeptDtCreate() {
		return this.deptDtCreate;
	}

	public void setDeptDtCreate(Date deptDtCreate) {
		this.deptDtCreate = deptDtCreate;
	}

	@Column(name = "DEPT_UID_CREATE", length = 35)
	public String getDeptUidCreate() {
		return this.deptUidCreate;
	}

	public void setDeptUidCreate(String deptUidCreate) {
		this.deptUidCreate = deptUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DEPT_DT_LUPD", length = 19)
	public Date getDeptDtLupd() {
		return this.deptDtLupd;
	}

	public void setDeptDtLupd(Date deptDtLupd) {
		this.deptDtLupd = deptDtLupd;
	}

	@Column(name = "DEPT_UID_LUPD", length = 35)
	public String getDeptUidLupd() {
		return this.deptUidLupd;
	}

	public void setDeptUidLupd(String deptUidLupd) {
		this.deptUidLupd = deptUidLupd;
	}

	@Override
	public int compareTo(TCkCtDept o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
