package com.guudint.clickargo.clictruck.common.model;
// Generated 14 Feb, 2023 12:17:14 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.guudint.clickargo.clictruck.common.constant.CkCtLocationConstant.LocationId;
import com.guudint.clickargo.clictruck.master.model.TCkCtMstLocationType;
import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtLocation generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_LOCATION")
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
public class TCkCtLocation extends COAbstractEntity<TCkCtLocation> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -5275964103902549912L;

	// Attributes
	/////////////
	private String locId;
	private TCkCtMstLocationType TCkCtMstLocationType;
	private TCoreAccn TCoreAccn;
	private String locName;
	private String locAddress;
	private Date locDtStart;
	private Date locDtEnd;
	private String locRemarks;
	private String locGps;
	private Character locStatus;
	private Date locDtCreate;
	private String locUidCreate;
	private Date locDtLupd;
	private String locUidLupd;

	// Constructors
	///////////////
	public TCkCtLocation() {
	}

	public TCkCtLocation(String locId) {
		this.locId = locId;
	}

	public TCkCtLocation(String locId, TCkCtMstLocationType TCkCtMstLocationType, TCoreAccn TCoreAccn, String locName,
			String locAddress, Date locDtStart, Date locDtEnd, String locRemarks, String locGps,
			Character locStatus, Date locDtCreate, String locUidCreate, Date locDtLupd,
			String locUidLupd) {
		this.locId = locId;
		this.TCkCtMstLocationType = TCkCtMstLocationType;
		this.TCoreAccn = TCoreAccn;
		this.locName = locName;
		this.locAddress = locAddress;
		this.locDtStart = locDtStart;
		this.locDtEnd = locDtEnd;
		this.locRemarks = locRemarks;
		this.locGps = locGps;
		this.locStatus = locStatus;
		this.locDtCreate = locDtCreate;
		this.locUidCreate = locUidCreate;
		this.locDtLupd = locDtLupd;
		this.locUidLupd = locUidLupd;
	}
	


	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkCtLocation arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}
	
	@Override
	public String toString() {
		return "TCkCtLocation [locId=" + locId + ", TCkCtMstLocationType=" + TCkCtMstLocationType + ", TCoreAccn="
				+ TCoreAccn + ", locName=" + locName + ", locAddress=" + locAddress + ", locDtStart=" + locDtStart
				+ ", locDtEnd=" + locDtEnd + ", locRemarks=" + locRemarks + ", locGps=" + locGps + ", locStatus="
				+ locStatus + ", locDtCreate=" + locDtCreate + ", locUidCreate=" + locUidCreate + ", locDtLupd="
				+ locDtLupd + ", locUidLupd=" + locUidLupd + "]";
	}

	@Transient
	public boolean isRegion() {
		return this.getTCkCtMstLocationType() != null && LocationId.REGION
				.equalsIgnoreCase(this.getTCkCtMstLocationType().getLctyId());
	}

	// Properties
	/////////////
	@Id
	@Column(name = "LOC_ID", unique = true, nullable = false, length = 35)
	public String getLocId() {
		return this.locId;
	}

	public void setLocId(String locId) {
		this.locId = locId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "LOC_TYPE")
	public TCkCtMstLocationType getTCkCtMstLocationType() {
		return this.TCkCtMstLocationType;
	}

	public void setTCkCtMstLocationType(TCkCtMstLocationType TCkCtMstLocationType) {
		this.TCkCtMstLocationType = TCkCtMstLocationType;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "LOC_COMPANY")
	public TCoreAccn getTCoreAccn() {
		return this.TCoreAccn;
	}

	public void setTCoreAccn(TCoreAccn TCoreAccn) {
		this.TCoreAccn = TCoreAccn;
	}

	@Column(name = "LOC_NAME", length = 1024)
	public String getLocName() {
		return this.locName;
	}

	public void setLocName(String locName) {
		this.locName = locName;
	}

	@Column(name = "LOC_ADDRESS", length = 65535)
	public String getLocAddress() {
		return this.locAddress;
	}

	public void setLocAddress(String locAddress) {
		this.locAddress = locAddress;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LOC_DT_START", length = 19)
	public Date getLocDtStart() {
		return this.locDtStart;
	}

	public void setLocDtStart(Date locDtStart) {
		this.locDtStart = locDtStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LOC_DT_END", length = 19)
	public Date getLocDtEnd() {
		return this.locDtEnd;
	}

	public void setLocDtEnd(Date locDtEnd) {
		this.locDtEnd = locDtEnd;
	}

	@Column(name = "LOC_REMARKS", length = 65535)
	public String getLocRemarks() {
		return this.locRemarks;
	}

	public void setLocRemarks(String locRemarks) {
		this.locRemarks = locRemarks;
	}

	@Column(name = "LOC_GPS", length = 1024)
	public String getLocGps() {
		return this.locGps;
	}

	public void setLocGps(String locGps) {
		this.locGps = locGps;
	}

	@Column(name = "LOC_STATUS", length = 1)
	public Character getLocStatus() {
		return this.locStatus;
	}

	public void setLocStatus(Character locStatus) {
		this.locStatus = locStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LOC_DT_CREATE", length = 19)
	@CreationTimestamp
	public Date getLocDtCreate() {
		return this.locDtCreate;
	}

	public void setLocDtCreate(Date locDtCreate) {
		this.locDtCreate = locDtCreate;
	}

	@Column(name = "LOC_UID_CREATE", length = 35)
	public String getLocUidCreate() {
		return this.locUidCreate;
	}

	public void setLocUidCreate(String locUidCreate) {
		this.locUidCreate = locUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LOC_DT_LUPD", length = 19)
	@UpdateTimestamp
	public Date getLocDtLupd() {
		return this.locDtLupd;
	}

	public void setLocDtLupd(Date locDtLupd) {
		this.locDtLupd = locDtLupd;
	}

	@Column(name = "LOC_UID_LUPD", length = 35)
	public String getLocUidLupd() {
		return this.locUidLupd;
	}

	public void setLocUidLupd(String locUidLupd) {
		this.locUidLupd = locUidLupd;
	}

}
