package com.guudint.clickargo.clictruck.common.model;
// Generated 14 Feb, 2023 12:17:14 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import org.springframework.beans.BeanUtils;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.guudint.clickargo.clictruck.common.dto.CkCtVeh;
import com.guudint.clickargo.clictruck.master.model.TCkCtMstChassisType;
import com.guudint.clickargo.clictruck.master.model.TCkCtMstVehState;
import com.guudint.clickargo.clictruck.master.model.TCkCtMstVehType;
import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtVeh generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_VEH")
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
public class TCkCtVeh extends COAbstractEntity<TCkCtVeh> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -4558380572275373688L;
	
	// Attributes
	/////////////
	private String vhId;
	private TCkCtMstChassisType TCkCtMstChassisType;
	private TCkCtMstVehState TCkCtMstVehState;
	private TCkCtMstVehType TCkCtMstVehType;
	// private TCkJob TCkJob;
	private TCoreAccn TCoreAccn;
	private String vhPlateNo;
	private Byte vhClass;
	private String vhPhotoName;
	private String vhPhotoLoc;
	private Short vhLength;
	private Short vhWidth;
	private Short vhHeight;
	private Integer vhWeight;
	private Integer vhVolume;
	private String vhChassisNo;
	private Character vhIsMaintenance;
	private String vhRemarks;
	private String vhGpsImei;
	private Character vhStatus;
	private Date vhDtCreate;
	private String vhUidCreate;
	private Date vhDtLupd;
	private String vhUidLupd;

	private TCkCtTrackDevice TCkCtTrackDevice = null;
	
	// Constructors
	///////////////
	public TCkCtVeh() {
	}

	public TCkCtVeh(String vhId) {
		this.vhId = vhId;
	}

	public TCkCtVeh(CkCtVeh ckCtVeh){
		BeanUtils.copyProperties(ckCtVeh, this, "base64File");
	}

	public TCkCtVeh(String vhId, TCkCtMstChassisType TCkCtMstChassisType, TCkCtMstVehState TCkCtMstVehState,
			TCkCtMstVehType TCkCtMstVehType, TCoreAccn TCoreAccn, String vhPlateNo, Byte vhClass,
			String vhPhotoName, String vhPhotoLoc, Short vhLength, Short vhWidth, Short vhHeight, Integer vhWeight,
			Integer vhVolume, String vhChassisNo, Character vhIsMaintenance, String vhRemarks, String vhGpsImei,
			Character vhStatus, Date vhDtCreate, String vhUidCreate, Date vhDtLupd, String vhUidLupd) {
		this.vhId = vhId;
		this.TCkCtMstChassisType = TCkCtMstChassisType;
		this.TCkCtMstVehState = TCkCtMstVehState;
		this.TCkCtMstVehType = TCkCtMstVehType;
		this.TCoreAccn = TCoreAccn;
		this.vhPlateNo = vhPlateNo;
		this.vhClass = vhClass;
		this.vhPhotoName = vhPhotoName;
		this.vhPhotoLoc = vhPhotoLoc;
		this.vhLength = vhLength;
		this.vhWidth = vhWidth;
		this.vhHeight = vhHeight;
		this.vhWeight = vhWeight;
		this.vhVolume = vhVolume;
		this.vhChassisNo = vhChassisNo;
		this.vhIsMaintenance = vhIsMaintenance;
		this.vhRemarks = vhRemarks;
		this.vhGpsImei = vhGpsImei;
		this.vhStatus = vhStatus;
		this.vhDtCreate = vhDtCreate;
		this.vhUidCreate = vhUidCreate;
		this.vhDtLupd = vhDtLupd;
		this.vhUidLupd = vhUidLupd;
	}

	// Properties
	/////////////
	@Id
	@Column(name = "VH_ID", unique = true, nullable = false, length = 35)
	public String getVhId() {
		return this.vhId;
	}

	public void setVhId(String vhId) {
		this.vhId = vhId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "VH_CHASSIS_TYPE")
	public TCkCtMstChassisType getTCkCtMstChassisType() {
		return this.TCkCtMstChassisType;
	}

	public void setTCkCtMstChassisType(TCkCtMstChassisType TCkCtMstChassisType) {
		this.TCkCtMstChassisType = TCkCtMstChassisType;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "VH_STATE")
	public TCkCtMstVehState getTCkCtMstVehState() {
		return this.TCkCtMstVehState;
	}

	public void setTCkCtMstVehState(TCkCtMstVehState TCkCtMstVehState) {
		this.TCkCtMstVehState = TCkCtMstVehState;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "VH_TYPE")
	public TCkCtMstVehType getTCkCtMstVehType() {
		return this.TCkCtMstVehType;
	}

	public void setTCkCtMstVehType(TCkCtMstVehType TCkCtMstVehType) {
		this.TCkCtMstVehType = TCkCtMstVehType;
	}

	// @ManyToOne(fetch = FetchType.EAGER)
	// @JoinColumn(name = "VH_ASSIGNED_JOB")
	// public TCkJob getTCkJob() {
	// 	return this.TCkJob;
	// }

	// public void setTCkJob(TCkJob TCkJob) {
	// 	this.TCkJob = TCkJob;
	// }

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "VH_COMPANY")
	public TCoreAccn getTCoreAccn() {
		return this.TCoreAccn;
	}

	public void setTCoreAccn(TCoreAccn TCoreAccn) {
		this.TCoreAccn = TCoreAccn;
	}

	@Column(name = "VH_PLATE_NO", length = 256)
	public String getVhPlateNo() {
		return this.vhPlateNo;
	}

	public void setVhPlateNo(String vhPlateNo) {
		this.vhPlateNo = vhPlateNo;
	}

	@Column(name = "VH_CLASS")
	public Byte getVhClass() {
		return this.vhClass;
	}

	public void setVhClass(Byte vhClass) {
		this.vhClass = vhClass;
	}

	@Column(name = "VH_PHOTO_NAME", length = 256)
	public String getVhPhotoName() {
		return this.vhPhotoName;
	}

	public void setVhPhotoName(String vhPhotoName) {
		this.vhPhotoName = vhPhotoName;
	}

	@Column(name = "VH_PHOTO_LOC", length = 1024)
	public String getVhPhotoLoc() {
		return this.vhPhotoLoc;
	}

	public void setVhPhotoLoc(String vhPhotoLoc) {
		this.vhPhotoLoc = vhPhotoLoc;
	}

	@Column(name = "VH_LENGTH")
	public Short getVhLength() {
		return this.vhLength;
	}

	public void setVhLength(Short vhLength) {
		this.vhLength = vhLength;
	}

	@Column(name = "VH_WIDTH")
	public Short getVhWidth() {
		return this.vhWidth;
	}

	public void setVhWidth(Short vhWidth) {
		this.vhWidth = vhWidth;
	}

	@Column(name = "VH_HEIGHT")
	public Short getVhHeight() {
		return this.vhHeight;
	}

	public void setVhHeight(Short vhHeight) {
		this.vhHeight = vhHeight;
	}

	@Column(name = "VH_WEIGHT")
	public Integer getVhWeight() {
		return this.vhWeight;
	}

	public void setVhWeight(Integer vhWeight) {
		this.vhWeight = vhWeight;
	}

	@Column(name = "VH_VOLUME")
	public Integer getVhVolume() {
		return this.vhVolume;
	}

	public void setVhVolume(Integer vhVolume) {
		this.vhVolume = vhVolume;
	}

	@Column(name = "VH_CHASSIS_NO", length = 256)
	public String getVhChassisNo() {
		return this.vhChassisNo;
	}

	public void setVhChassisNo(String vhChassisNo) {
		this.vhChassisNo = vhChassisNo;
	}

	@Column(name = "VH_IS_MAINTENANCE", length = 1)
	public Character getVhIsMaintenance() {
		return this.vhIsMaintenance;
	}

	public void setVhIsMaintenance(Character vhIsMaintenance) {
		this.vhIsMaintenance = vhIsMaintenance;
	}

	@Column(name = "VH_REMARKS", length = 16777215)
	public String getVhRemarks() {
		return this.vhRemarks;
	}

	public void setVhRemarks(String vhRemarks) {
		this.vhRemarks = vhRemarks;
	}

	@Column(name = "VH_GPS_IMEI", length = 1024)
	public String getVhGpsImei() {
		return this.vhGpsImei;
	}

	public void setVhGpsImei(String vhGpsImei) {
		this.vhGpsImei = vhGpsImei;
	}

	@Column(name = "VH_STATUS", length = 1)
	public Character getVhStatus() {
		return this.vhStatus;
	}

	public void setVhStatus(Character vhStatus) {
		this.vhStatus = vhStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VH_DT_CREATE", length = 19)
	@CreationTimestamp
	public Date getVhDtCreate() {
		return this.vhDtCreate;
	}

	public void setVhDtCreate(Date vhDtCreate) {
		this.vhDtCreate = vhDtCreate;
	}

	@Column(name = "VH_UID_CREATE", length = 35)
	public String getVhUidCreate() {
		return this.vhUidCreate;
	}

	public void setVhUidCreate(String vhUidCreate) {
		this.vhUidCreate = vhUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VH_DT_LUPD", length = 19)
	@UpdateTimestamp
	public Date getVhDtLupd() {
		return this.vhDtLupd;
	}

	public void setVhDtLupd(Date vhDtLupd) {
		this.vhDtLupd = vhDtLupd;
	}

	@Column(name = "VH_UID_LUPD", length = 35)
	public String getVhUidLupd() {
		return this.vhUidLupd;
	}

	public void setVhUidLupd(String vhUidLupd) {
		this.vhUidLupd = vhUidLupd;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "TCkCtVeh")
	public TCkCtTrackDevice getTCkCtTrackDevice() {
		return TCkCtTrackDevice;
	}

	public void setTCkCtTrackDevice(TCkCtTrackDevice tCkCtTrackDevice) {
		TCkCtTrackDevice = tCkCtTrackDevice;
	}

	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkCtVeh o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

}
