package com.guudint.clickargo.clictruck.common.model;
// Generated 8 Apr 2024, 6:46:58 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;
import com.vcc.camelone.master.model.TMstAttType;

/**
 * TCkCtAccnInqReqDocs generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_ACCN_INQ_REQ_DOCS")
public class TCkCtAccnInqReqDocs extends COAbstractEntity<TCkCtAccnInqReqDocs> {

	private static final long serialVersionUID = 6616191880278344329L;
	private String airdId;
	private TCkCtAccnInqReq TCkCtAccnInqReq;
	private TMstAttType TMstAttType;
	private String airdFilename;
	private String airdDoc;
	private Character airdStatus;
	private Date airdDtCreate;
	private String airdUidCreate;
	private Date airdDtLupd;
	private String airdUidLupd;

	public TCkCtAccnInqReqDocs() {
	}

	public TCkCtAccnInqReqDocs(String airdId, TCkCtAccnInqReq TCkCtAccnInqReq) {
		this.airdId = airdId;
		this.TCkCtAccnInqReq = TCkCtAccnInqReq;
	}

	public TCkCtAccnInqReqDocs(String airdId, TCkCtAccnInqReq TCkCtAccnInqReq, TMstAttType TMstAttType,
			String airdFilename, String airdDoc, Character airdStatus, Date airdDtCreate, String airdUidCreate,
			Date airdDtLupd, String airdUidLupd) {
		this.airdId = airdId;
		this.TCkCtAccnInqReq = TCkCtAccnInqReq;
		this.TMstAttType = TMstAttType;
		this.airdFilename = airdFilename;
		this.airdDoc = airdDoc;
		this.airdStatus = airdStatus;
		this.airdDtCreate = airdDtCreate;
		this.airdUidCreate = airdUidCreate;
		this.airdDtLupd = airdDtLupd;
		this.airdUidLupd = airdUidLupd;
	}

	@Id

	@Column(name = "AIRD_ID", unique = true, nullable = false, length = 35)
	public String getAirdId() {
		return this.airdId;
	}

	public void setAirdId(String airdId) {
		this.airdId = airdId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AIRD_AIR_ID", nullable = false)
	public TCkCtAccnInqReq getTCkCtAccnInqReq() {
		return this.TCkCtAccnInqReq;
	}

	public void setTCkCtAccnInqReq(TCkCtAccnInqReq TCkCtAccnInqReq) {
		this.TCkCtAccnInqReq = TCkCtAccnInqReq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AIRD_ATT_TYPE")
	public TMstAttType getTMstAttType() {
		return this.TMstAttType;
	}

	public void setTMstAttType(TMstAttType TMstAttType) {
		this.TMstAttType = TMstAttType;
	}

	@Column(name = "AIRD_FILENAME", length = 256)
	public String getAirdFilename() {
		return this.airdFilename;
	}

	public void setAirdFilename(String airdFilename) {
		this.airdFilename = airdFilename;
	}

	@Column(name = "AIRD_DOC", length = 1024)
	public String getAirdDoc() {
		return this.airdDoc;
	}

	public void setAirdDoc(String airdDoc) {
		this.airdDoc = airdDoc;
	}

	@Column(name = "AIRD_STATUS", length = 1)
	public Character getAirdStatus() {
		return this.airdStatus;
	}

	public void setAirdStatus(Character airdStatus) {
		this.airdStatus = airdStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AIRD_DT_CREATE", length = 19)
	public Date getAirdDtCreate() {
		return this.airdDtCreate;
	}

	public void setAirdDtCreate(Date airdDtCreate) {
		this.airdDtCreate = airdDtCreate;
	}

	@Column(name = "AIRD_UID_CREATE", length = 35)
	public String getAirdUidCreate() {
		return this.airdUidCreate;
	}

	public void setAirdUidCreate(String airdUidCreate) {
		this.airdUidCreate = airdUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AIRD_DT_LUPD", length = 19)
	public Date getAirdDtLupd() {
		return this.airdDtLupd;
	}

	public void setAirdDtLupd(Date airdDtLupd) {
		this.airdDtLupd = airdDtLupd;
	}

	@Column(name = "AIRD_UID_LUPD", length = 35)
	public String getAirdUidLupd() {
		return this.airdUidLupd;
	}

	public void setAirdUidLupd(String airdUidLupd) {
		this.airdUidLupd = airdUidLupd;
	}

	@Override
	public int compareTo(TCkCtAccnInqReqDocs o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

}
