package com.guudint.clickargo.clictruck.common.model;
// Generated 17 Jan 2024, 10:28:26 am by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtVehExtId generated by hbm2java
 */
@Embeddable
public class TCkCtVehExtId extends COAbstractEntity<TCkCtVehExtId> {

	private static final long serialVersionUID = 3803826516441877912L;
	private String vextId;
	private String vextParam;

	public TCkCtVehExtId() {
	}

	public TCkCtVehExtId(String vextId, String vextParam) {
		this.vextId = vextId;
		this.vextParam = vextParam;
	}

	@Column(name = "VEXT_ID", nullable = false, length = 35)
	public String getVextId() {
		return this.vextId;
	}

	public void setVextId(String vextId) {
		this.vextId = vextId;
	}

	@Column(name = "VEXT_PARAM", nullable = false)
	public String getVextParam() {
		return this.vextParam;
	}

	public void setVextParam(String vextParam) {
		this.vextParam = vextParam;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TCkCtVehExtId))
			return false;
		TCkCtVehExtId castOther = (TCkCtVehExtId) other;

		return ((this.getVextId() == castOther.getVextId()) || (this.getVextId() != null
				&& castOther.getVextId() != null && this.getVextId().equals(castOther.getVextId())))
				&& ((this.getVextParam() == castOther.getVextParam()) || (this.getVextParam() != null
						&& castOther.getVextParam() != null && this.getVextParam().equals(castOther.getVextParam())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getVextId() == null ? 0 : this.getVextId().hashCode());
		result = 37 * result + (getVextParam() == null ? 0 : this.getVextParam().hashCode());
		return result;
	}

	@Override
	public int compareTo(TCkCtVehExtId o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
