package com.guudint.clickargo.clictruck.common.model;
// Generated 17 Jan 2024, 10:28:26 am by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtVehExt generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_VEH_EXT")
public class TCkCtVehExt extends COAbstractEntity<TCkCtVehExt> {

	private static final long serialVersionUID = -381791340595074637L;
	private TCkCtVehExtId id;
	private TCkCtVeh TCkCtVeh;
	private String vextValue;
	private Character vextMonitorMthd;
	private String vextMonitorValue;
	private Character vextNotify;
	private String vextNotifyEmail;
	private String vextNotifyWhatsapp;
	private String vextRemarks;
	private Character vextStatus;
	private Date vextDtCreate;
	private String vextUidCreate;
	private Date vextDtLupd;
	private String vextUidLupd;

	public TCkCtVehExt() {
	}

	public TCkCtVehExt(TCkCtVehExtId id, TCkCtVeh TCkCtVeh) {
		this.id = id;
		this.TCkCtVeh = TCkCtVeh;
	}

	public TCkCtVehExt(TCkCtVehExtId id, TCkCtVeh TCkCtVeh, String vextValue, Character vextMonitorMthd,
			String vextMonitorValue, Character vextNotify, String vextNotifyEmail, String vextNotifyWhatsapp,
			String vextRemarks, Character vextStatus, Date vextDtCreate, String vextUidCreate, Date vextDtLupd, String vextUidLupd) {
		this.id = id;
		this.TCkCtVeh = TCkCtVeh;
		this.vextValue = vextValue;
		this.vextMonitorMthd = vextMonitorMthd;
		this.vextMonitorValue = vextMonitorValue;
		this.vextNotify = vextNotify;
		this.vextNotifyEmail = vextNotifyEmail;
		this.vextNotifyWhatsapp = vextNotifyWhatsapp;
		this.vextRemarks = vextRemarks;
		this.vextStatus = vextStatus;
		this.vextDtCreate = vextDtCreate;
		this.vextUidCreate = vextUidCreate;
		this.vextDtLupd = vextDtLupd;
		this.vextUidLupd = vextUidLupd;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "vextId", column = @Column(name = "VEXT_ID", nullable = false, length = 35)),
			@AttributeOverride(name = "vextParam", column = @Column(name = "VEXT_PARAM", nullable = false)) })
	public TCkCtVehExtId getId() {
		return this.id;
	}

	public void setId(TCkCtVehExtId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VEXT_ID", nullable = false, insertable = false, updatable = false)
	public TCkCtVeh getTCkCtVeh() {
		return this.TCkCtVeh;
	}

	public void setTCkCtVeh(TCkCtVeh TCkCtVeh) {
		this.TCkCtVeh = TCkCtVeh;
	}

	@Column(name = "VEXT_VALUE", length = 2048)
	public String getVextValue() {
		return this.vextValue;
	}

	public void setVextValue(String vextValue) {
		this.vextValue = vextValue;
	}

	@Column(name = "VEXT_MONITOR_MTHD", length = 1)
	public Character getVextMonitorMthd() {
		return this.vextMonitorMthd;
	}

	public void setVextMonitorMthd(Character vextMonitorMthd) {
		this.vextMonitorMthd = vextMonitorMthd;
	}
	

	@Column(name = "VEXT_MONITOR_VALUE", length = 2048)
	public String getVextMonitorValue() {
		return this.vextMonitorValue;
	}

	public void setVextMonitorValue(String vextMonitorValue) {
		this.vextMonitorValue = vextMonitorValue;
	}

	@Column(name = "VEXT_NOTIFY", length = 1)
	public Character getVextNotify() {
		return this.vextNotify;
	}

	public void setVextNotify(Character vextNotify) {
		this.vextNotify = vextNotify;
	}

	@Column(name = "VEXT_NOTIFY_EMAIL", length = 1024)
	public String getVextNotifyEmail() {
		return this.vextNotifyEmail;
	}

	public void setVextNotifyEmail(String vextNotifyEmail) {
		this.vextNotifyEmail = vextNotifyEmail;
	}

	@Column(name = "VEXT_NOTIFY_WHATSAPP", length = 1024)
	public String getVextNotifyWhatsapp() {
		return this.vextNotifyWhatsapp;
	}

	public void setVextNotifyWhatsapp(String vextNotifyWhatsapp) {
		this.vextNotifyWhatsapp = vextNotifyWhatsapp;
	}

	@Column(name = "VEXT_REMARKS", length = 16777215)
	public String getVextRemarks() {
		return this.vextRemarks;
	}

	public void setVextRemarks(String vextRemarks) {
		this.vextRemarks = vextRemarks;
	}

	@Column(name = "VEXT_STATUS", length = 1)
	public Character getVextStatus() {
		return this.vextStatus;
	}

	public void setVextStatus(Character vextStatus) {
		this.vextStatus = vextStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VEXT_DT_CREATE", length = 19)
	public Date getVextDtCreate() {
		return this.vextDtCreate;
	}

	public void setVextDtCreate(Date vextDtCreate) {
		this.vextDtCreate = vextDtCreate;
	}

	@Column(name = "VEXT_UID_CREATE", length = 35)
	public String getVextUidCreate() {
		return this.vextUidCreate;
	}

	public void setVextUidCreate(String vextUidCreate) {
		this.vextUidCreate = vextUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VEXT_DT_LUPD", length = 19)
	public Date getVextDtLupd() {
		return this.vextDtLupd;
	}

	public void setVextDtLupd(Date vextDtLupd) {
		this.vextDtLupd = vextDtLupd;
	}

	@Column(name = "VEXT_UID_LUPD", length = 35)
	public String getVextUidLupd() {
		return this.vextUidLupd;
	}

	public void setVextUidLupd(String vextUidLupd) {
		this.vextUidLupd = vextUidLupd;
	}

	@Override
	public int compareTo(TCkCtVehExt o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

}
