package com.guudint.clickargo.clictruck.common.model;
// Generated 17 Jan 2024, 10:28:26 am by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtVehMlog generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_VEH_MLOG")
public class TCkCtVehMlog extends COAbstractEntity<TCkCtVehMlog> {

	private static final long serialVersionUID = -8403581976773426752L;
	private String vmlId;
	private TCkCtVeh TCkCtVeh;
	private Date vmlDtStart;
	private Date vmlDtEnd;
	private BigDecimal vmlCost;
	private String vmlRemarks;
	private Character vmlStatus;
	private Date vmlDtCreate;
	private String vmlUidCreate;
	private Date vmlDtLupd;
	private String vmlUidLupd;

	public TCkCtVehMlog() {
	}

	public TCkCtVehMlog(String vmlId, TCkCtVeh TCkCtVeh) {
		this.vmlId = vmlId;
		this.TCkCtVeh = TCkCtVeh;
	}

	public TCkCtVehMlog(String vmlId, TCkCtVeh TCkCtVeh, Date vmlDtStart, Date vmlDtEnd, BigDecimal vmlCost,
			String vmlRemarks, Character vmlStatus, Date vmlDtCreate, String vmlUidCreate, Date vmlDtLupd,
			String vmlUidLupd) {
		this.vmlId = vmlId;
		this.TCkCtVeh = TCkCtVeh;
		this.vmlDtStart = vmlDtStart;
		this.vmlDtEnd = vmlDtEnd;
		this.vmlCost = vmlCost;
		this.vmlRemarks = vmlRemarks;
		this.vmlStatus = vmlStatus;
		this.vmlDtCreate = vmlDtCreate;
		this.vmlUidCreate = vmlUidCreate;
		this.vmlDtLupd = vmlDtLupd;
		this.vmlUidLupd = vmlUidLupd;
	}

	@Id

	@Column(name = "VML_ID", unique = true, nullable = false, length = 35)
	public String getVmlId() {
		return this.vmlId;
	}

	public void setVmlId(String vmlId) {
		this.vmlId = vmlId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VML_VEH_ID", nullable = false)
	public TCkCtVeh getTCkCtVeh() {
		return this.TCkCtVeh;
	}

	public void setTCkCtVeh(TCkCtVeh TCkCtVeh) {
		this.TCkCtVeh = TCkCtVeh;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VML_DT_START", length = 19)
	public Date getVmlDtStart() {
		return this.vmlDtStart;
	}

	public void setVmlDtStart(Date vmlDtStart) {
		this.vmlDtStart = vmlDtStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VML_DT_END", length = 19)
	public Date getVmlDtEnd() {
		return this.vmlDtEnd;
	}

	public void setVmlDtEnd(Date vmlDtEnd) {
		this.vmlDtEnd = vmlDtEnd;
	}

	@Column(name = "VML_COST", precision = 15)
	public BigDecimal getVmlCost() {
		return this.vmlCost;
	}

	public void setVmlCost(BigDecimal vmlCost) {
		this.vmlCost = vmlCost;
	}

	@Column(name = "VML_REMARKS", length = 16777215)
	public String getVmlRemarks() {
		return this.vmlRemarks;
	}

	public void setVmlRemarks(String vmlRemarks) {
		this.vmlRemarks = vmlRemarks;
	}

	@Column(name = "VML_STATUS", length = 1)
	public Character getVmlStatus() {
		return this.vmlStatus;
	}

	public void setVmlStatus(Character vmlStatus) {
		this.vmlStatus = vmlStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VML_DT_CREATE", length = 19)
	public Date getVmlDtCreate() {
		return this.vmlDtCreate;
	}

	public void setVmlDtCreate(Date vmlDtCreate) {
		this.vmlDtCreate = vmlDtCreate;
	}

	@Column(name = "VML_UID_CREATE", length = 35)
	public String getVmlUidCreate() {
		return this.vmlUidCreate;
	}

	public void setVmlUidCreate(String vmlUidCreate) {
		this.vmlUidCreate = vmlUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VML_DT_LUPD", length = 19)
	public Date getVmlDtLupd() {
		return this.vmlDtLupd;
	}

	public void setVmlDtLupd(Date vmlDtLupd) {
		this.vmlDtLupd = vmlDtLupd;
	}

	@Column(name = "VML_UID_LUPD", length = 35)
	public String getVmlUidLupd() {
		return this.vmlUidLupd;
	}

	public void setVmlUidLupd(String vmlUidLupd) {
		this.vmlUidLupd = vmlUidLupd;
	}

	@Override
	public int compareTo(TCkCtVehMlog o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
