package com.guudint.clickargo.clictruck.finacing.model;
// Generated 27 Jun 2023, 2:53:41 pm by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtToPayment generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_TO_PAYMENT")
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
public class TCkCtToPayment extends COAbstractEntity<TCkCtToPayment> {

	private static final long serialVersionUID = -8942871242138777771L;
	private String topId;
	private TCoreAccn TCoreAccn;
	private Date topDtTransfer;
	private BigDecimal topAmt;
	private String topReference;
	private String topJson;
	private String topException;
	private Character topStatus;
	private Date topDtCreate;
	private String topUidCreate;
	private Date topDtLupd;
	private String topUidLupd;

	public TCkCtToPayment() {
	}

	public TCkCtToPayment(String topId) {
		this.topId = topId;
	}

	public TCkCtToPayment(String topId, TCoreAccn TCoreAccn, Date topDtTransfer, BigDecimal topAmt, String topReference,
			String topJson, String topException, Character topStatus, Date topDtCreate, String topUidCreate,
			Date topDtLupd, String topUidLupd) {
		this.topId = topId;
		this.TCoreAccn = TCoreAccn;
		this.topDtTransfer = topDtTransfer;
		this.topAmt = topAmt;
		this.topReference = topReference;
		this.topJson = topJson;
		this.topException = topException;
		this.topStatus = topStatus;
		this.topDtCreate = topDtCreate;
		this.topUidCreate = topUidCreate;
		this.topDtLupd = topDtLupd;
		this.topUidLupd = topUidLupd;
	}

	@Id

	@Column(name = "TOP_ID", unique = true, nullable = false, length = 35)
	public String getTopId() {
		return this.topId;
	}

	public void setTopId(String topId) {
		this.topId = topId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TOP_ACCN_TO")
	public TCoreAccn getTCoreAccn() {
		return this.TCoreAccn;
	}

	public void setTCoreAccn(TCoreAccn TCoreAccn) {
		this.TCoreAccn = TCoreAccn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TOP_DT_TRANSFER", length = 19)
	public Date getTopDtTransfer() {
		return this.topDtTransfer;
	}

	public void setTopDtTransfer(Date topDtTransfer) {
		this.topDtTransfer = topDtTransfer;
	}

	@Column(name = "TOP_AMT", precision = 15)
	public BigDecimal getTopAmt() {
		return this.topAmt;
	}

	public void setTopAmt(BigDecimal topAmt) {
		this.topAmt = topAmt;
	}

	@Column(name = "TOP_REFERENCE", length = 2048)
	public String getTopReference() {
		return this.topReference;
	}

	public void setTopReference(String topReference) {
		this.topReference = topReference;
	}

	@Column(name = "TOP_JSON", length = 16777215)
	public String getTopJson() {
		return this.topJson;
	}

	public void setTopJson(String topJson) {
		this.topJson = topJson;
	}

	@Column(name = "TOP_EXCEPTION", length = 16777215)
	public String getTopException() {
		return this.topException;
	}

	public void setTopException(String topException) {
		this.topException = topException;
	}

	@Column(name = "TOP_STATUS", length = 1)
	public Character getTopStatus() {
		return this.topStatus;
	}

	public void setTopStatus(Character topStatus) {
		this.topStatus = topStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TOP_DT_CREATE", length = 19)
	public Date getTopDtCreate() {
		return this.topDtCreate;
	}

	public void setTopDtCreate(Date topDtCreate) {
		this.topDtCreate = topDtCreate;
	}

	@Column(name = "TOP_UID_CREATE", length = 35)
	public String getTopUidCreate() {
		return this.topUidCreate;
	}

	public void setTopUidCreate(String topUidCreate) {
		this.topUidCreate = topUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TOP_DT_LUPD", length = 19)
	public Date getTopDtLupd() {
		return this.topDtLupd;
	}

	public void setTopDtLupd(Date topDtLupd) {
		this.topDtLupd = topDtLupd;
	}

	@Column(name = "TOP_UID_LUPD", length = 35)
	public String getTopUidLupd() {
		return this.topUidLupd;
	}

	public void setTopUidLupd(String topUidLupd) {
		this.topUidLupd = topUidLupd;
	}

	@Override
	public int compareTo(TCkCtToPayment o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

}
