package com.guudint.clickargo.clictruck.finacing.model;
// Generated 23 Feb, 2023 4:00:19 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.beans.BeanUtils;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.guudint.clickargo.clictruck.finacing.dto.CkCtToInvoice;
import com.guudint.clickargo.clictruck.master.model.TCkCtMstToInvoiceState;
import com.guudint.clickargo.clictruck.planexec.trip.model.TCkCtTrip;
import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtToInvoice generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_TO_INVOICE")
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
public class TCkCtToInvoice extends COAbstractEntity<TCkCtToInvoice> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 1474029659929016777L;
	
	// Attributes
	/////////////
	private String invId;
	private TCkCtMstToInvoiceState TCkCtMstToInvoiceState;
	private TCoreAccn TCoreAccnByInvTo;
	private TCoreAccn TCoreAccnByInvFrom;
	private TCkCtTrip TCkCtTrip;
	private String invJobId;
	private String invNo;
	private Date invDtIssue;
	private String invName;
	private String invLoc;
	private String invInvocierComment;
	private String invInvocieeRemarks;
	private Character invStatus;
	private Date invDtCreate;
	private String invUidCreate;
	private Date invDtLupd;
	private String invUidLupd;

	// Constructors
	///////////////
	public TCkCtToInvoice() {
	}

	public TCkCtToInvoice(String invId, TCkCtMstToInvoiceState TCkCtMstToInvoiceState, String invNo) {
		this.invId = invId;
		this.TCkCtMstToInvoiceState = TCkCtMstToInvoiceState;
		this.invNo = invNo;
	}

	public TCkCtToInvoice(CkCtToInvoice ckCtToInvoice){
		BeanUtils.copyProperties(ckCtToInvoice, this);
	}

	public TCkCtToInvoice(String invId, TCkCtMstToInvoiceState TCkCtMstToInvoiceState, TCoreAccn TCoreAccnByInvTo,
			TCoreAccn TCoreAccnByInvFrom, String invJobId, String invNo, Date invDtIssue, String invName, String invLoc,
			String invInvocierComment, String invInvocieeRemarks, Character invStatus, Date invDtCreate,
			String invUidCreate, Date invDtLupd, String invUidLupd) {
		this.invId = invId;
		this.TCkCtMstToInvoiceState = TCkCtMstToInvoiceState;
		this.TCoreAccnByInvTo = TCoreAccnByInvTo;
		this.TCoreAccnByInvFrom = TCoreAccnByInvFrom;
		this.invJobId = invJobId;
		this.invNo = invNo;
		this.invDtIssue = invDtIssue;
		this.invName = invName;
		this.invLoc = invLoc;
		this.invInvocierComment = invInvocierComment;
		this.invInvocieeRemarks = invInvocieeRemarks;
		this.invStatus = invStatus;
		this.invDtCreate = invDtCreate;
		this.invUidCreate = invUidCreate;
		this.invDtLupd = invDtLupd;
		this.invUidLupd = invUidLupd;
	}

	// Properties
	/////////////
	@Id
	@Column(name = "INV_ID", unique = true, nullable = false, length = 35)
	public String getInvId() {
		return this.invId;
	}

	public void setInvId(String invId) {
		this.invId = invId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "INV_STATE", nullable = false)
	public TCkCtMstToInvoiceState getTCkCtMstToInvoiceState() {
		return this.TCkCtMstToInvoiceState;
	}

	public void setTCkCtMstToInvoiceState(TCkCtMstToInvoiceState TCkCtMstToInvoiceState) {
		this.TCkCtMstToInvoiceState = TCkCtMstToInvoiceState;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "INV_TO")
	public TCoreAccn getTCoreAccnByInvTo() {
		return this.TCoreAccnByInvTo;
	}

	public void setTCoreAccnByInvTo(TCoreAccn TCoreAccnByInvTo) {
		this.TCoreAccnByInvTo = TCoreAccnByInvTo;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "INV_FROM")
	public TCoreAccn getTCoreAccnByInvFrom() {
		return this.TCoreAccnByInvFrom;
	}

	
	public void setTCoreAccnByInvFrom(TCoreAccn TCoreAccnByInvFrom) {
		this.TCoreAccnByInvFrom = TCoreAccnByInvFrom;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "INV_TRIP")
	public TCkCtTrip getTCkCtTrip() {
		return this.TCkCtTrip;
	}

	public void setTCkCtTrip(TCkCtTrip TCkCtTrip) {
		this.TCkCtTrip = TCkCtTrip;
	}


	@Column(name = "INV_JOB_ID", length = 35)
	public String getInvJobId() {
		return this.invJobId;
	}

	public void setInvJobId(String invJobId) {
		this.invJobId = invJobId;
	}

	@Column(name = "INV_NO", length = 256)
	public String getInvNo() {
		return this.invNo;
	}

	public void setInvNo(String invNo) {
		this.invNo = invNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INV_DT_ISSUE", length = 19)
	public Date getInvDtIssue() {
		return this.invDtIssue;
	}

	public void setInvDtIssue(Date invDtIssue) {
		this.invDtIssue = invDtIssue;
	}

	@Column(name = "INV_NAME", length = 256)
	public String getInvName() {
		return this.invName;
	}

	public void setInvName(String invName) {
		this.invName = invName;
	}

	@Column(name = "INV_LOC", length = 1024)
	public String getInvLoc() {
		return this.invLoc;
	}

	public void setInvLoc(String invLoc) {
		this.invLoc = invLoc;
	}

	@Column(name = "INV_INVOCIER_COMMENT", length = 16777215)
	public String getInvInvocierComment() {
		return this.invInvocierComment;
	}

	public void setInvInvocierComment(String invInvocierComment) {
		this.invInvocierComment = invInvocierComment;
	}

	@Column(name = "INV_INVOCIEE_REMARKS", length = 16777215)
	public String getInvInvocieeRemarks() {
		return this.invInvocieeRemarks;
	}

	public void setInvInvocieeRemarks(String invInvocieeRemarks) {
		this.invInvocieeRemarks = invInvocieeRemarks;
	}

	@Column(name = "INV_STATUS", length = 1)
	public Character getInvStatus() {
		return this.invStatus;
	}

	public void setInvStatus(Character invStatus) {
		this.invStatus = invStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INV_DT_CREATE", length = 19)
	@CreationTimestamp
	public Date getInvDtCreate() {
		return this.invDtCreate;
	}

	public void setInvDtCreate(Date invDtCreate) {
		this.invDtCreate = invDtCreate;
	}

	@Column(name = "INV_UID_CREATE", length = 35)
	public String getInvUidCreate() {
		return this.invUidCreate;
	}

	public void setInvUidCreate(String invUidCreate) {
		this.invUidCreate = invUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INV_DT_LUPD", length = 19)
	@UpdateTimestamp
	public Date getInvDtLupd() {
		return this.invDtLupd;
	}

	public void setInvDtLupd(Date invDtLupd) {
		this.invDtLupd = invDtLupd;
	}

	@Column(name = "INV_UID_LUPD", length = 35)
	public String getInvUidLupd() {
		return this.invUidLupd;
	}

	public void setInvUidLupd(String invUidLupd) {
		this.invUidLupd = invUidLupd;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	 */
	@Override
	public int compareTo(TCkCtToInvoice o) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 * 
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

}
