package com.guudint.clickargo.clictruck.jobupload.model;
// Generated 29 Apr 2024, 11:23:34 am by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkJobUpload generated by hbm2java
 */
@Entity
@Table(name = "T_CK_JOB_UPLOAD")
public class TCkJobUpload extends COAbstractEntity<TCkJobUpload> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 1L;
	public static final String PREFIX_ID = "UP";

	// Attributes
	/////////////
	private String upId;
	private String upAccnId;
	private String upFileName;
	private String upFilePath;
	private Integer upFileSize;
	private Integer upTotalLines;
	private String upSuccessJobIds;
	private String upFailLines;
	private String upRemark;
	private Character upStatus;
	private Date upDtCreate;
	private String upUidCreate;
	private Date upDtLupd;
	private String upUidLupd;

	public TCkJobUpload() {
	}

	public TCkJobUpload(String upId) {
		this.upId = upId;
	}


	// Override Methods
	///////////////////

	@Override
	public int compareTo(TCkJobUpload o) {
		return 0;
	}

	@Override
	public void init() {
	}

	@Id

	@Column(name = "UP_ID", unique = true, nullable = false, length = 35)
	public String getUpId() {
		return this.upId;
	}

	public void setUpId(String upId) {
		this.upId = upId;
	}

	@Column(name = "UP_ACCN_ID", length = 35)
	public String getUpAccnId() {
		return this.upAccnId;
	}

	public void setUpAccnId(String upAccnId) {
		this.upAccnId = upAccnId;
	}

	@Column(name = "UP_FILE_NAME", length = 256)
	public String getUpFileName() {
		return this.upFileName;
	}

	public void setUpFileName(String upFileName) {
		this.upFileName = upFileName;
	}

	@Column(name = "UP_FILE_PATH", length = 512)
	public String getUpFilePath() {
		return this.upFilePath;
	}

	public void setUpFilePath(String upFilePath) {
		this.upFilePath = upFilePath;
	}

	@Column(name = "UP_FILE_SIZE")
	public Integer getUpFileSize() {
		return this.upFileSize;
	}

	public void setUpFileSize(Integer upFileSize) {
		this.upFileSize = upFileSize;
	}

	@Column(name = "UP_TOTAL_LINES")
	public Integer getUpTotalLines() {
		return this.upTotalLines;
	}

	public void setUpTotalLines(Integer upTotalLines) {
		this.upTotalLines = upTotalLines;
	}

	@Column(name = "UP_SUCCESS_JOB_IDS", length = 2048)
	public String getUpSuccessJobIds() {
		return this.upSuccessJobIds;
	}

	public void setUpSuccessJobIds(String upSuccessJobIds) {
		this.upSuccessJobIds = upSuccessJobIds;
	}

	@Column(name = "UP_FAIL_LINES", length = 512)
	public String getUpFailLines() {
		return this.upFailLines;
	}

	public void setUpFailLines(String upFailLines) {
		this.upFailLines = upFailLines;
	}

	@Column(name = "UP_REMARK", length = 1024)
	public String getUpRemark() {
		return this.upRemark;
	}

	public void setUpRemark(String upRemark) {
		this.upRemark = upRemark;
	}

	@Column(name = "UP_STATUS", length = 1)
	public Character getUpStatus() {
		return this.upStatus;
	}

	public void setUpStatus(Character upStatus) {
		this.upStatus = upStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UP_DT_CREATE", length = 19)
	public Date getUpDtCreate() {
		return this.upDtCreate;
	}

	public void setUpDtCreate(Date upDtCreate) {
		this.upDtCreate = upDtCreate;
	}

	@Column(name = "UP_UID_CREATE", length = 35)
	public String getUpUidCreate() {
		return this.upUidCreate;
	}

	public void setUpUidCreate(String upUidCreate) {
		this.upUidCreate = upUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UP_DT_LUPD", length = 19)
	public Date getUpDtLupd() {
		return this.upDtLupd;
	}

	public void setUpDtLupd(Date upDtLupd) {
		this.upDtLupd = upDtLupd;
	}

	@Column(name = "UP_UID_LUPD", length = 35)
	public String getUpUidLupd() {
		return this.upUidLupd;
	}

	public void setUpUidLupd(String upUidLupd) {
		this.upUidLupd = upUidLupd;
	}

}
