package com.guudint.clickargo.clictruck.admin.contract.model;
// Generated 22 Feb 2024, 10:53:23 am by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtAddAttrList generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_ADD_ATTR_LIST")
public class TCkCtAddAttrList extends COAbstractEntity<TCkCtAddAttrList> {

	private static final long serialVersionUID = -8871339733290481884L;
	private String aalId;
	private String aalList;
	private String aalDescription;
	private Character aalStatus;
	private Date aalDtCreate;
	private String aalUidCreate;
	private Date aalDtLupd;
	private String aalUidLupd;

	public TCkCtAddAttrList() {
	}

	public TCkCtAddAttrList(String aalId) {
		this.aalId = aalId;
	}

	public TCkCtAddAttrList(String aalId, String aalList, String aalDescription, Character aalStatus, Date aalDtCreate,
			String aalUidCreate, Date aalDtLupd, String aalUidLupd) {
		this.aalId = aalId;
		this.aalList = aalList;
		this.aalDescription = aalDescription;
		this.aalStatus = aalStatus;
		this.aalDtCreate = aalDtCreate;
		this.aalUidCreate = aalUidCreate;
		this.aalDtLupd = aalDtLupd;
		this.aalUidLupd = aalUidLupd;
	}

	@Id

	@Column(name = "AAL_ID", unique = true, nullable = false, length = 35)
	public String getAalId() {
		return this.aalId;
	}

	public void setAalId(String aalId) {
		this.aalId = aalId;
	}

	@Column(name = "AAL_LIST", length = 16777215)
	public String getAalList() {
		return this.aalList;
	}

	public void setAalList(String aalList) {
		this.aalList = aalList;
	}

	@Column(name = "AAL_DESCRIPTION", length = 1024)
	public String getAalDescription() {
		return this.aalDescription;
	}

	public void setAalDescription(String aalDescription) {
		this.aalDescription = aalDescription;
	}

	@Column(name = "AAL_STATUS", length = 1)
	public Character getAalStatus() {
		return this.aalStatus;
	}

	public void setAalStatus(Character aalStatus) {
		this.aalStatus = aalStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AAL_DT_CREATE", length = 19)
	public Date getAalDtCreate() {
		return this.aalDtCreate;
	}

	public void setAalDtCreate(Date aalDtCreate) {
		this.aalDtCreate = aalDtCreate;
	}

	@Column(name = "AAL_UID_CREATE", length = 35)
	public String getAalUidCreate() {
		return this.aalUidCreate;
	}

	public void setAalUidCreate(String aalUidCreate) {
		this.aalUidCreate = aalUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AAL_DT_LUPD", length = 19)
	public Date getAalDtLupd() {
		return this.aalDtLupd;
	}

	public void setAalDtLupd(Date aalDtLupd) {
		this.aalDtLupd = aalDtLupd;
	}

	@Column(name = "AAL_UID_LUPD", length = 35)
	public String getAalUidLupd() {
		return this.aalUidLupd;
	}

	public void setAalUidLupd(String aalUidLupd) {
		this.aalUidLupd = aalUidLupd;
	}

	@Override
	public int compareTo(TCkCtAddAttrList arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
