package com.guudint.clickargo.clictruck.admin.contract.model;
// Generated 23 Sep 2023, 3:37:59 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;
import com.vcc.camelone.master.model.TMstBank;
import com.vcc.camelone.master.model.TMstCurrency;

/**
 * TCkCtContractReq generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_CONTRACT_REQ")
public class TCkCtContractReq extends COAbstractEntity<TCkCtContractReq> {

	private static final long serialVersionUID = -4104967292483860395L;
	private String crId;
	private TCkCtContractCharge TCkCtContractChargeByCrChargeTo;
	private TCkCtContractCharge TCkCtContractChargeByCrChargeCoFf;
	private TCkCtContractCharge TCkCtContractChargeByCrChargeOpm;
	private TCkCtMstContractReqState TCkCtMstContractReqState;
	private TCoreAccn TCoreAccnByCrTo;
	private TCoreAccn TCoreAccnByCrCoFf;
	private TMstBank TMstBank;
	private TMstCurrency TMstCurrency;
	private String crName;
	private String crDescription;
	private Date crDtStart;
	private Date crDtEnd;
	private Integer crPaytermTo;
	private Integer crPaytermCoFf;
	private String crUidRequestor;
	private String crCommentRequestor;
	private Date crDtSubmit;
	private String crUidApprover;
	private String crCommentApprover;
	private Date crDtApproveReject;
	private String crComment;
	private Character crStatus;
	private Date crDtCreate;
	private String crUidCreate;
	private Date crDtLupd;
	private String crUidLupd;
	
	private String crFinanceModel;

	public TCkCtContractReq() {
	}

	public TCkCtContractReq(String crId, TCkCtMstContractReqState TCkCtMstContractReqState) {
		this.crId = crId;
		this.TCkCtMstContractReqState = TCkCtMstContractReqState;
	}

	public TCkCtContractReq(String crId, TCkCtContractCharge TCkCtContractChargeByCrChargeTo,
			TCkCtContractCharge TCkCtContractChargeByCrChargeCoFf, TCkCtMstContractReqState TCkCtMstContractReqState,
			TCoreAccn TCoreAccnByCrTo, TCoreAccn TCoreAccnByCrCoFf, TMstCurrency TMstCurrency, String crName,
			String crDescription, Date crDtStart, Date crDtEnd, Integer crPaytermTo, Integer crPaytermCoFf,
			String crUidRequestor, String crCommentRequestor, Date crDtSubmit, String crUidApprover,
			String crCommentApprover, Date crDtApproveReject, String crComment, Character crStatus, Date crDtCreate,
			String crUidCreate, Date crDtLupd, String crUidLupd) {
		this.crId = crId;
		this.TCkCtContractChargeByCrChargeTo = TCkCtContractChargeByCrChargeTo;
		this.TCkCtContractChargeByCrChargeCoFf = TCkCtContractChargeByCrChargeCoFf;
		this.TCkCtMstContractReqState = TCkCtMstContractReqState;
		this.TCoreAccnByCrTo = TCoreAccnByCrTo;
		this.TCoreAccnByCrCoFf = TCoreAccnByCrCoFf;
		this.TMstCurrency = TMstCurrency;
		this.crName = crName;
		this.crDescription = crDescription;
		this.crDtStart = crDtStart;
		this.crDtEnd = crDtEnd;
		this.crPaytermTo = crPaytermTo;
		this.crPaytermCoFf = crPaytermCoFf;
		this.crUidRequestor = crUidRequestor;
		this.crCommentRequestor = crCommentRequestor;
		this.crDtSubmit = crDtSubmit;
		this.crUidApprover = crUidApprover;
		this.crCommentApprover = crCommentApprover;
		this.crDtApproveReject = crDtApproveReject;
		this.crComment = crComment;
		this.crStatus = crStatus;
		this.crDtCreate = crDtCreate;
		this.crUidCreate = crUidCreate;
		this.crDtLupd = crDtLupd;
		this.crUidLupd = crUidLupd;
	}

	@Id

	@Column(name = "CR_ID", unique = true, nullable = false, length = 35)
	public String getCrId() {
		return this.crId;
	}

	public void setCrId(String crId) {
		this.crId = crId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CR_CHARGE_TO")
	public TCkCtContractCharge getTCkCtContractChargeByCrChargeTo() {
		return this.TCkCtContractChargeByCrChargeTo;
	}

	public void setTCkCtContractChargeByCrChargeTo(TCkCtContractCharge TCkCtContractChargeByCrChargeTo) {
		this.TCkCtContractChargeByCrChargeTo = TCkCtContractChargeByCrChargeTo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CR_CHARGE_CO_FF")
	public TCkCtContractCharge getTCkCtContractChargeByCrChargeCoFf() {
		return this.TCkCtContractChargeByCrChargeCoFf;
	}

	public void setTCkCtContractChargeByCrChargeCoFf(TCkCtContractCharge TCkCtContractChargeByCrChargeCoFf) {
		this.TCkCtContractChargeByCrChargeCoFf = TCkCtContractChargeByCrChargeCoFf;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CR_CHARGE_OPM")
	public TCkCtContractCharge getTCkCtContractChargeByCrChargeOpm() {
		return this.TCkCtContractChargeByCrChargeOpm;
	}

	public void setTCkCtContractChargeByCrChargeOpm(TCkCtContractCharge TCkCtContractChargeByCrChargeOpm) {
		this.TCkCtContractChargeByCrChargeOpm = TCkCtContractChargeByCrChargeOpm;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CR_STATE", nullable = false)
	public TCkCtMstContractReqState getTCkCtMstContractReqState() {
		return this.TCkCtMstContractReqState;
	}

	public void setTCkCtMstContractReqState(TCkCtMstContractReqState TCkCtMstContractReqState) {
		this.TCkCtMstContractReqState = TCkCtMstContractReqState;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CR_TO")
	public TCoreAccn getTCoreAccnByCrTo() {
		return this.TCoreAccnByCrTo;
	}

	public void setTCoreAccnByCrTo(TCoreAccn TCoreAccnByCrTo) {
		this.TCoreAccnByCrTo = TCoreAccnByCrTo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CR_CO_FF")
	public TCoreAccn getTCoreAccnByCrCoFf() {
		return this.TCoreAccnByCrCoFf;
	}

	public void setTCoreAccnByCrCoFf(TCoreAccn TCoreAccnByCrCoFf) {
		this.TCoreAccnByCrCoFf = TCoreAccnByCrCoFf;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CR_OPM_BANK")
	public TMstBank getTMstBank() {
		return this.TMstBank;
	}

	public void setTMstBank(TMstBank TMstBank) {
		this.TMstBank = TMstBank;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CR_CCY")
	public TMstCurrency getTMstCurrency() {
		return this.TMstCurrency;
	}

	public void setTMstCurrency(TMstCurrency TMstCurrency) {
		this.TMstCurrency = TMstCurrency;
	}

	@Column(name = "CR_NAME", length = 1024)
	public String getCrName() {
		return this.crName;
	}

	public void setCrName(String crName) {
		this.crName = crName;
	}

	@Column(name = "CR_DESCRIPTION", length = 16777215)
	public String getCrDescription() {
		return this.crDescription;
	}

	public void setCrDescription(String crDescription) {
		this.crDescription = crDescription;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CR_DT_START", length = 19)
	public Date getCrDtStart() {
		return this.crDtStart;
	}

	public void setCrDtStart(Date crDtStart) {
		this.crDtStart = crDtStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CR_DT_END", length = 19)
	public Date getCrDtEnd() {
		return this.crDtEnd;
	}

	public void setCrDtEnd(Date crDtEnd) {
		this.crDtEnd = crDtEnd;
	}

	@Column(name = "CR_PAYTERM_TO")
	public Integer getCrPaytermTo() {
		return this.crPaytermTo;
	}

	public void setCrPaytermTo(Integer crPaytermTo) {
		this.crPaytermTo = crPaytermTo;
	}

	@Column(name = "CR_PAYTERM_CO_FF")
	public Integer getCrPaytermCoFf() {
		return this.crPaytermCoFf;
	}

	public void setCrPaytermCoFf(Integer crPaytermCoFf) {
		this.crPaytermCoFf = crPaytermCoFf;
	}

	@Column(name = "CR_UID_REQUESTOR", length = 35)
	public String getCrUidRequestor() {
		return this.crUidRequestor;
	}

	public void setCrUidRequestor(String crUidRequestor) {
		this.crUidRequestor = crUidRequestor;
	}

	@Column(name = "CR_COMMENT_REQUESTOR", length = 16777215)
	public String getCrCommentRequestor() {
		return this.crCommentRequestor;
	}

	public void setCrCommentRequestor(String crCommentRequestor) {
		this.crCommentRequestor = crCommentRequestor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CR_DT_SUBMIT", length = 19)
	public Date getCrDtSubmit() {
		return this.crDtSubmit;
	}

	public void setCrDtSubmit(Date crDtSubmit) {
		this.crDtSubmit = crDtSubmit;
	}

	@Column(name = "CR_UID_APPROVER", length = 35)
	public String getCrUidApprover() {
		return this.crUidApprover;
	}

	public void setCrUidApprover(String crUidApprover) {
		this.crUidApprover = crUidApprover;
	}

	@Column(name = "CR_COMMENT_APPROVER", length = 16777215)
	public String getCrCommentApprover() {
		return this.crCommentApprover;
	}

	public void setCrCommentApprover(String crCommentApprover) {
		this.crCommentApprover = crCommentApprover;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CR_DT_APPROVE_REJECT", length = 19)
	public Date getCrDtApproveReject() {
		return this.crDtApproveReject;
	}

	public void setCrDtApproveReject(Date crDtApproveReject) {
		this.crDtApproveReject = crDtApproveReject;
	}

	@Column(name = "CR_COMMENT", length = 16777215)
	public String getCrComment() {
		return this.crComment;
	}

	public void setCrComment(String crComment) {
		this.crComment = crComment;
	}

	@Column(name = "CR_STATUS", length = 1)
	public Character getCrStatus() {
		return this.crStatus;
	}

	public void setCrStatus(Character crStatus) {
		this.crStatus = crStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CR_DT_CREATE", length = 19)
	public Date getCrDtCreate() {
		return this.crDtCreate;
	}

	public void setCrDtCreate(Date crDtCreate) {
		this.crDtCreate = crDtCreate;
	}

	@Column(name = "CR_UID_CREATE", length = 35)
	public String getCrUidCreate() {
		return this.crUidCreate;
	}

	public void setCrUidCreate(String crUidCreate) {
		this.crUidCreate = crUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CR_DT_LUPD", length = 19)
	public Date getCrDtLupd() {
		return this.crDtLupd;
	}

	public void setCrDtLupd(Date crDtLupd) {
		this.crDtLupd = crDtLupd;
	}

	@Column(name = "CR_UID_LUPD", length = 35)
	public String getCrUidLupd() {
		return this.crUidLupd;
	}

	public void setCrUidLupd(String crUidLupd) {
		this.crUidLupd = crUidLupd;
	}

	@Override
	public int compareTo(TCkCtContractReq o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

	@Column(name = "CR_FINANCE_MODEL", length = 35)
	public String getCrFinanceModel() {
		return crFinanceModel;
	}

	public void setCrFinanceModel(String crFinanceModel) {
		this.crFinanceModel = crFinanceModel;
	}
	
	
	

}
