package com.guudint.clickargo.clictruck.admin.contract.model;
// Generated 21 Feb, 2023 3:06:01 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import org.springframework.beans.BeanUtils;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.guudint.clickargo.clictruck.admin.contract.dto.CkCtContract;
import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;
import com.vcc.camelone.master.model.TMstBank;
import com.vcc.camelone.master.model.TMstCurrency;

/**
 * TCkCtContract generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_CONTRACT")
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
public class TCkCtContract extends COAbstractEntity<TCkCtContract> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 7684181573821960874L;

	// Attributes
	/////////////
	private String conId;
	private TCkCtContractCharge TCkCtContractChargeByConChargeTo;
	private Integer conPaytermTo;
	private TCkCtContractCharge TCkCtContractChargeByConChargeCoFf;
	private Integer conPaytermCoFf;
	private TCoreAccn TCoreAccnByConTo;
	private TCoreAccn TCoreAccnByConCoFf;
	private TMstCurrency TMstCurrency;
	private String conName;
	private String conDescription;
	private Date conDtStart;
	private Date conDtEnd;
	private Character conStatus;
	private Date conDtCreate;
	private String conUidCreate;
	private Date conDtLupd;
	private String conUidLupd;

	// OPM
	private String conFinanceModel;
	private TCkCtContractCharge TCkCtContractChargeByConOpm;
	private TMstBank TMstBank;
	
	// Constructors
	///////////////
	public TCkCtContract() {
	}

	public TCkCtContract(String conId) {
		this.conId = conId;
	}

	public TCkCtContract(CkCtContract ckCtContract) {
		BeanUtils.copyProperties(ckCtContract, this, "additionalTaxTo", "witholdTaxTo", "additionalTaxCoFf",
				"witholdTaxCoFf");
	}

	public TCkCtContract(String conId, TCkCtContractCharge TCkCtContractChargeByConChargeTo, Integer conPaytermTo,
			TCkCtContractCharge TCkCtContractChargeByConChargeCoFf, Integer conPaytermCoFf, TCoreAccn TCoreAccnByConTo,
			TCoreAccn TCoreAccnByConCoFf, TMstCurrency TMstCurrency, String conName, String conDescription,
			Date conDtStart, Date conDtEnd, Character conStatus, Date conDtCreate, String conUidCreate, Date conDtLupd,
			String conUidLupd) {
		this.conId = conId;
		this.TCkCtContractChargeByConChargeTo = TCkCtContractChargeByConChargeTo;
		this.conPaytermTo = conPaytermTo;
		this.conPaytermCoFf = conPaytermCoFf;
		this.TCkCtContractChargeByConChargeCoFf = TCkCtContractChargeByConChargeCoFf;
		this.TCoreAccnByConTo = TCoreAccnByConTo;
		this.TCoreAccnByConCoFf = TCoreAccnByConCoFf;
		this.TMstCurrency = TMstCurrency;
		this.conName = conName;
		this.conDescription = conDescription;
		this.conDtStart = conDtStart;
		this.conDtEnd = conDtEnd;
		this.conStatus = conStatus;
		this.conDtCreate = conDtCreate;
		this.conUidCreate = conUidCreate;
		this.conDtLupd = conDtLupd;
		this.conUidLupd = conUidLupd;
	}


	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkCtContract arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}
	
	// Properties
	/////////////
	@Id
	@Column(name = "CON_ID", unique = true, nullable = false, length = 35)
	public String getConId() {
		return this.conId;
	}

	public void setConId(String conId) {
		this.conId = conId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CON_CHARGE_TO")
	public TCkCtContractCharge getTCkCtContractChargeByConChargeTo() {
		return this.TCkCtContractChargeByConChargeTo;
	}

	public void setTCkCtContractChargeByConChargeTo(TCkCtContractCharge TCkCtContractChargeByConChargeTo) {
		this.TCkCtContractChargeByConChargeTo = TCkCtContractChargeByConChargeTo;
	}

	@Column(name = "CON_PAYTERM_TO")
	public Integer getConPaytermTo() {
		return this.conPaytermTo;
	}

	public void setConPaytermTo(Integer conPaytermTo) {
		this.conPaytermTo = conPaytermTo;
	}

	@Column(name = "CON_PAYTERM_CO_FF")
	public Integer getConPaytermCoFf() {
		return this.conPaytermCoFf;
	}

	public void setConPaytermCoFf(Integer conPaytermCoFf) {
		this.conPaytermCoFf = conPaytermCoFf;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CON_CHARGE_CO_FF")
	public TCkCtContractCharge getTCkCtContractChargeByConChargeCoFf() {
		return this.TCkCtContractChargeByConChargeCoFf;
	}

	public void setTCkCtContractChargeByConChargeCoFf(TCkCtContractCharge TCkCtContractChargeByConChargeCoFf) {
		this.TCkCtContractChargeByConChargeCoFf = TCkCtContractChargeByConChargeCoFf;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CON_TO")
	public TCoreAccn getTCoreAccnByConTo() {
		return this.TCoreAccnByConTo;
	}

	public void setTCoreAccnByConTo(TCoreAccn TCoreAccnByConTo) {
		this.TCoreAccnByConTo = TCoreAccnByConTo;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CON_CO_FF")
	public TCoreAccn getTCoreAccnByConCoFf() {
		return this.TCoreAccnByConCoFf;
	}

	public void setTCoreAccnByConCoFf(TCoreAccn TCoreAccnByConCoFf) {
		this.TCoreAccnByConCoFf = TCoreAccnByConCoFf;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CON_CCY")
	public TMstCurrency getTMstCurrency() {
		return this.TMstCurrency;
	}

	public void setTMstCurrency(TMstCurrency TMstCurrency) {
		this.TMstCurrency = TMstCurrency;
	}

	@Column(name = "CON_NAME", length = 1024)
	public String getConName() {
		return this.conName;
	}

	public void setConName(String conName) {
		this.conName = conName;
	}

	@Column(name = "CON_DESCRIPTION", length = 16777215)
	public String getConDescription() {
		return this.conDescription;
	}

	public void setConDescription(String conDescription) {
		this.conDescription = conDescription;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CON_DT_START", length = 19)
	public Date getConDtStart() {
		return this.conDtStart;
	}

	public void setConDtStart(Date conDtStart) {
		this.conDtStart = conDtStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CON_DT_END", length = 19)
	public Date getConDtEnd() {
		return this.conDtEnd;
	}

	public void setConDtEnd(Date conDtEnd) {
		this.conDtEnd = conDtEnd;
	}

	@Column(name = "CON_FINANCE_MODEL", length = 35)
	public String getConFinanceModel() {
		return this.conFinanceModel;
	}

	public void setConFinanceModel(String conFinanceModel) {
		this.conFinanceModel = conFinanceModel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CON_OPM")
	public TCkCtContractCharge getTCkCtContractChargeByConOpm() {
		return this.TCkCtContractChargeByConOpm;
	}

	public void setTCkCtContractChargeByConOpm(TCkCtContractCharge TCkCtContractChargeByConOpm) {
		this.TCkCtContractChargeByConOpm = TCkCtContractChargeByConOpm;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CON_OPM_BANK")
	public TMstBank getTMstBank() {
		return this.TMstBank;
	}

	public void setTMstBank(TMstBank TMstBank) {
		this.TMstBank = TMstBank;
	}
	
	
	@Column(name = "CON_STATUS", length = 1)
	public Character getConStatus() {
		return this.conStatus;
	}

	public void setConStatus(Character conStatus) {
		this.conStatus = conStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CON_DT_CREATE", length = 19)
	@CreationTimestamp
	public Date getConDtCreate() {
		return this.conDtCreate;
	}

	public void setConDtCreate(Date conDtCreate) {
		this.conDtCreate = conDtCreate;
	}

	@Column(name = "CON_UID_CREATE", length = 35)
	public String getConUidCreate() {
		return this.conUidCreate;
	}

	public void setConUidCreate(String conUidCreate) {
		this.conUidCreate = conUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CON_DT_LUPD", length = 19)
	@UpdateTimestamp
	public Date getConDtLupd() {
		return this.conDtLupd;
	}

	public void setConDtLupd(Date conDtLupd) {
		this.conDtLupd = conDtLupd;
	}

	@Column(name = "CON_UID_LUPD", length = 35)
	public String getConUidLupd() {
		return this.conUidLupd;
	}

	public void setConUidLupd(String conUidLupd) {
		this.conUidLupd = conUidLupd;
	}
}
