package com.guudint.clickargo.clictruck.opm.model;
// Generated 22 Mar 2024, 2:40:54 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkOpmSftpLog generated by hbm2java
 */
@Entity
@Table(name = "T_CK_OPM_SFTP_LOG")
public class TCkOpmSftpLog extends COAbstractEntity<TCkOpmSftpLog> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 8191831755093035598L;
	public static final String PREFIX_ID = "OPMSL";

	// Attributes
	/////////////
	private String opmslId;
	private String opmslFinancer;
	private String opmslDirection;
	private String opmslFileType;
	private String opmslFileName;
	private String opmslFilePath;
	private Integer opmslFileSize;
	private String opmslAccnIds;
	private String opmslJobIds;
	private Date opmslDtFileCreate;
	private Date opmslDtFilePush2sftp;
	private String opmslRemark;
	
	private String opmslErrorFileName;
	private String opmslErrorFilePath;
	private Integer opmslErrorFileSize;
	private String opmslErrorAccnIds;
	private String opmslErrorJobIds;
	private Date opmslDtErrorFileCreate;
	private Date opmslDtErrorFilePush2sftp;
	private String opmslErrorFileRemark;
	
	private Character opmslStatus;
	private Date opmslDtCreate;
	private String opmslUidCreate;
	private Date opmslDtLupd;
	private String opmslUidLupd;
	
	// Construction
	/////////////
	public TCkOpmSftpLog() {
	}

	public TCkOpmSftpLog(String opmslId) {
		this.opmslId = opmslId;
	}

	// Override
	/////////////
	@Override
	public int compareTo(TCkOpmSftpLog o) {
		return 0;
	}

	@Override
	public void init() {
	}

	@Id

	@Column(name = "OPMSL_ID", unique = true, nullable = false, length = 35)
	public String getOpmslId() {
		return this.opmslId;
	}

	public void setOpmslId(String opmslId) {
		this.opmslId = opmslId;
	}

	@Column(name = "OPMSL_FINANCER", length = 35)
	public String getOpmslFinancer() {
		return this.opmslFinancer;
	}

	public void setOpmslFinancer(String opmslFinancer) {
		this.opmslFinancer = opmslFinancer;
	}

	@Column(name = "OPMSL_DIRECTION")
	public String getOpmslDirection() {
		return this.opmslDirection;
	}

	public void setOpmslDirection(String opmslDirection) {
		this.opmslDirection = opmslDirection;
	}

	@Column(name = "OPMSL_FILE_TYPE")
	public String getOpmslFileType() {
		return this.opmslFileType;
	}

	public void setOpmslFileType(String opmslFileType) {
		this.opmslFileType = opmslFileType;
	}

	@Column(name = "OPMSL_FILE_NAME", length = 256)
	public String getOpmslFileName() {
		return this.opmslFileName;
	}

	public void setOpmslFileName(String opmslFileName) {
		this.opmslFileName = opmslFileName;
	}

	@Column(name = "OPMSL_FILE_PATH", length = 512)
	public String getOpmslFilePath() {
		return this.opmslFilePath;
	}

	public void setOpmslFilePath(String opmslFilePath) {
		this.opmslFilePath = opmslFilePath;
	}

	@Column(name = "OPMSL_FILE_SIZE")
	public Integer getOpmslFileSize() {
		return this.opmslFileSize;
	}

	public void setOpmslFileSize(Integer opmslFileSize) {
		this.opmslFileSize = opmslFileSize;
	}

	@Column(name = "OPMSL_ACCN_IDS", length = 256)
	public String getOpmslAccnIds() {
		return this.opmslAccnIds;
	}

	public void setOpmslAccnIds(String opmslAccnIds) {
		this.opmslAccnIds = opmslAccnIds;
	}

	@Column(name = "OPMSL_JOB_IDS", length = 2048)
	public String getOpmslJobIds() {
		return this.opmslJobIds;
	}

	public void setOpmslJobIds(String opmslJobIds) {
		this.opmslJobIds = opmslJobIds;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OPMSL_DT_FILE_CREATE", length = 19)
	public Date getOpmslDtFileCreate() {
		return this.opmslDtFileCreate;
	}

	public void setOpmslDtFileCreate(Date opmslDtFileCreate) {
		this.opmslDtFileCreate = opmslDtFileCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OPMSL_DT_FILE_PUSH2SFTP", length = 19)
	public Date getOpmslDtFilePush2sftp() {
		return this.opmslDtFilePush2sftp;
	}

	public void setOpmslDtFilePush2sftp(Date opmslDtFilePush2sftp) {
		this.opmslDtFilePush2sftp = opmslDtFilePush2sftp;
	}

	@Column(name = "OPMSL_REMARK", length = 1024)
	public String getOpmslRemark() {
		return this.opmslRemark;
	}

	public void setOpmslRemark(String opmslRemark) {
		this.opmslRemark = opmslRemark;
	}

	@Column(name = "OPMSL_ERROR_FILE_NAME", length = 256)
	public String getOpmslErrorFileName() {
		return this.opmslErrorFileName;
	}

	public void setOpmslErrorFileName(String opmslErrorFileName) {
		this.opmslErrorFileName = opmslErrorFileName;
	}

	@Column(name = "OPMSL_ERROR_FILE_PATH", length = 512)
	public String getOpmslErrorFilePath() {
		return this.opmslErrorFilePath;
	}

	public void setOpmslErrorFilePath(String opmslErrorFilePath) {
		this.opmslErrorFilePath = opmslErrorFilePath;
	}

	@Column(name = "OPMSL_ERROR_FILE_SIZE")
	public Integer getOpmslErrorFileSize() {
		return this.opmslErrorFileSize;
	}

	public void setOpmslErrorFileSize(Integer opmslErrorFileSize) {
		this.opmslErrorFileSize = opmslErrorFileSize;
	}

	@Column(name = "OPMSL_ERROR_ACCN_IDS", length = 256)
	public String getOpmslErrorAccnIds() {
		return this.opmslErrorAccnIds;
	}

	public void setOpmslErrorAccnIds(String opmslErrorAccnIds) {
		this.opmslErrorAccnIds = opmslErrorAccnIds;
	}

	@Column(name = "OPMSL_ERROR_JOB_IDS", length = 2048)
	public String getOpmslErrorJobIds() {
		return this.opmslErrorJobIds;
	}

	public void setOpmslErrorJobIds(String opmslErrorJobIds) {
		this.opmslErrorJobIds = opmslErrorJobIds;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OPMSL_DT_ERROR_FILE_CREATE", length = 19)
	public Date getOpmslDtErrorFileCreate() {
		return this.opmslDtErrorFileCreate;
	}

	public void setOpmslDtErrorFileCreate(Date opmslDtErrorFileCreate) {
		this.opmslDtErrorFileCreate = opmslDtErrorFileCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OPMSL_DT_ERROR_FILE_PUSH2SFTP", length = 19)
	public Date getOpmslDtErrorFilePush2sftp() {
		return this.opmslDtErrorFilePush2sftp;
	}

	public void setOpmslDtErrorFilePush2sftp(Date opmslDtErrorFilePush2sftp) {
		this.opmslDtErrorFilePush2sftp = opmslDtErrorFilePush2sftp;
	}

	@Column(name = "OPMSL_ERROR_FILE_REMARK", length = 1024)
	public String getOpmslErrorFileRemark() {
		return this.opmslErrorFileRemark;
	}

	public void setOpmslErrorFileRemark(String opmslErrorFileRemark) {
		this.opmslErrorFileRemark = opmslErrorFileRemark;
	}

	@Column(name = "OPMSL_STATUS", length = 1)
	public Character getOpmslStatus() {
		return this.opmslStatus;
	}

	public void setOpmslStatus(Character opmslStatus) {
		this.opmslStatus = opmslStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OPMSL_DT_CREATE", length = 19)
	public Date getOpmslDtCreate() {
		return this.opmslDtCreate;
	}

	public void setOpmslDtCreate(Date opmslDtCreate) {
		this.opmslDtCreate = opmslDtCreate;
	}

	@Column(name = "OPMSL_UID_CREATE", length = 35)
	public String getOpmslUidCreate() {
		return this.opmslUidCreate;
	}

	public void setOpmslUidCreate(String opmslUidCreate) {
		this.opmslUidCreate = opmslUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OPMSL_DT_LUPD", length = 19)
	public Date getOpmslDtLupd() {
		return this.opmslDtLupd;
	}

	public void setOpmslDtLupd(Date opmslDtLupd) {
		this.opmslDtLupd = opmslDtLupd;
	}

	@Column(name = "OPMSL_UID_LUPD", length = 35)
	public String getOpmslUidLupd() {
		return this.opmslUidLupd;
	}

	public void setOpmslUidLupd(String opmslUidLupd) {
		this.opmslUidLupd = opmslUidLupd;
	}

}
