package com.guudint.clickargo.clictruck.opm.model;
// Generated 14 Mar 2024, 9:10:12 am by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.guudint.clickargo.master.model.TCkMstServiceType;
import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;
import com.vcc.camelone.master.model.TMstCurrency;

/**
 * TCkOpmSummary generated by hbm2java
 */
@Entity
@Table(name = "T_CK_OPM_SUMMARY")
public class TCkOpmSummary extends COAbstractEntity<TCkOpmSummary> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 8191831755093035598L;
	public static final String PREFIX_ID = "OPMS";
	
	// Attributes
	/////////////
	private String opmsId;
	private TCkMstServiceType TCkMstServiceType;
	private TCoreAccn TCoreAccn;
	private TMstCurrency TMstCurrency;
	private BigDecimal opmsAmt;
	private BigDecimal opmsReserve;
	private BigDecimal opmsUtilized;
	private BigDecimal opmsBalance;
	private Character opmsStatus;
	private Date opmsDtCreate;
	private String opmsUidCreate;
	private Date opmsDtLupd;
	private String opmsUidLupd;
	private String opmsCredit;

	public TCkOpmSummary() {
	}

	public TCkOpmSummary(String opmsId) {
		this.opmsId = opmsId;
	}


	@Override
	public int compareTo(TCkOpmSummary o) {
		return 0;
	}

	@Override
	public void init() {
	}

	@Id

	@Column(name = "OPMS_ID", unique = true, nullable = false, length = 35)
	public String getOpmsId() {
		return this.opmsId;
	}

	public void setOpmsId(String opmsId) {
		this.opmsId = opmsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OPMS_SERVICE_TYPE")
	public TCkMstServiceType getTCkMstServiceType() {
		return this.TCkMstServiceType;
	}

	public void setTCkMstServiceType(TCkMstServiceType TCkMstServiceType) {
		this.TCkMstServiceType = TCkMstServiceType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OPMS_COMPANY")
	public TCoreAccn getTCoreAccn() {
		return this.TCoreAccn;
	}

	public void setTCoreAccn(TCoreAccn TCoreAccn) {
		this.TCoreAccn = TCoreAccn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OPMS_CCY")
	public TMstCurrency getTMstCurrency() {
		return this.TMstCurrency;
	}

	public void setTMstCurrency(TMstCurrency TMstCurrency) {
		this.TMstCurrency = TMstCurrency;
	}

	@Column(name = "OPMS_AMT", precision = 15)
	public BigDecimal getOpmsAmt() {
		return this.opmsAmt;
	}

	public void setOpmsAmt(BigDecimal opmsAmt) {
		this.opmsAmt = opmsAmt;
	}

	@Column(name = "OPMS_RESERVE", precision = 15)
	public BigDecimal getOpmsReserve() {
		return this.opmsReserve;
	}

	public void setOpmsReserve(BigDecimal opmsReserve) {
		this.opmsReserve = opmsReserve;
	}

	@Column(name = "OPMS_UTILIZED", precision = 15)
	public BigDecimal getOpmsUtilized() {
		return this.opmsUtilized;
	}

	public void setOpmsUtilized(BigDecimal opmsUtilized) {
		this.opmsUtilized = opmsUtilized;
	}

	@Column(name = "OPMS_BALANCE", precision = 15)
	public BigDecimal getOpmsBalance() {
		return this.opmsBalance;
	}

	public void setOpmsBalance(BigDecimal opmsBalance) {
		this.opmsBalance = opmsBalance;
	}

	@Column(name = "OPMS_STATUS", length = 1)
	public Character getOpmsStatus() {
		return this.opmsStatus;
	}

	public void setOpmsStatus(Character opmsStatus) {
		this.opmsStatus = opmsStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OPMS_DT_CREATE", length = 19)
	public Date getOpmsDtCreate() {
		return this.opmsDtCreate;
	}

	public void setOpmsDtCreate(Date opmsDtCreate) {
		this.opmsDtCreate = opmsDtCreate;
	}

	@Column(name = "OPMS_UID_CREATE", length = 35)
	public String getOpmsUidCreate() {
		return this.opmsUidCreate;
	}

	public void setOpmsUidCreate(String opmsUidCreate) {
		this.opmsUidCreate = opmsUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OPMS_DT_LUPD", length = 19)
	public Date getOpmsDtLupd() {
		return this.opmsDtLupd;
	}

	public void setOpmsDtLupd(Date opmsDtLupd) {
		this.opmsDtLupd = opmsDtLupd;
	}

	@Column(name = "OPMS_UID_LUPD", length = 35)
	public String getOpmsUidLupd() {
		return this.opmsUidLupd;
	}

	public void setOpmsUidLupd(String opmsUidLupd) {
		this.opmsUidLupd = opmsUidLupd;
	}

	@Column(name = "OPMS_CREDIT", length = 35)
	public String getOpmsCredit() {
		return this.opmsCredit;
	}

	public void setOpmsCredit(String opmsCredit) {
		this.opmsCredit = opmsCredit;
	}

}
