package com.guudint.clickargo.clictruck.opm.model;
// Generated 14 Mar 2024, 9:10:12 am by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.guudint.clickargo.master.model.TCkMstJournalTxnType;
import com.guudint.clickargo.master.model.TCkMstServiceType;
import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;
import com.vcc.camelone.master.model.TMstCurrency;

/**
 * TCkOpmJournal generated by hbm2java
 */
@Entity
@Table(name = "T_CK_OPM_JOURNAL")
public class TCkOpmJournal extends COAbstractEntity<TCkOpmJournal> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 1L;
	
	// Attributes
	/////////////
	private String opmjId;
	private TCkMstJournalTxnType TCkMstJournalTxnType;
	private TCkMstServiceType TCkMstServiceType;
	private TCoreAccn TCoreAccn;
	private TMstCurrency TMstCurrency;
	private String opmjTxnRef;
	private BigDecimal opmjReserve;
	private BigDecimal opmjUtilized;
	private Character opmjStatus;
	private Date opmjDtCreate;
	private String opmjUidCreate;
	private Date opmjDtLupd;
	private String opmjUidLupd;

	public TCkOpmJournal() {
	}

	public TCkOpmJournal(String opmjId) {
		this.opmjId = opmjId;
	}


	@Override
	public int compareTo(TCkOpmJournal o) {
		return 0;
	}

	@Override
	public void init() {
	}

	@Id

	@Column(name = "OPMJ_ID", unique = true, nullable = false, length = 35)
	public String getOpmjId() {
		return this.opmjId;
	}

	public void setOpmjId(String opmjId) {
		this.opmjId = opmjId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OPMJ_TXN_TYPE")
	public TCkMstJournalTxnType getTCkMstJournalTxnType() {
		return this.TCkMstJournalTxnType;
	}

	public void setTCkMstJournalTxnType(TCkMstJournalTxnType TCkMstJournalTxnType) {
		this.TCkMstJournalTxnType = TCkMstJournalTxnType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OPMJ_SERVICE_TYPE")
	public TCkMstServiceType getTCkMstServiceType() {
		return this.TCkMstServiceType;
	}

	public void setTCkMstServiceType(TCkMstServiceType TCkMstServiceType) {
		this.TCkMstServiceType = TCkMstServiceType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OPMJ_COMPANY")
	public TCoreAccn getTCoreAccn() {
		return this.TCoreAccn;
	}

	public void setTCoreAccn(TCoreAccn TCoreAccn) {
		this.TCoreAccn = TCoreAccn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OPMJ_CCY")
	public TMstCurrency getTMstCurrency() {
		return this.TMstCurrency;
	}

	public void setTMstCurrency(TMstCurrency TMstCurrency) {
		this.TMstCurrency = TMstCurrency;
	}

	@Column(name = "OPMJ_TXN_REF")
	public String getOpmjTxnRef() {
		return this.opmjTxnRef;
	}

	public void setOpmjTxnRef(String opmjTxnRef) {
		this.opmjTxnRef = opmjTxnRef;
	}

	@Column(name = "OPMJ_RESERVE", precision = 15)
	public BigDecimal getOpmjReserve() {
		return this.opmjReserve;
	}

	public void setOpmjReserve(BigDecimal opmjReserve) {
		this.opmjReserve = opmjReserve;
	}

	@Column(name = "OPMJ_UTILIZED", precision = 15)
	public BigDecimal getOpmjUtilized() {
		return this.opmjUtilized;
	}

	public void setOpmjUtilized(BigDecimal opmjUtilized) {
		this.opmjUtilized = opmjUtilized;
	}

	@Column(name = "OPMJ_STATUS", length = 1)
	public Character getOpmjStatus() {
		return this.opmjStatus;
	}

	public void setOpmjStatus(Character opmjStatus) {
		this.opmjStatus = opmjStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OPMJ_DT_CREATE", length = 19)
	public Date getOpmjDtCreate() {
		return this.opmjDtCreate;
	}

	public void setOpmjDtCreate(Date opmjDtCreate) {
		this.opmjDtCreate = opmjDtCreate;
	}

	@Column(name = "OPMJ_UID_CREATE", length = 35)
	public String getOpmjUidCreate() {
		return this.opmjUidCreate;
	}

	public void setOpmjUidCreate(String opmjUidCreate) {
		this.opmjUidCreate = opmjUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OPMJ_DT_LUPD", length = 19)
	public Date getOpmjDtLupd() {
		return this.opmjDtLupd;
	}

	public void setOpmjDtLupd(Date opmjDtLupd) {
		this.opmjDtLupd = opmjDtLupd;
	}

	@Column(name = "OPMJ_UID_LUPD", length = 35)
	public String getOpmjUidLupd() {
		return this.opmjUidLupd;
	}

	public void setOpmjUidLupd(String opmjUidLupd) {
		this.opmjUidLupd = opmjUidLupd;
	}

}
