package com.guudint.clickargo.clictruck.opm.model;
// Generated 14 Mar 2024, 9:10:12 am by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.guudint.clickargo.master.model.TCkMstCreditState;
import com.guudint.clickargo.master.model.TCkMstServiceType;
import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;
import com.vcc.camelone.master.model.TMstCurrency;

/**
 * TCkOpm generated by hbm2java
 */
@Entity
@Table(name = "T_CK_OPM")
public class TCkOpm extends COAbstractEntity<TCkOpm> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 8191831755093035598L;
	public static final String PREFIX_ID = "OPM";
	
	// Attributes
	/////////////
	private String opmId;
	private TCkMstCreditState TCkMstCreditState;
	private TCkMstServiceType TCkMstServiceType;
	private TCoreAccn TCoreAccn;
	private TMstCurrency TMstCurrency;
	private String opmFinancer;
	private BigDecimal opmAmt;
	
	private Date opmDtStart;
	private Date opmDtEnd;
	private String opmUsrVerify;
	private Date opmDtVerify;
	private String opmUsrApprove;
	private Date opmDtApprove;
	private String opmRemarks;
	
	private Character opmStatus;
	private Date opmDtCreate;
	private String opmUidCreate;
	private Date opmDtLupd;
	private String opmUidLupd;

	public TCkOpm() {
	}

	public TCkOpm(String opmId) {
		this.opmId = opmId;
	}

	public TCkOpm(String opmId, TCkMstCreditState TCkMstCreditState, TCkMstServiceType TCkMstServiceType,
			TCoreAccn TCoreAccn, TMstCurrency TMstCurrency, String opmFinancer, BigDecimal opmAmt, Date opmDtStart,
			Date opmDtEnd, String opmUsrVerify, Date opmDtVerify, String opmUsrApprove, Date opmDtApprove,
			String opmRemarks, Character opmStatus, Date opmDtCreate, String opmUidCreate, Date opmDtLupd,
			String opmUidLupd) {
		this.opmId = opmId;
		this.TCkMstCreditState = TCkMstCreditState;
		this.TCkMstServiceType = TCkMstServiceType;
		this.TCoreAccn = TCoreAccn;
		this.TMstCurrency = TMstCurrency;
		this.opmFinancer = opmFinancer;
		this.opmAmt = opmAmt;
		this.opmDtStart = opmDtStart;
		this.opmDtEnd = opmDtEnd;
		this.opmUsrVerify = opmUsrVerify;
		this.opmDtVerify = opmDtVerify;
		this.opmUsrApprove = opmUsrApprove;
		this.opmDtApprove = opmDtApprove;
		this.opmRemarks = opmRemarks;
		this.opmStatus = opmStatus;
		this.opmDtCreate = opmDtCreate;
		this.opmUidCreate = opmUidCreate;
		this.opmDtLupd = opmDtLupd;
		this.opmUidLupd = opmUidLupd;
	}


	@Override
	public int compareTo(TCkOpm o) {
		return 0;
	}

	@Override
	public void init() {
	}

	@Id

	@Column(name = "OPM_ID", unique = true, nullable = false, length = 35)
	public String getOpmId() {
		return this.opmId;
	}

	public void setOpmId(String opmId) {
		this.opmId = opmId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OPM_STATE")
	public TCkMstCreditState getTCkMstCreditState() {
		return this.TCkMstCreditState;
	}

	public void setTCkMstCreditState(TCkMstCreditState TCkMstCreditState) {
		this.TCkMstCreditState = TCkMstCreditState;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OPM_SERVICE_TYPE")
	public TCkMstServiceType getTCkMstServiceType() {
		return this.TCkMstServiceType;
	}

	public void setTCkMstServiceType(TCkMstServiceType TCkMstServiceType) {
		this.TCkMstServiceType = TCkMstServiceType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OPM_COMPANY")
	public TCoreAccn getTCoreAccn() {
		return this.TCoreAccn;
	}

	public void setTCoreAccn(TCoreAccn TCoreAccn) {
		this.TCoreAccn = TCoreAccn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OPM_CCY")
	public TMstCurrency getTMstCurrency() {
		return this.TMstCurrency;
	}

	public void setTMstCurrency(TMstCurrency TMstCurrency) {
		this.TMstCurrency = TMstCurrency;
	}

	@Column(name = "OPM_FINANCER", length = 35)
	public String getOpmFinancer() {
		return this.opmFinancer;
	}

	public void setOpmFinancer(String opmFinancer) {
		this.opmFinancer = opmFinancer;
	}

	@Column(name = "OPM_AMT", precision = 15)
	public BigDecimal getOpmAmt() {
		return this.opmAmt;
	}

	public void setOpmAmt(BigDecimal opmAmt) {
		this.opmAmt = opmAmt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OPM_DT_START", length = 19)
	public Date getOpmDtStart() {
		return this.opmDtStart;
	}

	public void setOpmDtStart(Date opmDtStart) {
		this.opmDtStart = opmDtStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OPM_DT_END", length = 19)
	public Date getOpmDtEnd() {
		return this.opmDtEnd;
	}

	public void setOpmDtEnd(Date opmDtEnd) {
		this.opmDtEnd = opmDtEnd;
	}

	@Column(name = "OPM_USR_VERIFY", length = 35)
	public String getOpmUsrVerify() {
		return this.opmUsrVerify;
	}

	public void setOpmUsrVerify(String opmUsrVerify) {
		this.opmUsrVerify = opmUsrVerify;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OPM_DT_VERIFY", length = 19)
	public Date getOpmDtVerify() {
		return this.opmDtVerify;
	}

	public void setOpmDtVerify(Date opmDtVerify) {
		this.opmDtVerify = opmDtVerify;
	}

	@Column(name = "OPM_USR_APPROVE", length = 35)
	public String getOpmUsrApprove() {
		return this.opmUsrApprove;
	}

	public void setOpmUsrApprove(String opmUsrApprove) {
		this.opmUsrApprove = opmUsrApprove;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OPM_DT_APPROVE", length = 19)
	public Date getOpmDtApprove() {
		return this.opmDtApprove;
	}

	public void setOpmDtApprove(Date opmDtApprove) {
		this.opmDtApprove = opmDtApprove;
	}

	@Column(name = "OPM_REMARKS", length = 16777215)
	public String getOpmRemarks() {
		return this.opmRemarks;
	}

	public void setOpmRemarks(String opmRemarks) {
		this.opmRemarks = opmRemarks;
	}

	@Column(name = "OPM_STATUS", length = 1)
	public Character getOpmStatus() {
		return this.opmStatus;
	}

	public void setOpmStatus(Character opmStatus) {
		this.opmStatus = opmStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OPM_DT_CREATE", length = 19)
	public Date getOpmDtCreate() {
		return this.opmDtCreate;
	}

	public void setOpmDtCreate(Date opmDtCreate) {
		this.opmDtCreate = opmDtCreate;
	}

	@Column(name = "OPM_UID_CREATE", length = 35)
	public String getOpmUidCreate() {
		return this.opmUidCreate;
	}

	public void setOpmUidCreate(String opmUidCreate) {
		this.opmUidCreate = opmUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OPM_DT_LUPD", length = 19)
	public Date getOpmDtLupd() {
		return this.opmDtLupd;
	}

	public void setOpmDtLupd(Date opmDtLupd) {
		this.opmDtLupd = opmDtLupd;
	}

	@Column(name = "OPM_UID_LUPD", length = 35)
	public String getOpmUidLupd() {
		return this.opmUidLupd;
	}

	public void setOpmUidLupd(String opmUidLupd) {
		this.opmUidLupd = opmUidLupd;
	}

}
