package com.guudint.clickargo.clictruck.planexec.job.event;

public enum ClicTruckNotifTemplates {

	BLANK("CKT_NTL_0000"),
	COFF_JOB_ACCEPTED("CKT_NTL_0001"),
	COFF_JOB_REJECTED("CKT_NTL_0002"),
	COFF_JOB_DELIVERED("CKT_NTL_0003"),
	COFF_INV_SUBMITTED("CKT_NTL_0004"),
	COFF_INV_VERIFIED("CKT_NTL_0005"),
	COFF_INV_APPROVED("CKT_NTL_0015"),
	TO_JOB_SUBMITTED("CKT_NTL_0006"),
	TO_INV_APPROVED("CKT_NTL_0007"),
	TO_INV_REJECTED("CKT_NTL_0008"),
	TO_SP_PAY_COMPLETE("CKT_NTL_0009"),
	SP_INV_APPROVED("CKT_NTL_0010"),
	SP_PAY_TXN_CREATED("CKT_NTL_0011"),
	SP_PAY_TXN_VERIFIED("CKT_NTL_0012"),
	SP_PAY_TXN_PAID("CKT_NTL_0013"),
	SP_PAY_TXN_FAILED("CKT_NTL_0014"),
	COFF_INV_SUBMITTED_APPROVALLINK("CKT_NTL_0051"),	
	DSV_POD_PHO("CKT_NTL_0061"),
	INSERANCE_APPLICATION("CKT_NTL_00100"),
	TO_TRUCK_PROVIDER_SUBMITTED("CKT_NTL_0063");

	private String id;
	
	private ClicTruckNotifTemplates(String id) {
		this.id = id;
	}
	
	public String getId() {
		return this.id;
	}
}
