package com.guudint.clickargo.clictruck.track.model;
// Generated 5 Oct 2023, 3:57:27 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.guudint.clickargo.clictruck.common.model.TCkCtLocation;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtTrackLocItem generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_TRACK_LOC_ITEM")
public class TCkCtTrackLocItem extends COAbstractEntity<TCkCtTrackLocItem> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -1L;
	public static final String PREFIX_ID = "LCI";

	private String tliId;
	private TCkCtLocation TCkCtLocation;
	private TCkCtTrackLoc TCkCtTrackLoc;
	private String tliGps;
	private int tliRadius;
	private Date tliDtEnter;
	private Date tliDtExit;
	private Character tliStatus;
	private Date tliDtCreate;
	private String tliUidCreate;
	private Date tliDtLupd;
	private String tliUidLupd;

	public TCkCtTrackLocItem() {
	}

	public TCkCtTrackLocItem(String tliId, TCkCtLocation TCkCtLocation, TCkCtTrackLoc TCkCtTrackLoc, String tliGps,
			int tliRadius) {
		this.tliId = tliId;
		this.TCkCtLocation = TCkCtLocation;
		this.TCkCtTrackLoc = TCkCtTrackLoc;
		this.tliGps = tliGps;
		this.tliRadius = tliRadius;
	}

	public TCkCtTrackLocItem(String tliId, TCkCtLocation TCkCtLocation, TCkCtTrackLoc TCkCtTrackLoc, String tliGps,
			int tliRadius, Date tliDtEnter, Date tliDtExit, Character tliStatus, Date tliDtCreate, String tliUidCreate,
			Date tliDtLupd, String tliUidLupd) {
		this.tliId = tliId;
		this.TCkCtLocation = TCkCtLocation;
		this.TCkCtTrackLoc = TCkCtTrackLoc;
		this.tliGps = tliGps;
		this.tliRadius = tliRadius;
		this.tliDtEnter = tliDtEnter;
		this.tliDtExit = tliDtExit;
		this.tliStatus = tliStatus;
		this.tliDtCreate = tliDtCreate;
		this.tliUidCreate = tliUidCreate;
		this.tliDtLupd = tliDtLupd;
		this.tliUidLupd = tliUidLupd;
	}

	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkCtTrackLocItem arg0) {
		return 0;
	}

	@Override
	public void init() {
	}

	@Id

	@Column(name = "TLI_ID", unique = true, nullable = false, length = 35)
	public String getTliId() {
		return this.tliId;
	}

	public void setTliId(String tliId) {
		this.tliId = tliId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TLI_TRIP_LOC_ID", nullable = false)
	public TCkCtLocation getTCkCtLocation() {
		return this.TCkCtLocation;
	}

	public void setTCkCtLocation(TCkCtLocation TCkCtLocation) {
		this.TCkCtLocation = TCkCtLocation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TLI_TRACK_LOC_ID", nullable = false)
	public TCkCtTrackLoc getTCkCtTrackLoc() {
		return this.TCkCtTrackLoc;
	}

	public void setTCkCtTrackLoc(TCkCtTrackLoc TCkCtTrackLoc) {
		this.TCkCtTrackLoc = TCkCtTrackLoc;
	}

	@Column(name = "TLI_GPS", nullable = false, length = 128)
	public String getTliGps() {
		return this.tliGps;
	}

	public void setTliGps(String tliGps) {
		this.tliGps = tliGps;
	}

	@Column(name = "TLI_RADIUS", nullable = false)
	public int getTliRadius() {
		return this.tliRadius;
	}

	public void setTliRadius(int tliRadius) {
		this.tliRadius = tliRadius;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TLI_DT_ENTER", length = 19)
	public Date getTliDtEnter() {
		return this.tliDtEnter;
	}

	public void setTliDtEnter(Date tliDtEnter) {
		this.tliDtEnter = tliDtEnter;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TLI_DT_EXIT", length = 19)
	public Date getTliDtExit() {
		return this.tliDtExit;
	}

	public void setTliDtExit(Date tliDtExit) {
		this.tliDtExit = tliDtExit;
	}

	@Column(name = "TLI_STATUS", length = 1)
	public Character getTliStatus() {
		return this.tliStatus;
	}

	public void setTliStatus(Character tliStatus) {
		this.tliStatus = tliStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TLI_DT_CREATE", length = 19)
	public Date getTliDtCreate() {
		return this.tliDtCreate;
	}

	public void setTliDtCreate(Date tliDtCreate) {
		this.tliDtCreate = tliDtCreate;
	}

	@Column(name = "TLI_UID_CREATE", length = 35)
	public String getTliUidCreate() {
		return this.tliUidCreate;
	}

	public void setTliUidCreate(String tliUidCreate) {
		this.tliUidCreate = tliUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TLI_DT_LUPD", length = 19)
	public Date getTliDtLupd() {
		return this.tliDtLupd;
	}

	public void setTliDtLupd(Date tliDtLupd) {
		this.tliDtLupd = tliDtLupd;
	}

	@Column(name = "TLI_UID_LUPD", length = 35)
	public String getTliUidLupd() {
		return this.tliUidLupd;
	}

	public void setTliUidLupd(String tliUidLupd) {
		this.tliUidLupd = tliUidLupd;
	}

}
