package com.guudint.clickargo.clictruck.track.model;
// Generated 8 Nov 2023, 9:58:05 am by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtTrackNotify generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_TRACK_NOTIFY")
public class TCkCtTrackNotify  extends COAbstractEntity<TCkCtTrackNotify> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -1L;
	public static final String PREFIX_ID = "TN";

	private String tnId;
	private String tnJobId;
	private String tnReceiver;
	private String tnMessage;
	private Date tnDtStart;
	private Date tnDtEnd;
	private String tnReqUrl;
	private String tnRspBody;
	private Integer tnSendStatus;
	private String tnHttpStatus;
	private String tnRemark;
	private Character tnStatus;
	private Date tnDtCreate;
	private String tnUidCreate;
	private Date tnDtLupd;
	private String tnUidLupd;

	public TCkCtTrackNotify() {
	}

	public TCkCtTrackNotify(String tnId) {
		this.tnId = tnId;
	}

	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkCtTrackNotify arg0) {
		return 0;
	}

	@Override
	public void init() {
	}

	@Id

	@Column(name = "TN_ID", unique = true, nullable = false, length = 35)
	public String getTnId() {
		return this.tnId;
	}

	public void setTnId(String tnId) {
		this.tnId = tnId;
	}

	@Column(name = "TN_JOB_ID", length = 35)
	public String getTnJobId() {
		return this.tnJobId;
	}

	public void setTnJobId(String tnJobId) {
		this.tnJobId = tnJobId;
	}

	@Column(name = "TN_RECEIVER", length = 1024)
	public String getTnReceiver() {
		return this.tnReceiver;
	}

	public void setTnReceiver(String tnReceiver) {
		this.tnReceiver = tnReceiver;
	}

	@Column(name = "TN_MESSAGE", length = 1024)
	public String getTnMessage() {
		return this.tnMessage;
	}

	public void setTnMessage(String tnMessage) {
		this.tnMessage = tnMessage;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TN_DT_START", length = 19)
	public Date getTnDtStart() {
		return this.tnDtStart;
	}

	public void setTnDtStart(Date tnDtStart) {
		this.tnDtStart = tnDtStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TN_DT_END", length = 19)
	public Date getTnDtEnd() {
		return this.tnDtEnd;
	}

	public void setTnDtEnd(Date tnDtEnd) {
		this.tnDtEnd = tnDtEnd;
	}

	@Column(name = "TN_REQ_URL", length = 1024)
	public String getTnReqUrl() {
		return this.tnReqUrl;
	}

	public void setTnReqUrl(String tnReqUrl) {
		this.tnReqUrl = tnReqUrl;
	}

	@Column(name = "TN_RSP_BODY", length = 16777215)
	public String getTnRspBody() {
		return this.tnRspBody;
	}

	public void setTnRspBody(String tnRspBody) {
		this.tnRspBody = tnRspBody;
	}

	@Column(name = "TN_SEND_STATUS")
	public Integer getTnSendStatus() {
		return this.tnSendStatus;
	}

	public void setTnSendStatus(Integer tnSendStatus) {
		this.tnSendStatus = tnSendStatus;
	}

	@Column(name = "TN_HTTP_STATUS", length = 35)
	public String getTnHttpStatus() {
		return this.tnHttpStatus;
	}

	public void setTnHttpStatus(String tnHttpStatus) {
		this.tnHttpStatus = tnHttpStatus;
	}

	@Column(name = "TN_REMARK", length = 1024)
	public String getTnRemark() {
		return this.tnRemark;
	}

	public void setTnRemark(String tnRemark) {
		this.tnRemark = tnRemark;
	}

	@Column(name = "TN_STATUS", length = 1)
	public Character getTnStatus() {
		return this.tnStatus;
	}

	public void setTnStatus(Character tnStatus) {
		this.tnStatus = tnStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TN_DT_CREATE", length = 19)
	public Date getTnDtCreate() {
		return this.tnDtCreate;
	}

	public void setTnDtCreate(Date tnDtCreate) {
		this.tnDtCreate = tnDtCreate;
	}

	@Column(name = "TN_UID_CREATE", length = 35)
	public String getTnUidCreate() {
		return this.tnUidCreate;
	}

	public void setTnUidCreate(String tnUidCreate) {
		this.tnUidCreate = tnUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TN_DT_LUPD", length = 19)
	public Date getTnDtLupd() {
		return this.tnDtLupd;
	}

	public void setTnDtLupd(Date tnDtLupd) {
		this.tnDtLupd = tnDtLupd;
	}

	@Column(name = "TN_UID_LUPD", length = 35)
	public String getTnUidLupd() {
		return this.tnUidLupd;
	}

	public void setTnUidLupd(String tnUidLupd) {
		this.tnUidLupd = tnUidLupd;
	}

}
