package com.guudint.clickargo.clictruck.track.model;
// Generated 8 Nov 2023, 9:58:05 am by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtTrackDistance generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_TRACK_DISTANCE")
public class TCkCtTrackDistance  extends COAbstractEntity<TCkCtTrackDistance> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -1L;
	public static final String PREFIX_ID = "TIS";

	private String tdId;
	private String tdJobId;
	private String tdOrigins;
	private String tdDestination;
	private String tdTransportaionMode;
	private Date tdDtStart;
	private Date tdDtEnd;
	private String tdReqUrl;
	private String tdRspBody;
	private Integer tdDistance;
	private Integer tdDuration;
	private String tdHttpStatus;
	private String tdRemark;
	private Character tdStatus;
	private Date tdDtCreate;
	private String tdUidCreate;
	private Date tdDtLupd;
	private String tdUidLupd;

	public TCkCtTrackDistance() {
	}

	public TCkCtTrackDistance(String tdId) {
		this.tdId = tdId;
	}

	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkCtTrackDistance arg0) {
		return 0;
	}

	@Override
	public void init() {
	}

	@Id

	@Column(name = "TD_ID", unique = true, nullable = false, length = 35)
	public String getTdId() {
		return this.tdId;
	}

	public void setTdId(String tdId) {
		this.tdId = tdId;
	}

	@Column(name = "TD_JOB_ID", length = 35)
	public String getTdJobId() {
		return this.tdJobId;
	}

	public void setTdJobId(String tdJobId) {
		this.tdJobId = tdJobId;
	}

	@Column(name = "TD_ORIGINS", length = 1024)
	public String getTdOrigins() {
		return this.tdOrigins;
	}

	public void setTdOrigins(String tdOrigins) {
		this.tdOrigins = tdOrigins;
	}

	@Column(name = "TD_DESTINATION", length = 1024)
	public String getTdDestination() {
		return this.tdDestination;
	}

	public void setTdDestination(String tdDestination) {
		this.tdDestination = tdDestination;
	}

	@Column(name = "TD_TRANSPORTAION_MODE", length = 35)
	public String getTdTransportaionMode() {
		return this.tdTransportaionMode;
	}

	public void setTdTransportaionMode(String tdTransportaionMode) {
		this.tdTransportaionMode = tdTransportaionMode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TD_DT_START", length = 19)
	public Date getTdDtStart() {
		return this.tdDtStart;
	}

	public void setTdDtStart(Date tdDtStart) {
		this.tdDtStart = tdDtStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TD_DT_END", length = 19)
	public Date getTdDtEnd() {
		return this.tdDtEnd;
	}

	public void setTdDtEnd(Date tdDtEnd) {
		this.tdDtEnd = tdDtEnd;
	}

	@Column(name = "TD_REQ_URL", length = 1024)
	public String getTdReqUrl() {
		return this.tdReqUrl;
	}

	public void setTdReqUrl(String tdReqUrl) {
		this.tdReqUrl = tdReqUrl;
	}

	@Column(name = "TD_RSP_BODY", length = 16777215)
	public String getTdRspBody() {
		return this.tdRspBody;
	}

	public void setTdRspBody(String tdRspBody) {
		this.tdRspBody = tdRspBody;
	}

	@Column(name = "TD_DISTANCE")
	public Integer getTdDistance() {
		return this.tdDistance;
	}

	public void setTdDistance(Integer tdDistance) {
		this.tdDistance = tdDistance;
	}

	@Column(name = "TD_DURATION")
	public Integer getTdDuration() {
		return this.tdDuration;
	}

	public void setTdDuration(Integer tdDuration) {
		this.tdDuration = tdDuration;
	}

	@Column(name = "TD_HTTP_STATUS", length = 35)
	public String getTdHttpStatus() {
		return this.tdHttpStatus;
	}

	public void setTdHttpStatus(String tdHttpStatus) {
		this.tdHttpStatus = tdHttpStatus;
	}

	@Column(name = "TD_REMARK", length = 1024)
	public String getTdRemark() {
		return this.tdRemark;
	}

	public void setTdRemark(String tdRemark) {
		this.tdRemark = tdRemark;
	}

	@Column(name = "TD_STATUS", length = 1)
	public Character getTdStatus() {
		return this.tdStatus;
	}

	public void setTdStatus(Character tdStatus) {
		this.tdStatus = tdStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TD_DT_CREATE", length = 19)
	public Date getTdDtCreate() {
		return this.tdDtCreate;
	}

	public void setTdDtCreate(Date tdDtCreate) {
		this.tdDtCreate = tdDtCreate;
	}

	@Column(name = "TD_UID_CREATE", length = 35)
	public String getTdUidCreate() {
		return this.tdUidCreate;
	}

	public void setTdUidCreate(String tdUidCreate) {
		this.tdUidCreate = tdUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TD_DT_LUPD", length = 19)
	public Date getTdDtLupd() {
		return this.tdDtLupd;
	}

	public void setTdDtLupd(Date tdDtLupd) {
		this.tdDtLupd = tdDtLupd;
	}

	@Column(name = "TD_UID_LUPD", length = 35)
	public String getTdUidLupd() {
		return this.tdUidLupd;
	}

	public void setTdUidLupd(String tdUidLupd) {
		this.tdUidLupd = tdUidLupd;
	}

}
