package com.guudint.clickargo.clictruck.track.model;
// Generated 8 Nov 2023, 9:58:05 am by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtTrackImeiStatus generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_TRACK_IMEI_STATUS")
public class TCkCtTrackImeiStatus extends COAbstractEntity<TCkCtTrackImeiStatus> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -1L;
	public static final String PREFIX_ID = "TIS";

	private String tisId;
	private String tisJobId;
	private String tisImei;
	private Date tisDtStart;
	private Date tisDtEnd;
	private String tisReqUrl;
	private String tisRspBody;
	private String tisGps;
	private String tisHttpStatus;
	private String tisRemark;
	private Character tisStatus;
	private Date tisDtCreate;
	private String tisUidCreate;
	private Date tisDtLupd;
	private String tisUidLupd;

	public TCkCtTrackImeiStatus() {
	}

	public TCkCtTrackImeiStatus(String tisId) {
		this.tisId = tisId;
	}

	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkCtTrackImeiStatus arg0) {
		return 0;
	}

	@Override
	public void init() {
	}

	@Id

	@Column(name = "TIS_ID", unique = true, nullable = false, length = 35)
	public String getTisId() {
		return this.tisId;
	}

	public void setTisId(String tisId) {
		this.tisId = tisId;
	}

	@Column(name = "TIS_JOB_ID", length = 35)
	public String getTisJobId() {
		return this.tisJobId;
	}

	public void setTisJobId(String tisJobId) {
		this.tisJobId = tisJobId;
	}

	@Column(name = "TIS_IMEI", length = 128)
	public String getTisImei() {
		return this.tisImei;
	}

	public void setTisImei(String tisImei) {
		this.tisImei = tisImei;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TIS_DT_START", length = 19)
	public Date getTisDtStart() {
		return this.tisDtStart;
	}

	public void setTisDtStart(Date tisDtStart) {
		this.tisDtStart = tisDtStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TIS_DT_END", length = 19)
	public Date getTisDtEnd() {
		return this.tisDtEnd;
	}

	public void setTisDtEnd(Date tisDtEnd) {
		this.tisDtEnd = tisDtEnd;
	}

	@Column(name = "TIS_REQ_URL", length = 1024)
	public String getTisReqUrl() {
		return this.tisReqUrl;
	}

	public void setTisReqUrl(String tisReqUrl) {
		this.tisReqUrl = tisReqUrl;
	}

	@Column(name = "TIS_RSP_BODY", length = 16777215)
	public String getTisRspBody() {
		return this.tisRspBody;
	}

	public void setTisRspBody(String tisRspBody) {
		this.tisRspBody = tisRspBody;
	}

	@Column(name = "TIS_GPS", length = 128)
	public String getTisGps() {
		return this.tisGps;
	}

	public void setTisGps(String tisGps) {
		this.tisGps = tisGps;
	}

	@Column(name = "TIS_HTTP_STATUS", length = 35)
	public String getTisHttpStatus() {
		return this.tisHttpStatus;
	}

	public void setTisHttpStatus(String tisHttpStatus) {
		this.tisHttpStatus = tisHttpStatus;
	}

	@Column(name = "TIS_REMARK", length = 1024)
	public String getTisRemark() {
		return this.tisRemark;
	}

	public void setTisRemark(String tisRemark) {
		this.tisRemark = tisRemark;
	}

	@Column(name = "TIS_STATUS", length = 1)
	public Character getTisStatus() {
		return this.tisStatus;
	}

	public void setTisStatus(Character tisStatus) {
		this.tisStatus = tisStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TIS_DT_CREATE", length = 19)
	public Date getTisDtCreate() {
		return this.tisDtCreate;
	}

	public void setTisDtCreate(Date tisDtCreate) {
		this.tisDtCreate = tisDtCreate;
	}

	@Column(name = "TIS_UID_CREATE", length = 35)
	public String getTisUidCreate() {
		return this.tisUidCreate;
	}

	public void setTisUidCreate(String tisUidCreate) {
		this.tisUidCreate = tisUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TIS_DT_LUPD", length = 19)
	public Date getTisDtLupd() {
		return this.tisDtLupd;
	}

	public void setTisDtLupd(Date tisDtLupd) {
		this.tisDtLupd = tisDtLupd;
	}

	@Column(name = "TIS_UID_LUPD", length = 35)
	public String getTisUidLupd() {
		return this.tisUidLupd;
	}

	public void setTisUidLupd(String tisUidLupd) {
		this.tisUidLupd = tisUidLupd;
	}

}
