package com.guudint.clickargo.clictruck.track.model;
// Generated 5 Oct 2023, 3:57:27 pm by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.guudint.clickargo.clictruck.planexec.job.model.TCkJobTruck;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtTrackLoc generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_TRACK_LOC")
public class TCkCtTrackLoc extends COAbstractEntity<TCkCtTrackLoc> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -1L;
	public static final String PREFIX_ID = "LC";
	

	private String tlId;
	private TCkJobTruck TCkJobTruck;
	private String tlImei;
	private Date tlDtStart;
	private Date tlDtEnd;
	private String tlReqUrl;
	private String tlRspBody;
	private String tlRemark;
	private Character tlStatus;
	private Date tlDtCreate;
	private String tlUidCreate;
	private Date tlDtLupd;
	private String tlUidLupd;
	private List<TCkCtTrackLocItem> TCkCtTrackLocItems = new ArrayList<TCkCtTrackLocItem>(0);

	public TCkCtTrackLoc() {
	}

	public TCkCtTrackLoc(String tlId, TCkJobTruck TCkJobTruck, String tlImei) {
		this.tlId = tlId;
		this.TCkJobTruck = TCkJobTruck;
		this.tlImei = tlImei;
	}

	public TCkCtTrackLoc(String tlId, TCkJobTruck TCkJobTruck, String tlImei, Date tlDtStart, Date tlDtEnd,
			String tlReqUrl, String tlRspBody, Character tlStatus, Date tlDtCreate, String tlUidCreate, Date tlDtLupd,
			String tlUidLupd) {
		this.tlId = tlId;
		this.TCkJobTruck = TCkJobTruck;
		this.tlImei = tlImei;
		this.tlDtStart = tlDtStart;
		this.tlDtEnd = tlDtEnd;
		this.tlReqUrl = tlReqUrl;
		this.tlRspBody = tlRspBody;
		this.tlStatus = tlStatus;
		this.tlDtCreate = tlDtCreate;
		this.tlUidCreate = tlUidCreate;
		this.tlDtLupd = tlDtLupd;
		this.tlUidLupd = tlUidLupd;
	}

	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkCtTrackLoc arg0) {
		return 0;
	}

	@Override
	public void init() {
	}

	@Id

	@Column(name = "TL_ID", unique = true, nullable = false, length = 35)
	public String getTlId() {
		return this.tlId;
	}

	public void setTlId(String tlId) {
		this.tlId = tlId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TL_JOB_ID", nullable = false)
	public TCkJobTruck getTCkJobTruck() {
		return this.TCkJobTruck;
	}

	public void setTCkJobTruck(TCkJobTruck TCkJobTruck) {
		this.TCkJobTruck = TCkJobTruck;
	}

	@Column(name = "TL_IMEI", nullable = false, length = 128)
	public String getTlImei() {
		return this.tlImei;
	}

	public void setTlImei(String tlImei) {
		this.tlImei = tlImei;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TL_DT_START", length = 19)
	public Date getTlDtStart() {
		return this.tlDtStart;
	}

	public void setTlDtStart(Date tlDtStart) {
		this.tlDtStart = tlDtStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TL_DT_END", length = 19)
	public Date getTlDtEnd() {
		return this.tlDtEnd;
	}

	public void setTlDtEnd(Date tlDtEnd) {
		this.tlDtEnd = tlDtEnd;
	}

	@Column(name = "TL_REQ_URL", length = 1024)
	public String getTlReqUrl() {
		return this.tlReqUrl;
	}

	public void setTlReqUrl(String tlReqUrl) {
		this.tlReqUrl = tlReqUrl;
	}

	@Column(name = "TL_RSP_BODY", length = 16777215)
	public String getTlRspBody() {
		return this.tlRspBody;
	}

	public void setTlRspBody(String tlRspBody) {
		this.tlRspBody = tlRspBody;
	}

	@Column(name = "TL_REMARK", length = 1024)
	public String getTlRemark() {
		return this.tlRemark;
	}

	public void setTlRemark(String tlRemark) {
		this.tlRemark = tlRemark;
	}

	@Column(name = "TL_STATUS", length = 1)
	public Character getTlStatus() {
		return this.tlStatus;
	}

	public void setTlStatus(Character tlStatus) {
		this.tlStatus = tlStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TL_DT_CREATE", length = 19)
	public Date getTlDtCreate() {
		return this.tlDtCreate;
	}

	public void setTlDtCreate(Date tlDtCreate) {
		this.tlDtCreate = tlDtCreate;
	}

	@Column(name = "TL_UID_CREATE", length = 35)
	public String getTlUidCreate() {
		return this.tlUidCreate;
	}

	public void setTlUidCreate(String tlUidCreate) {
		this.tlUidCreate = tlUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TL_DT_LUPD", length = 19)
	public Date getTlDtLupd() {
		return this.tlDtLupd;
	}

	public void setTlDtLupd(Date tlDtLupd) {
		this.tlDtLupd = tlDtLupd;
	}

	@Column(name = "TL_UID_LUPD", length = 35)
	public String getTlUidLupd() {
		return this.tlUidLupd;
	}

	public void setTlUidLupd(String tlUidLupd) {
		this.tlUidLupd = tlUidLupd;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCkCtTrackLoc")
	public List<TCkCtTrackLocItem> getTCkCtTrackLocItems() {
		return this.TCkCtTrackLocItems;
	}

	public void setTCkCtTrackLocItems(List<TCkCtTrackLocItem> TCkCtTrackLocItems) {
		this.TCkCtTrackLocItems = TCkCtTrackLocItems;
	}

}
