package com.guudint.clickargo.clictruck.dsv.model;
// Generated 14 Nov 2023, 4:30:10 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtMstShipmentState generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_MST_SHIPMENT_STATE")
public class TCkCtMstShipmentState extends COAbstractEntity<TCkCtMstShipmentState> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -1L;

	// Attributes
	/////////////
	private String stId;
	private String stName;
	private String stDesc;
	private String stDescOth;
	private Character stStatus;
	private Date stDtCreate;
	private String stUidCreate;
	private Date stDtLupd;
	private String stUidLupd;

	public TCkCtMstShipmentState() {
	}

	public TCkCtMstShipmentState(String stId) {
		this.stId = stId;
	}

	public TCkCtMstShipmentState(String stId, String stName, String stDesc, String stDescOth, Character stStatus,
			Date stDtCreate, String stUidCreate, Date stDtLupd, String stUidLupd) {
		this.stId = stId;
		this.stName = stName;
		this.stDesc = stDesc;
		this.stDescOth = stDescOth;
		this.stStatus = stStatus;
		this.stDtCreate = stDtCreate;
		this.stUidCreate = stUidCreate;
		this.stDtLupd = stDtLupd;
		this.stUidLupd = stUidLupd;
	}


	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	 */
	@Override
	public int compareTo(TCkCtMstShipmentState o) {
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 * 
	 */
	@Override
	public void init() {

	}


	// Properties
	/////////////
	@Id

	@Column(name = "ST_ID", unique = true, nullable = false, length = 35)
	public String getStId() {
		return this.stId;
	}

	public void setStId(String stId) {
		this.stId = stId;
	}

	@Column(name = "ST_NAME", nullable = false, length = 100)
	public String getStName() {
		return this.stName;
	}

	public void setStName(String stName) {
		this.stName = stName;
	}

	@Column(name = "ST_DESC")
	public String getStDesc() {
		return this.stDesc;
	}

	public void setStDesc(String stDesc) {
		this.stDesc = stDesc;
	}

	@Column(name = "ST_DESC_OTH", length = 512)
	public String getStDescOth() {
		return this.stDescOth;
	}

	public void setStDescOth(String stDescOth) {
		this.stDescOth = stDescOth;
	}

	@Column(name = "ST_STATUS", length = 1)
	public Character getStStatus() {
		return this.stStatus;
	}

	public void setStStatus(Character stStatus) {
		this.stStatus = stStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ST_DT_CREATE", length = 19)
	public Date getStDtCreate() {
		return this.stDtCreate;
	}

	public void setStDtCreate(Date stDtCreate) {
		this.stDtCreate = stDtCreate;
	}

	@Column(name = "ST_UID_CREATE", length = 35)
	public String getStUidCreate() {
		return this.stUidCreate;
	}

	public void setStUidCreate(String stUidCreate) {
		this.stUidCreate = stUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ST_DT_LUPD", length = 19)
	public Date getStDtLupd() {
		return this.stDtLupd;
	}

	public void setStDtLupd(Date stDtLupd) {
		this.stDtLupd = stDtLupd;
	}

	@Column(name = "ST_UID_LUPD", length = 35)
	public String getStUidLupd() {
		return this.stUidLupd;
	}

	public void setStUidLupd(String stUidLupd) {
		this.stUidLupd = stUidLupd;
	}
}
