package com.guudint.clickargo.clictruck.dsv.model;
// Generated 14 Nov 2023, 4:30:10 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.guudint.clickargo.job.model.TCkJob;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtDsvShipment generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_SHIPMENT")
public class TCkCtShipment extends COAbstractEntity<TCkCtShipment> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -1L;
	public static final String PREFIX_ID = "SH";

	// Attributes
	/////////////
	private String shId;
	private TCkCtMstShipmentState TCkCtMstShipmentState;
	private TCkJob TCkJob;
	private String shMsgId;
	private int shMsgVer;
	private String shName;
	private Date shDtIssue;
	private Date shDtLoad;
	private Date shDtJob;
	private String shErrCode;
	private String shContent;
	private Integer shContentSize = 0;
	private String shSourcePath;
	private Integer shRefresh;
	private String shRemark;
	private String shDirection;
	private String shProcessBy;
	private Character shReplaced;
	private String shHawb;
	private String shMawb;
	
	private Character shStatus;
	private Date shDtCreate;
	private String shUidCreate;
	private Date shDtLupd;
	private String shUidLupd;

	private String shStatusmessagePath;
	private Integer shStatusmessageSize = 0;
	private Short shStatusmessageStatus;
	private Date shDtStatusmessageCreate;
	private Date shDtStatusmessagePush2sftp;
	private String shStatusmessageRemark;
	
	private String shPodPath;
	private Integer shPodSize;
	private Short shPodStatus;
	private Date shDtPodCreate;
	private Date shDtPodEmailNotify;
	private String shPodRemark;
	
	private String shPhotoPath;
	private Integer shPhotoSize;
	private Short shPhotoStatus;
	private Date shDtPhotoCreate;
	private Date shDtPhotoEmailNotify;
	private String shPhotoRemark;

	
	public TCkCtShipment() {
	}

	public TCkCtShipment(String shId) {
		this.shId = shId;
	}

	public TCkCtShipment(String shId, TCkCtMstShipmentState TCkCtMstShipmentState, TCkJob TCkJob, String shMsgId,
			short shMsgVer, String shName, Date shDtIssue, Date shDtLoad, Date shDtJob, String shErrCode,
			String shContent, Character shStatus, Date shDtCreate, String shUidCreate, Date shDtLupd,
			String shUidLupd) {
		this.shId = shId;
		this.TCkCtMstShipmentState = TCkCtMstShipmentState;
		this.TCkJob = TCkJob;
		this.shMsgId = shMsgId;
		this.shMsgVer = shMsgVer;
		this.shName = shName;
		this.shDtIssue = shDtIssue;
		this.shDtLoad = shDtLoad;
		this.shDtJob = shDtJob;
		this.shErrCode = shErrCode;
		this.shContent = shContent;
		this.shStatus = shStatus;
		this.shDtCreate = shDtCreate;
		this.shUidCreate = shUidCreate;
		this.shDtLupd = shDtLupd;
		this.shUidLupd = shUidLupd;
	}


	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	 */
	@Override
	public int compareTo(TCkCtShipment o) {
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 * 
	 */
	@Override
	public void init() {

	}


	// Properties
	/////////////
	@Id

	@Column(name = "SH_ID", unique = true, nullable = false, length = 35)
	public String getShId() {
		return this.shId;
	}

	public void setShId(String shId) {
		this.shId = shId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SH_STATE")
	public TCkCtMstShipmentState getTCkCtMstShipmentState() {
		return this.TCkCtMstShipmentState;
	}

	public void setTCkCtMstShipmentState(TCkCtMstShipmentState TCkCtMstShipmentState) {
		this.TCkCtMstShipmentState = TCkCtMstShipmentState;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SH_JOB")
	public TCkJob getTCkJob() {
		return this.TCkJob;
	}

	public void setTCkJob(TCkJob TCkJob) {
		this.TCkJob = TCkJob;
	}

	@Column(name = "SH_MSG_ID", nullable = false, length = 35)
	public String getShMsgId() {
		return this.shMsgId;
	}

	public void setShMsgId(String shMsgId) {
		this.shMsgId = shMsgId;
	}

	@Column(name = "SH_MSG_VER", nullable = false)
	public int getShMsgVer() {
		return this.shMsgVer;
	}

	public void setShMsgVer(int shMsgVer) {
		this.shMsgVer = shMsgVer;
	}

	@Column(name = "SH_NAME", length = 1024)
	public String getShName() {
		return this.shName;
	}

	public void setShName(String shName) {
		this.shName = shName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SH_DT_ISSUE", length = 19)
	public Date getShDtIssue() {
		return this.shDtIssue;
	}

	public void setShDtIssue(Date shDtIssue) {
		this.shDtIssue = shDtIssue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SH_DT_LOAD", length = 19)
	public Date getShDtLoad() {
		return this.shDtLoad;
	}

	public void setShDtLoad(Date shDtLoad) {
		this.shDtLoad = shDtLoad;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SH_DT_JOB", length = 19)
	public Date getShDtJob() {
		return this.shDtJob;
	}

	public void setShDtJob(Date shDtJob) {
		this.shDtJob = shDtJob;
	}

	@Column(name = "SH_ERR_CODE", length = 5)
	public String getShErrCode() {
		return this.shErrCode;
	}

	public void setShErrCode(String shErrCode) {
		this.shErrCode = shErrCode;
	}

	@Column(name = "SH_CONTENT", length = 16777215)
	public String getShContent() {
		return this.shContent;
	}

	public void setShContent(String shContent) {
		this.shContent = shContent;
	}

	@Column(name = "SH_CONTENT_SIZE")
	public Integer getShContentSize() {
		return this.shContentSize;
	}

	public void setShContentSize(Integer shContentSize) {
		this.shContentSize = shContentSize;
	}

	@Column(name = "SH_SOURCE_PATH", length = 256)
	public String getShSourcePath() {
		return this.shSourcePath;
	}

	public void setShSourcePath(String shSourcePath) {
		this.shSourcePath = shSourcePath;
	}

	@Column(name = "SH_STATUSMESSAGE_PATH", length = 256)
	public String getShStatusmessagePath() {
		return this.shStatusmessagePath;
	}

	public void setShStatusmessagePath(String shStatusmessagePath) {
		this.shStatusmessagePath = shStatusmessagePath;
	}

	@Column(name = "SH_STATUSMESSAGE_SIZE")
	public Integer getShStatusmessageSize() {
		return this.shStatusmessageSize;
	}

	public void setShStatusmessageSize(Integer shStatusmessageSize) {
		this.shStatusmessageSize = shStatusmessageSize;
	}
	


	@Column(name = "SH_STATUSMESSAGE_STATUS")
	public Short getShStatusmessageStatus() {
		return this.shStatusmessageStatus;
	}

	public void setShStatusmessageStatus(Short shStatusmessageStatus) {
		this.shStatusmessageStatus = shStatusmessageStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SH_DT_STATUSMESSAGE_CREATE", length = 19)
	public Date getShDtStatusmessageCreate() {
		return this.shDtStatusmessageCreate;
	}

	public void setShDtStatusmessageCreate(Date shDtStatusmessageCreate) {
		this.shDtStatusmessageCreate = shDtStatusmessageCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SH_DT_STATUSMESSAGE_PUSH2SFTP", length = 19)
	public Date getShDtStatusmessagePush2sftp() {
		return this.shDtStatusmessagePush2sftp;
	}

	public void setShDtStatusmessagePush2sftp(Date shDtStatusmessagePush2sftp) {
		this.shDtStatusmessagePush2sftp = shDtStatusmessagePush2sftp;
	}

	@Column(name = "SH_STATUSMESSAGE_REMARK", length = 1024)
	public String getShStatusmessageRemark() {
		return this.shStatusmessageRemark;
	}

	public void setShStatusmessageRemark(String shStatusmessageRemark) {
		this.shStatusmessageRemark = shStatusmessageRemark;
	}

	@Column(name = "SH_POD_PATH", length = 256)
	public String getShPodPath() {
		return this.shPodPath;
	}

	public void setShPodPath(String shPodPath) {
		this.shPodPath = shPodPath;
	}

	@Column(name = "SH_POD_SIZE")
	public Integer getShPodSize() {
		return this.shPodSize;
	}

	public void setShPodSize(Integer shPodSize) {
		this.shPodSize = shPodSize;
	}

	@Column(name = "SH_POD_STATUS")
	public Short getShPodStatus() {
		return this.shPodStatus;
	}

	public void setShPodStatus(Short shPodStatus) {
		this.shPodStatus = shPodStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SH_DT_POD_CREATE", length = 19)
	public Date getShDtPodCreate() {
		return this.shDtPodCreate;
	}

	public void setShDtPodCreate(Date shDtPodCreate) {
		this.shDtPodCreate = shDtPodCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SH_DT_POD_EMAIL_NOTIFY", length = 19)
	public Date getShDtPodEmailNotify() {
		return this.shDtPodEmailNotify;
	}

	public void setShDtPodEmailNotify(Date shDtPodEmailNotify) {
		this.shDtPodEmailNotify = shDtPodEmailNotify;
	}

	@Column(name = "SH_PHOTO_PATH", length = 256)
	public String getShPhotoPath() {
		return this.shPhotoPath;
	}

	public void setShPhotoPath(String shPhotoPath) {
		this.shPhotoPath = shPhotoPath;
	}

	@Column(name = "SH_PHOTO_SIZE")
	public Integer getShPhotoSize() {
		return this.shPhotoSize;
	}

	public void setShPhotoSize(Integer shPhotoSize) {
		this.shPhotoSize = shPhotoSize;
	}

	@Column(name = "SH_PHOTO_STATUS")
	public Short getShPhotoStatus() {
		return this.shPhotoStatus;
	}

	public void setShPhotoStatus(Short shPhotoStatus) {
		this.shPhotoStatus = shPhotoStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SH_DT_PHOTO_CREATE", length = 19)
	public Date getShDtPhotoCreate() {
		return this.shDtPhotoCreate;
	}

	public void setShDtPhotoCreate(Date shDtPhotoCreate) {
		this.shDtPhotoCreate = shDtPhotoCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SH_DT_PHOTO_EMAIL_NOTIFY", length = 19)
	public Date getShDtPhotoEmailNotify() {
		return this.shDtPhotoEmailNotify;
	}

	public void setShDtPhotoEmailNotify(Date shDtPhotoEmailNotify) {
		this.shDtPhotoEmailNotify = shDtPhotoEmailNotify;
	}

	@Column(name = "SH_REFRESH")
	public Integer getShRefresh() {
		return this.shRefresh;
	}

	public void setShRefresh(Integer shRefresh) {
		this.shRefresh = shRefresh;
	}

	@Column(name = "SH_DIRECTION", length = 35)
	public String getShDirection() {
		return this.shDirection;
	}

	public void setShDirection(String shDirection) {
		this.shDirection = shDirection;
	}

	@Column(name = "SH_PROCESS_BY", length = 35)
	public String getShProcessBy() {
		return this.shProcessBy;
	}

	public void setShProcessBy(String shProcessBy) {
		this.shProcessBy = shProcessBy;
	}
	

	@Column(name = "SH_REPLACED", length = 1)
	public Character getShReplaced() {
		return this.shReplaced;
	}

	public void setShReplaced(Character shReplaced) {
		this.shReplaced = shReplaced;
	}

	@Column(name = "SH_HAWB", length = 64)
	public String getShHawb() {
		return this.shHawb;
	}

	public void setShHawb(String shHawb) {
		this.shHawb = shHawb;
	}

	@Column(name = "SH_MAWB", length = 64)
	public String getShMawb() {
		return this.shMawb;
	}

	public void setShMawb(String shMawb) {
		this.shMawb = shMawb;
	}
	

	@Column(name = "SH_REMARK", length = 1024)
	public String getShRemark() {
		return this.shRemark;
	}

	public void setShRemark(String shRemark) {
		this.shRemark = shRemark;
	}

	@Column(name = "SH_STATUS", length = 1)
	public Character getShStatus() {
		return this.shStatus;
	}

	public void setShStatus(Character shStatus) {
		this.shStatus = shStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SH_DT_CREATE", length = 19)
	public Date getShDtCreate() {
		return this.shDtCreate;
	}

	public void setShDtCreate(Date shDtCreate) {
		this.shDtCreate = shDtCreate;
	}

	@Column(name = "SH_UID_CREATE", length = 35)
	public String getShUidCreate() {
		return this.shUidCreate;
	}

	public void setShUidCreate(String shUidCreate) {
		this.shUidCreate = shUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SH_DT_LUPD", length = 19)
	public Date getShDtLupd() {
		return this.shDtLupd;
	}

	public void setShDtLupd(Date shDtLupd) {
		this.shDtLupd = shDtLupd;
	}

	@Column(name = "SH_UID_LUPD", length = 35)
	public String getShUidLupd() {
		return this.shUidLupd;
	}

	public void setShUidLupd(String shUidLupd) {
		this.shUidLupd = shUidLupd;
	}


	@Column(name = "SH_POD_REMARK", length = 1024)
	public String getShPodRemark() {
		return this.shPodRemark;
	}

	public void setShPodRemark(String shPodRemark) {
		this.shPodRemark = shPodRemark;
	}

	@Column(name = "SH_PHOTO_REMARK", length = 1024)
	public String getShPhotoRemark() {
		return this.shPhotoRemark;
	}

	public void setShPhotoRemark(String shPhotoRemark) {
		this.shPhotoRemark = shPhotoRemark;
	}
}
