import Mock from "../mock";
import * as WorkflowUtil from "app/views/applications/WorkflowUtil";

export const preArrivalDB = {
    list: [
      {
        appId: "PA20210308002",
        submitDate: "2021-03-01 12:30",
        ucrNo: "PEDI202012123",
        appType: "PAN",
        workflowName: "PAN",
        //status: WorkflowUtil.WorkflowStage.PendingAcknowledgement,
        status: "P",
        statusPortCu: WorkflowUtil.WorkflowStage.PendingAcknowledgement,
        statusPortIm: WorkflowUtil.WorkflowStage.PendingAcknowledgement,
        statusPortQu: WorkflowUtil.WorkflowStage.PendingAcknowledgement,
        statusPort: WorkflowUtil.WorkflowStage.PendingAcknowledgement,
        arrivalPort: "KHKOS",
        lastPortCountry: "TH",
        lastPort: "THKRB",
        impNo: "ERT3344",
        shipName: "Moon Light",
        shipCountry: "SG",
        callSign: "TR1234",
        applicantTin: "2332434232",
        masterName: "Tom Hanks",
        portOfArrivalOrDept: "PPAP",
        dateOfArrv: "13-12-2020",
        portArrivedFrom: "SG",
        nextPortCountry: "SG",
        nextPort: "SGJUR",
        dateOfDeparture: "12-1-2020",
  
        stowaways: "Y",
        animalOrPlants: "N",
        parcelPackage: "Y",
        armsAmmunitions: "N",
        illegalDrugs: "N",
        passengers: "Y",
        livestocks: "N",
        signUpload: "",
        reqMessage: "",
        application: "NIL",
        header: {
          type: "arrival",
          voyageDetails: {
            vcrNo: "PEDI202012123",
            voyageNo: "VE123765",
            voyageName: "2000918",
  
            arrivalPort: "KHKOS",
            arrivalDate: "01-12-2021",
            arrivalTime: "10:00:00",
            lastPortCountry: "TH",
            lastPort: "THKRB",
            departurePort: "KHKOS",
            departureDate: "01-05-2021",
            DepartureTime: "10:00:00",
            nextPortCountry: "SG",
            nextPort: "SGJUR",
            dutyPaidAt: "BORDER",
          },
          shipDetails: {
            impNo: "SHIP002",
            shipName: "Maersk Alabama",
            callSign: "CALL111",
            flageState: "SG",
            shipType: "TANKER",
            shipCountry: "SG",
            applicantTin: "L3342234232",
            applicantName: "CAM SHIPPING COMPANY",
          },
        },
        falForm: {
          fal1: {
            certificateReg: "VR 03455",
            grossTonnage: "1589 GT",
            netTonnage: "1098 NT",
            voyageDesc: "Transporting medical equipments",
            cargoDesc: "All containers contains medical equipments and medicines",
            remarks: "Please refer manifest for more details",
            facilities: "Provided by the port",
          },
          fal2: {
            list: [
              {
                blNo: "123",
                marksNo: "ER345",
                kindPck: "300 Tn",
                grossWeight: "400",
                measurement: "100",
              },
              {
                blNo: "4544",
                marksNo: "YT455",
                kindPck: "100 Tn",
                grossWeight: "200",
                measurement: "320",
              },
              {
                blNo: "5766",
                marksNo: "HG5645",
                kindPck: "300 Tn",
                grossWeight: "200",
                measurement: "444",
              },
            ],
            cargoDetails: {
              blNo: "123",
              marksNo: "ER345",
              kindPck: "Medicinal Equipments",
              grossWeight: "400",
              measurement: "100",
            },
            cargoDeclaration: {
              billInfo: {
                billNo: "111",
                billType: "Bill",
                billNature: "NT345",
                billMasterNo: "MS234",
  
                placeLoading: "Phnom Penh",
                placeUnloading: "Singapore",
                portLoading: "CAM",
                portUnloading: "SG",
              },
              traderInfo: {
                exporterName: "Shipping Line 1",
                exporterAddress: "Wat Nom",
                consigneeName: "Shipping Line 2",
                consigneeAddress: "Poi Pet",
                consigneeCode: "ER333",
                notifyName: "Notifier 1",
                notifyAddress: "Phnom Penh",
                notifyCode: "RT445",
              },
              goodsInfo: {
                goodsDescription: "Medicinal Equipments",
                numberOfContainers: "12",
                numberOfPackages: "200",
                packageType: "Closed containers",
                grossMass: "1003 Tonne",
                volumeInCubicMeters: "2033 CC",
                numberOfSeals: "23",
                sealPartyCode: "TT 4533",
                sealsMarks: "24",
                shippingMarks: "None",
                information: "Refer manifest",
              },
              containerInfo: {
                list: [
                  {
                    containerNo: "1234",
                    contanerType: "ER123",
                    emptyOrFull: "Chemicals",
                    nameCode: "300Tn",
                  },
                  {
                    containerNo: "4567",
                    contanerType: "RV123",
                    emptyOrFull: "Petrol",
                    nameCode: "100Tn",
                  },
                ],
                containerDetails: {
                  containerNo: "CONT001",
                  contanerType: "Closed Container",
                  emptyOrFull: "Full",
                  nameCode: "CONT202012",
                  noOfPackages: "34",
                  goodsDescription: "Medical Equipments",
                  grossMass: "2244 Tonne",
  
                  sealingParty: "Cambodia Agency",
                  marks1: "M1",
                  marks2: "M2",
                  marks3: "M3",
                  minTemp: "19 Deg Cel",
                  maxTemp: "34 Deg Cel",
                  humidity: "33 Ps",
                  dangerousGoods: "none",
                },
              },
            },
          },
  
          fal3: {
            stayPeriod: "4",
            onBoardPersons: "215",
            list: [
              {
                locationOnBoard: "Chemical Container",
                quantity: "20 Tn",
                articleName: "Upper Deck",
              },
              {
                locationOnBoard: "Petroleum Products",
                quantity: "40 Tn",
                articleName: "Lower Deck",
              },
            ],
            ShipStoresDeclaration: {
              articleName: "Coal",
              quantity: "5 Tn",
              locationOnBoard: "Bishan",
              selectType: "Tonne",
            },
          },
          fal4: {
            list: [
              {
                familyName: "John Doe",
                givenName: "Alex",
                rankRating: "Rank1",
                nationality: "VN",
                dob: "04/20/1985",
                signature: "",
                effects: "Cigars",
                identityDocType: "Identity.pdf",
                dateOfBirth: "04/20/1985",
                placeOfBirth: "Vietnam",
                gender: "Male",
                typeOfIdentity: "Passport",
                serialNumberOfIdentity: "1234444",
                issuingStateOfIdentity: "VN",
                expiryDateOfIdentity: "01/20/2030",
                portOfEmberkation: "",
                visaNumber: "VISA1234555",
                portOfDisemberkation: "CAMBODIA",
              },
            ],
            AddCrew: {
              familyName: "John Doe",
              givenName: "Alex",
              nationality: "Vietnamese",
              dateOfBirth: "04/20/1985",
              placeOfBirth: "Vietnam",
              gender: "Male",
              rankRating: "Rank1",
              typeOfIdentity: "Passport",
              serialNumberOfIdentity: "1234444",
              issuingStateOfIdentity: "VN",
              expiryDateOfIdentity: "01/20/2030",
              portOfEmberkation: "",
              visaNumber: "VISA1234555",
              portOfDisemberkation: "CAMBODIA",
            },
          },
          fal5: {
            list: [
              {
                familyName: "John Doe",
                givenName: "Alex",
                rankRating: "Rank1",
                nationality: "VN",
                dob: "04/20/1985",
                effects: "Cigars",
                identityDocType: "Identity.pdf",
                dateOfBirth: "04/20/1985",
                placeOfBirth: "Vietnam",
                gender: "Male",
                typeOfIdentity: "Passport",
                serialNumberOfIdentity: "1234444",
                issuingStateOfIdentity: "VN",
                expiryDateOfIdentity: "01/20/2030",
                portOfEmberkation: "",
                visaNumber: "VISA1234555",
                portOfDisemberkation: "CAMBODIA",
              },
            ],
            AddEffect: {
              familyName: "John Doe",
              givenName: "Alex",
              nationality: "Vietnamese",
              dateOfBirth: "04/20/1985",
              placeOfBirth: "Vietnam",
              gender: "Male",
              rankRating: "Rank1",
              typeOfIdentity: "Passport",
              serialNumberOfIdentity: "1234444",
              issuingStateOfIdentity: "VN",
              expiryDateOfIdentity: "01/20/2030",
              portOfEmberkation: "",
              visaNumber: "VISA1234555",
              portOfDisemberkation: "CAMBODIA",
              effects: "Eligible",
              signature: "JOHN Sign",
            },
          },
          fal6: {
            list: [
              {
                familyName: "John Doe",
                givenName: "Alex",
                nationality: "JP",
                identityType: "Passport",
                dateOfBirth: "04/20/1985",
                identityDocType: "Identity.pdf",
                placeOfBirth: "Japan",
                gender: "Male",
                typeOfIdentity: "Passport",
                serialNumberOfIdentity: "1234444",
                issuingStateOfIdentity: "JP",
                expiryDateOfIdentity: "01/20/2030",
                portOfEmberkation: "CAMBODIA",
                visaNumber: "V1234",
                portOfDisemberkation: "CAMBODIA",
                transitPassenger: "No",
              },
            ],
            AddPassenger: {
              familyName: "Doe",
              givenName: "John",
              nationality: "Vietnamese",
              dateOfBirth: "04/20/1985",
              placeOfBirth: "VN",
              gender: "Male",
              typeOfIdentity: "Passport",
              serialNumberOfIdentity: "1234444",
              issuingStateOfIdentity: "VN",
              expiryDateOfIdentity: "01/20/2030",
              portOfEmberkation: "CAMBODIA",
              visaNumber: "V1234",
              portOfDisemberkation: "CAMBODIA",
              transitPassenger: "No",
            },
          },
          fal7: {
            list: [
              {
                stowagePosition: "Lower Deck",
                referenceNumber: "REF20210212",
                marksNumber: "100",
                unNumber: "HK463",
                forVIdentification: "IDV20210214",
                properShippingName: "Maersk",
                corSRisks: "None",
                packingGroup: "GRP213",
                additionalInformation: "GARBAGE CANS",
                numberAndKindOfPackages: "GARBAGE",
                massOrVolume: "2 Tonne",
                ems: "NA",
              },
              {
                stowagePosition: "Upper Deck",
                referenceNumber: "REF202102234",
                marksNumber: "200",
                unNumber: "BG45665",
                forVIdentification: "IDV20210214",
                properShippingName: "Maersk",
                corSRisks: "None",
                packingGroup: "GRP213",
                additionalInformation: "GARBAGE CANS",
                numberAndKindOfPackages: "GARBAGE",
                massOrVolume: "2 Tonne",
                ems: "NA",
              },
            ],
            AddDangerousGoods: {
              stowagePosition: "Lower Deck",
              referenceNumber: "REF20210212",
              marksNumber: "100",
              forVIdentification: "IDV20210214",
              unNumber: "UN234",
              properShippingName: "Maersk",
              corSRisks: "None",
              packingGroup: "GRP213",
              additionalInformation: "GARBAGE CANS",
              numberAndKindOfPackages: "GARBAGE",
              massOrVolume: "2 Tonne",
              ems: "NA",
            },
          },
        },
        others: {
          vaccination: {
            list: [
              {
                familyName: "John Doe",
                givenName: "Alex",
                rankRating: "Rank1",
                nationality: "VN",
                dob: "04/20/1985",
                signature: "",
                effects: "Cigars",
              },
            ],
            AddCrew: {
              familyName: "John Doe",
              givenName: "Alex",
              nationality: "Vietnamese",
              dateOfBirth: "04/20/1985",
              placeOfBirth: "Vietnam",
              gender: "Male",
              rankRating: "Rank1",
              typeOfIdentity: "Passport",
              serialNumberOfIdentity: "1234444",
              issuingStateOfIdentity: "VN",
              expiryDateOfIdentity: "01/20/2030",
              portOfEmberkation: "",
              visaNumber: "VISA1234555",
              portOfDisemberkation: "CAMBODIA",
            },
          },
        },
        supportingDocs: {
          docType: "Ship Security Info Doc",
          docRefNo: "SS20201221",
        },
      },
  
      {
        appId: "PA2021030812345",
        arrivalPort: "KHKOS",
        impNo: "ERT33456",
        appType: "PAN",
        shipName: "Maersk Alabama",
        shipCountry: "SG",
        lastPortCountry: "Moracco",
        applicantTin: "2332434232",
        submitDate: "2020-08-10T11:20:02",
        workflowName: "PAN",
        //status: WorkflowUtil.WorkflowStage.Acknowledged,
        status: "A",
        statusPortCu: WorkflowUtil.WorkflowStage.Acknowledged,
        statusPortIm: WorkflowUtil.WorkflowStage.Acknowledged,
        statusPortQu: WorkflowUtil.WorkflowStage.Acknowledged,
        statusPort: WorkflowUtil.WorkflowStage.Acknowledged,
        callSign: "TR098234",
        masterName: "Tom Hanks",
        portOfArrivalOrDept: "PPAP",
        dateOfArrv: "13-12-2020",
        portArrivedFrom: "SG",
        nextPort: "SG",
        dateOfDeparture: "12-1-2020",
        stowaways: "Y",
        animalOrPlants: "N",
        parcelPackage: "Y",
        armsAmmunitions: "N",
        illegalDrugs: "N",
        passengers: "Y",
        livestocks: "N",
        signUpload: "",
        reqMessage: "",
        application: "NIL",
        header: {
          type: "arrival",
          voyageDetails: {
            vcrNo: "PEDI202012123",
            voyageNo: "PEDI944832",
            voyageName: "ERT-2324",
  
            arrivalPort: "KHPNH",
            arrivalDate: "01-12-2021",
            arrivalTime: "10:00:00",
            lastPortCountry: "TH",
            lastPort: "THKRB",
  
            departurePort: "KHPNH",
            departureDate: "01-21-2021",
            DepartureTime: "10:00:00",
            nextPortCountry: "SG",
            nextPort: "SGPOS",
            dutyPaidAt: "BORDER",
          },
          shipDetails: {
            impNo: "ERT33456",
            shipName: "Maersk Alabama",
            shipCountry: "SG",
            callSign: "TR098234",
            flageState: "FL1234",
            applicantTin: "2332434232",
            shipType: "TANKER",
            applicantName: "CAM SHIPPING COMPANY",
          },
        },
        falForm: {
          fal1: {
            certificateReg: "VR 03455",
            grossTonnage: "1589 GT",
            netTonnage: "1098 NT",
            voyageDesc: "Transporting medical equipments",
            cargoDesc: "All containers contains medical equipments and medicines",
            remarks: "Please refer manifest for more details",
            facilities: "Provided by the port",
          },
          fal2: {
            list: [
              {
                blNo: "123",
                marksNo: "ER345",
                kindPck: "300 Tn",
                grossWeight: "400",
                measurement: "100",
              },
              {
                blNo: "4544",
                marksNo: "YT455",
                kindPck: "100 Tn",
                grossWeight: "200",
                measurement: "320",
              },
              {
                blNo: "5766",
                marksNo: "HG5645",
                kindPck: "300 Tn",
                grossWeight: "200",
                measurement: "444",
              },
            ],
            cargoDetails: {
              blNo: "123",
              marksNo: "ER345",
              kindPck: "Medicinal Equipments",
              grossWeight: "400",
              measurement: "100",
            },
            cargoDeclaration: {
              billInfo: {
                billNo: "111",
                billType: "Bill",
                billNature: "NT345",
                billMasterNo: "MS234",
  
                placeLoading: "Phnom Penh",
                placeUnloading: "Singapore",
                portLoading: "CAM",
                portUnloading: "SG",
              },
              traderInfo: {
                exporterName: "Shipping Line 1",
                exporterAddress: "Wat Nom",
                consigneeName: "Shipping Line 2",
                consigneeAddress: "Poi Pet",
                consigneeCode: "ER333",
                notifyName: "Notifier 1",
                notifyAddress: "Phnom Penh",
                notifyCode: "RT445",
              },
              goodsInfo: {
                goodsDescription: "Medicinal Equipments",
                numberOfContainers: "12",
                numberOfPackages: "200",
                packageType: "Closed containers",
                grossMass: "1003 Tonne",
                volumeInCubicMeters: "2033 CC",
                numberOfSeals: "23",
                sealPartyCode: "TT 4533",
                sealsMarks: "24",
                shippingMarks: "None",
                information: "Refer manifest",
              },
              containerInfo: {
                list: [
                  {
                    containerNo: "1234",
                    contanerType: "ER123",
                    emptyOrFull: "Chemicals",
                    nameCode: "300Tn",
                  },
                  {
                    containerNo: "4567",
                    contanerType: "RV123",
                    emptyOrFull: "Petrol",
                    nameCode: "100Tn",
                  },
                ],
                containerDetails: {
                  containerNo: "CONT001",
                  contanerType: "Closed Container",
                  emptyOrFull: "Full",
                  nameCode: "CONT202012",
                  noOfPackages: "34",
                  goodsDescription: "Medical Equipments",
                  grossMass: "2244 Tonne",
  
                  sealingParty: "Cambodia Agency",
                  marks1: "M1",
                  marks2: "M2",
                  marks3: "M3",
                  minTemp: "19 Deg Cel",
                  maxTemp: "34 Deg Cel",
                  humidity: "33 Ps",
                  dangerousGoods: "none",
                },
              },
            },
          },
  
          fal3: {
            stayPeriod: "4",
            onBoardPersons: "215",
            list: [
              {
                locationOnBoard: "Chemical Container",
                quantity: "20 Tn",
                articleName: "Upper Deck",
              },
              {
                locationOnBoard: "Petroleum Products",
                quantity: "40 Tn",
                articleName: "Lower Deck",
              },
            ],
            ShipStoresDeclaration: {
              articleName: "Coal",
              quantity: "5 Tn",
              locationOnBoard: "Bishan",
              selectType: "Tonne",
            },
          },
          fal4: {
            list: [
              {
                familyName: "John Doe",
                givenName: "Alex",
                rankRating: "Rank1",
                nationality: "Vietnamese",
                dob: "04/20/1985",
                signature: "",
                effects: "Cigars",
                identityDocType: "Identity.pdf",
                dateOfBirth: "04/20/1985",
                placeOfBirth: "Vietnam",
                gender: "Male",
                typeOfIdentity: "Passport",
                serialNumberOfIdentity: "1234444",
                issuingStateOfIdentity: "VN",
                expiryDateOfIdentity: "01/20/2030",
                portOfEmberkation: "",
                visaNumber: "VISA1234555",
                portOfDisemberkation: "CAMBODIA",
              },
            ],
            AddCrew: {
              familyName: "John Doe",
              givenName: "Alex",
              nationality: "Vietnamese",
              dateOfBirth: "04/20/1985",
              placeOfBirth: "Vietnam",
              gender: "Male",
              rankRating: "Rank1",
              typeOfIdentity: "Passport",
              serialNumberOfIdentity: "1234444",
              issuingStateOfIdentity: "VN",
              expiryDateOfIdentity: "01/20/2030",
              portOfEmberkation: "",
              visaNumber: "VISA1234555",
              portOfDisemberkation: "CAMBODIA",
            },
          },
          fal5: {
            list: [
              {
                familyName: "John Doe",
                givenName: "Alex",
                rankRating: "Rank1",
                dob: "04-20-1985",
                effects: "Cigars",
                identityDocType: "Identity.pdf",
                dateOfBirth: "04/20/1985",
                placeOfBirth: "Vietnam",
                gender: "Male",
                typeOfIdentity: "Passport",
                serialNumberOfIdentity: "1234444",
                issuingStateOfIdentity: "VN",
                expiryDateOfIdentity: "01/20/2030",
                portOfEmberkation: "",
                visaNumber: "VISA1234555",
                portOfDisemberkation: "CAMBODIA",
              },
            ],
  
            AddEffect: {
              familyName: "John Doe",
              givenName: "Alex",
              nationality: "Vietnamese",
              dateOfBirth: "04-20-1985",
              placeOfBirth: "Vietnam",
              gender: "Male",
              rankRating: "Rank1",
              typeOfIdentity: "Passport",
              serialNumberOfIdentity: "1234444",
              issuingStateOfIdentity: "VN",
              expiryDateOfIdentity: "01/20/2030",
              portOfEmberkation: "",
              visaNumber: "VISA1234555",
              portOfDisemberkation: "CAMBODIA",
              effects: "Eligible",
              signature: "JOHN Sign",
            },
          },
          fal6: {
            list: [
              {
                familyName: "John Doe",
                givenName: "Alex",
                nationality: "JAPAN",
                identityType: "Passport",
                dateOfBirth: "04-20-1985",
                identityDocType: "Identity.pdf",
                placeOfBirth: "VN",
                gender: "Male",
                typeOfIdentity: "Passport",
                serialNumberOfIdentity: "1234444",
                issuingStateOfIdentity: "VN",
                expiryDateOfIdentity: "01/20/2030",
                portOfEmberkation: "CAMBODIA",
                visaNumber: "V1234",
                portOfDisemberkation: "CAMBODIA",
                transitPassenger: "No",
              },
            ],
            AddPassenger: {
              familyName: "Doe",
              givenName: "John",
              nationality: "Vietnamese",
              dateOfBirth: "04-20-1985",
              placeOfBirth: "VN",
              gender: "Male",
              typeOfIdentity: "Passport",
              serialNumberOfIdentity: "1234444",
              issuingStateOfIdentity: "VN",
              expiryDateOfIdentity: "01/20/2030",
              portOfEmberkation: "CAMBODIA",
              visaNumber: "V1234",
              portOfDisemberkation: "CAMBODIA",
              transitPassenger: "No",
            },
          },
          fal7: {
            list: [
              {
                stowagePosition: "Lower Deck",
                referenceNumber: "REF20210212",
                marksNumber: "100",
                unNumber: "HK463",
                forVIdentification: "IDV20210214",
                properShippingName: "Maersk",
                corSRisks: "None",
                packingGroup: "GRP213",
                additionalInformation: "GARBAGE CANS",
                numberAndKindOfPackages: "GARBAGE",
                massOrVolume: "2 Tonne",
                ems: "NA",
              },
              {
                stowagePosition: "Upper Deck",
                referenceNumber: "REF202102234",
                marksNumber: "200",
                unNumber: "BG45665",
                forVIdentification: "IDV20210214",
                properShippingName: "Maersk",
                corSRisks: "None",
                packingGroup: "GRP213",
                additionalInformation: "GARBAGE CANS",
                numberAndKindOfPackages: "GARBAGE",
                massOrVolume: "2 Tonne",
                ems: "NA",
              },
            ],
            AddDangerousGoods: {
              stowagePosition: "Lower Deck",
              referenceNumber: "REF20210212",
              marksNumber: "100",
              forVIdentification: "IDV20210214",
              unNumber: "UN234",
              properShippingName: "Maersk",
              corSRisks: "None",
              packingGroup: "GRP213",
              additionalInformation: "GARBAGE CANS",
              numberAndKindOfPackages: "GARBAGE",
              massOrVolume: "2 Tonne",
              ems: "NA",
            },
          },
        },
        others: {
          vaccination: {
            list: [
              {
                familyName: "John Doe",
                givenName: "Alex",
                rankRating: "Rank1",
                nationality: "Vietnamese",
                dob: "04/20/1985",
                signature: "",
                effects: "Cigars",
              },
            ],
            AddCrew: {
              familyName: "John Doe",
              givenName: "Alex",
              nationality: "Vietnamese",
              dateOfBirth: "04/20/1985",
              placeOfBirth: "Vietnam",
              gender: "Male",
              rankRating: "Rank1",
              typeOfIdentity: "Passport",
              serialNumberOfIdentity: "1234444",
              issuingStateOfIdentity: "VN",
              expiryDateOfIdentity: "01/20/2030",
              portOfEmberkation: "",
              visaNumber: "VISA1234555",
              portOfDisemberkation: "CAMBODIA",
            },
          },
        },
        supportingDocs: {
          docType: "Ship Security Info Doc",
          docRefNo: "SS20201221",
        },
      },
    ],
  };

  Mock.onGet("/api/process/all").reply((config) => {
    return [200, preArrivalDB.applications];
  });