package com.guudint.clickargo.clictruck.planexec.job.model;
// Generated 17 Nov 2023, 4:37:42 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtJobTripDelivery generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_JOB_TRIP_DELIVERY")
public class TCkCtJobTripDelivery extends COAbstractEntity<TCkCtJobTripDelivery> {

	private static final long serialVersionUID = 9145820973739690510L;
	private String jtdId;
	private String jtdJobId;
	private String jtdJobTrip;
	private String jtdImei;
	private String jtdMsgState;
	private Date jtdDtDeliver;
	private Date jtdDtNotifiedDeliver;
	private Date jtdDtLastScan;
	private String jtdOriginLoc;
	private String jtdDestLoc;
	private Integer jtdDistance;
	private Double jtdDuration;
	private Date jtdDtPreNotify;
	private String jtdStatus;
	private Date jtdDtCreate;
	private Date jtdDtLupd;

	public TCkCtJobTripDelivery() {
	}

	public TCkCtJobTripDelivery(String jtdId, String jtdImei, Date jtdDtDeliver, String jtdOriginLoc) {
		this.jtdId = jtdId;
		this.jtdImei = jtdImei;
		this.jtdDtDeliver = jtdDtDeliver;
		this.jtdOriginLoc = jtdOriginLoc;
	}

	public TCkCtJobTripDelivery(String jtdMsgState) {
		this.jtdMsgState = jtdMsgState;
	}

	public TCkCtJobTripDelivery(String jtdId, String jtdJobId, String jtdJobTrip, String jtdImei, Date jtdDtDeliver,
								Date jtdDtNotifiedDeliver, Date jtdDtLastScan, String jtdOriginLoc, String jtdDestLoc, Integer jtdDistance,
								Double jtdDuration, Date jtdDtPreNotify, String jtdStatus, Date jtdDtCreate, Date jtdDtLupd) {
		this.jtdId = jtdId;
		this.jtdJobId = jtdJobId;
		this.jtdJobTrip = jtdJobTrip;
		this.jtdImei = jtdImei;
		this.jtdDtDeliver = jtdDtDeliver;
		this.jtdDtNotifiedDeliver = jtdDtNotifiedDeliver;
		this.jtdDtLastScan = jtdDtLastScan;
		this.jtdOriginLoc = jtdOriginLoc;
		this.jtdDestLoc = jtdDestLoc;
		this.jtdDistance = jtdDistance;
		this.jtdDuration = jtdDuration;
		this.jtdDtPreNotify = jtdDtPreNotify;
		this.jtdStatus = jtdStatus;
		this.jtdDtCreate = jtdDtCreate;
		this.jtdDtLupd = jtdDtLupd;
	}

	@Id

	@Column(name = "JTD_ID", unique = true, nullable = false, length = 35)
	public String getJtdId() {
		return this.jtdId;
	}

	public void setJtdId(String jtdId) {
		this.jtdId = jtdId;
	}

	@Column(name = "JTD_JOB_ID", length = 45)
	public String getJtdJobId() {
		return this.jtdJobId;
	}

	public void setJtdJobId(String jtdJobId) {
		this.jtdJobId = jtdJobId;
	}

	@Column(name = "JTD_JOB_TRIP", length = 45)
	public String getJtdJobTrip() {
		return this.jtdJobTrip;
	}

	public void setJtdJobTrip(String jtdJobTrip) {
		this.jtdJobTrip = jtdJobTrip;
	}

	@Column(name = "JTD_IMEI", nullable = false, length = 1024)
	public String getJtdImei() {
		return this.jtdImei;
	}

	public void setJtdImei(String jtdImei) {
		this.jtdImei = jtdImei;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JTD_DT_DELIVER", nullable = false, length = 19)
	public Date getJtdDtDeliver() {
		return this.jtdDtDeliver;
	}

	public void setJtdDtDeliver(Date jtdDtDeliver) {
		this.jtdDtDeliver = jtdDtDeliver;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JTD_DT_NOTIFIED_DELIVER", length = 19)
	public Date getJtdDtNotifiedDeliver() {
		return this.jtdDtNotifiedDeliver;
	}

	public void setJtdDtNotifiedDeliver(Date jtdDtNotifiedDeliver) {
		this.jtdDtNotifiedDeliver = jtdDtNotifiedDeliver;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JTD_DT_LAST_SCAN", length = 19)
	public Date getJtdDtLastScan() {
		return this.jtdDtLastScan;
	}

	public void setJtdDtLastScan(Date jtdDtLastScan) {
		this.jtdDtLastScan = jtdDtLastScan;
	}

	@Column(name = "JTD_ORIGIN_LOC", nullable = false, length = 16777215)
	public String getJtdOriginLoc() {
		return this.jtdOriginLoc;
	}

	public void setJtdOriginLoc(String jtdOriginLoc) {
		this.jtdOriginLoc = jtdOriginLoc;
	}

	@Column(name = "JTD_DEST_LOC", length = 16777215)
	public String getJtdDestLoc() {
		return this.jtdDestLoc;
	}

	public void setJtdDestLoc(String jtdDestLoc) {
		this.jtdDestLoc = jtdDestLoc;
	}

	@Column(name = "JTD_DISTANCE")
	public Integer getJtdDistance() {
		return this.jtdDistance;
	}

	public void setJtdDistance(Integer jtdDistance) {
		this.jtdDistance = jtdDistance;
	}

	@Column(name = "JTD_DURATION", precision = 22, scale = 0)
	public Double getJtdDuration() {
		return this.jtdDuration;
	}
	@Column(name = "JTD_MSG_STATE")
	public String getJtdMsgState() {
		return jtdMsgState;
	}

	public void setJtdMsgState(String jtdMsgState) {
		this.jtdMsgState = jtdMsgState;
	}

	public void setJtdDuration(Double jtdDuration) {
		this.jtdDuration = jtdDuration;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JTD_DT_PRE_NOTIFY", length = 19)
	public Date getJtdDtPreNotify() {
		return this.jtdDtPreNotify;
	}

	public void setJtdDtPreNotify(Date jtdDtPreNotify) {
		this.jtdDtPreNotify = jtdDtPreNotify;
	}

	@Column(name = "JTD_STATUS", length = 35)
	public String getJtdStatus() {
		return this.jtdStatus;
	}

	public void setJtdStatus(String jtdStatus) {
		this.jtdStatus = jtdStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JTD_DT_CREATE", length = 19)
	public Date getJtdDtCreate() {
		return this.jtdDtCreate;
	}

	public void setJtdDtCreate(Date jtdDtCreate) {
		this.jtdDtCreate = jtdDtCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JTD_DT_LUPD", length = 19)
	public Date getJtdDtLupd() {
		return this.jtdDtLupd;
	}

	public void setJtdDtLupd(Date jtdDtLupd) {
		this.jtdDtLupd = jtdDtLupd;
	}

	@Override
	public int compareTo(TCkCtJobTripDelivery o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

}
