package com.guudint.clickargo.clictruck.planexec.job.model;
// Generated 22 Sep 2023, 6:15:54 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtJobTerm generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_JOB_TERM")
public class TCkCtJobTerm extends COAbstractEntity<TCkCtJobTerm> {

	private static final long serialVersionUID = -8649550174315038262L;
	public static final String PREFIX_ID = "JT";
	
	private String jtId;
	private TCkCtJobTermReq TCkCtJobTermReq;
	private TCkJobTruck TCkJobTruck;
	private Double jtJobDn;
	private Double jtJobPltfeeAmtCoff;
	private Double jtJobPltfeeAmtTo;
	private Character jtStatus;
	private Date jtDtCreate;
	private String jtUidCreate;
	private Date jtDtLupd;
	private String jtUidLupd;

	public TCkCtJobTerm() {
	}

	public TCkCtJobTerm(String jtId, TCkCtJobTermReq TCkCtJobTermReq, TCkJobTruck TCkJobTruck) {
		this.jtId = jtId;
		this.TCkCtJobTermReq = TCkCtJobTermReq;
		this.TCkJobTruck = TCkJobTruck;
	}

	public TCkCtJobTerm(String jtId, TCkCtJobTermReq TCkCtJobTermReq, TCkJobTruck TCkJobTruck, Double jtJobDn,
			Double jtJobPltfeeAmtCoff, Double jtJobPltfeeAmtTo, Character jtStatus, Date jtDtCreate, String jtUidCreate,
			Date jtDtLupd, String jtUidLupd) {
		this.jtId = jtId;
		this.TCkCtJobTermReq = TCkCtJobTermReq;
		this.TCkJobTruck = TCkJobTruck;
		this.jtJobDn = jtJobDn;
		this.jtJobPltfeeAmtCoff = jtJobPltfeeAmtCoff;
		this.jtJobPltfeeAmtTo = jtJobPltfeeAmtTo;
		this.jtStatus = jtStatus;
		this.jtDtCreate = jtDtCreate;
		this.jtUidCreate = jtUidCreate;
		this.jtDtLupd = jtDtLupd;
		this.jtUidLupd = jtUidLupd;
	}

	@Id

	@Column(name = "JT_ID", unique = true, nullable = false, length = 35)
	public String getJtId() {
		return this.jtId;
	}

	public void setJtId(String jtId) {
		this.jtId = jtId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JT_REQ", nullable = false)
	public TCkCtJobTermReq getTCkCtJobTermReq() {
		return this.TCkCtJobTermReq;
	}

	public void setTCkCtJobTermReq(TCkCtJobTermReq TCkCtJobTermReq) {
		this.TCkCtJobTermReq = TCkCtJobTermReq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JT_JOB", nullable = false)
	public TCkJobTruck getTCkJobTruck() {
		return this.TCkJobTruck;
	}

	public void setTCkJobTruck(TCkJobTruck TCkJobTruck) {
		this.TCkJobTruck = TCkJobTruck;
	}

	@Column(name = "JT_JOB_DN", precision = 15)
	public Double getJtJobDn() {
		return this.jtJobDn;
	}

	public void setJtJobDn(Double jtJobDn) {
		this.jtJobDn = jtJobDn;
	}

	@Column(name = "JT_JOB_PLTFEE_AMT_COFF", precision = 15)
	public Double getJtJobPltfeeAmtCoff() {
		return this.jtJobPltfeeAmtCoff;
	}

	public void setJtJobPltfeeAmtCoff(Double jtJobPltfeeAmtCoff) {
		this.jtJobPltfeeAmtCoff = jtJobPltfeeAmtCoff;
	}

	@Column(name = "JT_JOB_PLTFEE_AMT_TO", precision = 15)
	public Double getJtJobPltfeeAmtTo() {
		return this.jtJobPltfeeAmtTo;
	}

	public void setJtJobPltfeeAmtTo(Double jtJobPltfeeAmtTo) {
		this.jtJobPltfeeAmtTo = jtJobPltfeeAmtTo;
	}

	@Column(name = "JT_STATUS", length = 1)
	public Character getJtStatus() {
		return this.jtStatus;
	}

	public void setJtStatus(Character jtStatus) {
		this.jtStatus = jtStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JT_DT_CREATE", length = 19)
	public Date getJtDtCreate() {
		return this.jtDtCreate;
	}

	public void setJtDtCreate(Date jtDtCreate) {
		this.jtDtCreate = jtDtCreate;
	}

	@Column(name = "JT_UID_CREATE", length = 35)
	public String getJtUidCreate() {
		return this.jtUidCreate;
	}

	public void setJtUidCreate(String jtUidCreate) {
		this.jtUidCreate = jtUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JT_DT_LUPD", length = 19)
	public Date getJtDtLupd() {
		return this.jtDtLupd;
	}

	public void setJtDtLupd(Date jtDtLupd) {
		this.jtDtLupd = jtDtLupd;
	}

	@Column(name = "JT_UID_LUPD", length = 35)
	public String getJtUidLupd() {
		return this.jtUidLupd;
	}

	public void setJtUidLupd(String jtUidLupd) {
		this.jtUidLupd = jtUidLupd;
	}

	@Override
	public int compareTo(TCkCtJobTerm o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
