package com.guudint.clickargo.clictruck.planexec.job.model;
// Generated 23 Feb, 2023 4:00:19 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtContactDetail generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_CONTACT_DETAIL")
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
public class TCkCtContactDetail extends COAbstractEntity<TCkCtContactDetail> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 3820091136662937837L;
	
	// Attributes
	/////////////
	private String cdId;
	private String cdName;
	private String cdPhone;
	private String cdEmail;
	private Character cdStatus;
	private Date cdDtCreate;
	private String cdUidCreate;
	private Date cdDtLupd;
	private String rrUidLupd;

	// Constructors
	///////////////
	public TCkCtContactDetail() {
	}

	public TCkCtContactDetail(String cdId, String cdName) {
		this.cdId = cdId;
		this.cdName = cdName;
	}

	public TCkCtContactDetail(String cdId, String cdName, String cdPhone, String cdEmail, Character cdStatus,
			Date cdDtCreate, String cdUidCreate, Date cdDtLupd, String rrUidLupd) {
		this.cdId = cdId;
		this.cdName = cdName;
		this.cdPhone = cdPhone;
		this.cdEmail = cdEmail;
		this.cdStatus = cdStatus;
		this.cdDtCreate = cdDtCreate;
		this.cdUidCreate = cdUidCreate;
		this.cdDtLupd = cdDtLupd;
		this.rrUidLupd = rrUidLupd;
	}


	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	 */
	@Override
	public int compareTo(TCkCtContactDetail o) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 * 
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
	// Properties
	/////////////
	@Id
	@Column(name = "CD_ID", unique = true, nullable = false, length = 35)
	public String getCdId() {
		return this.cdId;
	}

	public void setCdId(String cdId) {
		this.cdId = cdId;
	}

	@Column(name = "CD_NAME", nullable = false, length = 256)
	public String getCdName() {
		return this.cdName;
	}

	public void setCdName(String cdName) {
		this.cdName = cdName;
	}

	@Column(name = "CD_PHONE", length = 1024)
	public String getCdPhone() {
		return this.cdPhone;
	}

	public void setCdPhone(String cdPhone) {
		this.cdPhone = cdPhone;
	}

	@Column(name = "CD_EMAIL", length = 128)
	public String getCdEmail() {
		return this.cdEmail;
	}

	public void setCdEmail(String cdEmail) {
		this.cdEmail = cdEmail;
	}

	@Column(name = "CD_STATUS", length = 1)
	public Character getCdStatus() {
		return this.cdStatus;
	}

	public void setCdStatus(Character cdStatus) {
		this.cdStatus = cdStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CD_DT_CREATE", length = 19)
	@CreationTimestamp
	public Date getCdDtCreate() {
		return this.cdDtCreate;
	}

	public void setCdDtCreate(Date cdDtCreate) {
		this.cdDtCreate = cdDtCreate;
	}

	@Column(name = "CD_UID_CREATE", length = 35)
	public String getCdUidCreate() {
		return this.cdUidCreate;
	}

	public void setCdUidCreate(String cdUidCreate) {
		this.cdUidCreate = cdUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CD_DT_LUPD", length = 19)
	@UpdateTimestamp
	public Date getCdDtLupd() {
		return this.cdDtLupd;
	}

	public void setCdDtLupd(Date cdDtLupd) {
		this.cdDtLupd = cdDtLupd;
	}

	@Column(name = "RR_UID_LUPD", length = 35)
	public String getRrUidLupd() {
		return this.rrUidLupd;
	}

	public void setRrUidLupd(String rrUidLupd) {
		this.rrUidLupd = rrUidLupd;
	}

}
