package com.guudint.clickargo.clictruck.planexec.job.model;
// Generated 20 Oct 2023, 4:45:13 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.guudint.clickargo.clictruck.master.model.TCkCtMstPartyType;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtParty generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_PARTY")
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
public class TCkCtParty extends COAbstractEntity<TCkCtParty> {

	private static final long serialVersionUID = 6879834477235116564L;
	public static final String PREFIX_ID = "PTY";
	
	private String ptyId;
	private String ptyXmlId;
	private TCkCtMstPartyType TCkCtMstPartyType;
	private String ptyName;
	private String ptyNameOth;
	private String ptyAddr1;
	private String ptyAddr2;
	private String ptyAddr3;
	private String ptyPcode;
	private String ptyCity;
	private String ptyCtycode;
	private Character ptyStatus;
	private Date ptyDtCreate;
	private String ptyUidCreate;
	private Date ptyDtLupd;
	private String ptyUidLupd;

	public TCkCtParty() {
	}

	public TCkCtParty(String ptyId, TCkCtMstPartyType TCkCtMstPartyType) {
		this.ptyId = ptyId;
		this.TCkCtMstPartyType = TCkCtMstPartyType;
	}

	public TCkCtParty(String ptyId, TCkCtMstPartyType TCkCtMstPartyType, String ptyName, String ptyNameOth,
			String ptyAddr1, String ptyAddr2, String ptyAddr3, String ptyPcode, String ptyCity, String ptyCtycode,
			Character ptyStatus, Date ptyDtCreate, String ptyUidCreate, Date ptyDtLupd, String ptyUidLupd) {
		this.ptyId = ptyId;
		this.TCkCtMstPartyType = TCkCtMstPartyType;
		this.ptyName = ptyName;
		this.ptyNameOth = ptyNameOth;
		this.ptyAddr1 = ptyAddr1;
		this.ptyAddr2 = ptyAddr2;
		this.ptyAddr3 = ptyAddr3;
		this.ptyPcode = ptyPcode;
		this.ptyCity = ptyCity;
		this.ptyCtycode = ptyCtycode;
		this.ptyStatus = ptyStatus;
		this.ptyDtCreate = ptyDtCreate;
		this.ptyUidCreate = ptyUidCreate;
		this.ptyDtLupd = ptyDtLupd;
		this.ptyUidLupd = ptyUidLupd;
	}

	@Id

	@Column(name = "PTY_ID", unique = true, nullable = false, length = 70)
	public String getPtyId() {
		return this.ptyId;
	}

	public void setPtyId(String ptyId) {
		this.ptyId = ptyId;
	}

	@Column(name = "PTY_XML_ID", length = 256)
	public String getPtyXmlId() {
		return ptyXmlId;
	}

	public void setPtyXmlId(String ptyXmlId) {
		this.ptyXmlId = ptyXmlId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PTY_TYPE", nullable = false)
	public TCkCtMstPartyType getTCkCtMstPartyType() {
		return this.TCkCtMstPartyType;
	}

	public void setTCkCtMstPartyType(TCkCtMstPartyType TCkCtMstPartyType) {
		this.TCkCtMstPartyType = TCkCtMstPartyType;
	}

	@Column(name = "PTY_NAME", length = 256)
	public String getPtyName() {
		return this.ptyName;
	}

	public void setPtyName(String ptyName) {
		this.ptyName = ptyName;
	}

	@Column(name = "PTY_NAME_OTH", length = 512)
	public String getPtyNameOth() {
		return this.ptyNameOth;
	}

	public void setPtyNameOth(String ptyNameOth) {
		this.ptyNameOth = ptyNameOth;
	}

	@Column(name = "PTY_ADDR1", length = 250)
	public String getPtyAddr1() {
		return this.ptyAddr1;
	}

	public void setPtyAddr1(String ptyAddr1) {
		this.ptyAddr1 = ptyAddr1;
	}

	@Column(name = "PTY_ADDR2", length = 70)
	public String getPtyAddr2() {
		return this.ptyAddr2;
	}

	public void setPtyAddr2(String ptyAddr2) {
		this.ptyAddr2 = ptyAddr2;
	}

	@Column(name = "PTY_ADDR3", length = 70)
	public String getPtyAddr3() {
		return this.ptyAddr3;
	}

	public void setPtyAddr3(String ptyAddr3) {
		this.ptyAddr3 = ptyAddr3;
	}

	@Column(name = "PTY_PCODE", length = 17)
	public String getPtyPcode() {
		return this.ptyPcode;
	}

	public void setPtyPcode(String ptyPcode) {
		this.ptyPcode = ptyPcode;
	}

	@Column(name = "PTY_CITY", length = 256)
	public String getPtyCity() {
		return this.ptyCity;
	}

	public void setPtyCity(String ptyCity) {
		this.ptyCity = ptyCity;
	}

	@Column(name = "PTY_CTYCODE", length = 3)
	public String getPtyCtycode() {
		return this.ptyCtycode;
	}

	public void setPtyCtycode(String ptyCtycode) {
		this.ptyCtycode = ptyCtycode;
	}

	@Column(name = "PTY_STATUS", length = 1)
	public Character getPtyStatus() {
		return this.ptyStatus;
	}

	public void setPtyStatus(Character ptyStatus) {
		this.ptyStatus = ptyStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PTY_DT_CREATE", length = 19)
	public Date getPtyDtCreate() {
		return this.ptyDtCreate;
	}

	public void setPtyDtCreate(Date ptyDtCreate) {
		this.ptyDtCreate = ptyDtCreate;
	}

	@Column(name = "PTY_UID_CREATE", length = 35)
	public String getPtyUidCreate() {
		return this.ptyUidCreate;
	}

	public void setPtyUidCreate(String ptyUidCreate) {
		this.ptyUidCreate = ptyUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PTY_DT_LUPD", length = 19)
	public Date getPtyDtLupd() {
		return this.ptyDtLupd;
	}

	public void setPtyDtLupd(Date ptyDtLupd) {
		this.ptyDtLupd = ptyDtLupd;
	}

	@Column(name = "PTY_UID_LUPD", length = 35)
	public String getPtyUidLupd() {
		return this.ptyUidLupd;
	}

	public void setPtyUidLupd(String ptyUidLupd) {
		this.ptyUidLupd = ptyUidLupd;
	}

	@Override
	public int compareTo(TCkCtParty o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
