package com.guudint.clickargo.clictruck.planexec.job.model;
// Generated 22 Sep 2023, 6:15:54 pm by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtJobTermReq generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_JOB_TERM_REQ")
public class TCkCtJobTermReq extends COAbstractEntity<TCkCtJobTermReq> {

	private static final long serialVersionUID = -4361770050655144337L;
	public static final String PREFIX_ID = "JTR";
	
	private String jtrId;
	private String jtrState;
	
	private TCoreAccn TCoreAccn;
	private Double jtrCrLimit;
	private Double jtrCrBal;
	private Integer jtrInvOpen;
	private Double jtrAmtOpen;
	private Date jtrDtDueInv;
	private Short jtrNoJobs;
	private BigDecimal jtrJobsPltfeeAmt;
	private BigDecimal jtrJobsDnAmt;
	private BigDecimal jtrJobsDefault;
	private String jtrUidRequestor;
	private String jtrCommentRequestor;
	private Date jtrDtSubmit;
	private String jtrUidApprover;
	private String jtrCommentApprover;
	private Date jtrDtApproveReject;
	private String jtrComment;
	private Character jtrStatus;
	private Date jtrDtCreate;
	private String jtrUidCreate;
	private Date jtrDtLupd;
	private String jtrUidLupd;
	
	private List<TCkCtJobTerm> TCkCtJobTerms = new ArrayList<TCkCtJobTerm>(0);
	
	

	public TCkCtJobTermReq() {
	}

	public TCkCtJobTermReq(String jtrId, TCoreAccn TCoreAccn) {
		this.jtrId = jtrId;
		this.TCoreAccn = TCoreAccn;
	}

	public TCkCtJobTermReq(String jtrId, TCoreAccn TCoreAccn, Double jtrCrLimit, Double jtrCrBal, Integer jtrInvOpen,
			Double jtrAmtOpen, Date jtrDtDueInv, Short jtrNoJobs, BigDecimal jtrJobsPltfeeAmt, BigDecimal jtrJobsDnAmt,
			BigDecimal jtrJobsDefault, String jtrUidRequestor, String jtrCommentRequestor, Date jtrDtSubmit,
			String jtrUidApprover, String jtrCommentApprover, Date jtrDtApproveReject, String jtrComment,
			Character jtrStatus, Date jtrDtCreate, String jtrUidCreate, Date jtrDtLupd, String jtrUidLupd) {
		this.jtrId = jtrId;
		this.TCoreAccn = TCoreAccn;
		this.jtrCrLimit = jtrCrLimit;
		this.jtrCrBal = jtrCrBal;
		this.jtrInvOpen = jtrInvOpen;
		this.jtrAmtOpen = jtrAmtOpen;
		this.jtrDtDueInv = jtrDtDueInv;
		this.jtrNoJobs = jtrNoJobs;
		this.jtrJobsPltfeeAmt = jtrJobsPltfeeAmt;
		this.jtrJobsDnAmt = jtrJobsDnAmt;
		this.jtrJobsDefault = jtrJobsDefault;
		this.jtrUidRequestor = jtrUidRequestor;
		this.jtrCommentRequestor = jtrCommentRequestor;
		this.jtrDtSubmit = jtrDtSubmit;
		this.jtrUidApprover = jtrUidApprover;
		this.jtrCommentApprover = jtrCommentApprover;
		this.jtrDtApproveReject = jtrDtApproveReject;
		this.jtrComment = jtrComment;
		this.jtrStatus = jtrStatus;
		this.jtrDtCreate = jtrDtCreate;
		this.jtrUidCreate = jtrUidCreate;
		this.jtrDtLupd = jtrDtLupd;
		this.jtrUidLupd = jtrUidLupd;
	}

	@Id

	@Column(name = "JTR_ID", unique = true, nullable = false, length = 35)
	public String getJtrId() {
		return this.jtrId;
	}

	public void setJtrId(String jtrId) {
		this.jtrId = jtrId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JTR_ACCN", nullable = false)
	public TCoreAccn getTCoreAccn() {
		return this.TCoreAccn;
	}

	public void setTCoreAccn(TCoreAccn TCoreAccn) {
		this.TCoreAccn = TCoreAccn;
	}

	@Column(name = "JTR_CR_LIMIT", precision = 15)
	public Double getJtrCrLimit() {
		return this.jtrCrLimit;
	}

	public void setJtrCrLimit(Double jtrCrLimit) {
		this.jtrCrLimit = jtrCrLimit;
	}

	@Column(name = "JTR_CR_BAL", precision = 15)
	public Double getJtrCrBal() {
		return this.jtrCrBal;
	}

	public void setJtrCrBal(Double jtrCrBal) {
		this.jtrCrBal = jtrCrBal;
	}

	@Column(name = "JTR_INV_OPEN")
	public Integer getJtrInvOpen() {
		return this.jtrInvOpen;
	}

	public void setJtrInvOpen(Integer jtrInvOpen) {
		this.jtrInvOpen = jtrInvOpen;
	}

	@Column(name = "JTR_AMT_OPEN", precision = 15)
	public Double getJtrAmtOpen() {
		return this.jtrAmtOpen;
	}

	public void setJtrAmtOpen(Double jtrAmtOpen) {
		this.jtrAmtOpen = jtrAmtOpen;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JTR_DT_DUE_INV", length = 19)
	public Date getJtrDtDueInv() {
		return this.jtrDtDueInv;
	}

	public void setJtrDtDueInv(Date jtrDtDueInv) {
		this.jtrDtDueInv = jtrDtDueInv;
	}

	@Column(name = "JTR_NO_JOBS")
	public Short getJtrNoJobs() {
		return this.jtrNoJobs;
	}

	public void setJtrNoJobs(Short jtrNoJobs) {
		this.jtrNoJobs = jtrNoJobs;
	}

	@Column(name = "JTR_JOBS_PLTFEE_AMT", precision = 15)
	public BigDecimal getJtrJobsPltfeeAmt() {
		return this.jtrJobsPltfeeAmt;
	}

	public void setJtrJobsPltfeeAmt(BigDecimal jtrJobsPltfeeAmt) {
		this.jtrJobsPltfeeAmt = jtrJobsPltfeeAmt;
	}

	@Column(name = "JTR_JOBS_DN_AMT", precision = 15)
	public BigDecimal getJtrJobsDnAmt() {
		return this.jtrJobsDnAmt;
	}

	public void setJtrJobsDnAmt(BigDecimal jtrJobsDnAmt) {
		this.jtrJobsDnAmt = jtrJobsDnAmt;
	}

	@Column(name = "JTR_JOBS_DEFAULT", precision = 15)
	public BigDecimal getJtrJobsDefault() {
		return this.jtrJobsDefault;
	}

	public void setJtrJobsDefault(BigDecimal jtrJobsDefault) {
		this.jtrJobsDefault = jtrJobsDefault;
	}

	@Column(name = "JTR_UID_REQUESTOR", length = 35)
	public String getJtrUidRequestor() {
		return this.jtrUidRequestor;
	}

	public void setJtrUidRequestor(String jtrUidRequestor) {
		this.jtrUidRequestor = jtrUidRequestor;
	}

	@Column(name = "JTR_COMMENT_REQUESTOR", length = 16777215)
	public String getJtrCommentRequestor() {
		return this.jtrCommentRequestor;
	}

	public void setJtrCommentRequestor(String jtrCommentRequestor) {
		this.jtrCommentRequestor = jtrCommentRequestor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JTR_DT_SUBMIT", length = 19)
	public Date getJtrDtSubmit() {
		return this.jtrDtSubmit;
	}

	public void setJtrDtSubmit(Date jtrDtSubmit) {
		this.jtrDtSubmit = jtrDtSubmit;
	}

	@Column(name = "JTR_UID_APPROVER", length = 35)
	public String getJtrUidApprover() {
		return this.jtrUidApprover;
	}

	public void setJtrUidApprover(String jtrUidApprover) {
		this.jtrUidApprover = jtrUidApprover;
	}

	@Column(name = "JTR_COMMENT_APPROVER", length = 16777215)
	public String getJtrCommentApprover() {
		return this.jtrCommentApprover;
	}

	public void setJtrCommentApprover(String jtrCommentApprover) {
		this.jtrCommentApprover = jtrCommentApprover;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JTR_DT_APPROVE_REJECT", length = 19)
	public Date getJtrDtApproveReject() {
		return this.jtrDtApproveReject;
	}

	public void setJtrDtApproveReject(Date jtrDtApproveReject) {
		this.jtrDtApproveReject = jtrDtApproveReject;
	}

	@Column(name = "JTR_COMMENT", length = 16777215)
	public String getJtrComment() {
		return this.jtrComment;
	}

	public void setJtrComment(String jtrComment) {
		this.jtrComment = jtrComment;
	}

	@Column(name = "JTR_STATUS", length = 1)
	public Character getJtrStatus() {
		return this.jtrStatus;
	}

	public void setJtrStatus(Character jtrStatus) {
		this.jtrStatus = jtrStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JTR_DT_CREATE", length = 19)
	public Date getJtrDtCreate() {
		return this.jtrDtCreate;
	}

	public void setJtrDtCreate(Date jtrDtCreate) {
		this.jtrDtCreate = jtrDtCreate;
	}

	@Column(name = "JTR_UID_CREATE", length = 35)
	public String getJtrUidCreate() {
		return this.jtrUidCreate;
	}

	public void setJtrUidCreate(String jtrUidCreate) {
		this.jtrUidCreate = jtrUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JTR_DT_LUPD", length = 19)
	public Date getJtrDtLupd() {
		return this.jtrDtLupd;
	}

	public void setJtrDtLupd(Date jtrDtLupd) {
		this.jtrDtLupd = jtrDtLupd;
	}

	@Column(name = "JTR_UID_LUPD", length = 35)
	public String getJtrUidLupd() {
		return this.jtrUidLupd;
	}

	public void setJtrUidLupd(String jtrUidLupd) {
		this.jtrUidLupd = jtrUidLupd;
	}

	@Column(name = "JTR_STATE", length = 3)
	public String getJtrState() {
		return jtrState;
	}

	public void setJtrState(String jtrState) {
		this.jtrState = jtrState;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCkCtJobTermReq")
	public List<TCkCtJobTerm> getTCkCtJobTerms() {
		return this.TCkCtJobTerms;
	}

	public void setTCkCtJobTerms(List<TCkCtJobTerm> TCkCtJobTerms) {
		this.TCkCtJobTerms = TCkCtJobTerms;
	}

	@Override
	public int compareTo(TCkCtJobTermReq o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
