package com.guudint.clickargo.clictruck.planexec.job.model;
// Generated 23 Feb, 2023 4:00:19 PM by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.guudint.clickargo.clictruck.common.model.TCkCtDept;
import com.guudint.clickargo.clictruck.common.model.TCkCtDrv;
import com.guudint.clickargo.clictruck.common.model.TCkCtVeh;
import com.guudint.clickargo.clictruck.finacing.model.TCkCtDebitNote;
import com.guudint.clickargo.clictruck.finacing.model.TCkCtToInvoice;
import com.guudint.clickargo.clictruck.master.model.TCkCtMstVehType;
import com.guudint.clickargo.job.model.TCkJob;
import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkJobTruck generated by hbm2java
 */
@Entity
@Table(name = "T_CK_JOB_TRUCK")
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
public class TCkJobTruck extends COAbstractEntity<TCkJobTruck> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -4917811691707040038L;

	// Attributes
	/////////////
	private String jobId;
	private TCkCtContactDetail TCkCtContactDetailByJobContactTo;
	private TCkCtContactDetail TCkCtContactDetailByJobContactCoFf;
	private TCkCtDebitNote TCkCtDebitNoteByJobInvoiceeDebitNote;
	private TCkCtDebitNote TCkCtDebitNoteByJobInvoicerDebitNote;
	private TCkCtDrv TCkCtDrv;
	private String jobDrvOth;
	private TCkCtMstVehType TCkCtMstVehType;
	private TCkCtToInvoice TCkCtToInvoice;
	private TCkCtVeh TCkCtVeh;
	private String jobVehOth;
	private TCkJob TCkJob;
	private TCoreAccn TCoreAccnByJobPartyCoFf;
	private TCoreAccn TCoreAccnByJobPartyTo;
	private Date jobDtBooking;
	private Date jobDtPlan;
	private Date jobDtDelivery;
	private Date jobDtStart;
	private Date jobDtEnd;
	private Short jobNoTrips;
	private String jobShipmentRef;
	private String jobCustomerRef;
	private BigDecimal jobTotalCharge;
	private BigDecimal jobTotalReimbursements;
	private BigDecimal jobTotalPlatformFees;
	private String jobInPaymentState;
	private String jobOutPaymentState;
	private Date jobInPaymentDtDue;
	private Date jobOutPaymentDtDue;
	private Character jobStatus;
	private Date jobDtCreate;
	private String jobUidCreate;
	private Date jobDtLupd;
	private String jobUidLupd;

	// 2.1.0
	private Character jobIsFinanced;
	private Character jobMobileEnabled;
	private String jobSource;
	private String jobProcessVia;

	private String jobFinanceOpt;
	private String jobFinancer;
	private Date jobDtOpmUtilize;

	// 2.1.1 SG2 Department categorization
	private TCkCtDept TCkCtDeptByJobCoDepartment;
	private TCkCtDept TCkCtDeptByJobToDepartment;

	private Date jobDtEpod;

	public TCkJobTruck() {
	}

	public TCkJobTruck(String jobId, TCkJob TCkJob) {
		this.jobId = jobId;
		this.TCkJob = TCkJob;
	}

	public TCkJobTruck(String jobId, TCkCtContactDetail TCkCtContactDetailByJobContactTo,
			TCkCtContactDetail TCkCtContactDetailByJobContactCoFf, TCkCtDebitNote TCkCtDebitNoteByJobInvoiceeDebitNote,
			TCkCtDebitNote TCkCtDebitNoteByJobInvoicerDebitNote, TCkCtDrv TCkCtDrv, String jobDrvOth,
			TCkCtMstVehType TCkCtMstVehType, TCkCtToInvoice TCkCtToInvoice, TCkCtVeh TCkCtVeh, String jobVehOth,
			TCkJob TCkJob, TCoreAccn TCoreAccnByJobPartyCoFf, TCoreAccn TCoreAccnByJobPartyTo, Date jobDtBooking,
			Date jobDtPlan, Date jobDtDelivery, Date jobDtStart, Date jobDtEnd, Short jobNoTrips, String jobShipmentRef,
			String jobCustomerRef, Character jobStatus, Date jobDtCreate, String jobUidCreate, Date jobDtLupd,
			String jobUidLupd) {
		this.jobId = jobId;
		this.TCkCtContactDetailByJobContactTo = TCkCtContactDetailByJobContactTo;
		this.TCkCtContactDetailByJobContactCoFf = TCkCtContactDetailByJobContactCoFf;
		this.TCkCtDebitNoteByJobInvoiceeDebitNote = TCkCtDebitNoteByJobInvoiceeDebitNote;
		this.TCkCtDebitNoteByJobInvoicerDebitNote = TCkCtDebitNoteByJobInvoicerDebitNote;
		this.TCkCtDrv = TCkCtDrv;
		this.jobDrvOth = jobDrvOth;
		this.TCkCtMstVehType = TCkCtMstVehType;
		this.TCkCtToInvoice = TCkCtToInvoice;
		this.TCkCtVeh = TCkCtVeh;
		this.jobVehOth = jobVehOth;
		this.TCkJob = TCkJob;
		this.TCoreAccnByJobPartyCoFf = TCoreAccnByJobPartyCoFf;
		this.TCoreAccnByJobPartyTo = TCoreAccnByJobPartyTo;
		this.jobDtBooking = jobDtBooking;
		this.jobDtPlan = jobDtPlan;
		this.jobDtDelivery = jobDtDelivery;
		this.jobDtStart = jobDtStart;
		this.jobDtEnd = jobDtEnd;
		this.jobNoTrips = jobNoTrips;
		this.jobShipmentRef = jobShipmentRef;
		this.jobCustomerRef = jobCustomerRef;
		this.jobStatus = jobStatus;
		this.jobDtCreate = jobDtCreate;
		this.jobUidCreate = jobUidCreate;
		this.jobDtLupd = jobDtLupd;
		this.jobUidLupd = jobUidLupd;
	}

	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}

	///////
	public BigDecimal computeTotalAmt() {

		BigDecimal totalAmt = BigDecimal.ZERO;

		if (null != jobTotalCharge) {
			totalAmt = totalAmt.add(jobTotalCharge);
		}

		if (null != jobTotalReimbursements) {
			totalAmt = totalAmt.add(jobTotalReimbursements);
		}

		return totalAmt;
	}

	// Properties
	/////////////
	@Id
	@Column(name = "JOB_ID", unique = true, nullable = false, length = 35)
	public String getJobId() {
		return this.jobId;
	}

	public void setJobId(String jobId) {
		this.jobId = jobId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "JOB_CONTACT_TO")
	public TCkCtContactDetail getTCkCtContactDetailByJobContactTo() {
		return this.TCkCtContactDetailByJobContactTo;
	}

	public void setTCkCtContactDetailByJobContactTo(TCkCtContactDetail TCkCtContactDetailByJobContactTo) {
		this.TCkCtContactDetailByJobContactTo = TCkCtContactDetailByJobContactTo;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "JOB_CONTACT_CO_FF")
	public TCkCtContactDetail getTCkCtContactDetailByJobContactCoFf() {
		return this.TCkCtContactDetailByJobContactCoFf;
	}

	public void setTCkCtContactDetailByJobContactCoFf(TCkCtContactDetail TCkCtContactDetailByJobContactCoFf) {
		this.TCkCtContactDetailByJobContactCoFf = TCkCtContactDetailByJobContactCoFf;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "JOB_INVOICEE_DEBIT_NOTE")
	public TCkCtDebitNote getTCkCtDebitNoteByJobInvoiceeDebitNote() {
		return this.TCkCtDebitNoteByJobInvoiceeDebitNote;
	}

	public void setTCkCtDebitNoteByJobInvoiceeDebitNote(TCkCtDebitNote TCkCtDebitNoteByJobInvoiceeDebitNote) {
		this.TCkCtDebitNoteByJobInvoiceeDebitNote = TCkCtDebitNoteByJobInvoiceeDebitNote;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "JOB_INVOICER_DEBIT_NOTE")
	public TCkCtDebitNote getTCkCtDebitNoteByJobInvoicerDebitNote() {
		return this.TCkCtDebitNoteByJobInvoicerDebitNote;
	}

	public void setTCkCtDebitNoteByJobInvoicerDebitNote(TCkCtDebitNote TCkCtDebitNoteByJobInvoicerDebitNote) {
		this.TCkCtDebitNoteByJobInvoicerDebitNote = TCkCtDebitNoteByJobInvoicerDebitNote;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "JOB_DRV")
	public TCkCtDrv getTCkCtDrv() {
		return this.TCkCtDrv;
	}

	public void setTCkCtDrv(TCkCtDrv TCkCtDrv) {
		this.TCkCtDrv = TCkCtDrv;
	}

	@Column(name = "JOB_DRV_OTH")
	public String getJobDrvOth() {
		return jobDrvOth;
	}

	public void setJobDrvOth(String jobDrvOth) {
		this.jobDrvOth = jobDrvOth;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "JOB_VEH_TYPE")
	public TCkCtMstVehType getTCkCtMstVehType() {
		return this.TCkCtMstVehType;
	}

	public void setTCkCtMstVehType(TCkCtMstVehType TCkCtMstVehType) {
		this.TCkCtMstVehType = TCkCtMstVehType;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "JOB_TO_INVOICE")
	public TCkCtToInvoice getTCkCtToInvoice() {
		return this.TCkCtToInvoice;
	}

	public void setTCkCtToInvoice(TCkCtToInvoice TCkCtToInvoice) {
		this.TCkCtToInvoice = TCkCtToInvoice;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "JOB_VEH")
	public TCkCtVeh getTCkCtVeh() {
		return this.TCkCtVeh;
	}

	public void setTCkCtVeh(TCkCtVeh TCkCtVeh) {
		this.TCkCtVeh = TCkCtVeh;
	}

	@Column(name = "JOB_VEH_OTH")
	public String getJobVehOth() {
		return jobVehOth;
	}

	public void setJobVehOth(String jobVehOth) {
		this.jobVehOth = jobVehOth;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "JOB_PARENT", nullable = false)
	public TCkJob getTCkJob() {
		return this.TCkJob;
	}

	public void setTCkJob(TCkJob TCkJob) {
		this.TCkJob = TCkJob;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "JOB_PARTY_CO_FF")
	public TCoreAccn getTCoreAccnByJobPartyCoFf() {
		return this.TCoreAccnByJobPartyCoFf;
	}

	public void setTCoreAccnByJobPartyCoFf(TCoreAccn TCoreAccnByJobPartyCoFf) {
		this.TCoreAccnByJobPartyCoFf = TCoreAccnByJobPartyCoFf;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "JOB_PARTY_TO")
	public TCoreAccn getTCoreAccnByJobPartyTo() {
		return this.TCoreAccnByJobPartyTo;
	}

	public void setTCoreAccnByJobPartyTo(TCoreAccn TCoreAccnByJobPartyTo) {
		this.TCoreAccnByJobPartyTo = TCoreAccnByJobPartyTo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JOB_DT_BOOKING", length = 19)
	public Date getJobDtBooking() {
		return this.jobDtBooking;
	}

	public void setJobDtBooking(Date jobDtBooking) {
		this.jobDtBooking = jobDtBooking;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JOB_DT_PLAN", length = 19)
	public Date getJobDtPlan() {
		return this.jobDtPlan;
	}

	public void setJobDtPlan(Date jobDtPlan) {
		this.jobDtPlan = jobDtPlan;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JOB_DT_DELIVERY", length = 19)
	public Date getJobDtDelivery() {
		return this.jobDtDelivery;
	}

	public void setJobDtDelivery(Date jobDtDelivery) {
		this.jobDtDelivery = jobDtDelivery;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JOB_DT_START", length = 19)
	public Date getJobDtStart() {
		return jobDtStart;
	}

	public void setJobDtStart(Date jobDtStart) {
		this.jobDtStart = jobDtStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JOB_DT_END", length = 19)
	public Date getJobDtEnd() {
		return jobDtEnd;
	}

	public void setJobDtEnd(Date jobDtEnd) {
		this.jobDtEnd = jobDtEnd;
	}

	@Column(name = "JOB_NO_TRIPS")
	public Short getJobNoTrips() {
		return this.jobNoTrips;
	}

	public void setJobNoTrips(Short jobNoTrips) {
		this.jobNoTrips = jobNoTrips;
	}

//	@Column(name = "JOB_DRV", length = 35)
//	public String getJobDrv() {
//		return this.jobDrv;
//	}
//
//	public void setJobDrv(String jobDrv) {
//		this.jobDrv = jobDrv;
//	}

	@Column(name = "JOB_STATUS", length = 1)
	public Character getJobStatus() {
		return this.jobStatus;
	}

	public void setJobStatus(Character jobStatus) {
		this.jobStatus = jobStatus;
	}

	@Column(name = "JOB_SHIPMENT_REF", length = 255)
	public String getJobShipmentRef() {
		return jobShipmentRef;
	}

	public void setJobShipmentRef(String jobShipmentRef) {
		this.jobShipmentRef = jobShipmentRef;
	}

	@Column(name = "JOB_CUSTOMER_REF", length = 255)
	public String getJobCustomerRef() {
		return jobCustomerRef;
	}

	public void setJobCustomerRef(String jobCustomerRef) {
		this.jobCustomerRef = jobCustomerRef;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JOB_DT_CREATE", length = 19)
	public Date getJobDtCreate() {
		return this.jobDtCreate;
	}

	public void setJobDtCreate(Date jobDtCreate) {
		this.jobDtCreate = jobDtCreate;
	}

	@Column(name = "JOB_UID_CREATE", length = 35)
	public String getJobUidCreate() {
		return this.jobUidCreate;
	}

	public void setJobUidCreate(String jobUidCreate) {
		this.jobUidCreate = jobUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JOB_DT_LUPD", length = 19)
	public Date getJobDtLupd() {
		return this.jobDtLupd;
	}

	public void setJobDtLupd(Date jobDtLupd) {
		this.jobDtLupd = jobDtLupd;
	}

	@Column(name = "JOB_UID_LUPD", length = 35)
	public String getJobUidLupd() {
		return this.jobUidLupd;
	}

	public void setJobUidLupd(String jobUidLupd) {
		this.jobUidLupd = jobUidLupd;
	}

	@Column(name = "JOB_TOTAL_CHARGE", precision = 15)
	public BigDecimal getJobTotalCharge() {
		return jobTotalCharge;
	}

	public void setJobTotalCharge(BigDecimal jobTotalCharge) {
		this.jobTotalCharge = jobTotalCharge;
	}

	@Column(name = "JOB_IN_PAYMENT_STATE")
	public String getJobInPaymentState() {
		return jobInPaymentState;
	}

	public void setJobInPaymentState(String jobInPaymentState) {
		this.jobInPaymentState = jobInPaymentState;
	}

	@Column(name = "JOB_OUT_PAYMENT_STATE")
	public String getJobOutPaymentState() {
		return jobOutPaymentState;
	}

	public void setJobOutPaymentState(String jobOutPaymentState) {
		this.jobOutPaymentState = jobOutPaymentState;
	}

	@Column(name = "JOB_TOTAL_REIMBURSEMENTS", precision = 15)
	public BigDecimal getJobTotalReimbursements() {
		return jobTotalReimbursements;
	}

	public void setJobTotalReimbursements(BigDecimal jobTotalReimbursements) {
		this.jobTotalReimbursements = jobTotalReimbursements;
	}

	@Column(name = "JOB_TOTAL_PLATFORM_FEES", precision = 15)
	public BigDecimal getJobTotalPlatformFees() {
		return jobTotalPlatformFees;
	}

	public void setJobTotalPlatformFees(BigDecimal jobTotalPlatformFees) {
		this.jobTotalPlatformFees = jobTotalPlatformFees;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JOB_IN_PAYMENT_DT_DUE", length = 19)
	public Date getJobInPaymentDtDue() {
		return jobInPaymentDtDue;
	}

	public void setJobInPaymentDtDue(Date jobInPaymentDtDue) {
		this.jobInPaymentDtDue = jobInPaymentDtDue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JOB_OUT_PAYMENT_DT_DUE", length = 19)
	public Date getJobOutPaymentDtDue() {
		return jobOutPaymentDtDue;
	}

	public void setJobOutPaymentDtDue(Date jobOutPaymentDtDue) {
		this.jobOutPaymentDtDue = jobOutPaymentDtDue;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	 */
	@Override
	public int compareTo(TCkJobTruck o) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 * 
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

	@Column(name = "JOB_IS_FINANCED", length = 1)
	public Character getJobIsFinanced() {
		return this.jobIsFinanced;
	}

	public void setJobIsFinanced(Character jobIsFinanced) {
		this.jobIsFinanced = jobIsFinanced;
	}

	@Column(name = "JOB_MOBILE_ENABLED", length = 1)
	public Character getJobMobileEnabled() {
		return jobMobileEnabled;
	}

	public void setJobMobileEnabled(Character jobMobileEnabled) {
		this.jobMobileEnabled = jobMobileEnabled;
	}

	@Column(name = "JOB_SOURCE")
	public String getJobSource() {
		return jobSource;
	}

	public void setJobSource(String jobSource) {
		this.jobSource = jobSource;
	}

	@Column(name = "JOB_PROCESS_VIA", length = 45)
	public String getJobProcessVia() {
		return this.jobProcessVia;
	}

	public void setJobProcessVia(String jobProcessVia) {
		this.jobProcessVia = jobProcessVia;
	}

	@Column(name = "JOB_FINANCE_OPT", length = 35)
	public String getJobFinanceOpt() {
		return this.jobFinanceOpt;
	}

	public void setJobFinanceOpt(String jobFinanceOpt) {
		this.jobFinanceOpt = jobFinanceOpt;
	}

	@Column(name = "JOB_FINANCER", length = 35)
	public String getJobFinancer() {
		return this.jobFinancer;
	}

	public void setJobFinancer(String jobFinancer) {
		this.jobFinancer = jobFinancer;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JOB_DT_OPM_UTILIZE", length = 19)
	public Date getJobDtOpmUtilize() {
		return this.jobDtOpmUtilize;
	}

	public void setJobDtOpmUtilize(Date jobDtOpmUtilize) {
		this.jobDtOpmUtilize = jobDtOpmUtilize;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "JOB_CO_DEPARTMENT")
	public TCkCtDept getTCkCtDeptByJobCoDepartment() {
		return this.TCkCtDeptByJobCoDepartment;
	}

	public void setTCkCtDeptByJobCoDepartment(TCkCtDept TCkCtDeptByJobCoDepartment) {
		this.TCkCtDeptByJobCoDepartment = TCkCtDeptByJobCoDepartment;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "JOB_TO_DEPARTMENT")
	public TCkCtDept getTCkCtDeptByJobToDepartment() {
		return this.TCkCtDeptByJobToDepartment;
	}

	public void setTCkCtDeptByJobToDepartment(TCkCtDept TCkCtDeptByJobToDepartment) {
		this.TCkCtDeptByJobToDepartment = TCkCtDeptByJobToDepartment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JOB_DT_EPOD", length = 19)
	public Date getJobDtEpod() {
		return jobDtEpod;
	}

	public void setJobDtEpod(Date jobDtEpod) {
		this.jobDtEpod = jobDtEpod;
	}

}
