package com.guudint.clickargo.clictruck.planexec.job.model;
// Generated 16 Nov 2023, 2:40:26 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkJobTruckExt generated by hbm2java
 */
@Entity
@Table(name = "T_CK_JOB_TRUCK_EXT")
public class TCkJobTruckExt extends COAbstractEntity<TCkJobTruckExt> {

	private static final long serialVersionUID = -1L;
	public static final String PREFIX_ID = "JE";

	private String jextId;
	private TCkJobTruck TCkJobTruck;
	private TCoreAccn TCoreAccn;
	private String jextKey;
	private String jextVal;
	private String jextValType;
	private String jextDesc;
	private Character jextStatus;
	private Date jextDtCreate;
	private String jextUidCreate;
	private Date jextDtLupd;
	private String jextUidLupd;

	public TCkJobTruckExt() {
	}

	public TCkJobTruckExt(String jextId, String jextKey, String jextVal) {
		this.jextId = jextId;
		this.jextKey = jextKey;
		this.jextVal = jextVal;
	}

	public TCkJobTruckExt(String jextId, TCkJobTruck TCkJobTruck, TCoreAccn TCoreAccn, String jextKey, String jextVal,
			String jextDesc, Character jextStatus, Date jextDtCreate, String jextUidCreate, Date jextDtLupd,
			String jextUidLupd) {
		this.jextId = jextId;
		this.TCkJobTruck = TCkJobTruck;
		this.TCoreAccn = TCoreAccn;
		this.jextKey = jextKey;
		this.jextVal = jextVal;
		this.jextDesc = jextDesc;
		this.jextStatus = jextStatus;
		this.jextDtCreate = jextDtCreate;
		this.jextUidCreate = jextUidCreate;
		this.jextDtLupd = jextDtLupd;
		this.jextUidLupd = jextUidLupd;
	}


	@Override
	public int compareTo(TCkJobTruckExt o) {
		return 0;
	}

	@Override
	public void init() {

	}

	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
	
	@Transient
	public Object getJextValAsStrOrObj() {
		try {
			if("date".equalsIgnoreCase(jextValType)) {
				return new Date(Long.valueOf(jextVal));
			}
		} catch(Exception e) {
			e.printStackTrace();
		}
		return this.jextVal;
	}
	
	@Id

	@Column(name = "JEXT_ID", unique = true, nullable = false, length = 35)
	public String getJextId() {
		return this.jextId;
	}

	public void setJextId(String jextId) {
		this.jextId = jextId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JEXT_JOB")
	public TCkJobTruck getTCkJobTruck() {
		return this.TCkJobTruck;
	}

	public void setTCkJobTruck(TCkJobTruck TCkJobTruck) {
		this.TCkJobTruck = TCkJobTruck;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JEXT_ACCN")
	public TCoreAccn getTCoreAccn() {
		return this.TCoreAccn;
	}

	public void setTCoreAccn(TCoreAccn TCoreAccn) {
		this.TCoreAccn = TCoreAccn;
	}

	@Column(name = "JEXT_KEY", nullable = false, length = 30)
	public String getJextKey() {
		return this.jextKey;
	}

	public void setJextKey(String jextKey) {
		this.jextKey = jextKey;
	}

	@Column(name = "JEXT_VAL", length = 256)
	public String getJextVal() {
		return this.jextVal;
	}

	public void setJextVal(String jextVal) {
		this.jextVal = jextVal;
	}

	@Column(name = "JEXT_VAL_TYPE")
	public String getJextValType() {
		return jextValType;
	}

	public void setJextValType(String jextValType) {
		this.jextValType = jextValType;
	}

	@Column(name = "JEXT_DESC", length = 1024)
	public String getJextDesc() {
		return this.jextDesc;
	}

	public void setJextDesc(String jextDesc) {
		this.jextDesc = jextDesc;
	}

	@Column(name = "JEXT_STATUS", length = 1)
	public Character getJextStatus() {
		return this.jextStatus;
	}

	public void setJextStatus(Character jextStatus) {
		this.jextStatus = jextStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JEXT_DT_CREATE", length = 19)
	public Date getJextDtCreate() {
		return this.jextDtCreate;
	}

	public void setJextDtCreate(Date jextDtCreate) {
		this.jextDtCreate = jextDtCreate;
	}

	@Column(name = "JEXT_UID_CREATE", length = 35)
	public String getJextUidCreate() {
		return this.jextUidCreate;
	}

	public void setJextUidCreate(String jextUidCreate) {
		this.jextUidCreate = jextUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JEXT_DT_LUPD", length = 19)
	public Date getJextDtLupd() {
		return this.jextDtLupd;
	}

	public void setJextDtLupd(Date jextDtLupd) {
		this.jextDtLupd = jextDtLupd;
	}

	@Column(name = "JEXT_UID_LUPD", length = 35)
	public String getJextUidLupd() {
		return this.jextUidLupd;
	}

	public void setJextUidLupd(String jextUidLupd) {
		this.jextUidLupd = jextUidLupd;
	}

}
