package com.guudint.clickargo.clictruck.planexec.job.model;
// Generated 22 Feb 2024, 10:53:23 am by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.guudint.clickargo.clictruck.admin.contract.model.TCkCtConAddAttr;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkJobTruckAddAttr generated by hbm2java
 */
@Entity
@Table(name = "T_CK_JOB_TRUCK_ADD_ATTR")
public class TCkJobTruckAddAttr extends COAbstractEntity<TCkJobTruckAddAttr> {

	private static final long serialVersionUID = 1628124004408698207L;
	private String jaaId;
	private TCkCtConAddAttr TCkCtConAddAttr;
	private TCkJobTruck TCkJobTruck;
	private String jaaValue;
	private Character jaaStatus;
	private Date jaaDtCreate;
	private String jaaUidCreate;
	private Date jaaDtLupd;
	private String jaaUidLupd;

	public TCkJobTruckAddAttr() {
	}

	public TCkJobTruckAddAttr(String jaaId, String jaaValue) {
		this.jaaId = jaaId;
		this.jaaValue = jaaValue;
	}

	public TCkJobTruckAddAttr(String jaaId, TCkCtConAddAttr TCkCtConAddAttr, TCkJobTruck TCkJobTruck, String jaaValue,
			Character jaaStatus, Date jaaDtCreate, String jaaUidCreate, Date jaaDtLupd, String jaaUidLupd) {
		this.jaaId = jaaId;
		this.TCkCtConAddAttr = TCkCtConAddAttr;
		this.TCkJobTruck = TCkJobTruck;
		this.jaaValue = jaaValue;
		this.jaaStatus = jaaStatus;
		this.jaaDtCreate = jaaDtCreate;
		this.jaaUidCreate = jaaUidCreate;
		this.jaaDtLupd = jaaDtLupd;
		this.jaaUidLupd = jaaUidLupd;
	}

	@Id

	@Column(name = "JAA_ID", unique = true, nullable = false, length = 35)
	public String getJaaId() {
		return this.jaaId;
	}

	public void setJaaId(String jaaId) {
		this.jaaId = jaaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JAA_CON_ATTR")
	public TCkCtConAddAttr getTCkCtConAddAttr() {
		return this.TCkCtConAddAttr;
	}

	public void setTCkCtConAddAttr(TCkCtConAddAttr TCkCtConAddAttr) {
		this.TCkCtConAddAttr = TCkCtConAddAttr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JAA_JOB")
	public TCkJobTruck getTCkJobTruck() {
		return this.TCkJobTruck;
	}

	public void setTCkJobTruck(TCkJobTruck TCkJobTruck) {
		this.TCkJobTruck = TCkJobTruck;
	}

	@Column(name = "JAA_VALUE", nullable = false, length = 1024)
	public String getJaaValue() {
		return this.jaaValue;
	}

	public void setJaaValue(String jaaValue) {
		this.jaaValue = jaaValue;
	}

	@Column(name = "JAA_STATUS", length = 1)
	public Character getJaaStatus() {
		return this.jaaStatus;
	}

	public void setJaaStatus(Character jaaStatus) {
		this.jaaStatus = jaaStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JAA_DT_CREATE", length = 19)
	public Date getJaaDtCreate() {
		return this.jaaDtCreate;
	}

	public void setJaaDtCreate(Date jaaDtCreate) {
		this.jaaDtCreate = jaaDtCreate;
	}

	@Column(name = "JAA_UID_CREATE", length = 35)
	public String getJaaUidCreate() {
		return this.jaaUidCreate;
	}

	public void setJaaUidCreate(String jaaUidCreate) {
		this.jaaUidCreate = jaaUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JAA_DT_LUPD", length = 19)
	public Date getJaaDtLupd() {
		return this.jaaDtLupd;
	}

	public void setJaaDtLupd(Date jaaDtLupd) {
		this.jaaDtLupd = jaaDtLupd;
	}

	@Column(name = "JAA_UID_LUPD", length = 35)
	public String getJaaUidLupd() {
		return this.jaaUidLupd;
	}

	public void setJaaUidLupd(String jaaUidLupd) {
		this.jaaUidLupd = jaaUidLupd;
	}

	@Override
	public int compareTo(TCkJobTruckAddAttr o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

}
