package com.guudint.clickargo.clictruck.master.model;
// Generated 14 Mar 2024, 6:38:26 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;
import com.vcc.camelone.master.model.TMstBank;
import com.vcc.camelone.master.model.TMstCurrency;

/**
 * TCkCtMstOpmRate generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_MST_OPM_RATE")
@Deprecated
public class TCkCtMstOpmRate extends COAbstractEntity<TCkCtMstOpmRate> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 2945375951380728378L;
	
	// Attributes
	/////////////
	private String opmrId;
	private TMstBank TMstBank;
	private TMstCurrency TMstCurrency;
	private Date opmrDtStart;
	private Date opmrDtEnd;
	private Double opmrPercentBank;
	private Double opmrPercentGli;
	private Integer opmrPaytermCo;
	private Integer opmrPaytermTo;
	private char opmrStatus;
	private Date opmrDtCreate;
	private String opmrUidCreate;
	private Date opmrDtLupd;
	private String opmrUidLupd;

	public TCkCtMstOpmRate() {
	}

	public TCkCtMstOpmRate(String opmrId, char opmrStatus) {
		this.opmrId = opmrId;
		this.opmrStatus = opmrStatus;
	}

	public TCkCtMstOpmRate(String opmrId, TMstBank TMstBank, TMstCurrency TMstCurrency, Date opmrDtStart,
			Date opmrDtEnd, Double opmrPercentBank, Double opmrPercentGli, Integer opmrPaytermCo, Integer opmrPaytermTo,
			char opmrStatus, Date opmrDtCreate, String opmrUidCreate, Date opmrDtLupd, String opmrUidLupd) {
		this.opmrId = opmrId;
		this.TMstBank = TMstBank;
		this.TMstCurrency = TMstCurrency;
		this.opmrDtStart = opmrDtStart;
		this.opmrDtEnd = opmrDtEnd;
		this.opmrPercentBank = opmrPercentBank;
		this.opmrPercentGli = opmrPercentGli;
		this.opmrPaytermCo = opmrPaytermCo;
		this.opmrPaytermTo = opmrPaytermTo;
		this.opmrStatus = opmrStatus;
		this.opmrDtCreate = opmrDtCreate;
		this.opmrUidCreate = opmrUidCreate;
		this.opmrDtLupd = opmrDtLupd;
		this.opmrUidLupd = opmrUidLupd;
	}

	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkCtMstOpmRate o) {
		return 0;
	}

	@Override
	public void init() {		
	}

	@Id

	@Column(name = "OPMR_ID", unique = true, nullable = false, length = 35)
	public String getOpmrId() {
		return this.opmrId;
	}

	public void setOpmrId(String opmrId) {
		this.opmrId = opmrId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OPMR_BANK")
	public TMstBank getTMstBank() {
		return this.TMstBank;
	}

	public void setTMstBank(TMstBank TMstBank) {
		this.TMstBank = TMstBank;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OPMR_CCY")
	public TMstCurrency getTMstCurrency() {
		return this.TMstCurrency;
	}

	public void setTMstCurrency(TMstCurrency TMstCurrency) {
		this.TMstCurrency = TMstCurrency;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OPMR_DT_START", length = 19)
	public Date getOpmrDtStart() {
		return this.opmrDtStart;
	}

	public void setOpmrDtStart(Date opmrDtStart) {
		this.opmrDtStart = opmrDtStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OPMR_DT_END", length = 19)
	public Date getOpmrDtEnd() {
		return this.opmrDtEnd;
	}

	public void setOpmrDtEnd(Date opmrDtEnd) {
		this.opmrDtEnd = opmrDtEnd;
	}

	@Column(name = "OPMR_PERCENT_BANK", precision = 15)
	public Double getOpmrPercentBank() {
		return this.opmrPercentBank;
	}

	public void setOpmrPercentBank(Double opmrPercentBank) {
		this.opmrPercentBank = opmrPercentBank;
	}

	@Column(name = "OPMR_PERCENT_GLI", precision = 15)
	public Double getOpmrPercentGli() {
		return this.opmrPercentGli;
	}

	public void setOpmrPercentGli(Double opmrPercentGli) {
		this.opmrPercentGli = opmrPercentGli;
	}

	@Column(name = "OPMR_PAYTERM_CO")
	public Integer getOpmrPaytermCo() {
		return this.opmrPaytermCo;
	}

	public void setOpmrPaytermCo(Integer opmrPaytermCo) {
		this.opmrPaytermCo = opmrPaytermCo;
	}

	@Column(name = "OPMR_PAYTERM_TO")
	public Integer getOpmrPaytermTo() {
		return this.opmrPaytermTo;
	}

	public void setOpmrPaytermTo(Integer opmrPaytermTo) {
		this.opmrPaytermTo = opmrPaytermTo;
	}

	@Column(name = "OPMR_STATUS", nullable = false, length = 1)
	public char getOpmrStatus() {
		return this.opmrStatus;
	}

	public void setOpmrStatus(char opmrStatus) {
		this.opmrStatus = opmrStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OPMR_DT_CREATE", length = 19)
	public Date getOpmrDtCreate() {
		return this.opmrDtCreate;
	}

	public void setOpmrDtCreate(Date opmrDtCreate) {
		this.opmrDtCreate = opmrDtCreate;
	}

	@Column(name = "OPMR_UID_CREATE", length = 35)
	public String getOpmrUidCreate() {
		return this.opmrUidCreate;
	}

	public void setOpmrUidCreate(String opmrUidCreate) {
		this.opmrUidCreate = opmrUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OPMR_DT_LUPD", length = 19)
	public Date getOpmrDtLupd() {
		return this.opmrDtLupd;
	}

	public void setOpmrDtLupd(Date opmrDtLupd) {
		this.opmrDtLupd = opmrDtLupd;
	}

	@Column(name = "OPMR_UID_LUPD", length = 35)
	public String getOpmrUidLupd() {
		return this.opmrUidLupd;
	}

	public void setOpmrUidLupd(String opmrUidLupd) {
		this.opmrUidLupd = opmrUidLupd;
	}

}
