package com.guudint.clickargo.clictruck.master.model;
// Generated 20 Oct 2023, 12:24:55 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtMstTripAttachType generated by hbm2java
 */
@Entity
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
@Table(name = "T_CK_CT_MST_TRIP_ATTACH_TYPE")
public class TCkCtMstTripAttachType extends COAbstractEntity<TCkCtMstTripAttachType> {

	private static final long serialVersionUID = -2637005432167544935L;
	private String atypId;
	private String atypName;
	private String atypDesc;
	private String atypDescOth;
	private Character atypStatus;
	private Date atypDtCreate;
	private String atypUidCreate;
	private Date atypDtLupd;
	private String atypUidLupd;

	public TCkCtMstTripAttachType() {
	}

	public TCkCtMstTripAttachType(String atypId, String atypName) {
		this.atypId = atypId;
		this.atypName = atypName;
	}

	public TCkCtMstTripAttachType(String atypId, String atypName, String atypDesc, String atypDescOth,
			Character atypStatus, Date atypDtCreate, String atypUidCreate, Date atypDtLupd, String atypUidLupd) {
		this.atypId = atypId;
		this.atypName = atypName;
		this.atypDesc = atypDesc;
		this.atypDescOth = atypDescOth;
		this.atypStatus = atypStatus;
		this.atypDtCreate = atypDtCreate;
		this.atypUidCreate = atypUidCreate;
		this.atypDtLupd = atypDtLupd;
		this.atypUidLupd = atypUidLupd;
	}

	@Id

	@Column(name = "ATYP_ID", unique = true, nullable = false, length = 35)
	public String getAtypId() {
		return this.atypId;
	}

	public void setAtypId(String atypId) {
		this.atypId = atypId;
	}

	@Column(name = "ATYP_NAME", nullable = false, length = 100)
	public String getAtypName() {
		return this.atypName;
	}

	public void setAtypName(String atypName) {
		this.atypName = atypName;
	}

	@Column(name = "ATYP_DESC")
	public String getAtypDesc() {
		return this.atypDesc;
	}

	public void setAtypDesc(String atypDesc) {
		this.atypDesc = atypDesc;
	}

	@Column(name = "ATYP_DESC_OTH", length = 512)
	public String getAtypDescOth() {
		return this.atypDescOth;
	}

	public void setAtypDescOth(String atypDescOth) {
		this.atypDescOth = atypDescOth;
	}

	@Column(name = "ATYP_STATUS", length = 1)
	public Character getAtypStatus() {
		return this.atypStatus;
	}

	public void setAtypStatus(Character atypStatus) {
		this.atypStatus = atypStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ATYP_DT_CREATE", length = 19)
	public Date getAtypDtCreate() {
		return this.atypDtCreate;
	}

	public void setAtypDtCreate(Date atypDtCreate) {
		this.atypDtCreate = atypDtCreate;
	}

	@Column(name = "ATYP_UID_CREATE", length = 35)
	public String getAtypUidCreate() {
		return this.atypUidCreate;
	}

	public void setAtypUidCreate(String atypUidCreate) {
		this.atypUidCreate = atypUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ATYP_DT_LUPD", length = 19)
	public Date getAtypDtLupd() {
		return this.atypDtLupd;
	}

	public void setAtypDtLupd(Date atypDtLupd) {
		this.atypDtLupd = atypDtLupd;
	}

	@Column(name = "ATYP_UID_LUPD", length = 35)
	public String getAtypUidLupd() {
		return this.atypUidLupd;
	}

	public void setAtypUidLupd(String atypUidLupd) {
		this.atypUidLupd = atypUidLupd;
	}

	@Override
	public int compareTo(TCkCtMstTripAttachType o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
