package com.guudint.clickargo.clictruck.master.model;
// Generated 23 Feb, 2023 4:00:19 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtMstToInvoiceState generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_MST_TO_INVOICE_STATE")
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
public class TCkCtMstToInvoiceState extends COAbstractEntity<TCkCtMstToInvoiceState> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -3140440903042282577L;
	
	// Attributes
	/////////////
	private String instId;
	private String instName;
	private String instDesc;
	private String instDescOth;
	private Character instStatus;
	private Date instDtCreate;
	private String instUidCreate;
	private Date instDtLupd;
	private String instUidLupd;

	// Constructors
	///////////////
	public TCkCtMstToInvoiceState() {
	}

	public TCkCtMstToInvoiceState(String instId, String instName) {
		this.instId = instId;
		this.instName = instName;
	}

	public TCkCtMstToInvoiceState(String instId, String instName, String instDesc, String instDescOth,
			Character instStatus, Date instDtCreate, String instUidCreate, Date instDtLupd, String instUidLupd) {
		this.instId = instId;
		this.instName = instName;
		this.instDesc = instDesc;
		this.instDescOth = instDescOth;
		this.instStatus = instStatus;
		this.instDtCreate = instDtCreate;
		this.instUidCreate = instUidCreate;
		this.instDtLupd = instDtLupd;
		this.instUidLupd = instUidLupd;
	}

	// Properties
	/////////////
	@Id
	@Column(name = "INST_ID", unique = true, nullable = false, length = 35)
	public String getInstId() {
		return this.instId;
	}

	public void setInstId(String instId) {
		this.instId = instId;
	}

	@Column(name = "INST_NAME", nullable = false, length = 100)
	public String getInstName() {
		return this.instName;
	}

	public void setInstName(String instName) {
		this.instName = instName;
	}

	@Column(name = "INST_DESC")
	public String getInstDesc() {
		return this.instDesc;
	}

	public void setInstDesc(String instDesc) {
		this.instDesc = instDesc;
	}

	@Column(name = "INST_DESC_OTH", length = 512)
	public String getInstDescOth() {
		return this.instDescOth;
	}

	public void setInstDescOth(String instDescOth) {
		this.instDescOth = instDescOth;
	}

	@Column(name = "INST_STATUS", length = 1)
	public Character getInstStatus() {
		return this.instStatus;
	}

	public void setInstStatus(Character instStatus) {
		this.instStatus = instStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INST_DT_CREATE", length = 19)
	@CreationTimestamp
	public Date getInstDtCreate() {
		return this.instDtCreate;
	}

	public void setInstDtCreate(Date instDtCreate) {
		this.instDtCreate = instDtCreate;
	}

	@Column(name = "INST_UID_CREATE", length = 35)
	public String getInstUidCreate() {
		return this.instUidCreate;
	}

	public void setInstUidCreate(String instUidCreate) {
		this.instUidCreate = instUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INST_DT_LUPD", length = 19)
	@UpdateTimestamp
	public Date getInstDtLupd() {
		return this.instDtLupd;
	}

	public void setInstDtLupd(Date instDtLupd) {
		this.instDtLupd = instDtLupd;
	}

	@Column(name = "INST_UID_LUPD", length = 35)
	public String getInstUidLupd() {
		return this.instUidLupd;
	}

	public void setInstUidLupd(String instUidLupd) {
		this.instUidLupd = instUidLupd;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	 */
	@Override
	public int compareTo(TCkCtMstToInvoiceState o) {
		// TODO Auto-generated method stub
		return 0;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 * 
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 * 
	 */
	@Override
	protected Object clone() throws CloneNotSupportedException {
		// TODO Auto-generated method stub
		return super.clone();
	}

	
}
