package com.guudint.clickargo.clictruck.master.model;
// Generated 14 Feb, 2023 12:17:14 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtMstRentalType generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_MST_RENTAL_TYPE")
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
public class TCkCtMstRentalType extends COAbstractEntity<TCkCtMstRentalType> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 4645847874117794054L;
	
	// Attributes
	/////////////
	private String rtId;
	private String rtName;
	private String rtDesc;
	private String rtDescOth;
	private Character rtStatus;
	private Date rtDtCreate;
	private String rtUidCreate;
	private Date rtDtLupd;
	private String rtUidLupd;

	// Constructors
	///////////////
	public TCkCtMstRentalType() {
	}

	public TCkCtMstRentalType(String rtId, String rtName) {
		this.rtId = rtId;
		this.rtName = rtName;
	}

	public TCkCtMstRentalType(String rtId, String rtName, String rtDesc, String rtDescOth, Character rtStatus,
			Date rtDtCreate, String rtUidCreate, Date rtDtLupd, String rtUidLupd) {
		this.rtId = rtId;
		this.rtName = rtName;
		this.rtDesc = rtDesc;
		this.rtDescOth = rtDescOth;
		this.rtStatus = rtStatus;
		this.rtDtCreate = rtDtCreate;
		this.rtUidCreate = rtUidCreate;
		this.rtDtLupd = rtDtLupd;
		this.rtUidLupd = rtUidLupd;
	}

	// Properties
	/////////////
	@Id
	@Column(name = "RT_ID", unique = true, nullable = false, length = 35)
	public String getRtId() {
		return this.rtId;
	}

	public void setRtId(String rtId) {
		this.rtId = rtId;
	}

	@Column(name = "RT_NAME", nullable = false, length = 100)
	public String getRtName() {
		return this.rtName;
	}

	public void setRtName(String rtName) {
		this.rtName = rtName;
	}

	@Column(name = "RT_DESC")
	public String getRtDesc() {
		return this.rtDesc;
	}

	public void setRtDesc(String rtDesc) {
		this.rtDesc = rtDesc;
	}

	@Column(name = "RT_DESC_OTH", length = 512)
	public String getRtDescOth() {
		return this.rtDescOth;
	}

	public void setRtDescOth(String rtDescOth) {
		this.rtDescOth = rtDescOth;
	}

	@Column(name = "RT_STATUS", length = 1)
	public Character getRtStatus() {
		return this.rtStatus;
	}

	public void setRtStatus(Character rtStatus) {
		this.rtStatus = rtStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RT_DT_CREATE", length = 19)
	@CreationTimestamp
	public Date getRtDtCreate() {
		return this.rtDtCreate;
	}

	public void setRtDtCreate(Date rtDtCreate) {
		this.rtDtCreate = rtDtCreate;
	}

	@Column(name = "RT_UID_CREATE", length = 35)
	public String getRtUidCreate() {
		return this.rtUidCreate;
	}

	public void setRtUidCreate(String rtUidCreate) {
		this.rtUidCreate = rtUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RT_DT_LUPD", length = 19)
	@UpdateTimestamp
	public Date getRtDtLupd() {
		return this.rtDtLupd;
	}

	public void setRtDtLupd(Date rtDtLupd) {
		this.rtDtLupd = rtDtLupd;
	}

	@Column(name = "RT_UID_LUPD", length = 35)
	public String getRtUidLupd() {
		return this.rtUidLupd;
	}

	public void setRtUidLupd(String rtUidLupd) {
		this.rtUidLupd = rtUidLupd;
	}

	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkCtMstRentalType o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

}
