package com.guudint.clickargo.clictruck.master.model;
// Generated 23 Feb, 2023 4:00:19 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.guudint.clickargo.clictruck.common.model.TCkCtLocation;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtMstCargoType generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_MST_CARGO_TYPE")
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
public class TCkCtMstCargoType extends COAbstractEntity<TCkCtLocation> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 7596532948027037380L;
	
	// Attributes
	/////////////
	private String crtypId;
	private String crtypName;
	private String crtypDesc;
	private String crtypDescOth;
	private int crtypSeq;
	private Character crtypStatus;
	private Date crtypDtCreate;
	private String crtypUidCreate;
	private Date crtypDtLupd;
	private String crtypUidLupd;

	// Constructors
	///////////////
	public TCkCtMstCargoType() {
	}

	public TCkCtMstCargoType(String crtypId) {
		this.crtypId = crtypId;
	}

	public TCkCtMstCargoType(String crtypId, String crtypName) {
		this.crtypId = crtypId;
		this.crtypName = crtypName;
	}

	public TCkCtMstCargoType(String crtypId, String crtypName, String crtypDesc, String crtypDescOth,
			Character crtypStatus, Date crtypDtCreate, String crtypUidCreate, Date crtypDtLupd, String crtypUidLupd) {
		this.crtypId = crtypId;
		this.crtypName = crtypName;
		this.crtypDesc = crtypDesc;
		this.crtypDescOth = crtypDescOth;
		this.crtypStatus = crtypStatus;
		this.crtypDtCreate = crtypDtCreate;
		this.crtypUidCreate = crtypUidCreate;
		this.crtypDtLupd = crtypDtLupd;
		this.crtypUidLupd = crtypUidLupd;
	}

	// Properties
	/////////////
	@Id
	@Column(name = "CRTYP_ID", unique = true, nullable = false, length = 35)
	public String getCrtypId() {
		return this.crtypId;
	}

	public void setCrtypId(String crtypId) {
		this.crtypId = crtypId;
	}

	@Column(name = "CRTYP_NAME", nullable = false, length = 100)
	public String getCrtypName() {
		return this.crtypName;
	}

	public void setCrtypName(String crtypName) {
		this.crtypName = crtypName;
	}

	@Column(name = "CRTYP_DESC")
	public String getCrtypDesc() {
		return this.crtypDesc;
	}

	public void setCrtypDesc(String crtypDesc) {
		this.crtypDesc = crtypDesc;
	}

	@Column(name = "CRTYP_DESC_OTH", length = 512)
	public String getCrtypDescOth() {
		return this.crtypDescOth;
	}

	public void setCrtypDescOth(String crtypDescOth) {
		this.crtypDescOth = crtypDescOth;
	}

	@Column(name = "CRTYP_SEQ")
	public int getCrtypSeq() {
		return crtypSeq;
	}

	public void setCrtypSeq(int crtypSeq) {
		this.crtypSeq = crtypSeq;
	}

	@Column(name = "CRTYP_STATUS", length = 1)
	public Character getCrtypStatus() {
		return this.crtypStatus;
	}

	public void setCrtypStatus(Character crtypStatus) {
		this.crtypStatus = crtypStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTYP_DT_CREATE", length = 19)
	@CreationTimestamp
	public Date getCrtypDtCreate() {
		return this.crtypDtCreate;
	}

	public void setCrtypDtCreate(Date crtypDtCreate) {
		this.crtypDtCreate = crtypDtCreate;
	}

	@Column(name = "CRTYP_UID_CREATE", length = 35)
	public String getCrtypUidCreate() {
		return this.crtypUidCreate;
	}

	public void setCrtypUidCreate(String crtypUidCreate) {
		this.crtypUidCreate = crtypUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTYP_DT_LUPD", length = 19)
	@UpdateTimestamp
	public Date getCrtypDtLupd() {
		return this.crtypDtLupd;
	}

	public void setCrtypDtLupd(Date crtypDtLupd) {
		this.crtypDtLupd = crtypDtLupd;
	}

	@Column(name = "CRTYP_UID_LUPD", length = 35)
	public String getCrtypUidLupd() {
		return this.crtypUidLupd;
	}

	public void setCrtypUidLupd(String crtypUidLupd) {
		this.crtypUidLupd = crtypUidLupd;
	}

	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkCtLocation o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

}
