package com.guudint.clickargo.clictruck.master.model;
// Generated 14 Feb, 2023 12:17:14 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtMstLocationType generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_MST_LOCATION_TYPE")
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
public class TCkCtMstLocationType extends COAbstractEntity<TCkCtMstLocationType> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 2945375951380728378L;
	
	// Attributes
	/////////////
	private String lctyId;
	private String lctyName;
	private String lctyDesc;
	private String lctyDescOth;
	private Character lctyStatus;
	private Date lctyDtCreate;
	private String lctyUidCreate;
	private Date lctyDtLupd;
	private String lctyUidLupd;

	// Constructors
	///////////////
	public TCkCtMstLocationType() {
	}

	public TCkCtMstLocationType(String lctyId, String lctyName) {
		this.lctyId = lctyId;
		this.lctyName = lctyName;
	}

	public TCkCtMstLocationType(String lctyId, String lctyName, String lctyDesc, String lctyDescOth,
			Character lctyStatus, Date lctyDtCreate, String lctyUidCreate, Date lctyDtLupd, String lctyUidLupd) {
		this.lctyId = lctyId;
		this.lctyName = lctyName;
		this.lctyDesc = lctyDesc;
		this.lctyDescOth = lctyDescOth;
		this.lctyStatus = lctyStatus;
		this.lctyDtCreate = lctyDtCreate;
		this.lctyUidCreate = lctyUidCreate;
		this.lctyDtLupd = lctyDtLupd;
		this.lctyUidLupd = lctyUidLupd;
	}

	// Properties
	/////////////
	@Id
	@Column(name = "LCTY_ID", unique = true, nullable = false, length = 35)
	public String getLctyId() {
		return this.lctyId;
	}

	public void setLctyId(String lctyId) {
		this.lctyId = lctyId;
	}

	@Column(name = "LCTY_NAME", nullable = false, length = 100)
	public String getLctyName() {
		return this.lctyName;
	}

	public void setLctyName(String lctyName) {
		this.lctyName = lctyName;
	}

	@Column(name = "LCTY_DESC")
	public String getLctyDesc() {
		return this.lctyDesc;
	}

	public void setLctyDesc(String lctyDesc) {
		this.lctyDesc = lctyDesc;
	}

	@Column(name = "LCTY_DESC_OTH", length = 512)
	public String getLctyDescOth() {
		return this.lctyDescOth;
	}

	public void setLctyDescOth(String lctyDescOth) {
		this.lctyDescOth = lctyDescOth;
	}

	@Column(name = "LCTY_STATUS", length = 1)
	public Character getLctyStatus() {
		return this.lctyStatus;
	}

	public void setLctyStatus(Character lctyStatus) {
		this.lctyStatus = lctyStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LCTY_DT_CREATE", length = 19)
	@CreationTimestamp
	public Date getLctyDtCreate() {
		return this.lctyDtCreate;
	}

	public void setLctyDtCreate(Date lctyDtCreate) {
		this.lctyDtCreate = lctyDtCreate;
	}

	@Column(name = "LCTY_UID_CREATE", length = 35)
	public String getLctyUidCreate() {
		return this.lctyUidCreate;
	}

	public void setLctyUidCreate(String lctyUidCreate) {
		this.lctyUidCreate = lctyUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LCTY_DT_LUPD", length = 19)
	@UpdateTimestamp
	public Date getLctyDtLupd() {
		return this.lctyDtLupd;
	}

	public void setLctyDtLupd(Date lctyDtLupd) {
		this.lctyDtLupd = lctyDtLupd;
	}

	@Column(name = "LCTY_UID_LUPD", length = 35)
	public String getLctyUidLupd() {
		return this.lctyUidLupd;
	}

	public void setLctyUidLupd(String lctyUidLupd) {
		this.lctyUidLupd = lctyUidLupd;
	}

	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkCtMstLocationType o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

}
