package com.guudint.clickargo.clictruck.master.model;
// Generated 23 Feb, 2023 4:00:19 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtMstReimbursementType generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_MST_REIMBURSEMENT_TYPE")
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
public class TCkCtMstReimbursementType extends COAbstractEntity<TCkCtMstReimbursementType> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 2911051016896233918L;
	
	// Attributes
	/////////////
	private String rbtypId;
	private String rbtypName;
	private String rbtypDesc;
	private String rbtypDescOth;
	private Character rbtypStatus;
	private Date rbtypDtCreate;
	private String rbtypUidCreate;
	private Date rbtypDtLupd;
	private String rbtypUidLupd;

	// Constructors
	///////////////
	public TCkCtMstReimbursementType() {
	}

	public TCkCtMstReimbursementType(String rbtypId, String rbtypName) {
		this.rbtypId = rbtypId;
		this.rbtypName = rbtypName;
	}

	public TCkCtMstReimbursementType(String rbtypId, String rbtypName, String rbtypDesc, String rbtypDescOth,
			Character rbtypStatus, Date rbtypDtCreate, String rbtypUidCreate, Date rbtypDtLupd, String rbtypUidLupd) {
		this.rbtypId = rbtypId;
		this.rbtypName = rbtypName;
		this.rbtypDesc = rbtypDesc;
		this.rbtypDescOth = rbtypDescOth;
		this.rbtypStatus = rbtypStatus;
		this.rbtypDtCreate = rbtypDtCreate;
		this.rbtypUidCreate = rbtypUidCreate;
		this.rbtypDtLupd = rbtypDtLupd;
		this.rbtypUidLupd = rbtypUidLupd;
	}

	// Properties
	/////////////
	@Id
	@Column(name = "RBTYP_ID", unique = true, nullable = false, length = 35)
	public String getRbtypId() {
		return this.rbtypId;
	}

	public void setRbtypId(String rbtypId) {
		this.rbtypId = rbtypId;
	}

	@Column(name = "RBTYP_NAME", nullable = false, length = 100)
	public String getRbtypName() {
		return this.rbtypName;
	}

	public void setRbtypName(String rbtypName) {
		this.rbtypName = rbtypName;
	}

	@Column(name = "RBTYP_DESC")
	public String getRbtypDesc() {
		return this.rbtypDesc;
	}

	public void setRbtypDesc(String rbtypDesc) {
		this.rbtypDesc = rbtypDesc;
	}

	@Column(name = "RBTYP_DESC_OTH", length = 512)
	public String getRbtypDescOth() {
		return this.rbtypDescOth;
	}

	public void setRbtypDescOth(String rbtypDescOth) {
		this.rbtypDescOth = rbtypDescOth;
	}

	@Column(name = "RBTYP_STATUS", length = 1)
	public Character getRbtypStatus() {
		return this.rbtypStatus;
	}

	public void setRbtypStatus(Character rbtypStatus) {
		this.rbtypStatus = rbtypStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RBTYP_DT_CREATE", length = 19)
	@CreationTimestamp
	public Date getRbtypDtCreate() {
		return this.rbtypDtCreate;
	}

	public void setRbtypDtCreate(Date rbtypDtCreate) {
		this.rbtypDtCreate = rbtypDtCreate;
	}

	@Column(name = "RBTYP_UID_CREATE", length = 35)
	public String getRbtypUidCreate() {
		return this.rbtypUidCreate;
	}

	public void setRbtypUidCreate(String rbtypUidCreate) {
		this.rbtypUidCreate = rbtypUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RBTYP_DT_LUPD", length = 19)
	@UpdateTimestamp
	public Date getRbtypDtLupd() {
		return this.rbtypDtLupd;
	}

	public void setRbtypDtLupd(Date rbtypDtLupd) {
		this.rbtypDtLupd = rbtypDtLupd;
	}

	@Column(name = "RBTYP_UID_LUPD", length = 35)
	public String getRbtypUidLupd() {
		return this.rbtypUidLupd;
	}

	public void setRbtypUidLupd(String rbtypUidLupd) {
		this.rbtypUidLupd = rbtypUidLupd;
	}

	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkCtMstReimbursementType o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

}
