package com.guudint.clickargo.clictruck.master.model;
// Generated 14 Feb, 2023 12:17:14 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtMstVehType generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_MST_VEH_TYPE")
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
public class TCkCtMstVehType extends COAbstractEntity<TCkCtMstVehType> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 204693660657977235L;
	
	// Attributes
	/////////////
	private String vhtyId;
	private String vhtyName;
	private String vhtyDesc;
	private String vhtyDescOth;
	private Character vhtyStatus;
	private Date vhtyDtCreate;
	private String vhtyUidCreate;
	private Date vhtyDtLupd;
	private String vhtyUidLupd;

	// Constructors
	///////////////
	public TCkCtMstVehType() {
	}

	public TCkCtMstVehType(String vhtyId, String vhtyName) {
		this.vhtyId = vhtyId;
		this.vhtyName = vhtyName;
	}

	public TCkCtMstVehType(String vhtyId, String vhtyName, String vhtyDesc, String vhtyDescOth, Character vhtyStatus,
			Date vhtyDtCreate, String vhtyUidCreate, Date vhtyDtLupd, String vhtyUidLupd) {
		this.vhtyId = vhtyId;
		this.vhtyName = vhtyName;
		this.vhtyDesc = vhtyDesc;
		this.vhtyDescOth = vhtyDescOth;
		this.vhtyStatus = vhtyStatus;
		this.vhtyDtCreate = vhtyDtCreate;
		this.vhtyUidCreate = vhtyUidCreate;
		this.vhtyDtLupd = vhtyDtLupd;
		this.vhtyUidLupd = vhtyUidLupd;
	}

	// Properties
	/////////////
	@Id
	@Column(name = "VHTY_ID", unique = true, nullable = false, length = 35)
	public String getVhtyId() {
		return this.vhtyId;
	}

	public void setVhtyId(String vhtyId) {
		this.vhtyId = vhtyId;
	}

	@Column(name = "VHTY_NAME", nullable = false, length = 100)
	public String getVhtyName() {
		return this.vhtyName;
	}

	public void setVhtyName(String vhtyName) {
		this.vhtyName = vhtyName;
	}

	@Column(name = "VHTY_DESC")
	public String getVhtyDesc() {
		return this.vhtyDesc;
	}

	public void setVhtyDesc(String vhtyDesc) {
		this.vhtyDesc = vhtyDesc;
	}

	@Column(name = "VHTY_DESC_OTH", length = 512)
	public String getVhtyDescOth() {
		return this.vhtyDescOth;
	}

	public void setVhtyDescOth(String vhtyDescOth) {
		this.vhtyDescOth = vhtyDescOth;
	}

	@Column(name = "VHTY_STATUS", length = 1)
	public Character getVhtyStatus() {
		return this.vhtyStatus;
	}

	public void setVhtyStatus(Character vhtyStatus) {
		this.vhtyStatus = vhtyStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VHTY_DT_CREATE", length = 19)
	@CreationTimestamp
	public Date getVhtyDtCreate() {
		return this.vhtyDtCreate;
	}

	public void setVhtyDtCreate(Date vhtyDtCreate) {
		this.vhtyDtCreate = vhtyDtCreate;
	}

	@Column(name = "VHTY_UID_CREATE", length = 35)
	public String getVhtyUidCreate() {
		return this.vhtyUidCreate;
	}

	public void setVhtyUidCreate(String vhtyUidCreate) {
		this.vhtyUidCreate = vhtyUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VHTY_DT_LUPD", length = 19)
	@UpdateTimestamp
	public Date getVhtyDtLupd() {
		return this.vhtyDtLupd;
	}

	public void setVhtyDtLupd(Date vhtyDtLupd) {
		this.vhtyDtLupd = vhtyDtLupd;
	}

	@Column(name = "VHTY_UID_LUPD", length = 35)
	public String getVhtyUidLupd() {
		return this.vhtyUidLupd;
	}

	public void setVhtyUidLupd(String vhtyUidLupd) {
		this.vhtyUidLupd = vhtyUidLupd;
	}

	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkCtMstVehType o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

}
