package com.guudint.clickargo.clictruck.master.model;
// Generated 14 Feb, 2023 12:17:14 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.guudint.clickargo.clictruck.common.model.TCkCtVeh;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtMstVehState generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_MST_VEH_STATE")
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
public class TCkCtMstVehState extends COAbstractEntity<TCkCtMstVehState> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 1133238725830969293L;
	
	// Attributes
	/////////////
	private String vhstId;
	private String vhstName;
	private String vhstDesc;
	private String vhstDescOth;
	private Character vhstStatus;
	private Date vhstDtCreate;
	private String vhstUidCreate;
	private Date vhstDtLupd;
	private String vhstUidLupd;
	private Set<TCkCtVeh> TCkCtVehs = new HashSet<TCkCtVeh>(0);

	// Constructors
	///////////////
	public TCkCtMstVehState() {
	}

	public TCkCtMstVehState(String vhstId, String vhstName) {
		this.vhstId = vhstId;
		this.vhstName = vhstName;
	}

	public TCkCtMstVehState(String vhstId, String vhstName, String vhstDesc, String vhstDescOth, Character vhstStatus,
			Date vhstDtCreate, String vhstUidCreate, Date vhstDtLupd, String vhstUidLupd, Set<TCkCtVeh> TCkCtVehs) {
		this.vhstId = vhstId;
		this.vhstName = vhstName;
		this.vhstDesc = vhstDesc;
		this.vhstDescOth = vhstDescOth;
		this.vhstStatus = vhstStatus;
		this.vhstDtCreate = vhstDtCreate;
		this.vhstUidCreate = vhstUidCreate;
		this.vhstDtLupd = vhstDtLupd;
		this.vhstUidLupd = vhstUidLupd;
		this.TCkCtVehs = TCkCtVehs;
	}

	// Properties
	/////////////
	@Id
	@Column(name = "VHST_ID", unique = true, nullable = false, length = 35)
	public String getVhstId() {
		return this.vhstId;
	}

	public void setVhstId(String vhstId) {
		this.vhstId = vhstId;
	}

	@Column(name = "VHST_NAME", nullable = false, length = 100)
	public String getVhstName() {
		return this.vhstName;
	}

	public void setVhstName(String vhstName) {
		this.vhstName = vhstName;
	}

	@Column(name = "VHST_DESC")
	public String getVhstDesc() {
		return this.vhstDesc;
	}

	public void setVhstDesc(String vhstDesc) {
		this.vhstDesc = vhstDesc;
	}

	@Column(name = "VHST_DESC_OTH", length = 512)
	public String getVhstDescOth() {
		return this.vhstDescOth;
	}

	public void setVhstDescOth(String vhstDescOth) {
		this.vhstDescOth = vhstDescOth;
	}

	@Column(name = "VHST_STATUS", length = 1)
	public Character getVhstStatus() {
		return this.vhstStatus;
	}

	public void setVhstStatus(Character vhstStatus) {
		this.vhstStatus = vhstStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VHST_DT_CREATE", length = 19)
	@CreationTimestamp
	public Date getVhstDtCreate() {
		return this.vhstDtCreate;
	}

	public void setVhstDtCreate(Date vhstDtCreate) {
		this.vhstDtCreate = vhstDtCreate;
	}

	@Column(name = "VHST_UID_CREATE", length = 35)
	public String getVhstUidCreate() {
		return this.vhstUidCreate;
	}

	public void setVhstUidCreate(String vhstUidCreate) {
		this.vhstUidCreate = vhstUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VHST_DT_LUPD", length = 19)
	@UpdateTimestamp
	public Date getVhstDtLupd() {
		return this.vhstDtLupd;
	}

	public void setVhstDtLupd(Date vhstDtLupd) {
		this.vhstDtLupd = vhstDtLupd;
	}

	@Column(name = "VHST_UID_LUPD", length = 35)
	public String getVhstUidLupd() {
		return this.vhstUidLupd;
	}

	public void setVhstUidLupd(String vhstUidLupd) {
		this.vhstUidLupd = vhstUidLupd;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TCkCtMstVehState")
	public Set<TCkCtVeh> getTCkCtVehs() {
		return this.TCkCtVehs;
	}

	public void setTCkCtVehs(Set<TCkCtVeh> TCkCtVehs) {
		this.TCkCtVehs = TCkCtVehs;
	}

	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkCtMstVehState o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

}
