package com.guudint.clickargo.clictruck.master.model;
// Generated 14 Feb, 2023 12:17:14 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtMstChassisType generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_MST_CHASSIS_TYPE")
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
public class TCkCtMstChassisType extends COAbstractEntity<TCkCtMstChassisType> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 6229192243660220457L;
	
	// Attributes
	/////////////
	private String chtyId;
	private String chtyName;
	private String chtyDesc;
	private String chtyDescOth;
	private Character chtyStatus;
	private Date chtyDtCreate;
	private String chtyUidCreate;
	private Date chtyDtLupd;
	private String chtyUidLupd;

	// Constructors
	///////////////
	public TCkCtMstChassisType() {
	}

	public TCkCtMstChassisType(String chtyId, String chtyName) {
		this.chtyId = chtyId;
		this.chtyName = chtyName;
	}

	public TCkCtMstChassisType(String chtyId, String chtyName, String chtyDesc, String chtyDescOth,
			Character chtyStatus, Date chtyDtCreate, String chtyUidCreate, Date chtyDtLupd, String chtyUidLupd) {
		this.chtyId = chtyId;
		this.chtyName = chtyName;
		this.chtyDesc = chtyDesc;
		this.chtyDescOth = chtyDescOth;
		this.chtyStatus = chtyStatus;
		this.chtyDtCreate = chtyDtCreate;
		this.chtyUidCreate = chtyUidCreate;
		this.chtyDtLupd = chtyDtLupd;
		this.chtyUidLupd = chtyUidLupd;
	}

	// Properties
	/////////////
	@Id
	@Column(name = "CHTY_ID", unique = true, nullable = false, length = 35)
	public String getChtyId() {
		return this.chtyId;
	}

	public void setChtyId(String chtyId) {
		this.chtyId = chtyId;
	}

	@Column(name = "CHTY_NAME", nullable = false, length = 100)
	public String getChtyName() {
		return this.chtyName;
	}

	public void setChtyName(String chtyName) {
		this.chtyName = chtyName;
	}

	@Column(name = "CHTY_DESC")
	public String getChtyDesc() {
		return this.chtyDesc;
	}

	public void setChtyDesc(String chtyDesc) {
		this.chtyDesc = chtyDesc;
	}

	@Column(name = "CHTY_DESC_OTH", length = 512)
	public String getChtyDescOth() {
		return this.chtyDescOth;
	}

	public void setChtyDescOth(String chtyDescOth) {
		this.chtyDescOth = chtyDescOth;
	}

	@Column(name = "CHTY_STATUS", length = 1)
	public Character getChtyStatus() {
		return this.chtyStatus;
	}

	public void setChtyStatus(Character chtyStatus) {
		this.chtyStatus = chtyStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CHTY_DT_CREATE", length = 19)
	@CreationTimestamp
	public Date getChtyDtCreate() {
		return this.chtyDtCreate;
	}

	public void setChtyDtCreate(Date chtyDtCreate) {
		this.chtyDtCreate = chtyDtCreate;
	}

	@Column(name = "CHTY_UID_CREATE", length = 35)
	public String getChtyUidCreate() {
		return this.chtyUidCreate;
	}

	public void setChtyUidCreate(String chtyUidCreate) {
		this.chtyUidCreate = chtyUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CHTY_DT_LUPD", length = 19)
	@UpdateTimestamp
	public Date getChtyDtLupd() {
		return this.chtyDtLupd;
	}

	public void setChtyDtLupd(Date chtyDtLupd) {
		this.chtyDtLupd = chtyDtLupd;
	}

	@Column(name = "CHTY_UID_LUPD", length = 35)
	public String getChtyUidLupd() {
		return this.chtyUidLupd;
	}

	public void setChtyUidLupd(String chtyUidLupd) {
		this.chtyUidLupd = chtyUidLupd;
	}

	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkCtMstChassisType o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

}
