package com.guudint.clickargo.clictruck.master.model;
// Generated 23 Feb, 2023 4:00:19 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.guudint.clickargo.clictruck.common.model.TCkCtLocation;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtMstDebitNoteState generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_MST_DEBIT_NOTE_STATE")
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
public class TCkCtMstDebitNoteState extends COAbstractEntity<TCkCtLocation> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 4596579052392595077L;
	
	// Attributes
	/////////////
	private String dnstId;
	private String dnstName;
	private String dnstDesc;
	private String dnstDescOth;
	private Character dnstStatus;
	private Date dnstDtCreate;
	private String dnstUidCreate;
	private Date dnstDtLupd;
	private String dnstUidLupd;

	// Constructors
	///////////////
	public TCkCtMstDebitNoteState() {
	}

	public TCkCtMstDebitNoteState(String dnstId, String dnstName) {
		this.dnstId = dnstId;
		this.dnstName = dnstName;
	}

	public TCkCtMstDebitNoteState(String dnstId, String dnstName, String dnstDesc, String dnstDescOth,
			Character dnstStatus, Date dnstDtCreate, String dnstUidCreate, Date dnstDtLupd, String dnstUidLupd) {
		this.dnstId = dnstId;
		this.dnstName = dnstName;
		this.dnstDesc = dnstDesc;
		this.dnstDescOth = dnstDescOth;
		this.dnstStatus = dnstStatus;
		this.dnstDtCreate = dnstDtCreate;
		this.dnstUidCreate = dnstUidCreate;
		this.dnstDtLupd = dnstDtLupd;
		this.dnstUidLupd = dnstUidLupd;
	}

	// Properties
	/////////////
	@Id
	@Column(name = "DNST_ID", unique = true, nullable = false, length = 35)
	public String getDnstId() {
		return this.dnstId;
	}

	public void setDnstId(String dnstId) {
		this.dnstId = dnstId;
	}

	@Column(name = "DNST_NAME", nullable = false, length = 100)
	public String getDnstName() {
		return this.dnstName;
	}

	public void setDnstName(String dnstName) {
		this.dnstName = dnstName;
	}

	@Column(name = "DNST_DESC")
	public String getDnstDesc() {
		return this.dnstDesc;
	}

	public void setDnstDesc(String dnstDesc) {
		this.dnstDesc = dnstDesc;
	}

	@Column(name = "DNST_DESC_OTH", length = 512)
	public String getDnstDescOth() {
		return this.dnstDescOth;
	}

	public void setDnstDescOth(String dnstDescOth) {
		this.dnstDescOth = dnstDescOth;
	}

	@Column(name = "DNST_STATUS", length = 1)
	public Character getDnstStatus() {
		return this.dnstStatus;
	}

	public void setDnstStatus(Character dnstStatus) {
		this.dnstStatus = dnstStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DNST_DT_CREATE", length = 19)
	@CreationTimestamp
	public Date getDnstDtCreate() {
		return this.dnstDtCreate;
	}

	public void setDnstDtCreate(Date dnstDtCreate) {
		this.dnstDtCreate = dnstDtCreate;
	}

	@Column(name = "DNST_UID_CREATE", length = 35)
	public String getDnstUidCreate() {
		return this.dnstUidCreate;
	}

	public void setDnstUidCreate(String dnstUidCreate) {
		this.dnstUidCreate = dnstUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DNST_DT_LUPD", length = 19)
	@UpdateTimestamp
	public Date getDnstDtLupd() {
		return this.dnstDtLupd;
	}

	public void setDnstDtLupd(Date dnstDtLupd) {
		this.dnstDtLupd = dnstDtLupd;
	}

	@Column(name = "DNST_UID_LUPD", length = 35)
	public String getDnstUidLupd() {
		return this.dnstUidLupd;
	}

	public void setDnstUidLupd(String dnstUidLupd) {
		this.dnstUidLupd = dnstUidLupd;
	}

	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkCtLocation o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

}
