package com.guudint.clickargo.clictruck.master.model;
// Generated 20 Oct 2023, 4:45:13 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtMstPartyType generated by hbm2java
 */
@Entity
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
@Table(name = "T_CK_CT_MST_PARTY_TYPE")
public class TCkCtMstPartyType extends COAbstractEntity<TCkCtMstPartyType> {

	private static final long serialVersionUID = -1210290748691873720L;
	private String ptId;
	private String ptName;
	private String ptDesc;
	private String ptDescOth;
	private Character ptStatus;
	private Date ptDtCreate;
	private String ptUidCreate;
	private Date ptDtLupd;
	private String ptUidLupd;

	public TCkCtMstPartyType() {
	}

	public TCkCtMstPartyType(String ptId) {
		this.ptId = ptId;
	}

	public TCkCtMstPartyType(String ptId, String ptName, String ptDesc, String ptDescOth, Character ptStatus,
			Date ptDtCreate, String ptUidCreate, Date ptDtLupd, String ptUidLupd) {
		this.ptId = ptId;
		this.ptName = ptName;
		this.ptDesc = ptDesc;
		this.ptDescOth = ptDescOth;
		this.ptStatus = ptStatus;
		this.ptDtCreate = ptDtCreate;
		this.ptUidCreate = ptUidCreate;
		this.ptDtLupd = ptDtLupd;
		this.ptUidLupd = ptUidLupd;
	}

	@Id

	@Column(name = "PT_ID", unique = true, nullable = false, length = 35)
	public String getPtId() {
		return this.ptId;
	}

	public void setPtId(String ptId) {
		this.ptId = ptId;
	}

	@Column(name = "PT_NAME", nullable = false, length = 100)
	public String getPtName() {
		return this.ptName;
	}

	public void setPtName(String ptName) {
		this.ptName = ptName;
	}

	@Column(name = "PT_DESC")
	public String getPtDesc() {
		return this.ptDesc;
	}

	public void setPtDesc(String ptDesc) {
		this.ptDesc = ptDesc;
	}

	@Column(name = "PT_DESC_OTH", length = 512)
	public String getPtDescOth() {
		return this.ptDescOth;
	}

	public void setPtDescOth(String ptDescOth) {
		this.ptDescOth = ptDescOth;
	}

	@Column(name = "PT_STATUS", length = 1)
	public Character getPtStatus() {
		return this.ptStatus;
	}

	public void setPtStatus(Character ptStatus) {
		this.ptStatus = ptStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PT_DT_CREATE", length = 19)
	public Date getPtDtCreate() {
		return this.ptDtCreate;
	}

	public void setPtDtCreate(Date ptDtCreate) {
		this.ptDtCreate = ptDtCreate;
	}

	@Column(name = "PT_UID_CREATE", length = 35)
	public String getPtUidCreate() {
		return this.ptUidCreate;
	}

	public void setPtUidCreate(String ptUidCreate) {
		this.ptUidCreate = ptUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PT_DT_LUPD", length = 19)
	public Date getPtDtLupd() {
		return this.ptDtLupd;
	}

	public void setPtDtLupd(Date ptDtLupd) {
		this.ptDtLupd = ptDtLupd;
	}

	@Column(name = "PT_UID_LUPD", length = 35)
	public String getPtUidLupd() {
		return this.ptUidLupd;
	}

	public void setPtUidLupd(String ptUidLupd) {
		this.ptUidLupd = ptUidLupd;
	}

	@Override
	public int compareTo(TCkCtMstPartyType o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

}
