package com.guudint.clickargo.clictruck.master.model;
// Generated 29 Aug 2023, 4:36:48 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtMstTrackDeviceState generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_MST_TRACK_DEVICE_STATE")
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
public class TCkCtMstTrackDeviceState extends COAbstractEntity<TCkCtMstTrackDeviceState> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -1L;
	
	private String tdsId;
	private String tdsName;
	private String tdsDesc;
	private String tdsDescOth;
	private Character tdsStatus;
	private Date tdsDtCreate;
	private String tdsUidCreate;
	private Date tdsDtLupd;
	private String tdsUidLupd;

	// Constructors
	///////////////
	public TCkCtMstTrackDeviceState() {
	}

	public TCkCtMstTrackDeviceState(String tdsId, String tdsName) {
		this.tdsId = tdsId;
		this.tdsName = tdsName;
	}

	public TCkCtMstTrackDeviceState(String tdsId, String tdsName, String tdsDesc, String tdsDescOth,
			Character tdsStatus, Date tdsDtCreate, String tdsUidCreate, Date tdsDtLupd, String tdsUidLupd) {
		this.tdsId = tdsId;
		this.tdsName = tdsName;
		this.tdsDesc = tdsDesc;
		this.tdsDescOth = tdsDescOth;
		this.tdsStatus = tdsStatus;
		this.tdsDtCreate = tdsDtCreate;
		this.tdsUidCreate = tdsUidCreate;
		this.tdsDtLupd = tdsDtLupd;
		this.tdsUidLupd = tdsUidLupd;
	}

	// Override Methods
	///////////////////
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	 */
	@Override
	public int compareTo(TCkCtMstTrackDeviceState o) {
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 * 
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}
	
	@Id
	@Column(name = "TDS_ID", unique = true, nullable = false, length = 35)
	public String getTdsId() {
		return this.tdsId;
	}

	public void setTdsId(String tdsId) {
		this.tdsId = tdsId;
	}

	@Column(name = "TDS_NAME", nullable = false, length = 100)
	public String getTdsName() {
		return this.tdsName;
	}

	public void setTdsName(String tdsName) {
		this.tdsName = tdsName;
	}

	@Column(name = "TDS_DESC")
	public String getTdsDesc() {
		return this.tdsDesc;
	}

	public void setTdsDesc(String tdsDesc) {
		this.tdsDesc = tdsDesc;
	}

	@Column(name = "TDS_DESC_OTH", length = 512)
	public String getTdsDescOth() {
		return this.tdsDescOth;
	}

	public void setTdsDescOth(String tdsDescOth) {
		this.tdsDescOth = tdsDescOth;
	}

	@Column(name = "TDS_STATUS", length = 1)
	public Character getTdsStatus() {
		return this.tdsStatus;
	}

	public void setTdsStatus(Character tdsStatus) {
		this.tdsStatus = tdsStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TDS_DT_CREATE", length = 19)
	public Date getTdsDtCreate() {
		return this.tdsDtCreate;
	}

	public void setTdsDtCreate(Date tdsDtCreate) {
		this.tdsDtCreate = tdsDtCreate;
	}

	@Column(name = "TDS_UID_CREATE", length = 35)
	public String getTdsUidCreate() {
		return this.tdsUidCreate;
	}

	public void setTdsUidCreate(String tdsUidCreate) {
		this.tdsUidCreate = tdsUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TDS_DT_LUPD", length = 19)
	public Date getTdsDtLupd() {
		return this.tdsDtLupd;
	}

	public void setTdsDtLupd(Date tdsDtLupd) {
		this.tdsDtLupd = tdsDtLupd;
	}

	@Column(name = "TDS_UID_LUPD", length = 35)
	public String getTdsUidLupd() {
		return this.tdsUidLupd;
	}

	public void setTdsUidLupd(String tdsUidLupd) {
		this.tdsUidLupd = tdsUidLupd;
	}

}
