DROP TABLE IF EXISTS `T_CK_JOB_TRUCK`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `T_CK_JOB_TRUCK` (
  `JOB_ID` varchar(35) NOT NULL COMMENT 'JOB ID - UUID',
  `JOB_PARENT` varchar(35) NOT NULL COMMENT 'JOB PARENT - REFERENCE T_CK_JOB:JOB_ID',
  `SHIPMENT_REF` varchar(255) DEFAULT NULL COMMENT 'TRUCK SHIPMENT REFERENCE',
  `CUSTOMER_REF` varchar(255) DEFAULT NULL COMMENT 'TRUCK CUSTOMER REFERENCE',
  `JOB_STATUS` char(1) DEFAULT NULL COMMENT 'RECORD STATUS - A : I',    
  `JOB_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `JOB_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `JOB_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `JOB_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`JOB_ID`),
  KEY `FK_CK_JOB_TRUCK_CK_JOB` (`JOB_PARENT`),
  CONSTRAINT `FK_CK_JOB_TRUCK_CK_JOB` FOREIGN KEY (`JOB_PARENT`) REFERENCES `T_CK_JOB` (`JOB_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='TRUCK JOB TABLE';
/*!40101 SET character_set_client = @saved_cs_client */;

-- INSERT INTO `clickargo`.`T_CORE_APPS` (`APPS_CODE`, `APPS_DESC`, `APPS_STATUS`, `APPS_LAUNCH_ICON_FNAME`, `APPS_LAUNCH_TEXT`, `APPS_LAUNCH_URL`, `APPS_DT_ACTIVE`, `APPS_DT_DEACTIVE`, `APPS_DT_CREATE`, `APPS_UID_CREATE`, `APPS_DT_LUPD`, `APPS_UID_LUPD`, `APPS_URI_BASE_PATH`, `APPS_PARAM_1_NAME`, `APPS_PARAM_1_VAL`, `APPS_PARAM_2_NAME`, `APPS_PARAM_2_VAL`, `APPS_PARAM_3_NAME`, `APPS_PARAM_3_VAL`, `APPS_PARAM_4_NAME`, `APPS_PARAM_4_VAL`, `APPS_PARAM_5_NAME`, `APPS_PARAM_5_VAL`, `APPS_PARAM_6_NAME`, `APPS_PARAM_6_VAL`, `APPS_PARAM_7_NAME`, `APPS_PARAM_7_VAL`, `APPS_PARAM_8_NAME`, `APPS_PARAM_8_VAL`, `APPS_PARAM_9_NAME`, `APPS_PARAM_9_VAL`, `APPS_PARAM_10_NAME`, `APPS_PARAM_10_VAL`) VALUES ('CKT', 'ClicTruck', 'A', NULL, 'ClicTruck', 'http://localhost:8080/Clickargo/dashboard', '2022-10-01 00:00:00', NULL, '2022-10-01 00:00:00', 'SYS', '2022-10-01 00:00:00', NULL, 'http://localhost:8080/clictruck', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO `clickargo`.`T_CK_MST_ENTITY_TYPE` (`ENTY_ID`, `ENTY_NAME`, `ENTY_DESC`, `ENTY_DESC_OTH`, `ENTY_STATUS`, `ENTY_DT_CREATE`, `ENTY_UID_CREATE`, `ENTY_DT_LUPD`, `ENTY_UID_LUPD`) VALUES ('JOB_TRUCK', 'TRUCK Import Job', 'TRUCK Import Job', 'TRUCK Import Job', 'A', '2022-10-01 01:00:00', 'SYS', '2022-10-01 01:00:00', 'SYS');

INSERT INTO `clickargo`.`T_CORE_USR` (`USR_UID`, `USR_ACCNID`, `USR_STATUS`, `USR_TYPE_ONLINE`, `USR_TYPE_MBOX`, `USR_NAME`, `USR_PASS_NID`, `USR_TITLE`, `USR_DEPT`, `USR_DT_REG`, `USR_DT_COMM`, `USR_DT_DEREG`, `USR_DT_REREG`, `USR_CLASS`, `USR_ADDR1`, `USR_ADDR2`, `USR_ADDR3`, `USR_PCODE`, `USR_CITY`, `USR_PROV`, `USR_CTYCODE`, `USR_TEL`, `USR_FAX`, `USR_EMAIL`, `USR_PWD`, `USR_PWD_1`, `USR_PWD_2`, `USR_PWD_3`, `USR_PWD_4`, `USR_DT_PWD_LUPD`, `USR_PWD_VALIDTY`, `USR_PWD_FORCE`, `USR_LOGIN_INVCNT`, `USR_DT_LOGINOK`, `USR_DT_LOGINERR`, `USR_MBOX_ID`, `USR_MBOX_MAXCNT`, `USR_MBOX_MAXSIZ`, `USR_DUR_INBX`, `USR_DUR_ARCH`, `USR_DT_CREATE`, `USR_UID_CREATE`, `USR_DT_LUPD`, `USR_UID_LUPD`) VALUES ('ADEAND_U001', 'ALKNAR', 'A', 'Y', 'N', 'Adenny Andrade', '88888888', 'Officer', 'OP', '2022-10-01 00:00:00', '2022-10-01 00:00:00', NULL, NULL, NULL, 'Kawasan Industri Cimareme', 'Jalan Industri Cimareme II No. 14', 'Padalarang, West Bandung - 40553', '40553', 'Jakarta', '', 'ID', '628568342615', '', 'adenny.andrade@guud.company', 'f82c16514f1ecf48d48b8808c7cc3b91', '', '', '', '', '2023-12-01 00:00:00', NULL, '', '0', '2022-10-01 00:00:00', '2022-10-01 00:00:00', '', NULL, NULL, NULL, NULL, '2022-10-01 00:00:00', 'SYS', '2023-01-29 12:32:05', 'SYS');

INSERT INTO `clickargo`.`T_CORE_USR_ROLE` (`UROL_UID`, `UROL_APPSCODE`, `UROL_ROLEID`, `UROL_ADMIN_OPT`, `UROL_STATUS`, `UROL_DT_CREATE`, `UROL_UID_CREATE`, `UROL_DT_LUPD`, `UROL_UID_LUPD`, `UROL_TEMP_ROLE`) VALUES ('ADEAND_U001', 'CKT', 'OFFICER', 'N', 'A', '2022-11-15 09:10:07', 'SYS', '2022-11-15 09:10:07', 'SYS', 'N');

INSERT INTO `clickargo`.`T_CORE_ROLE` (`ROLE_APPSCODE`, `ROLE_ID`, `ROLE_STATUS`, `ROLE_DESC`, `ROLE_DT_CREATE`, `ROLE_UID_CREATE`, `ROLE_DT_LUPD`, `ROLE_UID_LUPD`) VALUES ('CKT', 'OFFICER', 'A', 'Officer', '2018-12-01 00:00:00', 'SYS', '2018-12-01 00:00:00', 'SYS');

INSERT INTO `clickargo`.`T_CORE_MENU_EX` (`MENU_ID`, `MENU_APPS_CODE`, `MENU_GROUP_LABEL`, `MENU_GROUP_LABEL_OTH`, `MENU_NAME`, `MENU_NAME_OTH`, `MENU_SEQ`, `MENU_PATH`, `MENU_ICON`, `MENU_PARENT`, `MENU_STATUS`, `MENU_DT_CREATE`, `MENU_UID_CREATE`, `MENU_DT_LUPD`, `MENU_UID_LUPD`) VALUES ('CK_MH_060000', 'CKT', 'Help', 'Help', 'Help', 'Help', '40000', '/help', 'help_outline', NULL, 'A', '2022-11-15 09:06:44', 'SYS', '2022-11-15 09:06:44', 'SYS');
INSERT INTO `clickargo`.`T_CORE_MENU_EX` (`MENU_ID`, `MENU_APPS_CODE`, `MENU_GROUP_LABEL`, `MENU_GROUP_LABEL_OTH`, `MENU_NAME`, `MENU_NAME_OTH`, `MENU_SEQ`, `MENU_PATH`, `MENU_ICON`, `MENU_PARENT`, `MENU_STATUS`, `MENU_DT_CREATE`, `MENU_UID_CREATE`, `MENU_DT_LUPD`, `MENU_UID_LUPD`) VALUES ('CK_MP_010000', 'CKT', 'Pay Truck', 'Pay Truck', 'Pay Truck', 'Pay Truck', '20000', '/payments', 'payment', NULL, 'A', '2022-11-15 09:06:44', 'SYS', '2022-11-15 09:06:44', 'SYS');
INSERT INTO `clickargo`.`T_CORE_MENU_EX` (`MENU_ID`, `MENU_APPS_CODE`, `MENU_GROUP_LABEL`, `MENU_GROUP_LABEL_OTH`, `MENU_NAME`, `MENU_NAME_OTH`, `MENU_SEQ`, `MENU_PATH`, `MENU_ICON`, `MENU_PARENT`, `MENU_STATUS`, `MENU_DT_CREATE`, `MENU_UID_CREATE`, `MENU_DT_LUPD`, `MENU_UID_LUPD`) VALUES ('CK_MS_060000', 'CKT', 'Services', 'Services', 'Services', 'Services', '10000', '/', 'grid_view', NULL, 'A', '2022-11-15 09:06:44', 'SYS', '2022-11-15 09:06:44', 'SYS');
INSERT INTO `clickargo`.`T_CORE_MENU_EX` (`MENU_ID`, `MENU_APPS_CODE`, `MENU_GROUP_LABEL`, `MENU_GROUP_LABEL_OTH`, `MENU_NAME`, `MENU_NAME_OTH`, `MENU_SEQ`, `MENU_PATH`, `MENU_ICON`, `MENU_PARENT`, `MENU_STATUS`, `MENU_DT_CREATE`, `MENU_UID_CREATE`, `MENU_DT_LUPD`, `MENU_UID_LUPD`) VALUES ('CK_MA_060000', 'CKT', 'Administration', 'Administration', 'Administration', 'Administration', '30000', NULL, 'reorder', NULL, 'A', '2022-11-15 09:06:44', 'SYS', '2022-11-15 09:06:44', 'SYS');
INSERT INTO `clickargo`.`T_CORE_MENU_EX` (`MENU_ID`, `MENU_APPS_CODE`, `MENU_GROUP_LABEL`, `MENU_GROUP_LABEL_OTH`, `MENU_NAME`, `MENU_NAME_OTH`, `MENU_SEQ`, `MENU_PATH`, `MENU_ICON`, `MENU_PARENT`, `MENU_STATUS`, `MENU_DT_CREATE`, `MENU_UID_CREATE`, `MENU_DT_LUPD`, `MENU_UID_LUPD`) VALUES ('CK_MA_060100', 'CKT', '', '', 'Manage Trucks', 'Manage Trucks', '30100', '/truckManagement', NULL, 'CK_MA_060000', 'A', '2022-11-15 09:06:44', 'SYS', '2022-11-15 09:06:44', 'SYS');
INSERT INTO `clickargo`.`T_CORE_MENU_EX` (`MENU_ID`, `MENU_APPS_CODE`, `MENU_GROUP_LABEL`, `MENU_GROUP_LABEL_OTH`, `MENU_NAME`, `MENU_NAME_OTH`, `MENU_SEQ`, `MENU_PATH`, `MENU_ICON`, `MENU_PARENT`, `MENU_STATUS`, `MENU_DT_CREATE`, `MENU_UID_CREATE`, `MENU_DT_LUPD`, `MENU_UID_LUPD`) VALUES ('CK_MA_060200', 'CKT', '', '', 'Manage Drivers', 'Manage Drivers', '30200', '/driverManagement', NULL, 'CK_MA_060000', 'A', '2022-11-15 09:06:44', 'SYS', '2022-11-15 09:06:44', 'SYS');
INSERT INTO `clickargo`.`T_CORE_MENU_EX` (`MENU_ID`, `MENU_APPS_CODE`, `MENU_GROUP_LABEL`, `MENU_GROUP_LABEL_OTH`, `MENU_NAME`, `MENU_NAME_OTH`, `MENU_SEQ`, `MENU_PATH`, `MENU_ICON`, `MENU_PARENT`, `MENU_STATUS`, `MENU_DT_CREATE`, `MENU_UID_CREATE`, `MENU_DT_LUPD`, `MENU_UID_LUPD`) VALUES ('CK_MA_060300', 'CKT', '', '', 'Manage Locations', 'Manage Locations', '30300', '/locationManagement', NULL, 'CK_MA_060000', 'A', '2022-11-15 09:06:44', 'SYS', '2022-11-15 09:06:44', 'SYS');
INSERT INTO `clickargo`.`T_CORE_MENU_EX` (`MENU_ID`, `MENU_APPS_CODE`, `MENU_GROUP_LABEL`, `MENU_GROUP_LABEL_OTH`, `MENU_NAME`, `MENU_NAME_OTH`, `MENU_SEQ`, `MENU_PATH`, `MENU_ICON`, `MENU_PARENT`, `MENU_STATUS`, `MENU_DT_CREATE`, `MENU_UID_CREATE`, `MENU_DT_LUPD`, `MENU_UID_LUPD`) VALUES ('CK_MA_060400', 'CKT', '', '', 'Manage Rate Table', 'Manage Rate Table', '30400', '/manageRateTables/rateTable/list', NULL, 'CK_MA_060000', 'A', '2022-11-15 09:06:44', 'SYS', '2022-11-15 09:06:44', 'SYS');
INSERT INTO `clickargo`.`T_CORE_MENU_EX` (`MENU_ID`, `MENU_APPS_CODE`, `MENU_GROUP_LABEL`, `MENU_GROUP_LABEL_OTH`, `MENU_NAME`, `MENU_NAME_OTH`, `MENU_SEQ`, `MENU_PATH`, `MENU_ICON`, `MENU_PARENT`, `MENU_STATUS`, `MENU_DT_CREATE`, `MENU_UID_CREATE`, `MENU_DT_LUPD`, `MENU_UID_LUPD`) VALUES ('CK_MA_060500', 'CKT', '', '', 'Manage Contracts', 'Manage Contracts', '30500', '/contractManagement', NULL, 'CK_MA_060000', 'A', '2022-11-15 09:06:44', 'SYS', '2022-11-15 09:06:44', 'SYS');
INSERT INTO `clickargo`.`T_CORE_MENU_EX` (`MENU_ID`, `MENU_APPS_CODE`, `MENU_GROUP_LABEL`, `MENU_GROUP_LABEL_OTH`, `MENU_NAME`, `MENU_NAME_OTH`, `MENU_SEQ`, `MENU_PATH`, `MENU_ICON`, `MENU_PARENT`, `MENU_STATUS`, `MENU_DT_CREATE`, `MENU_UID_CREATE`, `MENU_DT_LUPD`, `MENU_UID_LUPD`) VALUES ('CK_MA_060600', 'CKT', '', '', 'Manage Rental', 'Manage Rental', '30600', '/rentalManagement', NULL, 'CK_MA_060000', 'A', '2022-11-15 09:06:44', 'SYS', '2022-11-15 09:06:44', 'SYS');

INSERT INTO `clickargo`.`T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`, `PERM_MENU_NAME`, `PERM_DOC_TYPE`, `PERM_DOC_CODE`, `PERM_ACTION`, `PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`, `PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM100', 'Y', 'CKT', NULL, 'M', NULL, NULL, 'CK_MS_060000', 'Services', NULL, NULL, NULL, 'Services', 'Services', 'R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `clickargo`.`T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`, `PERM_MENU_NAME`, `PERM_DOC_TYPE`, `PERM_DOC_CODE`, `PERM_ACTION`, `PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`, `PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM200', 'N', 'CKT', NULL, 'M', NULL, NULL, 'CK_MH_060000', 'Help', NULL, NULL, NULL, 'Help', 'Help', 'R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `clickargo`.`T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`, `PERM_MENU_NAME`, `PERM_DOC_TYPE`, `PERM_DOC_CODE`, `PERM_ACTION`, `PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`, `PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM300', 'Y', 'CKT', NULL, 'M', NULL, NULL, 'CK_MP_010000', 'Payments', NULL, NULL, NULL, 'Payments', 'Payments', 'R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `clickargo`.`T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`, `PERM_MENU_NAME`, `PERM_DOC_TYPE`, `PERM_DOC_CODE`, `PERM_ACTION`, `PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`, `PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM400', 'Y', 'CKT', NULL, 'M', NULL, NULL, 'CK_MA_060000', 'Administrations', NULL, NULL, NULL, 'Administrations', 'Administrations', 'R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');

INSERT INTO `clickargo`.`T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`, `GNTRLEX_DT_LUPD`, `GNTRLEX_UID_LUPD`) VALUES ('CKT', 'OFFICER', 'PM100', 'A', '2022-11-15 09:08:16', 'SYS', NULL, NULL);
INSERT INTO `clickargo`.`T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`, `GNTRLEX_DT_LUPD`, `GNTRLEX_UID_LUPD`) VALUES ('CKT', 'OFFICER', 'PM200', 'A', '2022-11-15 09:08:16', 'SYS', NULL, NULL);
INSERT INTO `clickargo`.`T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`, `GNTRLEX_DT_LUPD`, `GNTRLEX_UID_LUPD`) VALUES ('CKT', 'OFFICER', 'PM300', 'A', '2022-11-15 09:08:16', 'SYS', NULL, NULL);
INSERT INTO `clickargo`.`T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`, `GNTRLEX_DT_LUPD`, `GNTRLEX_UID_LUPD`) VALUES ('CKT', 'OFFICER', 'PM400', 'A', '2022-11-15 09:08:16', 'SYS', NULL, NULL);

-- SHIPMENT TYPE (MASTER) ----------------------------------------------------------------------------
/*
-- Query: SELECT * FROM clickargo.T_CK_MST_SHIPMENT_TYPE
-- Date: 2023-01-18 14:45
*/
INSERT INTO `T_CK_MST_SHIPMENT_TYPE` (`SHT_ID`,`SHT_NAME`,`SHT_DESC`,`SHT_DESC_OTH`,`SHT_STATUS`,`SHT_DT_CREATE`,`SHT_UID_CREATE`,`SHT_DT_LUPD`,`SHT_UID_LUPD`) VALUES ('DOMESTIC','DOMESTIC','DOMESTIC','DOMESTIC','A','2020-10-01 00:00:00','SYS','2020-10-01 00:00:00','SYS');
INSERT INTO `T_CK_MST_SHIPMENT_TYPE` (`SHT_ID`,`SHT_NAME`,`SHT_DESC`,`SHT_DESC_OTH`,`SHT_STATUS`,`SHT_DT_CREATE`,`SHT_UID_CREATE`,`SHT_DT_LUPD`,`SHT_UID_LUPD`) VALUES ('EXPORT','EXPORT','EXPORT','EXPORT','A','2020-10-01 00:00:00','SYS','2020-10-01 00:00:00','SYS');
INSERT INTO `T_CK_MST_SHIPMENT_TYPE` (`SHT_ID`,`SHT_NAME`,`SHT_DESC`,`SHT_DESC_OTH`,`SHT_STATUS`,`SHT_DT_CREATE`,`SHT_UID_CREATE`,`SHT_DT_LUPD`,`SHT_UID_LUPD`) VALUES ('IMPORT','IMPORT','IMPORT','IMPORT','A','2020-10-01 00:00:00','SYS','2020-10-01 00:00:00','SYS');

-- SHIPMENT STATE (MASTER) ----------------------------------------------------------------------------
CREATE TABLE `T_CK_MST_SHIPMENT_STATE` (
  `SHST_ID` varchar(35) NOT NULL COMMENT 'SHIPMENT STATE ID - NEW : PROGRESSING : COMPLETED : CANCELLED',
  `SHST_NAME` varchar(100) NOT NULL COMMENT 'SHIPMENT STATE NAME',
  `SHST_DESC` varchar(255) DEFAULT NULL COMMENT 'SHIPMENT STATE DESCRIPTION',
  `SHST_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'SHIPMENT STATE DESCRIPTION OTHER LANGUAGE',
  `SHST_STATUS` char(1) DEFAULT NULL COMMENT 'SHIPMENT STATE STATUS',
  `SHST_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `SHST_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `SHST_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `SHST_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`SHST_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='SHIPMENT STATE TABLE';

/*
-- Query: SELECT * FROM clickargo.T_CK_MST_SHIPMENT_STATE
-- Date: 2023-01-30 15:35
*/
INSERT INTO `T_CK_MST_SHIPMENT_STATE` (`SHST_ID`,`SHST_NAME`,`SHST_DESC`,`SHST_DESC_OTH`,`SHST_STATUS`,`SHST_DT_CREATE`,`SHST_UID_CREATE`,`SHST_DT_LUPD`,`SHST_UID_LUPD`) VALUES ('CANCELLED','CANCELLED','CANCELLED','CANCELLED','A','2020-10-01 00:00:00','SYS','2020-10-01 00:00:00','SYS');
INSERT INTO `T_CK_MST_SHIPMENT_STATE` (`SHST_ID`,`SHST_NAME`,`SHST_DESC`,`SHST_DESC_OTH`,`SHST_STATUS`,`SHST_DT_CREATE`,`SHST_UID_CREATE`,`SHST_DT_LUPD`,`SHST_UID_LUPD`) VALUES ('COMPLETED','IN COMPLETED','COMPLETED','COMPLETED','A','2020-10-01 00:00:00','SYS','2020-10-01 00:00:00','SYS');
INSERT INTO `T_CK_MST_SHIPMENT_STATE` (`SHST_ID`,`SHST_NAME`,`SHST_DESC`,`SHST_DESC_OTH`,`SHST_STATUS`,`SHST_DT_CREATE`,`SHST_UID_CREATE`,`SHST_DT_LUPD`,`SHST_UID_LUPD`) VALUES ('INPROG','IN PROGRESS','IN PROGRESS','IN PROGRESS','A','2020-10-01 00:00:00','SYS','2020-10-01 00:00:00','SYS');
INSERT INTO `T_CK_MST_SHIPMENT_STATE` (`SHST_ID`,`SHST_NAME`,`SHST_DESC`,`SHST_DESC_OTH`,`SHST_STATUS`,`SHST_DT_CREATE`,`SHST_UID_CREATE`,`SHST_DT_LUPD`,`SHST_UID_LUPD`) VALUES ('NEW','NEW','NEW','NEW','A','2020-10-01 00:00:00','SYS','2020-10-01 00:00:00','SYS');

-- VEHICLE TYPE (MASTER) ----------------------------------------------------------------------------
CREATE TABLE `T_CK_CT_MST_VEH_TYPE` (
  `VHTY_ID` varchar(35) NOT NULL COMMENT 'VEHICLE TYPE ID - CCD : CDE : 20FT : 40FT',
  `VHTY_NAME` varchar(100) NOT NULL COMMENT 'VEHICLE TYPE NAME',
  `VHTY_DESC` varchar(255) DEFAULT NULL COMMENT 'VEHICLE TYPE DESCRIPTION',
  `VHTY_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'VEHICLE TYPE DESCRIPTION OTHER LANGUAGE',
  `VHTY_STATUS` char(1) DEFAULT NULL COMMENT 'VEHICLE TYPE STATUS',
  `VHTY_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `VHTY_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `VHTY_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `VHTY_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`VHTY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='VEHICLE TYPE MASTER TABLE';

/*
-- Query: SELECT * FROM clickargo.T_CK_CT_MST_VEH_TYPE
-- Date: 2023-01-30 15:55
*/
INSERT INTO `T_CK_CT_MST_VEH_TYPE` (`VHTY_ID`,`VHTY_NAME`,`VHTY_DESC`,`VHTY_DESC_OTH`,`VHTY_STATUS`,`VHTY_DT_CREATE`,`VHTY_UID_CREATE`,`VHTY_DT_LUPD`,`VHTY_UID_LUPD`) VALUES ('CDD','CDD','CDD','CDD','A','2020-10-01 00:00:00','SYS','2020-10-01 00:00:00','SYS');
INSERT INTO `T_CK_CT_MST_VEH_TYPE` (`VHTY_ID`,`VHTY_NAME`,`VHTY_DESC`,`VHTY_DESC_OTH`,`VHTY_STATUS`,`VHTY_DT_CREATE`,`VHTY_UID_CREATE`,`VHTY_DT_LUPD`,`VHTY_UID_LUPD`) VALUES ('CDD LONG','CDD LONG','CDD LONG','CDD LONG','A','2020-10-01 00:00:00','SYS','2020-10-01 00:00:00','SYS');
INSERT INTO `T_CK_CT_MST_VEH_TYPE` (`VHTY_ID`,`VHTY_NAME`,`VHTY_DESC`,`VHTY_DESC_OTH`,`VHTY_STATUS`,`VHTY_DT_CREATE`,`VHTY_UID_CREATE`,`VHTY_DT_LUPD`,`VHTY_UID_LUPD`) VALUES ('CDE','CDE','CDE','CDE','A','2020-10-01 00:00:00','SYS','2020-10-01 00:00:00','SYS');
INSERT INTO `T_CK_CT_MST_VEH_TYPE` (`VHTY_ID`,`VHTY_NAME`,`VHTY_DESC`,`VHTY_DESC_OTH`,`VHTY_STATUS`,`VHTY_DT_CREATE`,`VHTY_UID_CREATE`,`VHTY_DT_LUPD`,`VHTY_UID_LUPD`) VALUES ('CONTAINER 20FT','CONTAINER 20FT','CONTAINER 20FT','CONTAINER 20FT','A','2020-10-01 00:00:00','SYS','2020-10-01 00:00:00','SYS');
INSERT INTO `T_CK_CT_MST_VEH_TYPE` (`VHTY_ID`,`VHTY_NAME`,`VHTY_DESC`,`VHTY_DESC_OTH`,`VHTY_STATUS`,`VHTY_DT_CREATE`,`VHTY_UID_CREATE`,`VHTY_DT_LUPD`,`VHTY_UID_LUPD`) VALUES ('CONTAINER 40FT','CONTAINER 40FT','CONTAINER 40FT','CONTAINER 40FT','A','2020-10-01 00:00:00','SYS','2020-10-01 00:00:00','SYS');
INSERT INTO `T_CK_CT_MST_VEH_TYPE` (`VHTY_ID`,`VHTY_NAME`,`VHTY_DESC`,`VHTY_DESC_OTH`,`VHTY_STATUS`,`VHTY_DT_CREATE`,`VHTY_UID_CREATE`,`VHTY_DT_LUPD`,`VHTY_UID_LUPD`) VALUES ('VAN','VAN','VAN','VAN','A','2020-10-01 00:00:00','SYS','2020-10-01 00:00:00','SYS');
INSERT INTO `T_CK_CT_MST_VEH_TYPE` (`VHTY_ID`,`VHTY_NAME`,`VHTY_DESC`,`VHTY_DESC_OTH`,`VHTY_STATUS`,`VHTY_DT_CREATE`,`VHTY_UID_CREATE`,`VHTY_DT_LUPD`,`VHTY_UID_LUPD`) VALUES ('WING BOX','WING BOX','WING BOX','WING BOX','A','2020-10-01 00:00:00','SYS','2020-10-01 00:00:00','SYS');

-- VEHICLE STATE (MASTER) ----------------------------------------------------------------------------
CREATE TABLE `T_CK_CT_MST_VEH_STATE` (
  `VHST_ID` varchar(35) NOT NULL COMMENT 'VEHICLE STATE ID - ASSIGNED : UNASSIGNED : MAINTEANCE',
  `VHST_NAME` varchar(100) NOT NULL COMMENT 'VEHICLE STATE NAME',
  `VHST_DESC` varchar(255) DEFAULT NULL COMMENT 'VEHICLE STATE DESCRIPTION',
  `VHST_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'VEHICLE STATE DESCRIPTION OTHER LANGUAGE',
  `VHST_STATUS` char(1) DEFAULT NULL COMMENT 'VEHICLE STATE STATUS',
  `VHST_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `VHST_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `VHST_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `VHST_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`VHST_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='VEHICLE STATE MASTER TABLE';

/*
-- Query: SELECT * FROM clickargo.T_CK_CT_MST_VEH_STATE
-- Date: 2023-01-30 16:05
*/
INSERT INTO `T_CK_CT_MST_VEH_STATE` (`VHST_ID`,`VHST_NAME`,`VHST_DESC`,`VHST_DESC_OTH`,`VHST_STATUS`,`VHST_DT_CREATE`,`VHST_UID_CREATE`,`VHST_DT_LUPD`,`VHST_UID_LUPD`) VALUES ('ASSIGNED','ASSIGNED','ASSIGNED','ASSIGNED','A','2020-10-01 00:00:00','SYS','2020-10-01 00:00:00','SYS');
INSERT INTO `T_CK_CT_MST_VEH_STATE` (`VHST_ID`,`VHST_NAME`,`VHST_DESC`,`VHST_DESC_OTH`,`VHST_STATUS`,`VHST_DT_CREATE`,`VHST_UID_CREATE`,`VHST_DT_LUPD`,`VHST_UID_LUPD`) VALUES ('MAINTENANCE','MAINTENANCE','MAINTENANCE','MAINTENANCE','A','2020-10-01 00:00:00','SYS','2020-10-01 00:00:00','SYS');
INSERT INTO `T_CK_CT_MST_VEH_STATE` (`VHST_ID`,`VHST_NAME`,`VHST_DESC`,`VHST_DESC_OTH`,`VHST_STATUS`,`VHST_DT_CREATE`,`VHST_UID_CREATE`,`VHST_DT_LUPD`,`VHST_UID_LUPD`) VALUES ('UNASSIGNED','UNASSIGNED','UNASSIGNED','UNASSIGNED','A','2020-10-01 00:00:00','SYS','2020-10-01 00:00:00','SYS');

-- CHASSIS TYPE (MASTER) ----------------------------------------------------------------------------
CREATE TABLE `T_CK_CT_MST_CHASSIS_TYPE` (
  `CHTY_ID` varchar(35) NOT NULL COMMENT 'CHASSIS TYPE ID - 20FT : 40FT',
  `CHTY_NAME` varchar(100) NOT NULL COMMENT 'CHASSIS TYPE NAME',
  `CHTY_DESC` varchar(255) DEFAULT NULL COMMENT 'CHASSIS TYPE DESCRIPTION',
  `CHTY_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'CHASSIS TYPE DESCRIPTION OTHER LANGUAGE',
  `CHTY_STATUS` char(1) DEFAULT NULL COMMENT 'CHASSIS TYPE STATUS',
  `CHTY_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `CHTY_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `CHTY_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `CHTY_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`CHTY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='CHASSIS TYPE MASTER TABLE';

/*
-- Query: SELECT * FROM clickargo.T_CK_CT_MST_CHASSIS_TYPE
-- Date: 2023-02-08 17:42
*/
INSERT INTO `T_CK_CT_MST_CHASSIS_TYPE` (`CHTY_ID`,`CHTY_NAME`,`CHTY_DESC`,`CHTY_DESC_OTH`,`CHTY_STATUS`,`CHTY_DT_CREATE`,`CHTY_UID_CREATE`,`CHTY_DT_LUPD`,`CHTY_UID_LUPD`) VALUES ('20FT','20FT CHASSIS','20FT CHASSIS','20FT CHASSIS','A','2020-10-01 00:00:00','SYS','2020-10-01 00:00:00','SYS');
INSERT INTO `T_CK_CT_MST_CHASSIS_TYPE` (`CHTY_ID`,`CHTY_NAME`,`CHTY_DESC`,`CHTY_DESC_OTH`,`CHTY_STATUS`,`CHTY_DT_CREATE`,`CHTY_UID_CREATE`,`CHTY_DT_LUPD`,`CHTY_UID_LUPD`) VALUES ('40FT','40FT CHASSIS','40FT CHASSIS','40FT CHASSIS','A','2020-10-01 00:00:00','SYS','2020-10-01 00:00:00',NULL);

-- VEHICLE TABLE ----------------------------------------------------------------------------
CREATE TABLE `T_CK_CT_VEH` (
  `VH_ID` varchar(35) NOT NULL COMMENT 'VEHICLE ID - UUID',
  `VH_TYPE` varchar(35) DEFAULT NULL COMMENT 'VEHICLE TYPE - REFERENCES T_CK_CT_MST_VEH_TYPE:VHTY_ID',
  `VH_STATE` varchar(35) DEFAULT NULL COMMENT 'VEHICLE STATE - REFERENCES T_CK_CT_MST_VEH_STATE:VHST_ID',
  `VH_COMPANY` varchar(35) DEFAULT NULL COMMENT 'VEHICLE OWNER - REFERENCES T_CORE_ACCN:ACCN_ID',  
  `VH_PLATE_NO` varchar(256) DEFAULT NULL NULL COMMENT 'VEHICLE PLATE NUMBER',
  `VH_CLASS` tinyint DEFAULT 0 NULL COMMENT 'VEHICLE CLASS - 1:2:3',
  `VH_PHOTO_NAME` varchar(256) DEFAULT NULL COMMENT 'VEHICLE PHOTO FILE NAME',
  `VH_PHOTO_LOC` varchar(1024) DEFAULT NULL COMMENT 'VEHICLE PHOTO PATH REFERENCE FROM SYS_PARAM SETUP',    
  `VH_LENGTH` smallint DEFAULT 0 COMMENT 'VEHICLE LENGTH IN METERS',
  `VH_WIDTH` smallint DEFAULT 0 COMMENT 'VEHICLE WIDTH IN METERS',
  `VH_HEIGHT` smallint DEFAULT 0 COMMENT 'VEHICLE HEIGHT IN METERS',
  `VH_WEIGHT` mediumint DEFAULT 0 COMMENT 'VEHICLE WEIGHT IN KG',
  `VH_VOLUME` mediumint DEFAULT 0 COMMENT 'VEHICLE VOLUME IN CUBIC METER',
  `VH_CHASSIS_TYPE` varchar(35) DEFAULT NULL COMMENT 'VEHICLE CHASSIS TYPE - REFERENCES T_CK_CT_MST_CHASSIS_TYPE:CHTY_ID',
  `VH_CHASSIS_NO` varchar(256) DEFAULT NULL COMMENT 'VEHICLE CHASSIS NUMBER',
  `VH_IS_MAINTENANCE` char(1) DEFAULT 'N' COMMENT 'VEHICLE IS UNDER MAINTENANCE - Y:N',
  `VH_REMARKS` mediumtext DEFAULT NULL COMMENT 'REMARKS FOR VEHICLES',
  `VH_GPS_IMEI` varchar(1024) DEFAULT NULL COMMENT 'GPS IMEI ASSIGNED TO TRUCK',  
  `VH_ASSIGNED_JOB` varchar(35) DEFAULT NULL COMMENT 'JOB THAT VECHICLE IS ASSGINED TO - REFERENCES T_CK_JOB:JOB_ID',    
  `VH_STATUS` char(1) DEFAULT NULL COMMENT 'VEHICLE STATE STATUS',
  `VH_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `VH_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `VH_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `VH_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`VH_ID`),
  CONSTRAINT `FK_CK_CT_VEH_CK_CT_MST_VEH_TYPE` FOREIGN KEY (`VH_TYPE`) REFERENCES `T_CK_CT_MST_VEH_STATE` (`VHST_ID`),
  CONSTRAINT `FK_CK_CT_VEH_CK_CT_MST_VEH_STATE` FOREIGN KEY (`VH_STATE`) REFERENCES `T_CK_CT_MST_VEH_TYPE` (`VHTY_ID`),
  CONSTRAINT `FK_CK_CT_VEH_CORE_ACCN` FOREIGN KEY (`VH_COMPANY`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),  
  CONSTRAINT `FK_CK_CT_VEH_CK_CT_MST_CHASSIS_TYPE` FOREIGN KEY (`VH_CHASSIS_TYPE`) REFERENCES `T_CK_CT_MST_CHASSIS_TYPE` (`CHTY_ID`),
  CONSTRAINT `FK_CK_CT_VEH_CK_JOB` FOREIGN KEY (`VH_ASSIGNED_JOB`) REFERENCES `T_CK_JOB` (`JOB_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='VEHICLE TABLE';

-- DRIVER TABLE ----------------------------------------------------------------------------
CREATE TABLE `T_CK_CT_DRV` (
  `DRV_ID` varchar(35) NOT NULL COMMENT 'DRIVER ID - UUID',
  `DRV_NAME` varchar(256) DEFAULT NULL COMMENT 'DRIVER NAME',
  `DRV_COMPANY` varchar(35) DEFAULT NULL COMMENT 'DRIVER COMPANY - REFERENCES T_CORE_ACCN:ACCN_ID',    
  `DRV_LICENSE_NO` varchar(256) DEFAULT NULL NULL COMMENT 'DRIVER LICENSE NUMBER',
  `DRV_LICENSE_EXPIRY` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `DRV_LICENSE_PHOTO_NAME` varchar(256) DEFAULT NULL COMMENT 'DRIVER LICENSE PHOTO FILE NAME',
  `DRV_LICENSE_PHOTO_LOC` varchar(1024) DEFAULT NULL COMMENT 'DRIVER LICENSE PHOTO PATH REFERENCE FROM SYS_PARAM SETUP',    
  `DRV_EMAIL` varchar(128) DEFAULT NULL COMMENT 'DRIVER EMAIL CONTACT',
  `DRV_PHONE` varchar(1024) DEFAULT NULL COMMENT 'DRIVER PHONE CONTACT',
  `DRV_MOBILE_ID` varchar(256) DEFAULT NULL COMMENT 'DRIVER EMAIL CONTACT',
  `DRV_MOBILE_PASSWORD` varchar(256) DEFAULT NULL COMMENT 'DRIVER PHONE CONTACT',
  `DRV_ASSIGNED_VEH` varchar(35) DEFAULT NULL COMMENT 'VEHICLE THAT DRIVER IS ASSGINED TO - REFERENCES T_CK_CT_VEH:VH_ID',    
  `DRV_STATUS` char(1) DEFAULT NULL COMMENT 'DRIVER STATE STATUS',
  `DRV_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `DRV_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `DRV_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `DRV_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`DRV_ID`),
  CONSTRAINT `FK_CK_CT_DRV_CORE_ACCN` FOREIGN KEY (`DRV_COMPANY`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_CT_DRV_CK_CT_VEH` FOREIGN KEY (`DRV_ASSIGNED_VEH`) REFERENCES `T_CK_CT_VEH` (`VH_ID`)  
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='DRIVER TABLE';

-- LOCATION TYPE (MASTER) ----------------------------------------------------------------------------
CREATE TABLE `T_CK_CT_MST_LOCATION_TYPE` (
  `LCTY_ID` varchar(35) NOT NULL COMMENT 'LOCATION TYPE ID - REGION : ADDRESS',
  `LCTY_NAME` varchar(100) NOT NULL COMMENT 'LOCATION TYPE NAME',
  `LCTY_DESC` varchar(255) DEFAULT NULL COMMENT 'LOCATION TYPE DESCRIPTION',
  `LCTY_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'LOCATION TYPE DESCRIPTION OTHER LANGUAGE',
  `LCTY_STATUS` char(1) DEFAULT NULL COMMENT 'LOCATION TYPE STATUS',
  `LCTY_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `LCTY_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `LCTY_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `LCTY_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`LCTY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='LOCATION TYPE MASTER TABLE';

/*
-- Query: SELECT * FROM clickargo.T_CK_CT_MST_LOCATION_TYPE
-- Date: 2023-02-08 19:21
*/
INSERT INTO `T_CK_CT_MST_LOCATION_TYPE` (`LCTY_ID`,`LCTY_NAME`,`LCTY_DESC`,`LCTY_DESC_OTH`,`LCTY_STATUS`,`LCTY_DT_CREATE`,`LCTY_UID_CREATE`,`LCTY_DT_LUPD`,`LCTY_UID_LUPD`) VALUES ('ADDRESS','ADDRESS','ADDRESS','ADDRESS','A','2020-10-01 00:00:00','SYS','2020-10-01 00:00:00',NULL);
INSERT INTO `T_CK_CT_MST_LOCATION_TYPE` (`LCTY_ID`,`LCTY_NAME`,`LCTY_DESC`,`LCTY_DESC_OTH`,`LCTY_STATUS`,`LCTY_DT_CREATE`,`LCTY_UID_CREATE`,`LCTY_DT_LUPD`,`LCTY_UID_LUPD`) VALUES ('REGION','REGION','REGION','REGION','A','2020-10-01 00:00:00','SYS','2020-10-01 00:00:00','SYS');

-- LOCATION TABLE ----------------------------------------------------------------------------
CREATE TABLE `T_CK_CT_LOCATION` (
  `LOC_ID` varchar(35) NOT NULL COMMENT 'LOCATION ID - UUID',
  `LOC_TYPE` varchar(35) DEFAULT NULL COMMENT 'LOCATION TYPE  - REFERENCES T_CK_CT_MST_LOCATION_TYPE:LCTY_ID',
  `LOC_COMPANY` varchar(35) DEFAULT NULL COMMENT 'LOCATION COMPANY - REFERENCES T_CORE_ACCN:ACCN_ID',     
  `LOC_NAME` varchar(1024) DEFAULT NULL COMMENT 'LOCATION NAME',
  `LOC_ADDRESS` text DEFAULT NULL COMMENT 'LOCATION ABSOLUTE ADDRESS IF TYPE IS ADDRESS',  
  `LOC_DT_START` datetime DEFAULT NULL COMMENT 'LOCATION VALIDITY START',
  `LOC_DT_END` datetime DEFAULT NULL COMMENT 'LOCATION VALIDITY END',
  `LOC_REMARKS` text DEFAULT NULL COMMENT 'LOCATION REMARKS',
  `LOC_STATUS` char(1) DEFAULT NULL COMMENT 'LOCATION STATE STATUS',
  `LOC_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `LOC_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `LOC_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `LOC_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`LOC_ID`),
  CONSTRAINT `FK_CK_CT_LOC_CK_CT_MST_LOCATION_TYPE` FOREIGN KEY (`LOC_TYPE`) REFERENCES `T_CK_CT_MST_LOCATION_TYPE` (`LCTY_ID`),
  CONSTRAINT `FK_CK_CT_LOC_CORE_ACCN` FOREIGN KEY (`LOC_COMPANY`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='LOCATION TABLE';

-- RATE TABLE ----------------------------------------------------------------------------
CREATE TABLE `T_CK_CT_RATE_TABLE` (
  `RT_ID` varchar(35) NOT NULL COMMENT 'RATE TABLE ID - UUID',
  `RT_COMPANY` varchar(35) DEFAULT NULL COMMENT 'RATE TABLE COMPANY PROVIDER WHICH IS TRUCKING OPEATOR - REFERENCES T_CORE_ACCN:ACCN_ID',     
  `RT_CO_FF` varchar(35) DEFAULT NULL COMMENT 'RATE TABLE COMPANY FOR - REFERENCES T_CORE_ACCN:ACCN_ID',     
  `RT_NAME` varchar(1024) DEFAULT NULL COMMENT 'RATE TABLE NAME',
  `RT_DESCRIPTION` mediumtext DEFAULT NULL COMMENT 'RATE TABLE NAME',
  `RT_CCY` varchar(3) DEFAULT NULL COMMENT 'RATE TABLE CURRENCY - REFERENCES T_MST_CURRENCY:CCY_CODE',
  `RT_DT_START` datetime DEFAULT NULL COMMENT 'RATE TABLE VALIDITY START',
  `RT_DT_END` datetime DEFAULT NULL COMMENT 'RATE TABLE VALIDITY END',
  `RT_REMARKS` text DEFAULT NULL COMMENT 'RATE TABLE REMARKS',
  `RT_STATUS` char(1) DEFAULT NULL COMMENT 'RATE TABLE STATE STATUS',
  `RT_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `RT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `RT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `RT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`RT_ID`),
  CONSTRAINT `FK_CK_CT_RATE_TABLE_CORE_ACCN1` FOREIGN KEY (`RT_COMPANY`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_CT_RATE_TABLE_CORE_ACCN2` FOREIGN KEY (`RT_CO_FF`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_CT_RATE_TABLE_MST_CURRENCY` FOREIGN KEY (`RT_CCY`) REFERENCES `T_MST_CURRENCY` (`CCY_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='RATE TABLE';

-- TRIP RATE TABLE ----------------------------------------------------------------------------
CREATE TABLE `T_CK_CT_TRIP_RATE` (
  `TR_ID` varchar(35) NOT NULL COMMENT 'TRIP RATE ID - UUID',
  `TR_RATE_TABLE` varchar(35) NOT NULL COMMENT 'TRIP RATE TABLE - REFERENCES  T_CK_CT_RATE_TABLE:RT_ID',  
  `TR_LOC_FROM` varchar(35) DEFAULT NULL COMMENT 'LOCATION FROM  - REFERENCES T_CK_CT_LOCATION:LOC_ID',
  `TR_LOC_TO` varchar(35) DEFAULT NULL COMMENT 'LOCATION TO  - REFERENCES T_CK_CT_LOCATION:LOC_ID',
  `TR_VEH_TYPE` varchar(35) DEFAULT NULL COMMENT 'VEHICLE TYPE  - REFERENCES T_CK_CT_MST_VEH_TYPE:VHTY_ID',
  `TR_CHARGE` decimal(15,2) DEFAULT 0.00 COMMENT 'CHARGE',
  `TR_STATUS` char(1) DEFAULT NULL COMMENT 'TRIP RATE STATE STATUS',
  `TR_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `TR_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `TR_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `TR_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`TR_ID`),
  CONSTRAINT `FK_CK_CT_TRIP_RATE_CK_CT_RATE_TABLE` FOREIGN KEY (`TR_RATE_TABLE`) REFERENCES `T_CK_CT_RATE_TABLE` (`RT_ID`),  
  CONSTRAINT `FK_CK_CT_TRIP_RATE_CK_CT_LOCATION1` FOREIGN KEY (`TR_LOC_FROM`) REFERENCES `T_CK_CT_LOCATION` (`LOC_ID`), 
  CONSTRAINT `FK_CK_CT_TRIP_RATE_CK_CT_LOCATION2` FOREIGN KEY (`TR_LOC_TO`) REFERENCES `T_CK_CT_LOCATION` (`LOC_ID`), 
  CONSTRAINT `FK_CK_CT_TRIP_RATE_CK_CT_MST_VEH_TYPE` FOREIGN KEY (`TR_VEH_TYPE`) REFERENCES `T_CK_CT_MST_VEH_TYPE` (`VHTY_ID`)  
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='TRIP RATE TABLE';

-- CONTRACT CHARGE TABLE ----------------------------------------------------------------------------
CREATE TABLE `T_CK_CT_CONTRACT_CHARGE` (
  `CONC_ID` varchar(35) NOT NULL COMMENT 'CONTRACT CHARGE ID - UUID',
  `CONC_PLTFEE_AMT` decimal(15,2) DEFAULT 0.00 NULL COMMENT 'PLATFORM FEE AMOUNT',
  `CONC_PLTFEE_TYPE` char(1) DEFAULT 'P' NULL COMMENT 'PLATFORM FEE TYPE - P : F',
  `CONC_ADDTAX_AMT` decimal(15,2) DEFAULT 0.00 NULL COMMENT 'ADDITIONAL TAX AMOUNT',
  `CONC_ADDTAX_TYPE` char(1) DEFAULT 'P' NULL COMMENT 'ADDITIONAL TAX TYPE - P : F',
  `CONC_WHTAX_AMT` decimal(15,2) DEFAULT 0.00 NULL COMMENT 'WITHOLD TAX AMOUNT',
  `CONC_WHTAX_TYPE` char(1) DEFAULT 'P' NULL COMMENT 'WITHOLD TAX TYPE - P : F',
  `CONC_STATUS` char(1) DEFAULT NULL COMMENT 'CONTRACT STATE STATUS',
  `CONC_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `CONC_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `CONC_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `CONC_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`CONC_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='CONTRACT CHARGE TABLE';

-- CONTRACT TABLE ----------------------------------------------------------------------------
CREATE TABLE `T_CK_CT_CONTRACT` (
  `CON_ID` varchar(35) NOT NULL COMMENT 'CONTRACT ID - UUID',
  `CON_NAME` varchar(1024) DEFAULT NULL COMMENT 'RATE TABLE NAME',
  `CON_DESCRIPTION` mediumtext DEFAULT NULL COMMENT 'RATE TABLE NAME',  
  `CON_CCY` varchar(3) DEFAULT NULL COMMENT 'CONTRACT CURRENCY - REFERENCES T_MST_CURRENCY:CCY_CODE',
  `CON_DT_START` datetime DEFAULT NULL COMMENT 'CONTRACT VALIDITY START',
  `CON_DT_END` datetime DEFAULT NULL COMMENT 'CONTRACT VALIDITY END',
  `CON_TO` varchar(35) DEFAULT NULL COMMENT 'CONTRACT TRUCK OPERATOR - REFERENCES T_CORE_ACCN:ACCN_ID',     
  `CON_CHARGE_TO` varchar(35) DEFAULT NULL COMMENT 'CONTRACT TRUCK OPERATOR CHARGE - REFERENCES T_CK_CT_CONTRACT_CHARGE:CONC_ID',     
  `CON_CO_FF` varchar(35) DEFAULT NULL COMMENT 'CONTRACT CARGO OWNER - REFERENCES T_CORE_ACCN:ACCN_ID',     
  `CON_CHARGE_CO_FF` varchar(35) DEFAULT NULL COMMENT 'CONTRACT CARGO OWNER CHARGE - REFERENCES T_CK_CT_CONTRACT_CHARGE:CONC_ID',     
  `CON_RATE_TABLE` varchar(35) DEFAULT NULL COMMENT 'CONTRACT RATE TABLE - REFERENCES T_CK_CT_RATE_TABLE:RT_ID',     
  `CON_STATUS` char(1) DEFAULT NULL COMMENT 'CONTRACT STATE STATUS',
  `CON_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `CON_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `CON_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `CON_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`CON_ID`),
  CONSTRAINT `FK_CK_CT_CONTRACT_MST_CURRENCY` FOREIGN KEY (`CON_CCY`) REFERENCES `T_MST_CURRENCY` (`CCY_CODE`),  
  CONSTRAINT `FK_CK_CT_CONTRACT_CORE_ACCN1` FOREIGN KEY (`CON_TO`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_CT_CONTRACT_CK_CT_CONTRACT_CHARGE1` FOREIGN KEY (`CON_CHARGE_TO`) REFERENCES `T_CK_CT_CONTRACT_CHARGE` (`CONC_ID`),
  CONSTRAINT `FK_CK_CT_CONTRACT_CORE_ACCN2` FOREIGN KEY (`CON_CO_FF`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_CT_CONTRACT_CK_CT_CONTRACT_CHARGE2` FOREIGN KEY (`CON_CHARGE_CO_FF`) REFERENCES `T_CK_CT_CONTRACT_CHARGE` (`CONC_ID`),
  CONSTRAINT `FK_CK_CT_CONTRACT_CK_CT_RATE_TABLE` FOREIGN KEY (`CON_RATE_TABLE`) REFERENCES `T_CK_CT_RATE_TABLE` (`RT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='CONTRACT TABLE';

-- RENTAL TABLE ----------------------------------------------------------------------------
CREATE TABLE `T_CK_CT_RENTAL_TABLE` (
  `RT_ID` varchar(35) NOT NULL COMMENT 'RENTAL TABLE ID - UUID',
  `RT_COMPANY` varchar(35) DEFAULT NULL COMMENT 'RENTAL TABLE TRUCKING OPERATOR COMPANY - REFERENCES T_CORE_ACCN:ACCN_ID',     
  `RT_CO_FF` varchar(35) DEFAULT NULL COMMENT 'RENTAL TABLE COMPANY FOR - REFERENCES T_CORE_ACCN:ACCN_ID',     
  `RT_NAME` varchar(1024) DEFAULT NULL COMMENT 'RENTAL TABLE NAME',
  `RT_DESCRIPTION` mediumtext DEFAULT NULL COMMENT 'RENTAL TABLE DESCRIPTION',
  `RT_CCY` varchar(3) DEFAULT NULL COMMENT 'RENTAL TABLE CURRENCY - REFERENCES T_MST_CURRENCY:CCY_CODE',
  `RT_DT_START` datetime DEFAULT NULL COMMENT 'RENTAL TABLE VALIDITY START',
  `RT_DT_END` datetime DEFAULT NULL COMMENT 'RENTAL TABLE VALIDITY END',
  `RT_REMARKS` text DEFAULT NULL COMMENT 'RENTAL TABLE REMARKS',
  `RT_STATUS` char(1) DEFAULT NULL COMMENT 'RENTAL TABLE STATE STATUS',
  `RT_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `RT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `RT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `RT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`RT_ID`),
  CONSTRAINT `FK_CK_CT_RENTAL_TABLE_CORE_ACCN1` FOREIGN KEY (`RT_COMPANY`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_CT_RENTAL_TABLE_CORE_ACCN2` FOREIGN KEY (`RT_CO_FF`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_CT_RENTAL_TABLE_MST_CURRENCY` FOREIGN KEY (`RT_CCY`) REFERENCES `T_MST_CURRENCY` (`CCY_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='RENTAL TABLE';

-- RENTAL TYPE (MASTER) ----------------------------------------------------------------------------
CREATE TABLE `T_CK_CT_MST_RENTAL_TYPE` (
  `RT_ID` varchar(35) NOT NULL COMMENT 'RENTAL TYPE ID - CCD : CDE : 20FT : 40FT',
  `RT_NAME` varchar(100) NOT NULL COMMENT 'RENTAL TYPE NAME',
  `RT_DESC` varchar(255) DEFAULT NULL COMMENT 'RENTAL TYPE DESCRIPTION',
  `RT_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'RENTAL TYPE DESCRIPTION OTHER LANGUAGE',
  `RT_STATUS` char(1) DEFAULT NULL COMMENT 'RENTAL TYPE STATUS',
  `RT_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `RT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `RT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `RT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`RT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='RENTAL TYPE MASTER TABLE';

/*
-- Query: SELECT * FROM clickargo.T_CK_CT_MST_RENTAL_TYPE
-- Date: 2023-02-13 00:51
*/
INSERT INTO `T_CK_CT_MST_RENTAL_TYPE` (`RT_ID`,`RT_NAME`,`RT_DESC`,`RT_DESC_OTH`,`RT_STATUS`,`RT_DT_CREATE`,`RT_UID_CREATE`,`RT_DT_LUPD`,`RT_UID_LUPD`) VALUES ('PD','PER DAY','PER DAY','PER DAY','A','2020-10-01 00:00:00','SYS','2020-10-01 00:00:00','SYS');
INSERT INTO `T_CK_CT_MST_RENTAL_TYPE` (`RT_ID`,`RT_NAME`,`RT_DESC`,`RT_DESC_OTH`,`RT_STATUS`,`RT_DT_CREATE`,`RT_UID_CREATE`,`RT_DT_LUPD`,`RT_UID_LUPD`) VALUES ('PM','PER MONTH','PER MONTH','PER MONTH','A','2020-10-01 00:00:00','SYS','2020-10-01 00:00:00','SYS');
INSERT INTO `T_CK_CT_MST_RENTAL_TYPE` (`RT_ID`,`RT_NAME`,`RT_DESC`,`RT_DESC_OTH`,`RT_STATUS`,`RT_DT_CREATE`,`RT_UID_CREATE`,`RT_DT_LUPD`,`RT_UID_LUPD`) VALUES ('PTD','PER TRUCK/DAY','PER TRUCK/DAY','PER TRUCK/DAY','A','2020-10-01 00:00:00','SYS','2020-10-01 00:00:00','SYS');
INSERT INTO `T_CK_CT_MST_RENTAL_TYPE` (`RT_ID`,`RT_NAME`,`RT_DESC`,`RT_DESC_OTH`,`RT_STATUS`,`RT_DT_CREATE`,`RT_UID_CREATE`,`RT_DT_LUPD`,`RT_UID_LUPD`) VALUES ('PTM','PER TRUCK/MONTH','TRUCK/MONTH','TRUCK/MONTH','A','2020-10-01 00:00:00','SYS','2020-10-01 00:00:00','SYS');
INSERT INTO `T_CK_CT_MST_RENTAL_TYPE` (`RT_ID`,`RT_NAME`,`RT_DESC`,`RT_DESC_OTH`,`RT_STATUS`,`RT_DT_CREATE`,`RT_UID_CREATE`,`RT_DT_LUPD`,`RT_UID_LUPD`) VALUES ('PTW','PER TRUCK/WEEK','PER TRUCK/WEEK','PER TRUCK/WEEK','A','2020-10-01 00:00:00','SYS','2020-10-01 00:00:00','SYS');
INSERT INTO `T_CK_CT_MST_RENTAL_TYPE` (`RT_ID`,`RT_NAME`,`RT_DESC`,`RT_DESC_OTH`,`RT_STATUS`,`RT_DT_CREATE`,`RT_UID_CREATE`,`RT_DT_LUPD`,`RT_UID_LUPD`) VALUES ('PW','PER WEEK','PER WEEK','PER WEEK','A','2020-10-01 00:00:00','SYS','2020-10-01 00:00:00','SYS');

-- RENTAL VEHICLE TABLE ----------------------------------------------------------------------------
CREATE TABLE `T_CK_CT_RENTAL_VEH` (
  `RV_ID` varchar(35) NOT NULL COMMENT 'RENTAL RATE ID - UUID',
  `RV_RENTAL_TABLE` varchar(35) NOT NULL COMMENT 'RENTAL RATE TABLE - REFERENCES  T_CK_CT_RENTAL_TABLE:RT_ID',
  `RV_VEH_TYPE` varchar(35) DEFAULT NULL COMMENT 'RENTAL TYPE  - REFERENCES T_CK_CT_MST_VEH_TYPE:VHTY_ID',
  `RV_NUM_VEH` smallint DEFAULT 0 COMMENT 'NUMBER OF TRUCKS OR VEHICLE TO RENT',
  `RV_RENTAL_AMT` decimal(15,2) DEFAULT 0.00 COMMENT 'CHARGES FOR THE VEHICLE',
  `RV_RENTAL_TYPE` varchar(35) DEFAULT NULL COMMENT 'RENTAL TYPE - REFERENCES T_CK_CT_MST_RENTAL_TYPE:RT_ID',
  `RV_STATUS` char(1) DEFAULT NULL COMMENT 'RENTAL RATE STATE STATUS',
  `RV_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `RV_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `RV_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `RR_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`RV_ID`),
  CONSTRAINT `FK_CK_CT_RENTAL_RATE_CK_CT_RENTAL_TABLE` FOREIGN KEY (`RV_RENTAL_TABLE`) REFERENCES `T_CK_CT_RENTAL_TABLE` (`RT_ID`),  
  CONSTRAINT `FK_CK_CT_RENTAL_RATE_CK_CT_MST_VEH_TYPE` FOREIGN KEY (`RV_VEH_TYPE`) REFERENCES `T_CK_CT_MST_VEH_TYPE` (`VHTY_ID`), 
  CONSTRAINT `FK_CK_CT_RENTAL_RATE_CK_CT_MST_RENTAL_TYPE` FOREIGN KEY (`RV_RENTAL_TYPE`) REFERENCES `T_CK_CT_MST_RENTAL_TYPE` (`RT_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='RENTAL VEHICLE TABLE';

-- JOB TYPE (MASTER) ----------------------------------------------------------------------------
/*
-- Query: SELECT * FROM clickargo.T_CK_MST_JOB_TYPE
-- Date: 2023-01-18 15:03
*/
INSERT INTO `T_CK_MST_JOB_TYPE` (`JBT_ID`,`JBT_NAME`,`JBT_DESC`,`JBT_DESC_OTH`,`JBT_STATUS`,`JBT_DT_CREATE`,`JBT_UID_CREATE`,`JBT_DT_LUPD`,`JBT_UID_LUPD`) VALUES ('TREXP','TRUCKING EXPORT','TRUCKING EXPORT','TRUCKING EXPORT','A','2020-10-01 00:00:00','SYS','2020-10-01 00:00:00','SYS');
INSERT INTO `T_CK_MST_JOB_TYPE` (`JBT_ID`,`JBT_NAME`,`JBT_DESC`,`JBT_DESC_OTH`,`JBT_STATUS`,`JBT_DT_CREATE`,`JBT_UID_CREATE`,`JBT_DT_LUPD`,`JBT_UID_LUPD`) VALUES ('TRIMP','TRUCKING IMPORT','TRUCKING IMPORT','TRUCKING IMPORT','A','2020-10-01 00:00:00','SYS','2020-10-01 00:00:00','SYS');
INSERT INTO `T_CK_MST_JOB_TYPE` (`JBT_ID`,`JBT_NAME`,`JBT_DESC`,`JBT_DESC_OTH`,`JBT_STATUS`,`JBT_DT_CREATE`,`JBT_UID_CREATE`,`JBT_DT_LUPD`,`JBT_UID_LUPD`) VALUES ('TRLL','TRUCKING LASTMILE','TRUCKING LASTMILE','TRUCKING LASTMILE','A','2020-10-01 00:00:00','SYS','2020-10-01 00:00:00','SYS');
INSERT INTO `T_CK_MST_JOB_TYPE` (`JBT_ID`,`JBT_NAME`,`JBT_DESC`,`JBT_DESC_OTH`,`JBT_STATUS`,`JBT_DT_CREATE`,`JBT_UID_CREATE`,`JBT_DT_LUPD`,`JBT_UID_LUPD`) VALUES ('TRML','TRUCKING MIDMILE','TRUCKING MIDMILE','TRUCKING MIDMILE','A','2020-10-01 00:00:00','SYS','2020-10-01 00:00:00','SYS');

-- SHIPMENT ----------------------------------------------------------------------------
CREATE TABLE `T_CK_SHIPMENT` (
  `SPT_ID` varchar(35) NOT NULL COMMENT 'SHIPMENT ID - IMPORT : EXPORT : MIDMILE : LASTMILE',
  `SPT_TYPE` varchar(35) NOT NULL COMMENT 'SHIPMENT TYPE - REFERENCES T_CK_MST_SHIPMENT_TYPE:SHTY_ID',
  `SPT_STATE` varchar(35) NOT NULL COMMENT 'SHIPMENT STATE  - REFERENCES T_CK_MST_SHIPMENT_STATE:SHST_ID',
  `SPT_REFERENCE` varchar(255) DEFAULT NULL COMMENT 'SHIPMENT REFERENCE',
  `SPT_DESC` varchar(1024) NOT NULL COMMENT 'SHIPMENT DESCRIPTION',
  `SPT_DESC_OTH` varchar(2048) DEFAULT NULL COMMENT 'SHIPMENT DESCRIPTION OTHER LANGUAGE',
  `SPT_CARGO_OWNER` varchar(35) DEFAULT NULL COMMENT 'CARGO OWNER OF SHIPMENT - REFERENCES T_CORE_ACCN:ACCN_ID',
  `SPT_FORWARDER` varchar(35) DEFAULT NULL COMMENT 'CARGO OWNER OF SHIPMENT - REFERENCES T_CORE_ACCN:ACCN_ID',
  `SPT_TRUCKING_OPERATOR` varchar(35) DEFAULT NULL COMMENT 'CARGO OWNER OF SHIPMENT - REFERENCES T_CORE_ACCN:ACCN_ID',
  `SPT_COMMENTS` mediumtext DEFAULT NULL COMMENT 'SHIPMENT COMMENTS BY CARGO OWNER OR FORWARDER',
  `SPT_DT_START` datetime DEFAULT NULL COMMENT 'SHIPMENT START DATE',
  `SPT_DT_END` datetime DEFAULT NULL COMMENT 'SHIPMENT END DATE',
  `SPT_STATUS` char(1) DEFAULT NULL COMMENT 'SHIPMENT TYPE STATUS',
  `SPT_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `SPT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `SPT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `SPT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`SPT_ID`),
  CONSTRAINT `FK_CK_SHIPMENT_CK_MST_SHIPMENT_TYPE` FOREIGN KEY (`SPT_TYPE`) REFERENCES `T_CK_MST_SHIPMENT_TYPE` (`SHTY_ID`),
  CONSTRAINT `FK_CK_SHIPMENT_CK_MST_SHIPMENT_STATE` FOREIGN KEY (`SPT_STATE`) REFERENCES `T_CK_MST_SHIPMENT_STATE` (`SHST_ID`),
  CONSTRAINT `FK_CK_SHIPMENT_CORE_ACCN1` FOREIGN KEY (`SPT_CARGO_OWNER`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_SHIPMENT_CORE_ACCN2` FOREIGN KEY (`SPT_FORWARDER`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_SHIPMENT_CORE_ACCN3` FOREIGN KEY (`SPT_TRUCKING_OPERATOR`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='SHIPMENT TYPE TABLE';