package com.guudint.clickargo.clictruck.admin.shell.model;
// Generated 6 May 2024, 2:09:45 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtShellKiosk generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_SHELL_KIOSK")
public class TCkCtShellKiosk extends COAbstractEntity<TCkCtShellKiosk> {

	private static final long serialVersionUID = -8013989235890398690L;
	private String skId;
	private String skName;
	private Character skStatus;
	private Date skDtCreate;
	private String skUidCreate;
	private Date skDtLupd;
	private String skUidLupd;

	public TCkCtShellKiosk() {
	}

	public TCkCtShellKiosk(String skId) {
		this.skId = skId;
	}

	public TCkCtShellKiosk(String skId, String skName, Character skStatus, Date skDtCreate, String skUidCreate,
			Date skDtLupd, String skUidLupd) {
		this.skId = skId;
		this.skName = skName;
		this.skStatus = skStatus;
		this.skDtCreate = skDtCreate;
		this.skUidCreate = skUidCreate;
		this.skDtLupd = skDtLupd;
		this.skUidLupd = skUidLupd;
	}

	@Id

	@Column(name = "SK_ID", unique = true, nullable = false, length = 35)
	public String getSkId() {
		return this.skId;
	}

	public void setSkId(String skId) {
		this.skId = skId;
	}

	@Column(name = "SK_NAME", length = 1024)
	public String getSkName() {
		return this.skName;
	}

	public void setSkName(String skName) {
		this.skName = skName;
	}

	@Column(name = "SK_STATUS", length = 1)
	public Character getSkStatus() {
		return this.skStatus;
	}

	public void setSkStatus(Character skStatus) {
		this.skStatus = skStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SK_DT_CREATE", length = 19)
	public Date getSkDtCreate() {
		return this.skDtCreate;
	}

	public void setSkDtCreate(Date skDtCreate) {
		this.skDtCreate = skDtCreate;
	}

	@Column(name = "SK_UID_CREATE", length = 35)
	public String getSkUidCreate() {
		return this.skUidCreate;
	}

	public void setSkUidCreate(String skUidCreate) {
		this.skUidCreate = skUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SK_DT_LUPD", length = 19)
	public Date getSkDtLupd() {
		return this.skDtLupd;
	}

	public void setSkDtLupd(Date skDtLupd) {
		this.skDtLupd = skDtLupd;
	}

	@Column(name = "SK_UID_LUPD", length = 35)
	public String getSkUidLupd() {
		return this.skUidLupd;
	}

	public void setSkUidLupd(String skUidLupd) {
		this.skUidLupd = skUidLupd;
	}

	@Override
	public int compareTo(TCkCtShellKiosk o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
