package com.guudint.clickargo.clictruck.admin.shell.model;
// Generated 6 May 2024, 2:09:45 pm by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtShellTxn generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_SHELL_TXN")
public class TCkCtShellTxn extends COAbstractEntity<TCkCtShellTxn> {

	private static final long serialVersionUID = 8929725023560395337L;
	private String stId;
	private TCkCtShellCard TCkCtShellCard;
	private TCoreAccn TCoreAccn;
	private BigDecimal stQty;
	private String stProduct;
	private String stTxnId;
	private Date stTxnDate;
	private BigDecimal stInvNet;
	private BigDecimal stInvGross;
	private BigDecimal stCrvNet;
	private BigDecimal stCrvGross;
	private Character sbStatus;
	private Date sbDtCreate;
	private String sbUidCreate;
	private Date sbDtLupd;
	private String sbUidLupd;

	public TCkCtShellTxn() {
	}

	public TCkCtShellTxn(String stId) {
		this.stId = stId;
	}

	public TCkCtShellTxn(String stId, TCkCtShellCard TCkCtShellCard, TCoreAccn TCoreAccn, BigDecimal stQty,
			String stProduct, String stTxnId, Date stTxnDate, BigDecimal stInvNet, BigDecimal stInvGross,
			BigDecimal stCrvNet, BigDecimal stCrvGross, Character sbStatus, Date sbDtCreate, String sbUidCreate,
			Date sbDtLupd, String sbUidLupd) {
		this.stId = stId;
		this.TCkCtShellCard = TCkCtShellCard;
		this.TCoreAccn = TCoreAccn;
		this.stQty = stQty;
		this.stProduct = stProduct;
		this.stTxnId = stTxnId;
		this.stTxnDate = stTxnDate;
		this.stInvNet = stInvNet;
		this.stInvGross = stInvGross;
		this.stCrvNet = stCrvNet;
		this.stCrvGross = stCrvGross;
		this.sbStatus = sbStatus;
		this.sbDtCreate = sbDtCreate;
		this.sbUidCreate = sbUidCreate;
		this.sbDtLupd = sbDtLupd;
		this.sbUidLupd = sbUidLupd;
	}

	@Id

	@Column(name = "ST_ID", unique = true, nullable = false, length = 35)
	public String getStId() {
		return this.stId;
	}

	public void setStId(String stId) {
		this.stId = stId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ST_CARD")
	public TCkCtShellCard getTCkCtShellCard() {
		return this.TCkCtShellCard;
	}

	public void setTCkCtShellCard(TCkCtShellCard TCkCtShellCard) {
		this.TCkCtShellCard = TCkCtShellCard;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ST_ACCN")
	public TCoreAccn getTCoreAccn() {
		return this.TCoreAccn;
	}

	public void setTCoreAccn(TCoreAccn TCoreAccn) {
		this.TCoreAccn = TCoreAccn;
	}

	@Column(name = "ST_QTY", precision = 8)
	public BigDecimal getStQty() {
		return this.stQty;
	}

	public void setStQty(BigDecimal stQty) {
		this.stQty = stQty;
	}

	@Column(name = "ST_PRODUCT", length = 512)
	public String getStProduct() {
		return this.stProduct;
	}

	public void setStProduct(String stProduct) {
		this.stProduct = stProduct;
	}

	@Column(name = "ST_TXN_ID", length = 256)
	public String getStTxnId() {
		return this.stTxnId;
	}

	public void setStTxnId(String stTxnId) {
		this.stTxnId = stTxnId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ST_TXN_DATE", length = 19)
	public Date getStTxnDate() {
		return this.stTxnDate;
	}

	public void setStTxnDate(Date stTxnDate) {
		this.stTxnDate = stTxnDate;
	}

	@Column(name = "ST_INV_NET", precision = 15)
	public BigDecimal getStInvNet() {
		return this.stInvNet;
	}

	public void setStInvNet(BigDecimal stInvNet) {
		this.stInvNet = stInvNet;
	}

	@Column(name = "ST_INV_GROSS", precision = 15)
	public BigDecimal getStInvGross() {
		return this.stInvGross;
	}

	public void setStInvGross(BigDecimal stInvGross) {
		this.stInvGross = stInvGross;
	}

	@Column(name = "ST_CRV_NET", precision = 15)
	public BigDecimal getStCrvNet() {
		return this.stCrvNet;
	}

	public void setStCrvNet(BigDecimal stCrvNet) {
		this.stCrvNet = stCrvNet;
	}

	@Column(name = "ST_CRV_GROSS", precision = 15)
	public BigDecimal getStCrvGross() {
		return this.stCrvGross;
	}

	public void setStCrvGross(BigDecimal stCrvGross) {
		this.stCrvGross = stCrvGross;
	}

	@Column(name = "SB_STATUS", length = 1)
	public Character getSbStatus() {
		return this.sbStatus;
	}

	public void setSbStatus(Character sbStatus) {
		this.sbStatus = sbStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SB_DT_CREATE", length = 19)
	public Date getSbDtCreate() {
		return this.sbDtCreate;
	}

	public void setSbDtCreate(Date sbDtCreate) {
		this.sbDtCreate = sbDtCreate;
	}

	@Column(name = "SB_UID_CREATE", length = 35)
	public String getSbUidCreate() {
		return this.sbUidCreate;
	}

	public void setSbUidCreate(String sbUidCreate) {
		this.sbUidCreate = sbUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SB_DT_LUPD", length = 19)
	public Date getSbDtLupd() {
		return this.sbDtLupd;
	}

	public void setSbDtLupd(Date sbDtLupd) {
		this.sbDtLupd = sbDtLupd;
	}

	@Column(name = "SB_UID_LUPD", length = 35)
	public String getSbUidLupd() {
		return this.sbUidLupd;
	}

	public void setSbUidLupd(String sbUidLupd) {
		this.sbUidLupd = sbUidLupd;
	}

	@Override
	public int compareTo(TCkCtShellTxn o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
