package com.guudint.clickargo.clictruck.admin.shell.model;
// Generated 6 May 2024, 2:09:45 pm by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtShellInvoice generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_SHELL_INVOICE")
public class TCkCtShellInvoice extends COAbstractEntity<TCkCtShellInvoice> {

	private static final long serialVersionUID = 2381967817169378730L;
	private String invId;
	private TCoreAccn TCoreAccn;
	private String invNo;
	private Date invDt;
	private BigDecimal invAmt;
	private Date invPaymentDt;
	private BigDecimal invPaymentAmt;
	private BigDecimal invBalanceAmt;
	private Character invStatus;
	private Date invDtCreate;
	private String invUidCreate;
	private Date invDtLupd;
	private String invUidLupd;

	public TCkCtShellInvoice() {
	}

	public TCkCtShellInvoice(String invId) {
		this.invId = invId;
	}

	public TCkCtShellInvoice(String invId, TCoreAccn TCoreAccn, String invNo, Date invDt, BigDecimal invAmt,
			Date invPaymentDt, BigDecimal invPaymentAmt, BigDecimal invBalanceAmt, Character invStatus,
			Date invDtCreate, String invUidCreate, Date invDtLupd, String invUidLupd) {
		this.invId = invId;
		this.TCoreAccn = TCoreAccn;
		this.invNo = invNo;
		this.invDt = invDt;
		this.invAmt = invAmt;
		this.invPaymentDt = invPaymentDt;
		this.invPaymentAmt = invPaymentAmt;
		this.invBalanceAmt = invBalanceAmt;
		this.invStatus = invStatus;
		this.invDtCreate = invDtCreate;
		this.invUidCreate = invUidCreate;
		this.invDtLupd = invDtLupd;
		this.invUidLupd = invUidLupd;
	}

	@Id

	@Column(name = "INV_ID", unique = true, nullable = false, length = 35)
	public String getInvId() {
		return this.invId;
	}

	public void setInvId(String invId) {
		this.invId = invId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "INV_ACCN")
	public TCoreAccn getTCoreAccn() {
		return this.TCoreAccn;
	}

	public void setTCoreAccn(TCoreAccn TCoreAccn) {
		this.TCoreAccn = TCoreAccn;
	}

	@Column(name = "INV_NO", length = 256)
	public String getInvNo() {
		return this.invNo;
	}

	public void setInvNo(String invNo) {
		this.invNo = invNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INV_DT", length = 19)
	public Date getInvDt() {
		return this.invDt;
	}

	public void setInvDt(Date invDt) {
		this.invDt = invDt;
	}

	@Column(name = "INV_AMT", precision = 15)
	public BigDecimal getInvAmt() {
		return this.invAmt;
	}

	public void setInvAmt(BigDecimal invAmt) {
		this.invAmt = invAmt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INV_PAYMENT_DT", length = 19)
	public Date getInvPaymentDt() {
		return this.invPaymentDt;
	}

	public void setInvPaymentDt(Date invPaymentDt) {
		this.invPaymentDt = invPaymentDt;
	}

	@Column(name = "INV_PAYMENT_AMT", precision = 15)
	public BigDecimal getInvPaymentAmt() {
		return this.invPaymentAmt;
	}

	public void setInvPaymentAmt(BigDecimal invPaymentAmt) {
		this.invPaymentAmt = invPaymentAmt;
	}

	@Column(name = "INV_BALANCE_AMT", precision = 15)
	public BigDecimal getInvBalanceAmt() {
		return this.invBalanceAmt;
	}

	public void setInvBalanceAmt(BigDecimal invBalanceAmt) {
		this.invBalanceAmt = invBalanceAmt;
	}

	@Column(name = "INV_STATUS", length = 1)
	public Character getInvStatus() {
		return this.invStatus;
	}

	public void setInvStatus(Character invStatus) {
		this.invStatus = invStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INV_DT_CREATE", length = 19)
	public Date getInvDtCreate() {
		return this.invDtCreate;
	}

	public void setInvDtCreate(Date invDtCreate) {
		this.invDtCreate = invDtCreate;
	}

	@Column(name = "INV_UID_CREATE", length = 35)
	public String getInvUidCreate() {
		return this.invUidCreate;
	}

	public void setInvUidCreate(String invUidCreate) {
		this.invUidCreate = invUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INV_DT_LUPD", length = 19)
	public Date getInvDtLupd() {
		return this.invDtLupd;
	}

	public void setInvDtLupd(Date invDtLupd) {
		this.invDtLupd = invDtLupd;
	}

	@Column(name = "INV_UID_LUPD", length = 35)
	public String getInvUidLupd() {
		return this.invUidLupd;
	}

	public void setInvUidLupd(String invUidLupd) {
		this.invUidLupd = invUidLupd;
	}

	@Override
	public int compareTo(TCkCtShellInvoice o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
