package com.guudint.clickargo.clictruck.admin.shell.model;
// Generated 6 May 2024, 2:09:45 pm by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.guudint.clickargo.clictruck.common.model.TCkCtVeh;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtShellInvoiceItem generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_SHELL_INVOICE_ITEM")
public class TCkCtShellInvoiceItem extends COAbstractEntity<TCkCtShellInvoiceItem> {

	private static final long serialVersionUID = -1050577483082440468L;
	private String itmId;
	private TCkCtShellCard TCkCtShellCard;
	private TCkCtShellInvoice TCkCtShellInvoice;
	private TCkCtVeh TCkCtVeh;
	private String itmDesc;
	private Date itmDtTxn;
	private BigDecimal itmCost;
	private BigDecimal itmDiscount;
	private BigDecimal itmTax;
	private BigDecimal itmCo2;
	private BigDecimal itmTotal;
	private Character itmStatus;
	private Date itmDtCreate;
	private String itmUidCreate;
	private Date itmDtLupd;
	private String itmUidLupd;

	public TCkCtShellInvoiceItem() {
	}

	public TCkCtShellInvoiceItem(String itmId) {
		this.itmId = itmId;
	}

	public TCkCtShellInvoiceItem(String itmId, TCkCtShellCard TCkCtShellCard, TCkCtShellInvoice TCkCtShellInvoice,
			TCkCtVeh TCkCtVeh, String itmDesc, Date itmDtTxn, BigDecimal itmCost, BigDecimal itmDiscount,
			BigDecimal itmTax, BigDecimal itmCo2, BigDecimal itmTotal, Character itmStatus, Date itmDtCreate,
			String itmUidCreate, Date itmDtLupd, String itmUidLupd) {
		this.itmId = itmId;
		this.TCkCtShellCard = TCkCtShellCard;
		this.TCkCtShellInvoice = TCkCtShellInvoice;
		this.TCkCtVeh = TCkCtVeh;
		this.itmDesc = itmDesc;
		this.itmDtTxn = itmDtTxn;
		this.itmCost = itmCost;
		this.itmDiscount = itmDiscount;
		this.itmTax = itmTax;
		this.itmCo2 = itmCo2;
		this.itmTotal = itmTotal;
		this.itmStatus = itmStatus;
		this.itmDtCreate = itmDtCreate;
		this.itmUidCreate = itmUidCreate;
		this.itmDtLupd = itmDtLupd;
		this.itmUidLupd = itmUidLupd;
	}

	@Id

	@Column(name = "ITM_ID", unique = true, nullable = false, length = 35)
	public String getItmId() {
		return this.itmId;
	}

	public void setItmId(String itmId) {
		this.itmId = itmId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ITM_CARD")
	public TCkCtShellCard getTCkCtShellCard() {
		return this.TCkCtShellCard;
	}

	public void setTCkCtShellCard(TCkCtShellCard TCkCtShellCard) {
		this.TCkCtShellCard = TCkCtShellCard;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ITM_INV")
	public TCkCtShellInvoice getTCkCtShellInvoice() {
		return this.TCkCtShellInvoice;
	}

	public void setTCkCtShellInvoice(TCkCtShellInvoice TCkCtShellInvoice) {
		this.TCkCtShellInvoice = TCkCtShellInvoice;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ITM_TRUCK")
	public TCkCtVeh getTCkCtVeh() {
		return this.TCkCtVeh;
	}

	public void setTCkCtVeh(TCkCtVeh TCkCtVeh) {
		this.TCkCtVeh = TCkCtVeh;
	}

	@Column(name = "ITM_DESC", length = 512)
	public String getItmDesc() {
		return this.itmDesc;
	}

	public void setItmDesc(String itmDesc) {
		this.itmDesc = itmDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ITM_DT_TXN", length = 19)
	public Date getItmDtTxn() {
		return this.itmDtTxn;
	}

	public void setItmDtTxn(Date itmDtTxn) {
		this.itmDtTxn = itmDtTxn;
	}

	@Column(name = "ITM_COST", precision = 15)
	public BigDecimal getItmCost() {
		return this.itmCost;
	}

	public void setItmCost(BigDecimal itmCost) {
		this.itmCost = itmCost;
	}

	@Column(name = "ITM_DISCOUNT", precision = 15)
	public BigDecimal getItmDiscount() {
		return this.itmDiscount;
	}

	public void setItmDiscount(BigDecimal itmDiscount) {
		this.itmDiscount = itmDiscount;
	}

	@Column(name = "ITM_TAX", precision = 15)
	public BigDecimal getItmTax() {
		return this.itmTax;
	}

	public void setItmTax(BigDecimal itmTax) {
		this.itmTax = itmTax;
	}

	@Column(name = "ITM_CO2", precision = 15)
	public BigDecimal getItmCo2() {
		return this.itmCo2;
	}

	public void setItmCo2(BigDecimal itmCo2) {
		this.itmCo2 = itmCo2;
	}

	@Column(name = "ITM_TOTAL", precision = 15)
	public BigDecimal getItmTotal() {
		return this.itmTotal;
	}

	public void setItmTotal(BigDecimal itmTotal) {
		this.itmTotal = itmTotal;
	}

	@Column(name = "ITM_STATUS", length = 1)
	public Character getItmStatus() {
		return this.itmStatus;
	}

	public void setItmStatus(Character itmStatus) {
		this.itmStatus = itmStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ITM_DT_CREATE", length = 19)
	public Date getItmDtCreate() {
		return this.itmDtCreate;
	}

	public void setItmDtCreate(Date itmDtCreate) {
		this.itmDtCreate = itmDtCreate;
	}

	@Column(name = "ITM_UID_CREATE", length = 35)
	public String getItmUidCreate() {
		return this.itmUidCreate;
	}

	public void setItmUidCreate(String itmUidCreate) {
		this.itmUidCreate = itmUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ITM_DT_LUPD", length = 19)
	public Date getItmDtLupd() {
		return this.itmDtLupd;
	}

	public void setItmDtLupd(Date itmDtLupd) {
		this.itmDtLupd = itmDtLupd;
	}

	@Column(name = "ITM_UID_LUPD", length = 35)
	public String getItmUidLupd() {
		return this.itmUidLupd;
	}

	public void setItmUidLupd(String itmUidLupd) {
		this.itmUidLupd = itmUidLupd;
	}

	@Override
	public int compareTo(TCkCtShellInvoiceItem o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
