package com.guudint.clickargo.clictruck.admin.shell.model;
// Generated 6 May 2024, 2:09:45 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.guudint.clickargo.clictruck.common.model.TCkCtVeh;
import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtShellCardTruck generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_SHELL_CARD_TRUCK")
public class TCkCtShellCardTruck extends COAbstractEntity<TCkCtShellCardTruck> {

	private static final long serialVersionUID = -3218528329428513958L;
	private String ctId;
	private TCkCtShellCard TCkCtShellCard;
	private TCkCtVeh TCkCtVeh;
	private TCoreAccn TCoreAccn;
	private Character ctStatus;
	private Date ctDtCreate;
	private String ctUidCreate;
	private Date ctDtLupd;
	private String ctUidLupd;

	public TCkCtShellCardTruck() {
	}

	public TCkCtShellCardTruck(String ctId) {
		this.ctId = ctId;
	}

	public TCkCtShellCardTruck(String ctId, TCkCtShellCard TCkCtShellCard, TCkCtVeh TCkCtVeh, TCoreAccn TCoreAccn,
			Character ctStatus, Date ctDtCreate, String ctUidCreate, Date ctDtLupd, String ctUidLupd) {
		this.ctId = ctId;
		this.TCkCtShellCard = TCkCtShellCard;
		this.TCkCtVeh = TCkCtVeh;
		this.TCoreAccn = TCoreAccn;
		this.ctStatus = ctStatus;
		this.ctDtCreate = ctDtCreate;
		this.ctUidCreate = ctUidCreate;
		this.ctDtLupd = ctDtLupd;
		this.ctUidLupd = ctUidLupd;
	}

	@Id

	@Column(name = "CT_ID", unique = true, nullable = false, length = 35)
	public String getCtId() {
		return this.ctId;
	}

	public void setCtId(String ctId) {
		this.ctId = ctId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CT_CARD")
	public TCkCtShellCard getTCkCtShellCard() {
		return this.TCkCtShellCard;
	}

	public void setTCkCtShellCard(TCkCtShellCard TCkCtShellCard) {
		this.TCkCtShellCard = TCkCtShellCard;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CT_TRUCK")
	public TCkCtVeh getTCkCtVeh() {
		return this.TCkCtVeh;
	}

	public void setTCkCtVeh(TCkCtVeh TCkCtVeh) {
		this.TCkCtVeh = TCkCtVeh;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CT_ACCN")
	public TCoreAccn getTCoreAccn() {
		return this.TCoreAccn;
	}

	public void setTCoreAccn(TCoreAccn TCoreAccn) {
		this.TCoreAccn = TCoreAccn;
	}

	@Column(name = "CT_STATUS", length = 1)
	public Character getCtStatus() {
		return this.ctStatus;
	}

	public void setCtStatus(Character ctStatus) {
		this.ctStatus = ctStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CT_DT_CREATE", length = 19)
	public Date getCtDtCreate() {
		return this.ctDtCreate;
	}

	public void setCtDtCreate(Date ctDtCreate) {
		this.ctDtCreate = ctDtCreate;
	}

	@Column(name = "CT_UID_CREATE", length = 35)
	public String getCtUidCreate() {
		return this.ctUidCreate;
	}

	public void setCtUidCreate(String ctUidCreate) {
		this.ctUidCreate = ctUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CT_DT_LUPD", length = 19)
	public Date getCtDtLupd() {
		return this.ctDtLupd;
	}

	public void setCtDtLupd(Date ctDtLupd) {
		this.ctDtLupd = ctDtLupd;
	}

	@Column(name = "CT_UID_LUPD", length = 35)
	public String getCtUidLupd() {
		return this.ctUidLupd;
	}

	public void setCtUidLupd(String ctUidLupd) {
		this.ctUidLupd = ctUidLupd;
	}

	@Override
	public int compareTo(TCkCtShellCardTruck o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
