import Mock from "../mock";

const data = [
  {
    otherLangDesc: null,
    coreMstLocale: null,
    atypId: "ACC_TYPE_CAMELONE",
    atypDescription: "ADMIN",
    atypDescriptionOth: null,
    atypStatus: "A",
    atypDtCreate: 1664553600000,
    atypUidCreate: "SYS",
    atypDtLupd: 1664553600000,
    atypUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    atypId: "ACC_TYPE_CK",
    atypDescription: "CLICKARGO",
    atypDescriptionOth: null,
    atypStatus: "A",
    atypDtCreate: 1664553600000,
    atypUidCreate: "SYS",
    atypDtLupd: 1664553600000,
    atypUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    atypId: "ACC_TYPE_CO",
    atypDescription: "CARGO OWNER",
    atypDescriptionOth: null,
    atypStatus: "A",
    atypDtCreate: 1664553600000,
    atypUidCreate: "SYS",
    atypDtLupd: 1664553600000,
    atypUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    atypId: "ACC_TYPE_FF",
    atypDescription: "FREIGHT FORWADER",
    atypDescriptionOth: null,
    atypStatus: "A",
    atypDtCreate: 1664553600000,
    atypUidCreate: "SYS",
    atypDtLupd: 1664553600000,
    atypUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    atypId: "ACC_TYPE_SL",
    atypDescription: "SHIPPING LINE",
    atypDescriptionOth: null,
    atypStatus: "A",
    atypDtCreate: 1664553600000,
    atypUidCreate: "SYS",
    atypDtLupd: 1664553600000,
    atypUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    atypId: "ACC_TYPE_SP",
    atypDescription: "SERVICE PROVIDER",
    atypDescriptionOth: null,
    atypStatus: "A",
    atypDtCreate: 1664553600000,
    atypUidCreate: "SYS",
    atypDtLupd: 1664553600000,
    atypUidLupd: "SYS",
  },
];

Mock.onGet("/api/co/master/entity/accnType").reply((config) => {
    return [200, data];
  });