import Mock from "../mock";

import * as WorkflowUtil from "app/views/applications/WorkflowUtil";

export const arrivalDeclarationDB = {
    list: [
        {
          appId: "AD20210308001",
          version: "1",
          appType: "AD",
          arrivalPort: "KHPNH",
          impNo: "ERT33456",
          shipName: "Maersk Alabama",
          shipCountry: "SG",
          lastPortCountry: "TH",
          applicantTin: "2332434232",
          submitDate: "2020-11-20T12:30:45",
          workflowName: "AD",
          // status: WorkflowUtil.WorkflowStage.PendingVerification,
          status: "P",
          statusBodCu: WorkflowUtil.WorkflowStage.Approved,
          statusBodIm: WorkflowUtil.WorkflowStage.PendingApproval,
          statusBodQu: WorkflowUtil.WorkflowStage.PendingVerification,
          statusPortCu: WorkflowUtil.WorkflowStage.PendingVerification,
          statusPortIm: WorkflowUtil.WorkflowStage.PendingVerification,
          statusPortQu: WorkflowUtil.WorkflowStage.PendingVerification,
          statusPort: WorkflowUtil.WorkflowStage.PendingVerification,
          callSign: "TR098234",
          masterName: "Tom Hanks",
          portOfArrivalOrDept: "PPAP",
          dateOfArrv: "13-12-2020",
          portArrivedFrom: "SG",
          nextPort: "SG",
          dateOfDeparture: "12-1-2020",
          stowaways: "Y",
          animalOrPlants: "N",
          parcelPackage: "Y",
          armsAmmunitions: "N",
          illegalDrugs: "N",
          passengers: "Y",
          livestocks: "N",
          signUpload: "",
          reqMessage: "",
          application: "NIL",
          header: {
            type: "arrival",
            voyageDetails: {
              vcrNo: "PEDI202012123",
              voyageNo: "PEDI944832",
              voyageName: "ERT-2324",
    
              arrivalPort: "KHPNH",
              arrivalDate: "2021-01-12",
              arrivalTime: "10:00:00",
              lastPortCountry: "TH",
              lastPort: "THKRB",
              departurePort: "KHPNH",
              departureDate: "21-10-2021",
              DepartureTime: "10:00:00",
              nextPortCountry: "SG",
              nextPort: "SGJUR",
              dutyPaidAt: "BORDER",
            },
            shipDetails: {
              impNo: "ERT33456",
              shipName: "Maersk Alabama",
              shipCountry: "SG",
              callSign: "TR098234",
              flageState: "FL1234",
              shipType: "TANKER",
              applicantTin: "L3342234232",
              applicantName: "CAM SHIPPING COMPANY",
            },
          },
          falForm: {
            fal1: {
              certificateReg: "VR 03455",
              grossTonnage: "1589 GT",
              netTonnage: "1098 NT",
              voyageDesc: "Transporting medical equipments",
              cargoDesc: "All containers contains medical equipments and medicines",
              remarks: "Please refer manifest for more details",
              facilities: "Provided by the port",
            },
            fal2: {
              list: [
                {
                  blNo: "123",
                  marksNo: "ER345",
                  kindPck: "300 Tn",
                  grossWeight: "400",
                  measurement: "100",
                },
                {
                  blNo: "4544",
                  marksNo: "YT455",
                  kindPck: "100 Tn",
                  grossWeight: "200",
                  measurement: "320",
                },
                {
                  blNo: "5766",
                  marksNo: "HG5645",
                  kindPck: "300 Tn",
                  grossWeight: "200",
                  measurement: "444",
                },
              ],
              cargoDetails: {
                blNo: "123",
                marksNo: "ER345",
                kindPck: "Medicinal Equipments",
                grossWeight: "400",
                measurement: "100",
              },
              cargoDeclaration: {
                billInfo: {
                  billNo: "111",
                  billType: "Bill",
                  billNature: "NT345",
                  billMasterNo: "MS234",
    
                  placeLoading: "Phnom Penh",
                  placeUnloading: "Singapore",
                  portLoading: "CAM",
                  portUnloading: "SG",
                },
                traderInfo: {
                  exporterName: "Shipping Line 1",
                  exporterAddress: "Wat Nom",
                  consigneeName: "Shipping Line 2",
                  consigneeAddress: "Poi Pet",
                  consigneeCode: "ER333",
                  notifyName: "Notifier 1",
                  notifyAddress: "Phnom Penh",
                  notifyCode: "RT445",
                },
                goodsInfo: {
                  goodsDescription: "Medicinal Equipments",
                  numberOfContainers: "12",
                  numberOfPackages: "200",
                  packageType: "Closed containers",
                  grossMass: "1003 Tonne",
                  volumeInCubicMeters: "2033 CC",
                  numberOfSeals: "23",
                  sealPartyCode: "TT 4533",
                  sealsMarks: "24",
                  shippingMarks: "None",
                  information: "Refer manifest",
                },
                containerInfo: {
                  list: [
                    {
                      containerNo: "1234",
                      contanerType: "ER123",
                      emptyOrFull: "Chemicals",
                      nameCode: "300Tn",
                    },
                    {
                      containerNo: "4567",
                      contanerType: "RV123",
                      emptyOrFull: "Petrol",
                      nameCode: "100Tn",
                    },
                  ],
                  containerDetails: {
                    containerNo: "CONT001",
                    contanerType: "Closed Container",
                    emptyOrFull: "Full",
                    nameCode: "CONT202012",
                    noOfPackages: "34",
                    goodsDescription: "Medical Equipments",
                    grossMass: "2244 Tonne",
    
                    sealingParty: "Cambodia Agency",
                    marks1: "M1",
                    marks2: "M2",
                    marks3: "M3",
                    minTemp: "19 Deg Cel",
                    maxTemp: "34 Deg Cel",
                    humidity: "33 Ps",
                    dangerousGoods: "none",
                  },
                },
              },
            },
    
            fal3: {
              stayPeriod: "4",
              onBoardPersons: "215",
              list: [
                {
                  locationOnBoard: "Chemical Container",
                  quantity: "20 Tn",
                  articleName: "Upper Deck",
                },
                {
                  locationOnBoard: "Petroleum Products",
                  quantity: "40 Tn",
                  articleName: "Lower Deck",
                },
              ],
              ShipStoresDeclaration: {
                articleName: "Coal",
                quantity: "5 Tn",
                locationOnBoard: "Bishan",
                selectType: "Tonne",
              },
            },
            fal4: {
              list: [
                {
                  familyName: "John Doe",
                  givenName: "Alex",
                  rankRating: "Rank1",
                  nationality: "Vietnamese",
                  dob: "04-20-1985",
                  signature: "",
                  effects: "Cigars",
                  identityDocType: "Identity.pdf",
                  dateOfBirth: "04/20/1985",
                  placeOfBirth: "Vietnam",
                  gender: "Male",
                  typeOfIdentity: "Passport",
                  serialNumberOfIdentity: "1234444",
                  issuingStateOfIdentity: "VN",
                  expiryDateOfIdentity: "01/20/2030",
                  portOfEmberkation: "",
                  visaNumber: "VISA1234555",
                  portOfDisemberkation: "CAMBODIA",
                },
              ],
              AddCrew: {
                familyName: "John Doe",
                givenName: "Alex",
                nationality: "Vietnamese",
                dateOfBirth: "04-20-1985",
                placeOfBirth: "Vietnam",
                gender: "Male",
                rankRating: "Rank1",
                typeOfIdentity: "Passport",
                serialNumberOfIdentity: "1234444",
                issuingStateOfIdentity: "VN",
                expiryDateOfIdentity: "01/20/2030",
                portOfEmberkation: "",
                visaNumber: "VISA1234555",
                portOfDisemberkation: "CAMBODIA",
              },
            },
            fal5: {
              list: [
                {
                  familyName: "John Doe",
                  givenName: "Alex",
                  rankRating: "Rank1",
                  dob: "04-20-1985",
                  effects: "Cigars",
                  identityDocType: "Identity.pdf",
                  dateOfBirth: "04/20/1985",
                  placeOfBirth: "Vietnam",
                  gender: "Male",
                  typeOfIdentity: "Passport",
                  serialNumberOfIdentity: "1234444",
                  issuingStateOfIdentity: "VN",
                  expiryDateOfIdentity: "01/20/2030",
                  portOfEmberkation: "",
                  visaNumber: "VISA1234555",
                  portOfDisemberkation: "CAMBODIA",
                },
              ],
    
              AddEffect: {
                familyName: "John Doe",
                givenName: "Alex",
                nationality: "Vietnamese",
                dateOfBirth: "04/20/1985",
                placeOfBirth: "Vietnam",
                gender: "Male",
                rankRating: "Rank1",
                typeOfIdentity: "Passport",
                serialNumberOfIdentity: "1234444",
                issuingStateOfIdentity: "VN",
                expiryDateOfIdentity: "01/20/2030",
                portOfEmberkation: "",
                visaNumber: "VISA1234555",
                portOfDisemberkation: "CAMBODIA",
                effects: "Eligible",
                signature: "JOHN Sign",
              },
            },
    
            fal6: {
              list: [
                {
                  familyName: "John Doe",
                  givenName: "Alex",
                  nationality: "JAPAN",
                  identityType: "Passport",
                  dateOfBirth: "04-20-1985",
                  identityDocType: "Identity.pdf",
                  placeOfBirth: "VN",
                  gender: "Male",
                  typeOfIdentity: "Passport",
                  serialNumberOfIdentity: "1234444",
                  issuingStateOfIdentity: "VN",
                  expiryDateOfIdentity: "01/20/2030",
                  portOfEmberkation: "CAMBODIA",
                  visaNumber: "V1234",
                  portOfDisemberkation: "CAMBODIA",
                  transitPassenger: "No",
                },
              ],
              AddPassenger: {
                familyName: "Doe",
                givenName: "John",
                nationality: "Vietnamese",
                dateOfBirth: "04/20/1985",
                placeOfBirth: "VN",
                gender: "Male",
                typeOfIdentity: "Passport",
                serialNumberOfIdentity: "1234444",
                issuingStateOfIdentity: "VN",
                expiryDateOfIdentity: "01/20/2030",
                portOfEmberkation: "CAMBODIA",
                visaNumber: "V1234",
                portOfDisemberkation: "CAMBODIA",
                transitPassenger: "No",
              },
            },
            fal7: {
              list: [
                {
                  stowagePosition: "Lower Deck",
                  referenceNumber: "REF20210212",
                  marksNumber: "100",
                  unNumber: "HK463",
                  forVIdentification: "IDV20210214",
                  properShippingName: "Maersk",
                  corSRisks: "None",
                  packingGroup: "GRP213",
                  additionalInformation: "GARBAGE CANS",
                  numberAndKindOfPackages: "GARBAGE",
                  massOrVolume: "2 Tonne",
                  ems: "NA",
                },
                {
                  stowagePosition: "Upper Deck",
                  referenceNumber: "REF202102234",
                  marksNumber: "200",
                  unNumber: "BG45665",
                  forVIdentification: "IDV20210214",
                  properShippingName: "Maersk",
                  corSRisks: "None",
                  packingGroup: "GRP213",
                  additionalInformation: "GARBAGE CANS",
                  numberAndKindOfPackages: "GARBAGE",
                  massOrVolume: "2 Tonne",
                  ems: "NA",
                },
              ],
              AddDangerousGoods: {
                stowagePosition: "Lower Deck",
                referenceNumber: "REF20210212",
                marksNumber: "100",
                forVIdentification: "IDV20210214",
                unNumber: "UN234",
                properShippingName: "Maersk",
                corSRisks: "None",
                packingGroup: "GRP213",
                additionalInformation: "GARBAGE CANS",
                numberAndKindOfPackages: "GARBAGE",
                massOrVolume: "2 Tonne",
                ems: "NA",
              },
            },
          },
          others: {
            vaccination: {
              list: [
                {
                  familyName: "John Doe",
                  givenName: "Alex",
                  rankRating: "Rank1",
                  nationality: "Vietnamese",
                  dob: "04/20/1985",
                  signature: "",
                  effects: "Cigars",
                },
              ],
              AddCrew: {
                familyName: "John Doe",
                givenName: "Alex",
                nationality: "Vietnamese",
                dateOfBirth: "04/20/1985",
                placeOfBirth: "Vietnam",
                gender: "Male",
                rankRating: "Rank1",
                typeOfIdentity: "Passport",
                serialNumberOfIdentity: "1234444",
                issuingStateOfIdentity: "VN",
                expiryDateOfIdentity: "01/20/2030",
                portOfEmberkation: "",
                visaNumber: "VISA1234555",
                portOfDisemberkation: "CAMBODIA",
              },
            },
          },
          supportingDocs: {
            docType: "Ship Security Info Doc",
            docRefNo: "SS20201221",
          },
        },
        {
          appId: "AD20210308002",
          version: "1",
          appType: "AD",
          arrivalPort: "KHPNH",
          impNo: "ERT33456",
          shipName: "Maersk Alabama",
          shipCountry: "SG",
          lastPortCountry: "TH",
          applicantTin: "2332434232",
          submitDate: "2020-11-20T12:30:45",
          workflowName: "AD",
          // status: WorkflowUtil.WorkflowStage.PendingVerification,
          status: "P",
          statusBodCu: WorkflowUtil.WorkflowStage.Approved,
          statusBodIm: WorkflowUtil.WorkflowStage.Approved,
          statusBodQu: WorkflowUtil.WorkflowStage.Approved,
          statusPortCu: WorkflowUtil.WorkflowStage.PendingVerification,
          statusPortIm: WorkflowUtil.WorkflowStage.PendingVerification,
          statusPortQu: WorkflowUtil.WorkflowStage.PendingVerification,
          statusPort: WorkflowUtil.WorkflowStage.PendingVerification,
          callSign: "TR098234",
          masterName: "Tom Hanks",
          portOfArrivalOrDept: "PPAP",
          dateOfArrv: "13-12-2020",
          portArrivedFrom: "SG",
          nextPort: "SG",
          dateOfDeparture: "12-1-2020",
          stowaways: "Y",
          animalOrPlants: "N",
          parcelPackage: "Y",
          armsAmmunitions: "N",
          illegalDrugs: "N",
          passengers: "Y",
          livestocks: "N",
          signUpload: "",
          reqMessage: "",
          application: "NIL",
          header: {
            type: "arrival",
            voyageDetails: {
              vcrNo: "PEDI202012123",
              voyageNo: "PEDI944832",
              voyageName: "ERT-2324",
    
              arrivalPort: "KHPNH",
              arrivalDate: "2021-01-12",
              arrivalTime: "10:00:00",
              lastPortCountry: "TH",
              lastPort: "THKRB",
              departurePort: "KHPNH",
              departureDate: "21-10-2021",
              DepartureTime: "10:00:00",
              nextPortCountry: "SG",
              nextPort: "SGJUR",
              dutyPaidAt: "BORDER",
            },
            shipDetails: {
              impNo: "ERT33456",
              shipName: "Maersk Alabama",
              shipCountry: "SG",
              callSign: "TR098234",
              flageState: "FL1234",
              shipType: "TANKER",
              applicantTin: "L3342234232",
              applicantName: "CAM SHIPPING COMPANY",
            },
          },
          falForm: {
            fal1: {
              certificateReg: "VR 03455",
              grossTonnage: "1589 GT",
              netTonnage: "1098 NT",
              voyageDesc: "Transporting medical equipments",
              cargoDesc: "All containers contains medical equipments and medicines",
              remarks: "Please refer manifest for more details",
              facilities: "Provided by the port",
            },
            fal2: {
              list: [
                {
                  blNo: "123",
                  marksNo: "ER345",
                  kindPck: "300 Tn",
                  grossWeight: "400",
                  measurement: "100",
                },
                {
                  blNo: "4544",
                  marksNo: "YT455",
                  kindPck: "100 Tn",
                  grossWeight: "200",
                  measurement: "320",
                },
                {
                  blNo: "5766",
                  marksNo: "HG5645",
                  kindPck: "300 Tn",
                  grossWeight: "200",
                  measurement: "444",
                },
              ],
              cargoDetails: {
                blNo: "123",
                marksNo: "ER345",
                kindPck: "Medicinal Equipments",
                grossWeight: "400",
                measurement: "100",
              },
              cargoDeclaration: {
                billInfo: {
                  billNo: "111",
                  billType: "Bill",
                  billNature: "NT345",
                  billMasterNo: "MS234",
    
                  placeLoading: "Phnom Penh",
                  placeUnloading: "Singapore",
                  portLoading: "CAM",
                  portUnloading: "SG",
                },
                traderInfo: {
                  exporterName: "Shipping Line 1",
                  exporterAddress: "Wat Nom",
                  consigneeName: "Shipping Line 2",
                  consigneeAddress: "Poi Pet",
                  consigneeCode: "ER333",
                  notifyName: "Notifier 1",
                  notifyAddress: "Phnom Penh",
                  notifyCode: "RT445",
                },
                goodsInfo: {
                  goodsDescription: "Medicinal Equipments",
                  numberOfContainers: "12",
                  numberOfPackages: "200",
                  packageType: "Closed containers",
                  grossMass: "1003 Tonne",
                  volumeInCubicMeters: "2033 CC",
                  numberOfSeals: "23",
                  sealPartyCode: "TT 4533",
                  sealsMarks: "24",
                  shippingMarks: "None",
                  information: "Refer manifest",
                },
                containerInfo: {
                  list: [
                    {
                      containerNo: "1234",
                      contanerType: "ER123",
                      emptyOrFull: "Chemicals",
                      nameCode: "300Tn",
                    },
                    {
                      containerNo: "4567",
                      contanerType: "RV123",
                      emptyOrFull: "Petrol",
                      nameCode: "100Tn",
                    },
                  ],
                  containerDetails: {
                    containerNo: "CONT001",
                    contanerType: "Closed Container",
                    emptyOrFull: "Full",
                    nameCode: "CONT202012",
                    noOfPackages: "34",
                    goodsDescription: "Medical Equipments",
                    grossMass: "2244 Tonne",
    
                    sealingParty: "Cambodia Agency",
                    marks1: "M1",
                    marks2: "M2",
                    marks3: "M3",
                    minTemp: "19 Deg Cel",
                    maxTemp: "34 Deg Cel",
                    humidity: "33 Ps",
                    dangerousGoods: "none",
                  },
                },
              },
            },
    
            fal3: {
              stayPeriod: "4",
              onBoardPersons: "215",
              list: [
                {
                  locationOnBoard: "Chemical Container",
                  quantity: "20 Tn",
                  articleName: "Upper Deck",
                },
                {
                  locationOnBoard: "Petroleum Products",
                  quantity: "40 Tn",
                  articleName: "Lower Deck",
                },
              ],
              ShipStoresDeclaration: {
                articleName: "Coal",
                quantity: "5 Tn",
                locationOnBoard: "Bishan",
                selectType: "Tonne",
              },
            },
            fal4: {
              list: [
                {
                  familyName: "John Doe",
                  givenName: "Alex",
                  rankRating: "Rank1",
                  nationality: "Vietnamese",
                  dob: "04-20-1985",
                  signature: "",
                  effects: "Cigars",
                  identityDocType: "Identity.pdf",
                  dateOfBirth: "04/20/1985",
                  placeOfBirth: "Vietnam",
                  gender: "Male",
                  typeOfIdentity: "Passport",
                  serialNumberOfIdentity: "1234444",
                  issuingStateOfIdentity: "VN",
                  expiryDateOfIdentity: "01/20/2030",
                  portOfEmberkation: "",
                  visaNumber: "VISA1234555",
                  portOfDisemberkation: "CAMBODIA",
                },
              ],
              AddCrew: {
                familyName: "John Doe",
                givenName: "Alex",
                nationality: "Vietnamese",
                dateOfBirth: "04-20-1985",
                placeOfBirth: "Vietnam",
                gender: "Male",
                rankRating: "Rank1",
                typeOfIdentity: "Passport",
                serialNumberOfIdentity: "1234444",
                issuingStateOfIdentity: "VN",
                expiryDateOfIdentity: "01/20/2030",
                portOfEmberkation: "",
                visaNumber: "VISA1234555",
                portOfDisemberkation: "CAMBODIA",
              },
            },
            fal5: {
              list: [
                {
                  familyName: "John Doe",
                  givenName: "Alex",
                  rankRating: "Rank1",
                  effects: "Eligible",
                  dob: "04-20-1985",
                  identityDocType: "Identity.pdf",
                  dateOfBirth: "04/20/1985",
                  placeOfBirth: "Vietnam",
                  gender: "Male",
                  typeOfIdentity: "Passport",
                  serialNumberOfIdentity: "1234444",
                  issuingStateOfIdentity: "VN",
                  expiryDateOfIdentity: "01/20/2030",
                  portOfEmberkation: "",
                  visaNumber: "VISA1234555",
                  portOfDisemberkation: "CAMBODIA",
                },
              ],
    
              AddEffect: {
                familyName: "John Doe",
                givenName: "Alex",
                nationality: "Vietnamese",
                dateOfBirth: "04/20/1985",
                placeOfBirth: "Vietnam",
                gender: "Male",
                rankRating: "Rank1",
                typeOfIdentity: "Passport",
                serialNumberOfIdentity: "1234444",
                issuingStateOfIdentity: "VN",
                expiryDateOfIdentity: "01/20/2030",
                portOfEmberkation: "",
                visaNumber: "VISA1234555",
                portOfDisemberkation: "CAMBODIA",
                effects: "Eligible",
                signature: "JOHN Sign",
              },
            },
    
            fal6: {
              list: [
                {
                  familyName: "John Doe",
                  givenName: "Alex",
                  nationality: "JAPAN",
                  identityType: "Passport",
                  dateOfBirth: "04-20-1985",
                  identityDocType: "Identity.pdf",
                  placeOfBirth: "VN",
                  gender: "Male",
                  typeOfIdentity: "Passport",
                  serialNumberOfIdentity: "1234444",
                  issuingStateOfIdentity: "VN",
                  expiryDateOfIdentity: "01/20/2030",
                  portOfEmberkation: "CAMBODIA",
                  visaNumber: "V1234",
                  portOfDisemberkation: "CAMBODIA",
                  transitPassenger: "No",
                },
              ],
              AddPassenger: {
                familyName: "Doe",
                givenName: "John",
                nationality: "Vietnamese",
                dateOfBirth: "04/20/1985",
                placeOfBirth: "VN",
                gender: "Male",
                typeOfIdentity: "Passport",
                serialNumberOfIdentity: "1234444",
                issuingStateOfIdentity: "VN",
                expiryDateOfIdentity: "01/20/2030",
                portOfEmberkation: "CAMBODIA",
                visaNumber: "V1234",
                portOfDisemberkation: "CAMBODIA",
                transitPassenger: "No",
              },
            },
            fal7: {
              list: [
                {
                  stowagePosition: "Lower Deck",
                  referenceNumber: "REF20210212",
                  marksNumber: "100",
                  unNumber: "HK463",
                  forVIdentification: "IDV20210214",
                  properShippingName: "Maersk",
                  corSRisks: "None",
                  packingGroup: "GRP213",
                  additionalInformation: "GARBAGE CANS",
                  numberAndKindOfPackages: "GARBAGE",
                  massOrVolume: "2 Tonne",
                  ems: "NA",
                },
                {
                  stowagePosition: "Upper Deck",
                  referenceNumber: "REF202102234",
                  marksNumber: "200",
                  unNumber: "BG45665",
                  forVIdentification: "IDV20210214",
                  properShippingName: "Maersk",
                  corSRisks: "None",
                  packingGroup: "GRP213",
                  additionalInformation: "GARBAGE CANS",
                  numberAndKindOfPackages: "GARBAGE",
                  massOrVolume: "2 Tonne",
                  ems: "NA",
                },
              ],
              AddDangerousGoods: {
                stowagePosition: "Lower Deck",
                referenceNumber: "REF20210212",
                marksNumber: "100",
                forVIdentification: "IDV20210214",
                unNumber: "UN234",
                properShippingName: "Maersk",
                corSRisks: "None",
                packingGroup: "GRP213",
                additionalInformation: "GARBAGE CANS",
                numberAndKindOfPackages: "GARBAGE",
                massOrVolume: "2 Tonne",
                ems: "NA",
              },
            },
          },
          others: {
            vaccination: {
              list: [
                {
                  familyName: "John Doe",
                  givenName: "Alex",
                  rankRating: "Rank1",
                  nationality: "Vietnamese",
                  dob: "04/20/1985",
                  signature: "",
                  effects: "Cigars",
                },
              ],
              AddCrew: {
                familyName: "John Doe",
                givenName: "Alex",
                nationality: "Vietnamese",
                dateOfBirth: "04/20/1985",
                placeOfBirth: "Vietnam",
                gender: "Male",
                rankRating: "Rank1",
                typeOfIdentity: "Passport",
                serialNumberOfIdentity: "1234444",
                issuingStateOfIdentity: "VN",
                expiryDateOfIdentity: "01/20/2030",
                portOfEmberkation: "",
                visaNumber: "VISA1234555",
                portOfDisemberkation: "CAMBODIA",
              },
            },
          },
          supportingDocs: {
            docType: "Ship Security Info Doc",
            docRefNo: "SS20201221",
          },
        },
        {
          appId: "AD20210308003",
          version: "1",
          appType: "AD",
          arrivalPort: "KHPNH",
          impNo: "ERT33456",
          shipName: "Maersk Alabama",
          shipCountry: "SG",
          lastPortCountry: "TH",
          applicantTin: "2332434232",
          submitDate: "2020-12-20T12:30:45",
          workflowName: "AD",
          // status: WorkflowUtil.WorkflowStage.PendingVerification,
          status: "P",
          statusBodCu: WorkflowUtil.WorkflowStage.Approved,
          statusBodIm: WorkflowUtil.WorkflowStage.Approved,
          statusBodQu: WorkflowUtil.WorkflowStage.Approved,
          statusPortCu: WorkflowUtil.WorkflowStage.Approved,
          statusPortIm: WorkflowUtil.WorkflowStage.Approved,
          statusPortQu: WorkflowUtil.WorkflowStage.Approved,
          statusPort: WorkflowUtil.WorkflowStage.PendingVerification,
          callSign: "TR098234",
          masterName: "Tom Hanks",
          portOfArrivalOrDept: "PPAP",
          dateOfArrv: "13-12-2020",
          portArrivedFrom: "SG",
          nextPort: "SG",
          dateOfDeparture: "12-1-2020",
          stowaways: "Y",
          animalOrPlants: "N",
          parcelPackage: "Y",
          armsAmmunitions: "N",
          illegalDrugs: "N",
          passengers: "Y",
          livestocks: "N",
          signUpload: "",
          reqMessage: "",
          application: "NIL",
          header: {
            type: "arrival",
            voyageDetails: {
              vcrNo: "PEDI202012123",
              voyageNo: "PEDI944832",
              voyageName: "ERT-2324",
    
              arrivalPort: "KHPNH",
              arrivalDate: "2021-01-12",
              arrivalTime: "10:00:00",
              lastPortCountry: "TH",
              lastPort: "THKRB",
              departurePort: "KHPNH",
              departureDate: "21-10-2021",
              DepartureTime: "10:00:00",
              nextPortCountry: "SG",
              nextPort: "SGJUR",
              dutyPaidAt: "BORDER",
            },
            shipDetails: {
              impNo: "ERT33456",
              shipName: "Maersk Alabama",
              shipCountry: "SG",
              callSign: "TR098234",
              flageState: "FL1234",
              shipType: "TANKER",
              applicantTin: "L3342234232",
              applicantName: "CAM SHIPPING COMPANY",
            },
          },
          falForm: {
            fal1: {
              certificateReg: "VR 03455",
              grossTonnage: "1589 GT",
              netTonnage: "1098 NT",
              voyageDesc: "Transporting medical equipments",
              cargoDesc: "All containers contains medical equipments and medicines",
              remarks: "Please refer manifest for more details",
              facilities: "Provided by the port",
            },
            fal2: {
              list: [
                {
                  blNo: "123",
                  marksNo: "ER345",
                  kindPck: "300 Tn",
                  grossWeight: "400",
                  measurement: "100",
                },
                {
                  blNo: "4544",
                  marksNo: "YT455",
                  kindPck: "100 Tn",
                  grossWeight: "200",
                  measurement: "320",
                },
                {
                  blNo: "5766",
                  marksNo: "HG5645",
                  kindPck: "300 Tn",
                  grossWeight: "200",
                  measurement: "444",
                },
              ],
              cargoDetails: {
                blNo: "123",
                marksNo: "ER345",
                kindPck: "Medicinal Equipments",
                grossWeight: "400",
                measurement: "100",
              },
              cargoDeclaration: {
                billInfo: {
                  billNo: "111",
                  billType: "Bill",
                  billNature: "NT345",
                  billMasterNo: "MS234",
    
                  placeLoading: "Phnom Penh",
                  placeUnloading: "Singapore",
                  portLoading: "CAM",
                  portUnloading: "SG",
                },
                traderInfo: {
                  exporterName: "Shipping Line 1",
                  exporterAddress: "Wat Nom",
                  consigneeName: "Shipping Line 2",
                  consigneeAddress: "Poi Pet",
                  consigneeCode: "ER333",
                  notifyName: "Notifier 1",
                  notifyAddress: "Phnom Penh",
                  notifyCode: "RT445",
                },
                goodsInfo: {
                  goodsDescription: "Medicinal Equipments",
                  numberOfContainers: "12",
                  numberOfPackages: "200",
                  packageType: "Closed containers",
                  grossMass: "1003 Tonne",
                  volumeInCubicMeters: "2033 CC",
                  numberOfSeals: "23",
                  sealPartyCode: "TT 4533",
                  sealsMarks: "24",
                  shippingMarks: "None",
                  information: "Refer manifest",
                },
                containerInfo: {
                  list: [
                    {
                      containerNo: "1234",
                      contanerType: "ER123",
                      emptyOrFull: "Chemicals",
                      nameCode: "300Tn",
                    },
                    {
                      containerNo: "4567",
                      contanerType: "RV123",
                      emptyOrFull: "Petrol",
                      nameCode: "100Tn",
                    },
                  ],
                  containerDetails: {
                    containerNo: "CONT001",
                    contanerType: "Closed Container",
                    emptyOrFull: "Full",
                    nameCode: "CONT202012",
                    noOfPackages: "34",
                    goodsDescription: "Medical Equipments",
                    grossMass: "2244 Tonne",
    
                    sealingParty: "Cambodia Agency",
                    marks1: "M1",
                    marks2: "M2",
                    marks3: "M3",
                    minTemp: "19 Deg Cel",
                    maxTemp: "34 Deg Cel",
                    humidity: "33 Ps",
                    dangerousGoods: "none",
                  },
                },
              },
            },
    
            fal3: {
              stayPeriod: "4",
              onBoardPersons: "215",
              list: [
                {
                  locationOnBoard: "Chemical Container",
                  quantity: "20 Tn",
                  articleName: "Upper Deck",
                },
                {
                  locationOnBoard: "Petroleum Products",
                  quantity: "40 Tn",
                  articleName: "Lower Deck",
                },
              ],
              ShipStoresDeclaration: {
                articleName: "Coal",
                quantity: "5 Tn",
                locationOnBoard: "Bishan",
                selectType: "Tonne",
              },
            },
            fal4: {
              list: [
                {
                  familyName: "John Doe",
                  givenName: "Alex",
                  rankRating: "Rank1",
                  nationality: "Vietnamese",
                  dob: "04-20-1985",
                  signature: "",
                  effects: "Cigars",
                  identityDocType: "Identity.pdf",
                  dateOfBirth: "04/20/1985",
                  placeOfBirth: "Vietnam",
                  gender: "Male",
                  typeOfIdentity: "Passport",
                  serialNumberOfIdentity: "1234444",
                  issuingStateOfIdentity: "VN",
                  expiryDateOfIdentity: "01/20/2030",
                  portOfEmberkation: "",
                  visaNumber: "VISA1234555",
                  portOfDisemberkation: "CAMBODIA",
                },
              ],
              AddCrew: {
                familyName: "John Doe",
                givenName: "Alex",
                nationality: "Vietnamese",
                dateOfBirth: "04-20-1985",
                placeOfBirth: "Vietnam",
                gender: "Male",
                rankRating: "Rank1",
                typeOfIdentity: "Passport",
                serialNumberOfIdentity: "1234444",
                issuingStateOfIdentity: "VN",
                expiryDateOfIdentity: "01/20/2030",
                portOfEmberkation: "",
                visaNumber: "VISA1234555",
                portOfDisemberkation: "CAMBODIA",
              },
            },
            fal5: {
              list: [
                {
                  familyName: "John Doe",
                  givenName: "Alex",
                  rankRating: "Rank1",
                  dob: "04-20-1985",
                  effects: "Cigars",
                  identityDocType: "Identity.pdf",
                  dateOfBirth: "04/20/1985",
                  placeOfBirth: "Vietnam",
                  gender: "Male",
                  typeOfIdentity: "Passport",
                  serialNumberOfIdentity: "1234444",
                  issuingStateOfIdentity: "VN",
                  expiryDateOfIdentity: "01/20/2030",
                  portOfEmberkation: "",
                  visaNumber: "VISA1234555",
                  portOfDisemberkation: "CAMBODIA",
                },
              ],
    
              AddEffect: {
                familyName: "John Doe",
                givenName: "Alex",
                nationality: "Vietnamese",
                dateOfBirth: "04/20/1985",
                placeOfBirth: "Vietnam",
                gender: "Male",
                rankRating: "Rank1",
                typeOfIdentity: "Passport",
                serialNumberOfIdentity: "1234444",
                issuingStateOfIdentity: "VN",
                expiryDateOfIdentity: "01/20/2030",
                portOfEmberkation: "",
                visaNumber: "VISA1234555",
                portOfDisemberkation: "CAMBODIA",
                effects: "Eligible",
                signature: "JOHN Sign",
              },
            },
    
            fal6: {
              list: [
                {
                  familyName: "John Doe",
                  givenName: "Alex",
                  nationality: "JAPAN",
                  identityType: "Passport",
                  dateOfBirth: "04-20-1985",
                  identityDocType: "Identity.pdf",
                  placeOfBirth: "VN",
                  gender: "Male",
                  typeOfIdentity: "Passport",
                  serialNumberOfIdentity: "1234444",
                  issuingStateOfIdentity: "VN",
                  expiryDateOfIdentity: "01/20/2030",
                  portOfEmberkation: "CAMBODIA",
                  visaNumber: "V1234",
                  portOfDisemberkation: "CAMBODIA",
                  transitPassenger: "No",
                },
              ],
              AddPassenger: {
                familyName: "Doe",
                givenName: "John",
                nationality: "Vietnamese",
                dateOfBirth: "04/20/1985",
                placeOfBirth: "VN",
                gender: "Male",
                typeOfIdentity: "Passport",
                serialNumberOfIdentity: "1234444",
                issuingStateOfIdentity: "VN",
                expiryDateOfIdentity: "01/20/2030",
                portOfEmberkation: "CAMBODIA",
                visaNumber: "V1234",
                portOfDisemberkation: "CAMBODIA",
                transitPassenger: "No",
              },
            },
            fal7: {
              list: [
                {
                  stowagePosition: "Lower Deck",
                  referenceNumber: "REF20210212",
                  marksNumber: "100",
                  unNumber: "HK463",
                  forVIdentification: "IDV20210214",
                  properShippingName: "Maersk",
                  corSRisks: "None",
                  packingGroup: "GRP213",
                  additionalInformation: "GARBAGE CANS",
                  numberAndKindOfPackages: "GARBAGE",
                  massOrVolume: "2 Tonne",
                  ems: "NA",
                },
                {
                  stowagePosition: "Upper Deck",
                  referenceNumber: "REF202102234",
                  marksNumber: "200",
                  unNumber: "BG45665",
                  forVIdentification: "IDV20210214",
                  properShippingName: "Maersk",
                  corSRisks: "None",
                  packingGroup: "GRP213",
                  additionalInformation: "GARBAGE CANS",
                  numberAndKindOfPackages: "GARBAGE",
                  massOrVolume: "2 Tonne",
                  ems: "NA",
                },
              ],
              AddDangerousGoods: {
                stowagePosition: "Lower Deck",
                referenceNumber: "REF20210212",
                marksNumber: "100",
                forVIdentification: "IDV20210214",
                unNumber: "UN234",
                properShippingName: "Maersk",
                corSRisks: "None",
                packingGroup: "GRP213",
                additionalInformation: "GARBAGE CANS",
                numberAndKindOfPackages: "GARBAGE",
                massOrVolume: "2 Tonne",
                ems: "NA",
              },
            },
          },
          others: {
            vaccination: {
              list: [
                {
                  familyName: "John Doe",
                  givenName: "Alex",
                  rankRating: "Rank1",
                  nationality: "Vietnamese",
                  dob: "04/20/1985",
                  signature: "",
                  effects: "Cigars",
                },
              ],
              AddCrew: {
                familyName: "John Doe",
                givenName: "Alex",
                nationality: "Vietnamese",
                dateOfBirth: "04/20/1985",
                placeOfBirth: "Vietnam",
                gender: "Male",
                rankRating: "Rank1",
                typeOfIdentity: "Passport",
                serialNumberOfIdentity: "1234444",
                issuingStateOfIdentity: "VN",
                expiryDateOfIdentity: "01/20/2030",
                portOfEmberkation: "",
                visaNumber: "VISA1234555",
                portOfDisemberkation: "CAMBODIA",
              },
            },
          },
          supportingDocs: {
            docType: "Ship Security Info Doc",
            docRefNo: "SS20201221",
          },
        },
    
        {
          appId: "AD20210308004",
          version: "1",
          appType: "AD",
          submitDate: "2020-11-20T12:30:45",
          workflowName: "AD",
           status: WorkflowUtil.WorkflowStage.Approved,
          //status: "A",
          statusBodCu: WorkflowUtil.WorkflowStage.Approved,
          statusBodIm: WorkflowUtil.WorkflowStage.Approved,
          statusBodQu: WorkflowUtil.WorkflowStage.Approved,
          statusPortCu: WorkflowUtil.WorkflowStage.Approved,
          statusPortIm: WorkflowUtil.WorkflowStage.Approved,
          statusPortQu: WorkflowUtil.WorkflowStage.Approved,
          statusPort: WorkflowUtil.WorkflowStage.Approved,
          arrivalPort: "KHKOS",
          lastPortCountry: "Thailand",
          impNo: "ERT3344",
          shipName: "Moon Light",
          shipCountry: "SG",
          callSign: "TR1234",
          applicantTin: "2332434232",
          masterName: "Tom Hanks",
          portOfArrivalOrDept: "PPAP",
          dateOfArrv: "13-12-2020",
          portArrivedFrom: "SG",
          nextPort: "SG",
          dateOfDeparture: "12-1-2020",
          stowaways: "Y",
          animalOrPlants: "N",
          parcelPackage: "Y",
          armsAmmunitions: "N",
          illegalDrugs: "N",
          passengers: "Y",
          livestocks: "N",
          signUpload: "",
          reqMessage: "",
          application: "NIL",
          header: {
            type: "arrival",
            voyageDetails: {
              vcrNo: "PEDI202012123",
              voyageNo: "VE123765",
              voyageName: "2000918",
    
              arrivalPort: "KHPNH",
              arrivalDate: "01-12-2021",
              arrivalTime: "10:00:00",
              lastPortCountry: "TH",
              lastPort: "THKRB",
              departurePort: "KHPNH",
              departureDate: "01-10-2021",
              DepartureTime: "10:00:00",
              nextPortCountry: "SG",
              nextPort: "SGJUR",
              dutyPaidAt: "BORDER",
            },
            shipDetails: {
              impNo: "ERT3344",
              shipName: "Moon Light",
              shipCountry: "SG",
              callSign: "TR1234",
              flageState: "FL1234",
              shipType: "TANKER",
              applicantTin: "L3342234232",
              applicantName: "CAM SHIPPING COMPANY",
            },
          },
          falForm: {
            fal1: {
              certificateReg: "VR 03455",
              grossTonnage: "1589 GT",
              netTonnage: "1098 NT",
              voyageDesc: "Transporting medical equipments",
              cargoDesc: "All containers contains medical equipments and medicines",
              remarks: "Please refer manifest for more details",
              facilities: "Provided by the port",
            },
            fal2: {
              list: [
                {
                  blNo: "123",
                  marksNo: "ER345",
                  kindPck: "300 Tn",
                  grossWeight: "400",
                  measurement: "100",
                },
                {
                  blNo: "4544",
                  marksNo: "YT455",
                  kindPck: "100 Tn",
                  grossWeight: "200",
                  measurement: "320",
                },
                {
                  blNo: "5766",
                  marksNo: "HG5645",
                  kindPck: "300 Tn",
                  grossWeight: "200",
                  measurement: "444",
                },
              ],
              cargoDetails: {
                blNo: "123",
                marksNo: "ER345",
                kindPck: "Medicinal Equipments",
                grossWeight: "400",
                measurement: "100",
              },
              cargoDeclaration: {
                billInfo: {
                  billNo: "111",
                  billType: "Bill",
                  billNature: "NT345",
                  billMasterNo: "MS234",
    
                  placeLoading: "Phnom Penh",
                  placeUnloading: "Singapore",
                  portLoading: "CAM",
                  portUnloading: "SG",
                },
                traderInfo: {
                  exporterName: "Shipping Line 1",
                  exporterAddress: "Wat Nom",
                  consigneeName: "Shipping Line 2",
                  consigneeAddress: "Poi Pet",
                  consigneeCode: "ER333",
                  notifyName: "Notifier 1",
                  notifyAddress: "Phnom Penh",
                  notifyCode: "RT445",
                },
                goodsInfo: {
                  goodsDescription: "Medicinal Equipments",
                  numberOfContainers: "12",
                  numberOfPackages: "200",
                  packageType: "Closed containers",
                  grossMass: "1003 Tonne",
                  volumeInCubicMeters: "2033 CC",
                  numberOfSeals: "23",
                  sealPartyCode: "TT 4533",
                  sealsMarks: "24",
                  shippingMarks: "None",
                  information: "Refer manifest",
                },
                containerInfo: {
                  list: [
                    {
                      containerNo: "1234",
                      contanerType: "ER123",
                      emptyOrFull: "Chemicals",
                      nameCode: "300Tn",
                    },
                    {
                      containerNo: "4567",
                      contanerType: "RV123",
                      emptyOrFull: "Petrol",
                      nameCode: "100Tn",
                    },
                  ],
                  containerDetails: {
                    containerNo: "CONT001",
                    contanerType: "Closed Container",
                    emptyOrFull: "Full",
                    nameCode: "CONT202012",
                    noOfPackages: "34",
                    goodsDescription: "Medical Equipments",
                    grossMass: "2244 Tonne",
    
                    sealingParty: "Cambodia Agency",
                    marks1: "M1",
                    marks2: "M2",
                    marks3: "M3",
                    minTemp: "19 Deg Cel",
                    maxTemp: "34 Deg Cel",
                    humidity: "33 Ps",
                    dangerousGoods: "none",
                  },
                },
              },
            },
    
            fal3: {
              stayPeriod: "4",
              onBoardPersons: "215",
              list: [
                {
                  locationOnBoard: "Chemical Container",
                  quantity: "20 Tn",
                  articleName: "Upper Deck",
                },
                {
                  locationOnBoard: "Petroleum Products",
                  quantity: "40 Tn",
                  articleName: "Lower Deck",
                },
              ],
              ShipStoresDeclaration: {
                articleName: "Coal",
                quantity: "5 Tn",
                locationOnBoard: "Bishan",
                selectType: "Tonne",
              },
            },
            fal4: {
              list: [
                {
                  familyName: "John Doe",
                  givenName: "Alex",
                  rankRating: "Rank1",
                  nationality: "Vietnamese",
                  dob: "04-20-1985",
                  signature: "",
                  effects: "Cigars",
                  identityDocType: "Identity.pdf",
                  dateOfBirth: "04/20/1985",
                  placeOfBirth: "Vietnam",
                  gender: "Male",
                  typeOfIdentity: "Passport",
                  serialNumberOfIdentity: "1234444",
                  issuingStateOfIdentity: "VN",
                  expiryDateOfIdentity: "01/20/2030",
                  portOfEmberkation: "",
                  visaNumber: "VISA1234555",
                  portOfDisemberkation: "CAMBODIA",
                },
              ],
              AddCrew: {
                familyName: "John Doe",
                givenName: "Alex",
                nationality: "Vietnamese",
                dateOfBirth: "04/20/1985",
                placeOfBirth: "Vietnam",
                gender: "Male",
                rankRating: "Rank1",
                typeOfIdentity: "Passport",
                serialNumberOfIdentity: "1234444",
                issuingStateOfIdentity: "VN",
                expiryDateOfIdentity: "01/20/2030",
                portOfEmberkation: "",
                visaNumber: "VISA1234555",
                portOfDisemberkation: "CAMBODIA",
              },
            },
            fal5: {
              list: [
                {
                  familyName: "John Doe",
                  givenName: "Alex",
                  rankRating: "Rank1",
                  effects: "Eligible",
                  dob: "04-20-1985",
                  identityDocType: "Identity.pdf",
                  dateOfBirth: "04/20/1985",
                  placeOfBirth: "Vietnam",
                  gender: "Male",
                  typeOfIdentity: "Passport",
                  serialNumberOfIdentity: "1234444",
                  issuingStateOfIdentity: "VN",
                  expiryDateOfIdentity: "01/20/2030",
                  portOfEmberkation: "",
                  visaNumber: "VISA1234555",
                  portOfDisemberkation: "CAMBODIA",
                },
              ],
              AddEffect: {
                familyName: "John Doe",
                givenName: "Alex",
                nationality: "Vietnamese",
                dateOfBirth: "04-20-1985",
                placeOfBirth: "Vietnam",
                gender: "Male",
                rankRating: "Rank1",
                typeOfIdentity: "Passport",
                serialNumberOfIdentity: "1234444",
                issuingStateOfIdentity: "VN",
                expiryDateOfIdentity: "01/20/2030",
                portOfEmberkation: "",
                visaNumber: "VISA1234555",
                portOfDisemberkation: "CAMBODIA",
                effects: "Eligible",
                signature: "JOHN Sign",
              },
            },
    
            fal6: {
              list: [
                {
                  familyName: "John Doe",
                  givenName: "Alex",
                  nationality: "JAPAN",
                  identityType: "Passport",
                  dateOfBirth: "04-20-1985",
                  identityDocType: "Identity.pdf",
                  placeOfBirth: "VN",
                  gender: "Male",
                  typeOfIdentity: "Passport",
                  serialNumberOfIdentity: "1234444",
                  issuingStateOfIdentity: "VN",
                  expiryDateOfIdentity: "01/20/2030",
                  portOfEmberkation: "CAMBODIA",
                  visaNumber: "V1234",
                  portOfDisemberkation: "CAMBODIA",
                  transitPassenger: "No",
                },
              ],
              AddPassenger: {
                familyName: "Doe",
                givenName: "John",
                nationality: "Vietnamese",
                dateOfBirth: "04/20/1985",
                placeOfBirth: "VN",
                gender: "Male",
                typeOfIdentity: "Passport",
                serialNumberOfIdentity: "1234444",
                issuingStateOfIdentity: "VN",
                expiryDateOfIdentity: "01/20/2030",
                portOfEmberkation: "CAMBODIA",
                visaNumber: "V1234",
                portOfDisemberkation: "CAMBODIA",
                transitPassenger: "No",
              },
            },
            fal7: {
              list: [
                {
                  stowagePosition: "Lower Deck",
                  referenceNumber: "REF20210212",
                  marksNumber: "100",
                  unNumber: "HK463",
                  forVIdentification: "IDV20210214",
                  properShippingName: "Maersk",
                  corSRisks: "None",
                  packingGroup: "GRP213",
                  additionalInformation: "GARBAGE CANS",
                  numberAndKindOfPackages: "GARBAGE",
                  massOrVolume: "2 Tonne",
                  ems: "NA",
                },
                {
                  stowagePosition: "Upper Deck",
                  referenceNumber: "REF202102234",
                  marksNumber: "200",
                  unNumber: "BG45665",
                  forVIdentification: "IDV20210214",
                  properShippingName: "Maersk",
                  corSRisks: "None",
                  packingGroup: "GRP213",
                  additionalInformation: "GARBAGE CANS",
                  numberAndKindOfPackages: "GARBAGE",
                  massOrVolume: "2 Tonne",
                  ems: "NA",
                },
              ],
              AddDangerousGoods: {
                stowagePosition: "Lower Deck",
                referenceNumber: "REF20210212",
                marksNumber: "100",
                forVIdentification: "IDV20210214",
                unNumber: "UN234",
                properShippingName: "Maersk",
                corSRisks: "None",
                packingGroup: "GRP213",
                additionalInformation: "GARBAGE CANS",
                numberAndKindOfPackages: "GARBAGE",
                massOrVolume: "2 Tonne",
                ems: "NA",
              },
            },
          },
          others: {
            vaccination: {
              list: [
                {
                  familyName: "John Doe",
                  givenName: "Alex",
                  rankRating: "Rank1",
                  nationality: "Vietnamese",
                  dob: "04/20/1985",
                  signature: "",
                  effects: "Cigars",
                },
              ],
              AddCrew: {
                familyName: "John Doe",
                givenName: "Alex",
                nationality: "Vietnamese",
                dateOfBirth: "04/20/1985",
                placeOfBirth: "Vietnam",
                gender: "Male",
                rankRating: "Rank1",
                typeOfIdentity: "Passport",
                serialNumberOfIdentity: "1234444",
                issuingStateOfIdentity: "VN",
                expiryDateOfIdentity: "01/20/2030",
                portOfEmberkation: "",
                visaNumber: "VISA1234555",
                portOfDisemberkation: "CAMBODIA",
              },
            },
          },
          supportingDocs: {
            docType: "Ship Security Info Doc",
            docRefNo: "SS20201221",
          },
        },
        {
          appId: "AD20210308005",
          version: "1",
          appType: "AD",
          submitDate: "2020-11-20T12:30:45",
          workflowName: "AD",
          status: WorkflowUtil.WorkflowStage.Approved,
          //status: "A",
          statusBodCu: WorkflowUtil.WorkflowStage.Approved,
          statusBodIm: WorkflowUtil.WorkflowStage.Approved,
          statusBodQu: WorkflowUtil.WorkflowStage.Approved,
          statusPortCu: WorkflowUtil.WorkflowStage.Approved,
          statusPortIm: WorkflowUtil.WorkflowStage.Approved,
          statusPortQu: WorkflowUtil.WorkflowStage.Approved,
          statusPort: WorkflowUtil.WorkflowStage.Approved,
          arrivalPort: "KHKOS",
          lastPortCountry: "Thailand",
          impNo: "ERT3344",
          shipName: "Moon Light",
          shipCountry: "SG",
          callSign: "TR1234",
          applicantTin: "2332434232",
          masterName: "Tom Hanks",
          portOfArrivalOrDept: "PPAP",
          dateOfArrv: "13-12-2020",
          portArrivedFrom: "SG",
          nextPort: "SG",
          dateOfDeparture: "12-1-2020",
          stowaways: "Y",
          animalOrPlants: "N",
          parcelPackage: "Y",
          armsAmmunitions: "N",
          illegalDrugs: "N",
          passengers: "Y",
          livestocks: "N",
          signUpload: "",
          reqMessage: "",
          application: "NIL",
          header: {
            type: "arrival",
            voyageDetails: {
              vcrNo: "PEDI202012123",
              voyageNo: "VE123765",
              voyageName: "2000918",
    
              arrivalPort: "KHPNH",
              arrivalDate: "01-12-2021",
              arrivalTime: "10:00:00",
              lastPortCountry: "TH",
              lastPort: "THKRB",
              departurePort: "KHPNH",
              departureDate: "01-10-2021",
              DepartureTime: "10:00:00",
              nextPortCountry: "SG",
              nextPort: "SGJUR",
              dutyPaidAt: "BORDER",
            },
            shipDetails: {
              impNo: "ERT3344",
              shipName: "Moon Light",
              shipCountry: "SG",
              callSign: "TR1234",
              flageState: "FL1234",
              shipType: "TANKER",
              applicantTin: "L3342234232",
              applicantName: "CAM SHIPPING COMPANY",
            },
          },
          falForm: {
            fal1: {
              certificateReg: "VR 03455",
              grossTonnage: "1589 GT",
              netTonnage: "1098 NT",
              voyageDesc: "Transporting medical equipments",
              cargoDesc: "All containers contains medical equipments and medicines",
              remarks: "Please refer manifest for more details",
              facilities: "Provided by the port",
            },
            fal2: {
              list: [
                {
                  blNo: "123",
                  marksNo: "ER345",
                  kindPck: "300 Tn",
                  grossWeight: "400",
                  measurement: "100",
                },
                {
                  blNo: "4544",
                  marksNo: "YT455",
                  kindPck: "100 Tn",
                  grossWeight: "200",
                  measurement: "320",
                },
                {
                  blNo: "5766",
                  marksNo: "HG5645",
                  kindPck: "300 Tn",
                  grossWeight: "200",
                  measurement: "444",
                },
              ],
              cargoDetails: {
                blNo: "123",
                marksNo: "ER345",
                kindPck: "Medicinal Equipments",
                grossWeight: "400",
                measurement: "100",
              },
              cargoDeclaration: {
                billInfo: {
                  billNo: "111",
                  billType: "Bill",
                  billNature: "NT345",
                  billMasterNo: "MS234",
    
                  placeLoading: "Phnom Penh",
                  placeUnloading: "Singapore",
                  portLoading: "CAM",
                  portUnloading: "SG",
                },
                traderInfo: {
                  exporterName: "Shipping Line 1",
                  exporterAddress: "Wat Nom",
                  consigneeName: "Shipping Line 2",
                  consigneeAddress: "Poi Pet",
                  consigneeCode: "ER333",
                  notifyName: "Notifier 1",
                  notifyAddress: "Phnom Penh",
                  notifyCode: "RT445",
                },
                goodsInfo: {
                  goodsDescription: "Medicinal Equipments",
                  numberOfContainers: "12",
                  numberOfPackages: "200",
                  packageType: "Closed containers",
                  grossMass: "1003 Tonne",
                  volumeInCubicMeters: "2033 CC",
                  numberOfSeals: "23",
                  sealPartyCode: "TT 4533",
                  sealsMarks: "24",
                  shippingMarks: "None",
                  information: "Refer manifest",
                },
                containerInfo: {
                  list: [
                    {
                      containerNo: "1234",
                      contanerType: "ER123",
                      emptyOrFull: "Chemicals",
                      nameCode: "300Tn",
                    },
                    {
                      containerNo: "4567",
                      contanerType: "RV123",
                      emptyOrFull: "Petrol",
                      nameCode: "100Tn",
                    },
                  ],
                  containerDetails: {
                    containerNo: "CONT001",
                    contanerType: "Closed Container",
                    emptyOrFull: "Full",
                    nameCode: "CONT202012",
                    noOfPackages: "34",
                    goodsDescription: "Medical Equipments",
                    grossMass: "2244 Tonne",
    
                    sealingParty: "Cambodia Agency",
                    marks1: "M1",
                    marks2: "M2",
                    marks3: "M3",
                    minTemp: "19 Deg Cel",
                    maxTemp: "34 Deg Cel",
                    humidity: "33 Ps",
                    dangerousGoods: "none",
                  },
                },
              },
            },
    
            fal3: {
              stayPeriod: "4",
              onBoardPersons: "215",
              list: [
                {
                  locationOnBoard: "Chemical Container",
                  quantity: "20 Tn",
                  articleName: "Upper Deck",
                },
                {
                  locationOnBoard: "Petroleum Products",
                  quantity: "40 Tn",
                  articleName: "Lower Deck",
                },
              ],
              ShipStoresDeclaration: {
                articleName: "Coal",
                quantity: "5 Tn",
                locationOnBoard: "Bishan",
                selectType: "Tonne",
              },
            },
            fal4: {
              list: [
                {
                  familyName: "John Doe",
                  givenName: "Alex",
                  rankRating: "Rank1",
                  nationality: "Vietnamese",
                  dob: "04-20-1985",
                  signature: "",
                  effects: "Cigars",
                  identityDocType: "Identity.pdf",
                  dateOfBirth: "04/20/1985",
                  placeOfBirth: "Vietnam",
                  gender: "Male",
                  typeOfIdentity: "Passport",
                  serialNumberOfIdentity: "1234444",
                  issuingStateOfIdentity: "VN",
                  expiryDateOfIdentity: "01/20/2030",
                  portOfEmberkation: "",
                  visaNumber: "VISA1234555",
                  portOfDisemberkation: "CAMBODIA",
                },
              ],
              AddCrew: {
                familyName: "John Doe",
                givenName: "Alex",
                nationality: "Vietnamese",
                dateOfBirth: "04/20/1985",
                placeOfBirth: "Vietnam",
                gender: "Male",
                rankRating: "Rank1",
                typeOfIdentity: "Passport",
                serialNumberOfIdentity: "1234444",
                issuingStateOfIdentity: "VN",
                expiryDateOfIdentity: "01/20/2030",
                portOfEmberkation: "",
                visaNumber: "VISA1234555",
                portOfDisemberkation: "CAMBODIA",
              },
            },
            fal5: {
              list: [
                {
                  familyName: "John Doe",
                  givenName: "Alex",
                  rankRating: "Rank1",
                  dob: "04-20-1985",
                  effects: "Cigars",
                  identityDocType: "Identity.pdf",
                  dateOfBirth: "04/20/1985",
                  placeOfBirth: "Vietnam",
                  gender: "Male",
                  typeOfIdentity: "Passport",
                  serialNumberOfIdentity: "1234444",
                  issuingStateOfIdentity: "VN",
                  expiryDateOfIdentity: "01/20/2030",
                  portOfEmberkation: "",
                  visaNumber: "VISA1234555",
                  portOfDisemberkation: "CAMBODIA",
                },
              ],
              AddEffect: {
                familyName: "John Doe",
                givenName: "Alex",
                nationality: "Vietnamese",
                dateOfBirth: "04-20-1985",
                placeOfBirth: "Vietnam",
                gender: "Male",
                rankRating: "Rank1",
                typeOfIdentity: "Passport",
                serialNumberOfIdentity: "1234444",
                issuingStateOfIdentity: "VN",
                expiryDateOfIdentity: "01/20/2030",
                portOfEmberkation: "",
                visaNumber: "VISA1234555",
                portOfDisemberkation: "CAMBODIA",
                effects: "Eligible",
                signature: "JOHN Sign",
              },
            },
    
            fal6: {
              list: [
                {
                  familyName: "John Doe",
                  givenName: "Alex",
                  nationality: "JAPAN",
                  identityType: "Passport",
                  dateOfBirth: "04-20-1985",
                  identityDocType: "Identity.pdf",
                  placeOfBirth: "VN",
                  gender: "Male",
                  typeOfIdentity: "Passport",
                  serialNumberOfIdentity: "1234444",
                  issuingStateOfIdentity: "VN",
                  expiryDateOfIdentity: "01/20/2030",
                  portOfEmberkation: "CAMBODIA",
                  visaNumber: "V1234",
                  portOfDisemberkation: "CAMBODIA",
                  transitPassenger: "No",
                },
              ],
              AddPassenger: {
                familyName: "Doe",
                givenName: "John",
                nationality: "Vietnamese",
                dateOfBirth: "04/20/1985",
                placeOfBirth: "VN",
                gender: "Male",
                typeOfIdentity: "Passport",
                serialNumberOfIdentity: "1234444",
                issuingStateOfIdentity: "VN",
                expiryDateOfIdentity: "01/20/2030",
                portOfEmberkation: "CAMBODIA",
                visaNumber: "V1234",
                portOfDisemberkation: "CAMBODIA",
                transitPassenger: "No",
              },
            },
            fal7: {
              list: [
                {
                  stowagePosition: "Lower Deck",
                  referenceNumber: "REF20210212",
                  marksNumber: "100",
                  unNumber: "HK463",
                  forVIdentification: "IDV20210214",
                  properShippingName: "Maersk",
                  corSRisks: "None",
                  packingGroup: "GRP213",
                  additionalInformation: "GARBAGE CANS",
                  numberAndKindOfPackages: "GARBAGE",
                  massOrVolume: "2 Tonne",
                  ems: "NA",
                },
                {
                  stowagePosition: "Upper Deck",
                  referenceNumber: "REF202102234",
                  marksNumber: "200",
                  unNumber: "BG45665",
                  forVIdentification: "IDV20210214",
                  properShippingName: "Maersk",
                  corSRisks: "None",
                  packingGroup: "GRP213",
                  additionalInformation: "GARBAGE CANS",
                  numberAndKindOfPackages: "GARBAGE",
                  massOrVolume: "2 Tonne",
                  ems: "NA",
                },
              ],
              AddDangerousGoods: {
                stowagePosition: "Lower Deck",
                referenceNumber: "REF20210212",
                marksNumber: "100",
                forVIdentification: "IDV20210214",
                unNumber: "UN234",
                properShippingName: "Maersk",
                corSRisks: "None",
                packingGroup: "GRP213",
                additionalInformation: "GARBAGE CANS",
                numberAndKindOfPackages: "GARBAGE",
                massOrVolume: "2 Tonne",
                ems: "NA",
              },
            },
          },
          others: {
            vaccination: {
              list: [
                {
                  familyName: "John Doe",
                  givenName: "Alex",
                  rankRating: "Rank1",
                  nationality: "Vietnamese",
                  dob: "04/20/1985",
                  signature: "",
                  effects: "Cigars",
                },
              ],
              AddCrew: {
                familyName: "John Doe",
                givenName: "Alex",
                nationality: "Vietnamese",
                dateOfBirth: "04/20/1985",
                placeOfBirth: "Vietnam",
                gender: "Male",
                rankRating: "Rank1",
                typeOfIdentity: "Passport",
                serialNumberOfIdentity: "1234444",
                issuingStateOfIdentity: "VN",
                expiryDateOfIdentity: "01/20/2030",
                portOfEmberkation: "",
                visaNumber: "VISA1234555",
                portOfDisemberkation: "CAMBODIA",
              },
            },
          },
          supportingDocs: {
            docType: "Ship Security Info Doc",
            docRefNo: "SS20201221",
          },
        },
      ],
}

Mock.onGet("/api/process/all").reply((config) => {
  return [200, arrivalDeclarationDB.applications];
});