import Mock from "../mock";

const data = [
  {
    otherLangDesc: null,
    coreMstLocale: null,
    mattId: "ACR",
    mattName: "ACCOUNT ACRA",
    mattDesc: "ACCOUNT ACRA",
    mattDescOth: null,
    mattStatus: "A",
    mattExpiry: "N",
    mattRefNo: "N",
    mattDtCreate: 1543593600000,
    mattUidCreate: "SYS",
    mattDtLupd: 1543593600000,
    mattUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    mattId: "BL",
    mattName: "BILL OF LADING",
    mattDesc: "BILL OF LADING",
    mattDescOth: null,
    mattStatus: "A",
    mattExpiry: "N",
    mattRefNo: "N",
    mattDtCreate: 1543593600000,
    mattUidCreate: "SYS",
    mattDtLupd: 1543593600000,
    mattUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    mattId: "CGA",
    mattName: "CONTAINER GUARANTEE",
    mattDesc: "CONTAINER GUARANTEE",
    mattDescOth: null,
    mattStatus: "A",
    mattExpiry: "N",
    mattRefNo: "N",
    mattDtCreate: 1543593600000,
    mattUidCreate: "SYS",
    mattDtLupd: 1543593600000,
    mattUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    mattId: "CLO",
    mattName: "COMPANY LOGO",
    mattDesc: "COMPANY LOGO",
    mattDescOth: null,
    mattStatus: "A",
    mattExpiry: "N",
    mattRefNo: "N",
    mattDtCreate: 1543593600000,
    mattUidCreate: "SYS",
    mattDtLupd: 1543593600000,
    mattUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    mattId: "CUS",
    mattName: "COMPANY USER SIGNATURES",
    mattDesc: "COMPANY USER SIGNATURES",
    mattDescOth: null,
    mattStatus: "A",
    mattExpiry: "N",
    mattRefNo: "N",
    mattDtCreate: 1543593600000,
    mattUidCreate: "SYS",
    mattDtLupd: 1543593600000,
    mattUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    mattId: "ETI",
    mattName: "E TAX INVOICE",
    mattDesc: "E TAX INVOICE",
    mattDescOth: null,
    mattStatus: "A",
    mattExpiry: "N",
    mattRefNo: "N",
    mattDtCreate: 1543593600000,
    mattUidCreate: "SYS",
    mattDtLupd: 1543593600000,
    mattUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    mattId: "LAS",
    mattName: "LIST OF AUTHORISED SIGN",
    mattDesc: "LIST OF AUTHORISED SIGN",
    mattDescOth: null,
    mattStatus: "A",
    mattExpiry: "N",
    mattRefNo: "N",
    mattDtCreate: 1543593600000,
    mattUidCreate: "SYS",
    mattDtLupd: 1543593600000,
    mattUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    mattId: "LOA",
    mattName: "LETTER OF ASSIGNMENT",
    mattDesc: "LETTER OF ASSIGNMENT",
    mattDescOth: null,
    mattStatus: "A",
    mattExpiry: "N",
    mattRefNo: "N",
    mattDtCreate: 1543593600000,
    mattUidCreate: "SYS",
    mattDtLupd: 1543593600000,
    mattUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    mattId: "LOI",
    mattName: "LETTER OF INDEMNITY",
    mattDesc: "LETTER OF INDEMNITY",
    mattDescOth: null,
    mattStatus: "A",
    mattExpiry: "N",
    mattRefNo: "N",
    mattDtCreate: 1543593600000,
    mattUidCreate: "SYS",
    mattDtLupd: 1543593600000,
    mattUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    mattId: "LOU",
    mattName: "LETTER OF UNDERTAKING",
    mattDesc: "LETTER OF UNDERTAKING",
    mattDescOth: null,
    mattStatus: "A",
    mattExpiry: "N",
    mattRefNo: "N",
    mattDtCreate: 1543593600000,
    mattUidCreate: "SYS",
    mattDtLupd: 1543593600000,
    mattUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    mattId: "OTH",
    mattName: "OTHERS",
    mattDesc: "OTHERS",
    mattDescOth: null,
    mattStatus: "A",
    mattExpiry: "N",
    mattRefNo: "N",
    mattDtCreate: 1543593600000,
    mattUidCreate: "SYS",
    mattDtLupd: 1543593600000,
    mattUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    mattId: "PFI",
    mattName: "PROFORMA INVOICE",
    mattDesc: "PROFORMA INVOICE",
    mattDescOth: null,
    mattStatus: "A",
    mattExpiry: "N",
    mattRefNo: "N",
    mattDtCreate: 1543593600000,
    mattUidCreate: "SYS",
    mattDtLupd: 1543593600000,
    mattUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    mattId: "PHO",
    mattName: "USER PROFILE PICTURE",
    mattDesc: "USER PROFILE PICTURE",
    mattDescOth: null,
    mattStatus: "A",
    mattExpiry: "N",
    mattRefNo: "N",
    mattDtCreate: 1543593600000,
    mattUidCreate: "SYS",
    mattDtLupd: 1543593600000,
    mattUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    mattId: "POA",
    mattName: "POWER OF AUTHORITY",
    mattDesc: "POWER OF AUTHORITY",
    mattDescOth: null,
    mattStatus: "A",
    mattExpiry: "N",
    mattRefNo: "N",
    mattDtCreate: 1543593600000,
    mattUidCreate: "SYS",
    mattDtLupd: 1543593600000,
    mattUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    mattId: "SIG",
    mattName: "USER SIGNATURE PHOTO",
    mattDesc: "USER SIGNATURE",
    mattDescOth: null,
    mattStatus: "A",
    mattExpiry: "N",
    mattRefNo: "N",
    mattDtCreate: 1543593600000,
    mattUidCreate: "SYS",
    mattDtLupd: 1543593600000,
    mattUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    mattId: "SK",
    mattName: "SURAT KUASA",
    mattDesc: "SURAT KUASA",
    mattDescOth: null,
    mattStatus: "A",
    mattExpiry: "N",
    mattRefNo: "N",
    mattDtCreate: 1543593600000,
    mattUidCreate: "SYS",
    mattDtLupd: 1543593600000,
    mattUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    mattId: "STP",
    mattName: "COMPANY STAMP",
    mattDesc: "COMPANY STAMP",
    mattDescOth: null,
    mattStatus: "A",
    mattExpiry: "N",
    mattRefNo: "N",
    mattDtCreate: 1543593600000,
    mattUidCreate: "SYS",
    mattDtLupd: 1543593600000,
    mattUidLupd: "SYS",
  },
];

Mock.onGet("/api/co/master/entity/attType").reply((config) => {
    return [200, data];
  });