import Mock from "../mock";

const data = {
    "iTotalRecords": 10,
    "iTotalDisplayRecords": 10,
    "aaData": [
        {
            "otherLangDesc": null,
            "coreMstLocale": null,
            "blId": "DOBL9617502051239381",
            "blBlNo": "MEDUU2330055",
            "blBlType": "IMPORT",
            "blDoc": "/home/vcc/appAttachments/DOBL9617502051239381/Undangan Presentasi Solusi Platform dari Click Cargo.pdf",
            "blCntNo": "MSDU7600125",
            "blVesselNo": "MSC VIDUCIA",
            "blVoyageNo": "112X",
            "blDtSubmitted": 1683535949000,
            "blAssignedJobNo": "DOJF9620668391695738",
            "blDtAssigned": 1683539131000,
            "blStatus": "C",
            "blDtCreate": 1683535949000,
            "blUidCreate": "ALKNAR_U001",
            "blDtLupd": 1683539131000,
            "blUidLupd": "COMLG_U001",
            "history": null,
            "blFileData": null,
            "blFileName": "Undangan Presentasi Solusi Platform dari Click Cargo.pdf",
            "action": null,
            "cancelled": false,
            "tcoreAccnByBlOwnerAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "ALKNAR",
                "accnStatus": "A",
                "accnName": "Alkindo Naratama",
                "accnNameOth": "Alkindo Naratama",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "23",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "tckMstBlState": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "blstId": "ASSIGNED",
                "blstName": "ASSIGNED",
                "blstDesc": "ASSIGNED",
                "blstDescOth": "ASSIGNED",
                "blstStatus": "A",
                "blstDtCreate": 1601481600000,
                "blstUidCreate": "SYS",
                "blstDtLupd": 1601481600000,
                "blstUidLupd": "SYS"
            },
            "tcoreAccnByBlFfAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "COMLG",
                "accnStatus": "A",
                "accnName": "Combi Logistics",
                "accnNameOth": "Combi Logistics",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "21",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "tcoreAccnByBlCoAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "ALKNAR",
                "accnStatus": "A",
                "accnName": "Alkindo Naratama",
                "accnNameOth": "Alkindo Naratama",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "23",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "tcoreAccnByBlSlAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "MSC",
                "accnStatus": "A",
                "accnName": "Mediterranean Shipping Company SA",
                "accnNameOth": "Mediterranean Shipping Company SA",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "21",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "rejected": false
        },
        {
            "otherLangDesc": null,
            "coreMstLocale": null,
            "blId": "DOBL9274391249401009",
            "blBlNo": "MEDUU2330048",
            "blBlType": "IMPORT",
            "blDoc": "/home/vcc/appAttachments/DOBL9274391249401009/Undangan Presentasi Solusi Platform dari Click Cargo.pdf",
            "blCntNo": "MSDU7600118",
            "blVesselNo": "MSC MIMISHA",
            "blVoyageNo": "118N",
            "blDtSubmitted": 1683192838000,
            "blAssignedJobNo": "DOJF9274476770051528",
            "blDtAssigned": 1683192953000,
            "blStatus": "C",
            "blDtCreate": 1683192838000,
            "blUidCreate": "ALKNAR_U001",
            "blDtLupd": 1683192953000,
            "blUidLupd": "COMLG_U001",
            "history": null,
            "blFileData": null,
            "blFileName": "Undangan Presentasi Solusi Platform dari Click Cargo.pdf",
            "action": null,
            "cancelled": false,
            "tcoreAccnByBlOwnerAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "ALKNAR",
                "accnStatus": "A",
                "accnName": "Alkindo Naratama",
                "accnNameOth": "Alkindo Naratama",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "23",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "tckMstBlState": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "blstId": "ASSIGNED",
                "blstName": "ASSIGNED",
                "blstDesc": "ASSIGNED",
                "blstDescOth": "ASSIGNED",
                "blstStatus": "A",
                "blstDtCreate": 1601481600000,
                "blstUidCreate": "SYS",
                "blstDtLupd": 1601481600000,
                "blstUidLupd": "SYS"
            },
            "tcoreAccnByBlFfAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "COMLG",
                "accnStatus": "A",
                "accnName": "Combi Logistics",
                "accnNameOth": "Combi Logistics",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "21",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "tcoreAccnByBlCoAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "ALKNAR",
                "accnStatus": "A",
                "accnName": "Alkindo Naratama",
                "accnNameOth": "Alkindo Naratama",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "23",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "tcoreAccnByBlSlAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "MSC",
                "accnStatus": "A",
                "accnName": "Mediterranean Shipping Company SA",
                "accnNameOth": "Mediterranean Shipping Company SA",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "21",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "rejected": false
        },
        {
            "otherLangDesc": null,
            "coreMstLocale": null,
            "blId": "DOBL9274186634393047",
            "blBlNo": "MEDUU2330047",
            "blBlType": "IMPORT",
            "blDoc": "/home/vcc/appAttachments/DOBL9274186634393047/Undangan Presentasi Solusi Platform dari Click Cargo.pdf",
            "blCntNo": "MSDU7600117",
            "blVesselNo": "MSC MIMISHA",
            "blVoyageNo": "118N",
            "blDtSubmitted": 1683192633000,
            "blAssignedJobNo": "DOJF9274469242326473",
            "blDtAssigned": 1683192942000,
            "blStatus": "C",
            "blDtCreate": 1683192633000,
            "blUidCreate": "ALKNAR_U001",
            "blDtLupd": 1683192942000,
            "blUidLupd": "COMLG_U001",
            "history": null,
            "blFileData": null,
            "blFileName": "Undangan Presentasi Solusi Platform dari Click Cargo.pdf",
            "action": null,
            "cancelled": false,
            "tcoreAccnByBlOwnerAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "ALKNAR",
                "accnStatus": "A",
                "accnName": "Alkindo Naratama",
                "accnNameOth": "Alkindo Naratama",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "23",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "tckMstBlState": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "blstId": "ASSIGNED",
                "blstName": "ASSIGNED",
                "blstDesc": "ASSIGNED",
                "blstDescOth": "ASSIGNED",
                "blstStatus": "A",
                "blstDtCreate": 1601481600000,
                "blstUidCreate": "SYS",
                "blstDtLupd": 1601481600000,
                "blstUidLupd": "SYS"
            },
            "tcoreAccnByBlFfAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "COMLG",
                "accnStatus": "A",
                "accnName": "Combi Logistics",
                "accnNameOth": "Combi Logistics",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "21",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "tcoreAccnByBlCoAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "ALKNAR",
                "accnStatus": "A",
                "accnName": "Alkindo Naratama",
                "accnNameOth": "Alkindo Naratama",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "23",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "tcoreAccnByBlSlAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "MSC",
                "accnStatus": "A",
                "accnName": "Mediterranean Shipping Company SA",
                "accnNameOth": "Mediterranean Shipping Company SA",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "21",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "rejected": false
        },
        {
            "otherLangDesc": null,
            "coreMstLocale": null,
            "blId": "DOBL9260113952570246",
            "blBlNo": "MEDUU2330046",
            "blBlType": "IMPORT",
            "blDoc": "/home/vcc/appAttachments/DOBL9260113952570246/Undangan Presentasi Solusi Platform dari Click Cargo.pdf",
            "blCntNo": "MSDU7600116",
            "blVesselNo": "MSC Viduca",
            "blVoyageNo": "112N",
            "blDtSubmitted": 1683178561000,
            "blAssignedJobNo": "DOJF9262108172161990",
            "blDtAssigned": 1683180574000,
            "blStatus": "C",
            "blDtCreate": 1683178561000,
            "blUidCreate": "ALKNAR_U001",
            "blDtLupd": 1683180574000,
            "blUidLupd": "COMLG_U001",
            "history": null,
            "blFileData": null,
            "blFileName": "Undangan Presentasi Solusi Platform dari Click Cargo.pdf",
            "action": null,
            "cancelled": false,
            "tcoreAccnByBlOwnerAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "ALKNAR",
                "accnStatus": "A",
                "accnName": "Alkindo Naratama",
                "accnNameOth": "Alkindo Naratama",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "23",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "tckMstBlState": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "blstId": "ASSIGNED",
                "blstName": "ASSIGNED",
                "blstDesc": "ASSIGNED",
                "blstDescOth": "ASSIGNED",
                "blstStatus": "A",
                "blstDtCreate": 1601481600000,
                "blstUidCreate": "SYS",
                "blstDtLupd": 1601481600000,
                "blstUidLupd": "SYS"
            },
            "tcoreAccnByBlFfAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "COMLG",
                "accnStatus": "A",
                "accnName": "Combi Logistics",
                "accnNameOth": "Combi Logistics",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "21",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "tcoreAccnByBlCoAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "ALKNAR",
                "accnStatus": "A",
                "accnName": "Alkindo Naratama",
                "accnNameOth": "Alkindo Naratama",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "23",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "tcoreAccnByBlSlAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "MSC",
                "accnStatus": "A",
                "accnName": "Mediterranean Shipping Company SA",
                "accnNameOth": "Mediterranean Shipping Company SA",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "21",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "rejected": false
        },
        {
            "otherLangDesc": null,
            "coreMstLocale": null,
            "blId": "DOBL9259421184249767",
            "blBlNo": "MEDUU2330045",
            "blBlType": "IMPORT",
            "blDoc": "/home/vcc/appAttachments/DOBL9259421184249767/Undangan Presentasi Solusi Platform dari Click Cargo.pdf",
            "blCntNo": "MSDU7600115",
            "blVesselNo": "MSC Viduca",
            "blVoyageNo": "112N",
            "blDtSubmitted": 1683177868000,
            "blAssignedJobNo": "DOJF9260334598041208",
            "blDtAssigned": 1683179462000,
            "blStatus": "C",
            "blDtCreate": 1683177868000,
            "blUidCreate": "ALKNAR_U001",
            "blDtLupd": 1683179462000,
            "blUidLupd": "COMLG_U001",
            "history": null,
            "blFileData": null,
            "blFileName": "Undangan Presentasi Solusi Platform dari Click Cargo.pdf",
            "action": null,
            "cancelled": false,
            "tcoreAccnByBlOwnerAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "ALKNAR",
                "accnStatus": "A",
                "accnName": "Alkindo Naratama",
                "accnNameOth": "Alkindo Naratama",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "23",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "tckMstBlState": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "blstId": "ASSIGNED",
                "blstName": "ASSIGNED",
                "blstDesc": "ASSIGNED",
                "blstDescOth": "ASSIGNED",
                "blstStatus": "A",
                "blstDtCreate": 1601481600000,
                "blstUidCreate": "SYS",
                "blstDtLupd": 1601481600000,
                "blstUidLupd": "SYS"
            },
            "tcoreAccnByBlFfAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "COMLG",
                "accnStatus": "A",
                "accnName": "Combi Logistics",
                "accnNameOth": "Combi Logistics",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "21",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "tcoreAccnByBlCoAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "ALKNAR",
                "accnStatus": "A",
                "accnName": "Alkindo Naratama",
                "accnNameOth": "Alkindo Naratama",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "23",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "tcoreAccnByBlSlAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "MSC",
                "accnStatus": "A",
                "accnName": "Mediterranean Shipping Company SA",
                "accnNameOth": "Mediterranean Shipping Company SA",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "21",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "rejected": false
        },
        {
            "otherLangDesc": null,
            "coreMstLocale": null,
            "blId": "DOBL9252758349852634",
            "blBlNo": "MEDUU2330044",
            "blBlType": "IMPORT",
            "blDoc": "/home/vcc/appAttachments/DOBL9252758349852634/Undangan Presentasi Solusi Platform dari Click Cargo.pdf",
            "blCntNo": "MSDU7600114",
            "blVesselNo": "MSC Vidinia",
            "blVoyageNo": "112N",
            "blDtSubmitted": 1683171205000,
            "blAssignedJobNo": "DOJF9252926452591149",
            "blDtAssigned": 1683171473000,
            "blStatus": "C",
            "blDtCreate": 1683171205000,
            "blUidCreate": "ALKNAR_U001",
            "blDtLupd": 1683171473000,
            "blUidLupd": "COMLG_U001",
            "history": null,
            "blFileData": null,
            "blFileName": "Undangan Presentasi Solusi Platform dari Click Cargo.pdf",
            "action": null,
            "cancelled": false,
            "tcoreAccnByBlOwnerAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "ALKNAR",
                "accnStatus": "A",
                "accnName": "Alkindo Naratama",
                "accnNameOth": "Alkindo Naratama",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "23",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "tckMstBlState": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "blstId": "ASSIGNED",
                "blstName": "ASSIGNED",
                "blstDesc": "ASSIGNED",
                "blstDescOth": "ASSIGNED",
                "blstStatus": "A",
                "blstDtCreate": 1601481600000,
                "blstUidCreate": "SYS",
                "blstDtLupd": 1601481600000,
                "blstUidLupd": "SYS"
            },
            "tcoreAccnByBlFfAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "COMLG",
                "accnStatus": "A",
                "accnName": "Combi Logistics",
                "accnNameOth": "Combi Logistics",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "21",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "tcoreAccnByBlCoAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "ALKNAR",
                "accnStatus": "A",
                "accnName": "Alkindo Naratama",
                "accnNameOth": "Alkindo Naratama",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "23",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "tcoreAccnByBlSlAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "MSC",
                "accnStatus": "A",
                "accnName": "Mediterranean Shipping Company SA",
                "accnNameOth": "Mediterranean Shipping Company SA",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "21",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "rejected": false
        },
        {
            "otherLangDesc": null,
            "coreMstLocale": null,
            "blId": "DOBL9251774922334771",
            "blBlNo": "MEDUU2330043",
            "blBlType": "IMPORT",
            "blDoc": "/home/vcc/appAttachments/DOBL9251774922334771/SamplePDF.pdf",
            "blCntNo": "MSDU7600113",
            "blVesselNo": "VES283",
            "blVoyageNo": "VOY625",
            "blDtSubmitted": 1683170222000,
            "blAssignedJobNo": "DOJF9273313715606426",
            "blDtAssigned": 1683191775000,
            "blStatus": "C",
            "blDtCreate": 1683170222000,
            "blUidCreate": "ALKNAR_U003",
            "blDtLupd": 1683191775000,
            "blUidLupd": "COMLG_U001",
            "history": null,
            "blFileData": null,
            "blFileName": "SamplePDF.pdf",
            "action": null,
            "cancelled": false,
            "tcoreAccnByBlOwnerAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "ALKNAR",
                "accnStatus": "A",
                "accnName": "Alkindo Naratama",
                "accnNameOth": "Alkindo Naratama",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "23",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "tckMstBlState": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "blstId": "ASSIGNED",
                "blstName": "ASSIGNED",
                "blstDesc": "ASSIGNED",
                "blstDescOth": "ASSIGNED",
                "blstStatus": "A",
                "blstDtCreate": 1601481600000,
                "blstUidCreate": "SYS",
                "blstDtLupd": 1601481600000,
                "blstUidLupd": "SYS"
            },
            "tcoreAccnByBlFfAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "COMLG",
                "accnStatus": "A",
                "accnName": "Combi Logistics",
                "accnNameOth": "Combi Logistics",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "21",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "tcoreAccnByBlCoAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "ALKNAR",
                "accnStatus": "A",
                "accnName": "Alkindo Naratama",
                "accnNameOth": "Alkindo Naratama",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "23",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "tcoreAccnByBlSlAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "MSC",
                "accnStatus": "A",
                "accnName": "Mediterranean Shipping Company SA",
                "accnNameOth": "Mediterranean Shipping Company SA",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "21",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "rejected": false
        },
        {
            "otherLangDesc": null,
            "coreMstLocale": null,
            "blId": "DOBL9249446517513232",
            "blBlNo": "MEDUU2330042",
            "blBlType": "IMPORT",
            "blDoc": "/home/vcc/appAttachments/DOBL9249446517513232/steeltoguedrum_chords.pdf",
            "blCntNo": "MSDU7600112",
            "blVesselNo": "MEDUU2330042",
            "blVoyageNo": "MEDUU2330042",
            "blDtSubmitted": 1683167893000,
            "blAssignedJobNo": "DOJC9249615367271278",
            "blDtAssigned": 1683168118000,
            "blStatus": "C",
            "blDtCreate": 1683167893000,
            "blUidCreate": "ALKNAR_U001",
            "blDtLupd": 1683168118000,
            "blUidLupd": "ALKNAR_U001",
            "history": null,
            "blFileData": null,
            "blFileName": "steeltoguedrum_chords.pdf",
            "action": null,
            "cancelled": false,
            "tcoreAccnByBlOwnerAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "ALKNAR",
                "accnStatus": "A",
                "accnName": "Alkindo Naratama",
                "accnNameOth": "Alkindo Naratama",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "23",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "tckMstBlState": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "blstId": "ASSIGNED",
                "blstName": "ASSIGNED",
                "blstDesc": "ASSIGNED",
                "blstDescOth": "ASSIGNED",
                "blstStatus": "A",
                "blstDtCreate": 1601481600000,
                "blstUidCreate": "SYS",
                "blstDtLupd": 1601481600000,
                "blstUidLupd": "SYS"
            },
            "tcoreAccnByBlFfAccn": null,
            "tcoreAccnByBlCoAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "ALKNAR",
                "accnStatus": "A",
                "accnName": "Alkindo Naratama",
                "accnNameOth": "Alkindo Naratama",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "23",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "tcoreAccnByBlSlAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "MSC",
                "accnStatus": "A",
                "accnName": "Mediterranean Shipping Company SA",
                "accnNameOth": "Mediterranean Shipping Company SA",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "21",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "rejected": false
        },
        {
            "otherLangDesc": null,
            "coreMstLocale": null,
            "blId": "DOBL9248575036479235",
            "blBlNo": "MEDUU2330041",
            "blBlType": "IMPORT",
            "blDoc": "/home/vcc/appAttachments/DOBL9248575036479235/Proforma Invoice-1.pdf",
            "blCntNo": "MSDU7600111",
            "blVesselNo": "MEDUU2330041",
            "blVoyageNo": "MEDUU2330041",
            "blDtSubmitted": 1683167022000,
            "blAssignedJobNo": "DOJC9248878191255967",
            "blDtAssigned": 1683167354000,
            "blStatus": "C",
            "blDtCreate": 1683167022000,
            "blUidCreate": "ALKNAR_U001",
            "blDtLupd": 1683167354000,
            "blUidLupd": "ALKNAR_U001",
            "history": null,
            "blFileData": null,
            "blFileName": "Proforma Invoice-1.pdf",
            "action": null,
            "cancelled": false,
            "tcoreAccnByBlOwnerAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "ALKNAR",
                "accnStatus": "A",
                "accnName": "Alkindo Naratama",
                "accnNameOth": "Alkindo Naratama",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "23",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "tckMstBlState": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "blstId": "ASSIGNED",
                "blstName": "ASSIGNED",
                "blstDesc": "ASSIGNED",
                "blstDescOth": "ASSIGNED",
                "blstStatus": "A",
                "blstDtCreate": 1601481600000,
                "blstUidCreate": "SYS",
                "blstDtLupd": 1601481600000,
                "blstUidLupd": "SYS"
            },
            "tcoreAccnByBlFfAccn": null,
            "tcoreAccnByBlCoAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "ALKNAR",
                "accnStatus": "A",
                "accnName": "Alkindo Naratama",
                "accnNameOth": "Alkindo Naratama",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "23",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "tcoreAccnByBlSlAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "MSC",
                "accnStatus": "A",
                "accnName": "Mediterranean Shipping Company SA",
                "accnNameOth": "Mediterranean Shipping Company SA",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "21",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "rejected": false
        },
        {
            "otherLangDesc": null,
            "coreMstLocale": null,
            "blId": "DOBL9198907867155702",
            "blBlNo": "MEDUU2330092",
            "blBlType": "IMPORT",
            "blDoc": "/home/vcc/appAttachments/DOBL9198907867155702/SamplePDF.pdf",
            "blCntNo": "MSDU7600162",
            "blVesselNo": "VES6736",
            "blVoyageNo": "VOY2314",
            "blDtSubmitted": 1683117355000,
            "blAssignedJobNo": "DOJC9198990023705815",
            "blDtAssigned": 1683117956000,
            "blStatus": "C",
            "blDtCreate": 1683117355000,
            "blUidCreate": "ALKNAR_U003",
            "blDtLupd": 1683117956000,
            "blUidLupd": "ALKNAR_U003",
            "history": null,
            "blFileData": null,
            "blFileName": "SamplePDF.pdf",
            "action": null,
            "cancelled": false,
            "tcoreAccnByBlOwnerAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "ALKNAR",
                "accnStatus": "A",
                "accnName": "Alkindo Naratama",
                "accnNameOth": "Alkindo Naratama",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "23",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "tckMstBlState": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "blstId": "ASSIGNED",
                "blstName": "ASSIGNED",
                "blstDesc": "ASSIGNED",
                "blstDescOth": "ASSIGNED",
                "blstStatus": "A",
                "blstDtCreate": 1601481600000,
                "blstUidCreate": "SYS",
                "blstDtLupd": 1601481600000,
                "blstUidLupd": "SYS"
            },
            "tcoreAccnByBlFfAccn": null,
            "tcoreAccnByBlCoAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "ALKNAR",
                "accnStatus": "A",
                "accnName": "Alkindo Naratama",
                "accnNameOth": "Alkindo Naratama",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "23",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "tcoreAccnByBlSlAccn": {
                "otherLangDesc": null,
                "coreMstLocale": null,
                "accnId": "MSC",
                "accnStatus": "A",
                "accnName": "Mediterranean Shipping Company SA",
                "accnNameOth": "Mediterranean Shipping Company SA",
                "accnCoyRegn": "21",
                "accnPassNid": null,
                "accnNationality": "Indonesia",
                "accnVatFlag": null,
                "accnVatNo": null,
                "accnAddr": null,
                "accnContact": null,
                "accnDtAgree": null,
                "accnDtReg": 1664553600000,
                "accnDtDereg": null,
                "accnDtRereg": null,
                "accnDtSusp": null,
                "accnDtReins": null,
                "accnDtCreate": 1664553600000,
                "accnUidCreate": "SYS",
                "accnDtLupd": 1664553600000,
                "accnUidLupd": "SYS",
                "accnBusinessAct": null,
                "accnOwnerNationality": null,
                "accnOwnerName": null,
                "cityCode": "21",
                "coreLocale": null,
                "TMstAccnType": null
            },
            "rejected": false
        }
    ]
}

Mock.onGet(/api\/ck\/doi\/ckDoBl\/list\/?.*/).reply((config) => {
    return [200, data];
  });
