import Mock from "../mock";

const data = [
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "AD",
    ctyDescription: "ANDORRA",
    ctyStatus: "A",
    ctyDescriptionOth: "安道尔",
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "AE",
    ctyDescription: "UNITED ARAB EMIRATES",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "AF",
    ctyDescription: "AFGHANISTAN",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "AG",
    ctyDescription: "ANTIGUA AND BARBUDA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "AI",
    ctyDescription: "ANGUILLA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "AL",
    ctyDescription: "ALBANIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "AM",
    ctyDescription: "ARMENIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "AN",
    ctyDescription: "NETHERLANDS ANTILLES",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "AO",
    ctyDescription: "ANGOLA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "AQ",
    ctyDescription: "ANTARCTICA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "AR",
    ctyDescription: "ARGENTINA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "AS",
    ctyDescription: "AMERICAN SAMOA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "AT",
    ctyDescription: "AUSTRIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "AU",
    ctyDescription: "AUSTRALIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "AW",
    ctyDescription: "ARUBA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "AZ",
    ctyDescription: "AZERBAIJAN",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "BA",
    ctyDescription: "BOSNIA-HERZEGOVINA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "BB",
    ctyDescription: "BARBADOS",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "BD",
    ctyDescription: "BANGLADESH",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "BE",
    ctyDescription: "BELGIUM",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "BF",
    ctyDescription: "BURKINA FASO",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "BG",
    ctyDescription: "BULGARIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "BH",
    ctyDescription: "BAHRAIN",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "BI",
    ctyDescription: "BURUNDI",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "BJ",
    ctyDescription: "BENIN",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "BM",
    ctyDescription: "BERMUDA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "BN",
    ctyDescription: "BRUNEI DARUSSALAM",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "BO",
    ctyDescription: "BOLIVIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "BR",
    ctyDescription: "BRAZIL",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "BS",
    ctyDescription: "BAHAMAS",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "BT",
    ctyDescription: "BHUTAN",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "BU",
    ctyDescription: "BURUNDI",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "BV",
    ctyDescription: "BOUVET ISLAND",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "BW",
    ctyDescription: "BOTSWANA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "BY",
    ctyDescription: "BELARUS",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "BZ",
    ctyDescription: "BELIZE",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "CA",
    ctyDescription: "CANADA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "CC",
    ctyDescription: "COCOS (KEELING) ISLANDS",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "CD",
    ctyDescription: "DEMOCRATIC REPUBLIC OF THE CONGO",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "CF",
    ctyDescription: "CENTRAL AFRICAN REPUBLIC",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "CG",
    ctyDescription: "CONGO",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "CH",
    ctyDescription: "SWITZERLAND",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "CI",
    ctyDescription: "COTE D'IVOIRE",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "CK",
    ctyDescription: "COOK ISLANDS",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "CL",
    ctyDescription: "CHILE",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "CM",
    ctyDescription: "CAMEROON",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "CN",
    ctyDescription: "CHINA PEO REP OF",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "CO",
    ctyDescription: "COLOMBIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "CR",
    ctyDescription: "COSTA RICA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "CU",
    ctyDescription: "CUBA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "CV",
    ctyDescription: "CAPE VERDE",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "CX",
    ctyDescription: "CHRISTMAS ISLANDS",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "CY",
    ctyDescription: "CYPRUS",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "CZ",
    ctyDescription: "CZECH REPUBLIC",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "DE",
    ctyDescription: "GERMANY, FED REP OF",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "DJ",
    ctyDescription: "DJIBOUTI",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "DK",
    ctyDescription: "DENMARK",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "DM",
    ctyDescription: "DOMINICA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "DO",
    ctyDescription: "DOMINICAN REPUBLIC",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "DZ",
    ctyDescription: "ALGERIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "EA",
    ctyDescription: "EAC",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "EC",
    ctyDescription: "ECUADOR",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "EE",
    ctyDescription: "ESTONIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "EG",
    ctyDescription: "EGYPT",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "EH",
    ctyDescription: "WESTERN SAHARA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "ER",
    ctyDescription: "ERITREA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "ES",
    ctyDescription: "SPAIN",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "ET",
    ctyDescription: "ETHIOPIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "EU",
    ctyDescription: "EURO",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "FI",
    ctyDescription: "FINLAND",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "FJ",
    ctyDescription: "FIJI",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "FK",
    ctyDescription: "FALKLAND ISLANDS (MALVINAS)",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "FM",
    ctyDescription: "MICRONESIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "FO",
    ctyDescription: "FAEROE ISLANDS",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "FR",
    ctyDescription: "FRANCE",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "GA",
    ctyDescription: "GABON",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "GB",
    ctyDescription: "UNITED KINGDOM",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "GD",
    ctyDescription: "GRENADA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "GE",
    ctyDescription: "GEORGIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "GF",
    ctyDescription: "FRENCH GUIANA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "GG",
    ctyDescription: "GUERNSEY",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "GH",
    ctyDescription: "GHANA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "GI",
    ctyDescription: "GIBRALTAR",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "GL",
    ctyDescription: "GREENLAND",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "GM",
    ctyDescription: "GAMBIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "GN",
    ctyDescription: "GUINEA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "GP",
    ctyDescription: "GUADELOUPE",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "GQ",
    ctyDescription: "EQUATORIAL GUINEA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "GR",
    ctyDescription: "GREECE",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "GT",
    ctyDescription: "GUATEMALA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "GU",
    ctyDescription: "GUAM",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "GW",
    ctyDescription: "GUINEA-BISSAU",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "GY",
    ctyDescription: "GUYANA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "HK",
    ctyDescription: "HONG KONG, CHINA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "HM",
    ctyDescription: "HEARD AND MCDONALD ISLAND",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "HN",
    ctyDescription: "HONDURAS",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "HR",
    ctyDescription: "CROATIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "HT",
    ctyDescription: "HAITI",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "HU",
    ctyDescription: "HUNGARY",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "ID",
    ctyDescription: "INDONESIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "IE",
    ctyDescription: "IRELAND",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "IL",
    ctyDescription: "ISRAEL",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "IM",
    ctyDescription: "ISLE OF MAN",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "IN",
    ctyDescription: "INDIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "IO",
    ctyDescription: "BRITISH INDIAN OCEAN TERRITORY",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "IQ",
    ctyDescription: "IRAQ",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "IR",
    ctyDescription: "IRAN (ISLAMIC REP OF)",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "IS",
    ctyDescription: "ICELAND",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "IT",
    ctyDescription: "ITALY",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "JE",
    ctyDescription: "JERSEY",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "JM",
    ctyDescription: "JAMAICA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "JO",
    ctyDescription: "JORDAN",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "JP",
    ctyDescription: "JAPAN",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "KE",
    ctyDescription: "KENYA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "KG",
    ctyDescription: "KYRGYZSTAN",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "KH",
    ctyDescription: "CAMBODIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "KI",
    ctyDescription: "KIRIBATI",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "KM",
    ctyDescription: "COMOROS",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "KN",
    ctyDescription: "SAINT KITTS AND NEVIS",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "KP",
    ctyDescription: "KOREA, DEM PEO REP OF",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "KR",
    ctyDescription: "KOREA, REP OF",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "KW",
    ctyDescription: "KUWAIT",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "KY",
    ctyDescription: "CAYMAN ISLANDS",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "KZ",
    ctyDescription: "KAZAKHSTAN",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "LA",
    ctyDescription: "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "LB",
    ctyDescription: "LEBANON",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "LC",
    ctyDescription: "ST. LUCIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "LI",
    ctyDescription: "LIECHTENSTEIN",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "LK",
    ctyDescription: "SRI LANKA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "LR",
    ctyDescription: "LIBERIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "LS",
    ctyDescription: "LESOTHO",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "LT",
    ctyDescription: "LITHUANIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "LU",
    ctyDescription: "LUXEMBOURG",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "LV",
    ctyDescription: "LATVIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "LY",
    ctyDescription: "LIBYAN ARAB JAMAHIRIYA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "MA",
    ctyDescription: "MOROCCO",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "MC",
    ctyDescription: "MONACO",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "MD",
    ctyDescription: "MOLDOVA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "ME",
    ctyDescription: "MONTENEGRO",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "MG",
    ctyDescription: "MADAGASCAR",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "MH",
    ctyDescription: "MARSHALL ISLANDS",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "MK",
    ctyDescription: "MACEDONIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "ML",
    ctyDescription: "MALI",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "MM",
    ctyDescription: "MYANMAR",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "MN",
    ctyDescription: "MONGOLIAN PEO REP",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "MO",
    ctyDescription: "MACAU",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "MP",
    ctyDescription: "NORTHERN MARIANA ISLANDS",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "MQ",
    ctyDescription: "MARTINIQUE",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "MR",
    ctyDescription: "MAURITANIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "MS",
    ctyDescription: "MONTSERRAT",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "MT",
    ctyDescription: "MALTA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "MU",
    ctyDescription: "Mauritius",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "MV",
    ctyDescription: "MALDIVES REP OF",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "MW",
    ctyDescription: "MALAWI",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "MX",
    ctyDescription: "MEXICO",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "MY",
    ctyDescription: "MALAYSIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "MZ",
    ctyDescription: "MOZAMBIQUE",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "NA",
    ctyDescription: "NAMIBIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "NC",
    ctyDescription: "NEW CALEDONIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "NE",
    ctyDescription: "NIGER",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "NF",
    ctyDescription: "NORFOLK ISLAND",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "NG",
    ctyDescription: "NIGERIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "NI",
    ctyDescription: "NICARAGUA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "NL",
    ctyDescription: "NETHERLANDS",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "NO",
    ctyDescription: "NORWAY",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "NP",
    ctyDescription: "NEPAL",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "NR",
    ctyDescription: "NAURU",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "NU",
    ctyDescription: "NIUE",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "NZ",
    ctyDescription: "NEW ZEALAND",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "OM",
    ctyDescription: "OMAN",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "PA",
    ctyDescription: "PANAMA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "PE",
    ctyDescription: "PERU",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "PF",
    ctyDescription: "FRENCH POLYNESIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "PG",
    ctyDescription: "PAPUA NEW GUINEA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "PH",
    ctyDescription: "PHILIPPINES",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "PK",
    ctyDescription: "PAKISTAN",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "PL",
    ctyDescription: "POLAND",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "PM",
    ctyDescription: "ST PIERRE ET MIQUELON",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "PN",
    ctyDescription: "PITCAIRN",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "PR",
    ctyDescription: "PUERTO RICO",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "PT",
    ctyDescription: "PORTUGAL",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "PW",
    ctyDescription: "PALAU",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "PY",
    ctyDescription: "PARAGUAY",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "QA",
    ctyDescription: "QATAR",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "RE",
    ctyDescription: "REUNION",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "RO",
    ctyDescription: "ROMANIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "RS",
    ctyDescription: "SERBIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "RU",
    ctyDescription: "RUANDA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "RW",
    ctyDescription: "RWANDA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "SA",
    ctyDescription: "SAUDI ARABIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "SB",
    ctyDescription: "SOLOMON ISLANDS",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "SC",
    ctyDescription: "SEYCHELLES",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "SD",
    ctyDescription: "SUDAN",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "SE",
    ctyDescription: "SWEDEN",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "SG",
    ctyDescription: "SINGAPORE",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "SH",
    ctyDescription: "ST. HELENA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "SI",
    ctyDescription: "SLOVENIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "SJ",
    ctyDescription: "SVALBARD AND JAN MAYEN ISLANDS",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "SK",
    ctyDescription: "SLOVAK REPUBLIC",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "SL",
    ctyDescription: "SIERRA LEONE",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "SM",
    ctyDescription: "SAN MARINO",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "SN",
    ctyDescription: "SENEGAL",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "SO",
    ctyDescription: "SOMALIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "SR",
    ctyDescription: "SURINAM",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "SS",
    ctyDescription: "SOUTH SUDAN",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "ST",
    ctyDescription: "SAO TOME AND PRINCIPE",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "SV",
    ctyDescription: "EL SALVADOR",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "SY",
    ctyDescription: "SYRIAN ARAB REP",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "SZ",
    ctyDescription: "SWAZILAND",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "TC",
    ctyDescription: "TURKS AND CAICOS ISLANDS",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "TD",
    ctyDescription: "CHAD",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "TF",
    ctyDescription: "FRENCH SOUTHERN TERRITORIES",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "TG",
    ctyDescription: "TOGO",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "TH",
    ctyDescription: "THAILAND",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "TJ",
    ctyDescription: "TAJIKISTAN",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "TK",
    ctyDescription: "TOKELAU",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "TL",
    ctyDescription: "TIMOR-LESTE",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "TM",
    ctyDescription: "TURKMENISTAN",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "TN",
    ctyDescription: "TUNISIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "TO",
    ctyDescription: "TONGA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "TR",
    ctyDescription: "TURKEY",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "TT",
    ctyDescription: "TRINIDAD AND TOBAGO",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "TV",
    ctyDescription: "TUVALU",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "TW",
    ctyDescription: "TAIWAN",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "TZ",
    ctyDescription: "TANZANIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "UA",
    ctyDescription: "UKRAINE",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "UG",
    ctyDescription: "UGANDA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "UM",
    ctyDescription: "US MINOR OUTLYING ISLANDS",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "US",
    ctyDescription: "UNITED STATES",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "UY",
    ctyDescription: "URUGUAY",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "UZ",
    ctyDescription: "UZBEKISTAN",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "VA",
    ctyDescription: "VATICAN CITY STATE (HOLY SEE)",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "VC",
    ctyDescription: "SAINT VINCENT AND THE GRENADINES",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "VE",
    ctyDescription: "VENEZUELA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "VG",
    ctyDescription: "BRITISH VIRGIN ISLANDS",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "VI",
    ctyDescription: "VIRGIN ISLANDS (US)",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "VN",
    ctyDescription: "VIET NAM",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "VU",
    ctyDescription: "VANUATU",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "WF",
    ctyDescription: "WALLIS AND FUTUNA ISLANDS",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "WS",
    ctyDescription: "SAMOA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "YE",
    ctyDescription: "YEMEN",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "YT",
    ctyDescription: "MAYOTTE",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "ZA",
    ctyDescription: "SOUTH AFRICA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "ZM",
    ctyDescription: "ZAMBIA",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    ctyCode: "ZW",
    ctyDescription: "ZIMBABWE",
    ctyStatus: "A",
    ctyDescriptionOth: null,
    ctyDtCreate: 1543593600000,
    ctyUidCreate: "SYS",
    ctyDtLupd: 1543593600000,
    ctyUidLupd: "SYS",
  },
];

Mock.onGet("/api/co/master/entity/country").reply((config) => {
    return [200, data];
  });