import Mock from "../mock";

const data = [
  {
    otherLangDesc: null,
    coreMstLocale: null,
    uomCode: "KGM",
    uomStatus: "A",
    uomDescription: "KILOGRAM",
    uomDescriptionOth: null,
    uomDtCreate: 1543593600000,
    uomUidCreate: "SYS",
    uomDtLupd: 1543593600000,
    uomUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    uomCode: "MTQ",
    uomStatus: "A",
    uomDescription: "CUBIC METRES",
    uomDescriptionOth: null,
    uomDtCreate: 1543593600000,
    uomUidCreate: "SYS",
    uomDtLupd: 1543593600000,
    uomUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    uomCode: "MTR",
    uomStatus: "A",
    uomDescription: "METRES",
    uomDescriptionOth: null,
    uomDtCreate: 1543593600000,
    uomUidCreate: "SYS",
    uomDtLupd: 1543593600000,
    uomUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    uomCode: "NMB",
    uomStatus: "A",
    uomDescription: "PIECES",
    uomDescriptionOth: null,
    uomDtCreate: 1543593600000,
    uomUidCreate: "SYS",
    uomDtLupd: 1543593600000,
    uomUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    uomCode: "OTH",
    uomStatus: "A",
    uomDescription: "OTHERS",
    uomDescriptionOth: null,
    uomDtCreate: 1543593600000,
    uomUidCreate: "SYS",
    uomDtLupd: 1543593600000,
    uomUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    uomCode: "SET",
    uomStatus: "A",
    uomDescription: "SET",
    uomDescriptionOth: null,
    uomDtCreate: 1543593600000,
    uomUidCreate: "SYS",
    uomDtLupd: 1543593600000,
    uomUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    uomCode: "TNE",
    uomStatus: "A",
    uomDescription: "TONNE",
    uomDescriptionOth: null,
    uomDtCreate: 1543593600000,
    uomUidCreate: "SYS",
    uomDtLupd: 1543593600000,
    uomUidLupd: "SYS",
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    uomCode: "UNT",
    uomStatus: "A",
    uomDescription: "UNIT",
    uomDescriptionOth: null,
    uomDtCreate: 1543564837000,
    uomUidCreate: "SYS",
    uomDtLupd: 1543593600000,
    uomUidLupd: "SYS",
  },
];

Mock.onGet("/api/co/master/entity/uom").reply((config) => {
    return [200, data];
  });