import Mock from "../mock";

const data = {
  token:
    "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBTEtOQVJfVTAwMSIsInVzZXJJZCI6IkFMS05BUl9VMDAxIiwidmNjU2Vzc2lvbmlkIjoiMzIxMjk5NDhBNEMyMThFQUVERUZGODc2M0UyMzlFMzAiLCJleHAiOjE2NzcxMzA5MzA0NDN9.ZshLThPuCxCt8QC6EgW-8laZLmupCAKqT0H1PeivCNXthO8AA98OjPWQRJ3MfYLF0U25S9ilArzedz-M5V7zaA",
  user: {
    password: "DERIAN",
    username: "TO_DERIAN",
    authorities: [{ authority: "TO_OPERATION" }],
    accountNonExpired: true,
    accountNonLocked: true,
    credentialsNonExpired: true,
    enabled: true,
    vccSessionId: "32129948A4C218EAEDEFF8763E239E30",
    exp: 1677130930443,
    groupList: "",
    coreAccn: {
      otherLangDesc: null,
      coreMstLocale: null,
      accnId: "ALKNAR",
      accnStatus: "A",
      accnName: "Alkindo Naratama",
      accnNameOth: "Alkindo Naratama",
      accnCoyRegn: "21",
      accnPassNid: null,
      accnNationality: "Indonesia",
      accnVatFlag: null,
      accnVatNo: null,
      accnAddr: {
        otherLangDesc: null,
        coreMstLocale: null,
        addrLn1: "Kawasan Industri Cimareme",
        addrLn2: "Jalan Industri Cimareme II No. 14",
        addrLn3: "Padalarang, West Bandung - 40553",
        addrPcode: "40553",
        addrCity: "Bandung",
        addrProv: "Bandung",
        addrCtry: null,
      },
      accnContact: {
        otherLangDesc: null,
        coreMstLocale: null,
        contactTel: "62226011220",
        contactFax: "62226011220",
        contactEmail: "kuswara@alkindo.co.id",
      },
      accnDtAgree: null,
      accnDtReg: 1664553600000,
      accnDtDereg: null,
      accnDtRereg: null,
      accnDtSusp: null,
      accnDtReins: null,
      accnDtCreate: 1664553600000,
      accnUidCreate: "SYS",
      accnDtLupd: 1664553600000,
      accnUidLupd: "SYS",
      accnBusinessAct: null,
      accnOwnerNationality: null,
      accnOwnerName: null,
      cityCode: "23",
      coreLocale: null,
      TMstAccnType: {
        otherLangDesc: null,
        coreMstLocale: null,
        atypId: "ACC_TYPE_TO",
        atypDescription: "TRUCK OPERATOR",
        atypDescriptionOth: null,
        atypStatus: "A",
        atypDtCreate: 1664553600000,
        atypUidCreate: "SYS",
        atypDtLupd: 1664553600000,
        atypUidLupd: "SYS",
      },
    },
    name: "Derian Pratama",
    id: "TO_DERIAN",
    role: "TO_OPERATION",
  },
  err: null,
  loginStatus: null,
};

Mock.onGet("/api/co/cac/profile/").reply((config) => {
    return [200, data];
  });