import Mock from "../mock";

export const newRegister =
{
    portalAccn: {
        accnDetails: {
            otherLangDesc: null,
            coreMstLocale: null,
            accnId: null,
            accnStatus: "\u0000",
            accnName: null,
            accnNameOth: null,
            accnCoyRegn: null,
            accnPassNid: null,
            accnNationality: null,
            accnVatFlag: null,
            accnVatNo: null,
            accnAddr: null,
            accnContact: null,
            accnDtAgree: null,
            accnDtReg: null,
            accnDtDereg: null,
            accnDtRereg: null,
            accnDtSusp: null,
            accnDtReins: null,
            accnDtCreate: null,
            accnUidCreate: null,
            accnDtLupd: null,
            accnUidLupd: null,
            accnBusinessAct: null,
            accnOwnerNationality: null,
            accnOwnerName: null,
            cityCode: null,
            coreLocale: null,
            TMstAccnType: null
        },
        accnSignatures: null,
        accnStamp: null,
        accnLogo: null,
        accnDocs: null
    },
    coreUsr: {
        otherLangDesc: null,
        coreMstLocale: null,
        usrUid: null,
        usrStatus: "\u0000",
        usrTypeOnline: null,
        usrTypeMbox: null,
        usrName: null,
        usrPassNid: null,
        usrTitle: null,
        usrDept: null,
        usrDtReg: null,
        usrDtComm: null,
        usrDtDereg: null,
        usrDtRereg: null,
        usrAddr: null,
        usrContact: null,
        usrPwd: null,
        usrPwd1: null,
        usrPwd2: null,
        usrPwd3: null,
        usrPwd4: null,
        usrDtPwdLupd: null,
        usrPwdValidty: null,
        usrPwdForce: null,
        usrLoginInvcnt: 0,
        usrDtLoginok: null,
        usrDtLoginerr: null,
        usrMboxId: null,
        usrMboxMaxcnt: null,
        usrMboxMaxsiz: null,
        usrDurInbx: null,
        usrDurArch: null,
        usrDtCreate: null,
        usrUidCreate: null,
        usrDtLupd: null,
        usrUidLupd: null,
        roles: null,
        tmstUclass: null,
        TCoreAccn: null,
        TCoreRoles: []
    },
    regDocIds: null,
    regDocs: null,
    requestAction: null,
    adminTabEnabled: false,
    supDocsEnabled: false
}

Mock.onGet("api/mockregister/new").reply((config) => {
    return [200, newRegister];
});