import Mock from "../mock";

const data = [
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "011",
      regCtryCd: "BF",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "WESTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "011",
      regCtryCd: "BJ",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "WESTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "011",
      regCtryCd: "CI",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "WESTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "011",
      regCtryCd: "CV",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "WESTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "011",
      regCtryCd: "GH",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "WESTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "011",
      regCtryCd: "GM",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "WESTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "011",
      regCtryCd: "GN",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "WESTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "011",
      regCtryCd: "GW",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "WESTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "011",
      regCtryCd: "LR",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "WESTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "011",
      regCtryCd: "ML",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "WESTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "011",
      regCtryCd: "MR",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "WESTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "011",
      regCtryCd: "NE",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "WESTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "011",
      regCtryCd: "NG",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "WESTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "011",
      regCtryCd: "SH",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "WESTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "011",
      regCtryCd: "SL",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "WESTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "011",
      regCtryCd: "SN",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "WESTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "011",
      regCtryCd: "TG",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "WESTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "014",
      regCtryCd: "BI",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "EASTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "014",
      regCtryCd: "DJ",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "EASTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "014",
      regCtryCd: "ER",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "EASTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "014",
      regCtryCd: "ET",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "EASTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "014",
      regCtryCd: "KE",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "EASTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "014",
      regCtryCd: "KM",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "EASTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "014",
      regCtryCd: "MG",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "EASTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "014",
      regCtryCd: "MU",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "EASTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "014",
      regCtryCd: "MW",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "EASTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "014",
      regCtryCd: "MZ",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "EASTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "014",
      regCtryCd: "RE",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "EASTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "014",
      regCtryCd: "RW",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "EASTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "014",
      regCtryCd: "SC",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "EASTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "014",
      regCtryCd: "SO",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "EASTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "014",
      regCtryCd: "SS",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "EASTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "014",
      regCtryCd: "TZ",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "EASTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "014",
      regCtryCd: "UG",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "EASTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "014",
      regCtryCd: "YT",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "EASTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "014",
      regCtryCd: "ZM",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "EASTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "014",
      regCtryCd: "ZW",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "EASTERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "015",
      regCtryCd: "DZ",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "NORTHERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "015",
      regCtryCd: "EG",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "NORTHERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "015",
      regCtryCd: "EH",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "NORTHERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "015",
      regCtryCd: "LY",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "NORTHERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "015",
      regCtryCd: "MA",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "NORTHERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "015",
      regCtryCd: "SD",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "NORTHERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "015",
      regCtryCd: "TN",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "NORTHERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "017",
      regCtryCd: "AO",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "MIDDLE AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543564780000,
    regUidLupd: "COPORTSA00",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "017",
      regCtryCd: "CD",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "MIDDLE AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "017",
      regCtryCd: "CF",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "MIDDLE AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "017",
      regCtryCd: "CG",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "MIDDLE AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "017",
      regCtryCd: "CM",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "MIDDLE AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "017",
      regCtryCd: "GA",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "MIDDLE AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "017",
      regCtryCd: "GQ",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "MIDDLE AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "017",
      regCtryCd: "ST",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "MIDDLE AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "017",
      regCtryCd: "TD",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "MIDDLE AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "018",
      regCtryCd: "BW",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "SOUTHERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "018",
      regCtryCd: "LS",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "SOUTHERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "018",
      regCtryCd: "NA",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "SOUTHERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "018",
      regCtryCd: "SZ",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "SOUTHERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "002",
      regSubCd: "018",
      regCtryCd: "ZA",
    },
    regName: "AFRICA",
    regNameOth: null,
    regSubName: "SOUTHERN AFRICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "009",
      regSubCd: "053",
      regCtryCd: "AU",
    },
    regName: "OCEANIA",
    regNameOth: null,
    regSubName: "AUSTRALIA AND NEW ZEALAND",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "009",
      regSubCd: "053",
      regCtryCd: "NF",
    },
    regName: "OCEANIA",
    regNameOth: null,
    regSubName: "AUSTRALIA AND NEW ZEALAND",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "009",
      regSubCd: "053",
      regCtryCd: "NZ",
    },
    regName: "OCEANIA",
    regNameOth: null,
    regSubName: "AUSTRALIA AND NEW ZEALAND",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "009",
      regSubCd: "054",
      regCtryCd: "FJ",
    },
    regName: "OCEANIA",
    regNameOth: null,
    regSubName: "MELANESIA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "009",
      regSubCd: "054",
      regCtryCd: "NC",
    },
    regName: "OCEANIA",
    regNameOth: null,
    regSubName: "MELANESIA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "009",
      regSubCd: "054",
      regCtryCd: "PG",
    },
    regName: "OCEANIA",
    regNameOth: null,
    regSubName: "MELANESIA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "009",
      regSubCd: "054",
      regCtryCd: "SB",
    },
    regName: "OCEANIA",
    regNameOth: null,
    regSubName: "MELANESIA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "009",
      regSubCd: "054",
      regCtryCd: "VU",
    },
    regName: "OCEANIA",
    regNameOth: null,
    regSubName: "MELANESIA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "009",
      regSubCd: "057",
      regCtryCd: "FM",
    },
    regName: "OCEANIA",
    regNameOth: null,
    regSubName: "MICRONESIA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "009",
      regSubCd: "057",
      regCtryCd: "GU",
    },
    regName: "OCEANIA",
    regNameOth: null,
    regSubName: "MICRONESIA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "009",
      regSubCd: "057",
      regCtryCd: "KI",
    },
    regName: "OCEANIA",
    regNameOth: null,
    regSubName: "MICRONESIA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "009",
      regSubCd: "057",
      regCtryCd: "MH",
    },
    regName: "OCEANIA",
    regNameOth: null,
    regSubName: "MICRONESIA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "009",
      regSubCd: "057",
      regCtryCd: "MP",
    },
    regName: "OCEANIA",
    regNameOth: null,
    regSubName: "MICRONESIA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "009",
      regSubCd: "057",
      regCtryCd: "NR",
    },
    regName: "OCEANIA",
    regNameOth: null,
    regSubName: "MICRONESIA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "009",
      regSubCd: "057",
      regCtryCd: "PW",
    },
    regName: "OCEANIA",
    regNameOth: null,
    regSubName: "MICRONESIA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "009",
      regSubCd: "061",
      regCtryCd: "AS",
    },
    regName: "OCEANIA",
    regNameOth: null,
    regSubName: "POLYNESIA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "009",
      regSubCd: "061",
      regCtryCd: "CK",
    },
    regName: "OCEANIA",
    regNameOth: null,
    regSubName: "POLYNESIA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "009",
      regSubCd: "061",
      regCtryCd: "NU",
    },
    regName: "OCEANIA",
    regNameOth: null,
    regSubName: "POLYNESIA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "009",
      regSubCd: "061",
      regCtryCd: "PF",
    },
    regName: "OCEANIA",
    regNameOth: null,
    regSubName: "POLYNESIA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "009",
      regSubCd: "061",
      regCtryCd: "PN",
    },
    regName: "OCEANIA",
    regNameOth: null,
    regSubName: "POLYNESIA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "009",
      regSubCd: "061",
      regCtryCd: "TK",
    },
    regName: "OCEANIA",
    regNameOth: null,
    regSubName: "POLYNESIA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "009",
      regSubCd: "061",
      regCtryCd: "TO",
    },
    regName: "OCEANIA",
    regNameOth: null,
    regSubName: "POLYNESIA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "009",
      regSubCd: "061",
      regCtryCd: "TV",
    },
    regName: "OCEANIA",
    regNameOth: null,
    regSubName: "POLYNESIA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "009",
      regSubCd: "061",
      regCtryCd: "WF",
    },
    regName: "OCEANIA",
    regNameOth: null,
    regSubName: "POLYNESIA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "009",
      regSubCd: "061",
      regCtryCd: "WS",
    },
    regName: "OCEANIA",
    regNameOth: null,
    regSubName: "POLYNESIA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "019",
      regSubCd: "005",
      regCtryCd: "AR",
    },
    regName: "AMERICAS",
    regNameOth: null,
    regSubName: "SOUTH AMERICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "019",
      regSubCd: "005",
      regCtryCd: "BO",
    },
    regName: "AMERICAS",
    regNameOth: null,
    regSubName: "SOUTH AMERICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "019",
      regSubCd: "005",
      regCtryCd: "BR",
    },
    regName: "AMERICAS",
    regNameOth: null,
    regSubName: "SOUTH AMERICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "019",
      regSubCd: "005",
      regCtryCd: "CL",
    },
    regName: "AMERICAS",
    regNameOth: null,
    regSubName: "SOUTH AMERICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "019",
      regSubCd: "005",
      regCtryCd: "CO",
    },
    regName: "AMERICAS",
    regNameOth: null,
    regSubName: "SOUTH AMERICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "019",
      regSubCd: "005",
      regCtryCd: "EC",
    },
    regName: "AMERICAS",
    regNameOth: null,
    regSubName: "SOUTH AMERICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "019",
      regSubCd: "005",
      regCtryCd: "FK",
    },
    regName: "AMERICAS",
    regNameOth: null,
    regSubName: "SOUTH AMERICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "019",
      regSubCd: "005",
      regCtryCd: "GF",
    },
    regName: "AMERICAS",
    regNameOth: null,
    regSubName: "SOUTH AMERICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "019",
      regSubCd: "005",
      regCtryCd: "GY",
    },
    regName: "AMERICAS",
    regNameOth: null,
    regSubName: "SOUTH AMERICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "019",
      regSubCd: "005",
      regCtryCd: "PE",
    },
    regName: "AMERICAS",
    regNameOth: null,
    regSubName: "SOUTH AMERICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "019",
      regSubCd: "005",
      regCtryCd: "PY",
    },
    regName: "AMERICAS",
    regNameOth: null,
    regSubName: "SOUTH AMERICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "019",
      regSubCd: "005",
      regCtryCd: "SR",
    },
    regName: "AMERICAS",
    regNameOth: null,
    regSubName: "SOUTH AMERICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "019",
      regSubCd: "005",
      regCtryCd: "UY",
    },
    regName: "AMERICAS",
    regNameOth: null,
    regSubName: "SOUTH AMERICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "019",
      regSubCd: "005",
      regCtryCd: "VE",
    },
    regName: "AMERICAS",
    regNameOth: null,
    regSubName: "SOUTH AMERICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "019",
      regSubCd: "013",
      regCtryCd: "BZ",
    },
    regName: "AMERICAS",
    regNameOth: null,
    regSubName: "CENTRAL AMERICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "019",
      regSubCd: "013",
      regCtryCd: "CR",
    },
    regName: "AMERICAS",
    regNameOth: null,
    regSubName: "CENTRAL AMERICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "019",
      regSubCd: "013",
      regCtryCd: "GT",
    },
    regName: "AMERICAS",
    regNameOth: null,
    regSubName: "CENTRAL AMERICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "019",
      regSubCd: "013",
      regCtryCd: "HN",
    },
    regName: "AMERICAS",
    regNameOth: null,
    regSubName: "CENTRAL AMERICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "019",
      regSubCd: "013",
      regCtryCd: "MX",
    },
    regName: "AMERICAS",
    regNameOth: null,
    regSubName: "CENTRAL AMERICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "019",
      regSubCd: "013",
      regCtryCd: "NI",
    },
    regName: "AMERICAS",
    regNameOth: null,
    regSubName: "CENTRAL AMERICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "019",
      regSubCd: "013",
      regCtryCd: "PA",
    },
    regName: "AMERICAS",
    regNameOth: null,
    regSubName: "CENTRAL AMERICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "019",
      regSubCd: "013",
      regCtryCd: "SV",
    },
    regName: "AMERICAS",
    regNameOth: null,
    regSubName: "CENTRAL AMERICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "019",
      regSubCd: "021",
      regCtryCd: "BM",
    },
    regName: "AMERICAS",
    regNameOth: null,
    regSubName: "NORTHERN AMERICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "019",
      regSubCd: "021",
      regCtryCd: "CA",
    },
    regName: "AMERICAS",
    regNameOth: null,
    regSubName: "NORTHERN AMERICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "019",
      regSubCd: "021",
      regCtryCd: "GL",
    },
    regName: "AMERICAS",
    regNameOth: null,
    regSubName: "NORTHERN AMERICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "019",
      regSubCd: "021",
      regCtryCd: "PM",
    },
    regName: "AMERICAS",
    regNameOth: null,
    regSubName: "NORTHERN AMERICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "019",
      regSubCd: "021",
      regCtryCd: "US",
    },
    regName: "AMERICAS",
    regNameOth: null,
    regSubName: "NORTHERN AMERICA",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "019",
      regSubCd: "029",
      regCtryCd: "AG",
    },
    regName: "AMERICAS",
    regNameOth: null,
    regSubName: "CARIBBEAN",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "019",
      regSubCd: "029",
      regCtryCd: "AI",
    },
    regName: "AMERICAS",
    regNameOth: null,
    regSubName: "CARIBBEAN",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "019",
      regSubCd: "029",
      regCtryCd: "AW",
    },
    regName: "AMERICAS",
    regNameOth: null,
    regSubName: "CARIBBEAN",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
  {
    otherLangDesc: null,
    coreMstLocale: null,
    id: {
      otherLangDesc: null,
      coreMstLocale: null,
      regCd: "019",
      regSubCd: "029",
      regCtryCd: "BB",
    },
    regName: "AMERICAS",
    regNameOth: null,
    regSubName: "CARIBBEAN",
    regSubNameOth: null,
    regStatus: "A",
    regDtCreate: 1543593600000,
    regUidCreate: "SYS",
    regDtLupd: 1543593600000,
    regUidLupd: "SYS",
    tmstCountry: null,
  },
];

Mock.onGet("/api/co/master/entity/region").reply((config) => {
    return [200, data];
  });