
export const sscecCertificateDetails = [
  {
    id: "1",
    sscecId: "SSCC20201213435",
    seq: 1,
    attUid: "sys",
    attSeq: "1",
    attUcrNo: "PEDI202012123",
    attData: "",
    areasInspected: "GALLERY",
    evidenceFound: "Evidence Found",
    sampleResult: "Other Document Name.pdf",
    docReviewd: "Ship Certificate.pdf",
  },
  {
    id: "2",
    sscecId: "SSCC20201213435",
    seq: 2,
    attUid: "sys",
    attSeq: "1",
    attUcrNo: "PEDI202012123",
    attData: "",
    areasInspected: "PANTRY",
    evidenceFound: "evidence  Found",
    sampleResult: "Other Document Name.doc",
    docReviewd: "Ship Certificate.doc",
  },
  {
    id: "3",
    sscecId: "SSCEC20201220123",
    seq: 1,
    attUid: "sys",
    attSeq: "1",
    attUcrNo: "PEDI202012123",
    attData: "",
    areasInspected: "GALLERY",
    evidenceFound: "PEDI202012123",
    sampleResult: "Other Document Name.pdf",
    docReviewd: "Ship Certificate.pdf",
  },
  {
    id: "4",
    sscecId: "SSCEC20201220123",
    seq: 2,
    attUid: "sys",
    attSeq: "1",
    attUcrNo: "PEDI202012123",
    attData: "",
    areasInspected: "PANTRY",
    evidenceFound: "PEDI202012123",
    sampleResult: "Other Document Name.doc",
    docReviewd: "Ship Certificate.doc",
  },
];

export const ssccCertificateDetails = [
  {
    id: "1",
    sscecId: "SSCC20201213435",
    attUid: "sys",
    attSeq: "1",
    attUcrNo: "PEDI202012123",
    attData: "",
    controlMeasures: "Control Measure 1",
    reInspectionDate: "12/03/2021",
    comments: "comments 1",
  },
  {
    id: "2",
    sscecId: "SSCC20201213435",
    attUid: "sys",
    attSeq: "1",
    attUcrNo: "PEDI202012123",
    attData: "",
    controlMeasures: "Control Measure 2",
    reInspectionDate: "12/03/2021",
    comments: "Verified",
  },
  {
    id: "3",
    sscecId: "SSCEC20201220123",
    attUid: "sys",
    attSeq: "1",
    attUcrNo: "PEDI202012123",
    attData: "",
    controlMeasures: "Control Measure 3",
    reInspectionDate: "12/03/2021",
    comments: "comments 3",
  },
  {
    id: "4",
    sscecId: "SSCEC20201220123",
    attUid: "sys",
    attSeq: "1",
    attUcrNo: "PEDI202012123",
    attData: "",
    controlMeasures: "Control Measure 5",
    reInspectionDate: "12/03/2021",
    comments: "comments 5",
  },
];

export const attachmentsDetails = [
  {
    id: "1",
    attUid: "sys",
    attSeq: "1",
    sscecId: "SSCC20201213435",
    attData: "",
    areasInspectedMain: "Food",
    areasInspectedSub: "Source",
    areasInspected: "Gallery",
    evidenceFound: "PEDI202012123",
    sampleResult: "Other Document Name.pdf",
    docReviewed: "File Description",
    controlMeasures: "Control measures 2",
    reInspectionDate: "12/03/2021",
    comments: "comments 2",
  },
  {
    id: "2",
    attUid: "sys",
    attSeq: "1",
    sscecId: "SSCEC20201220123",
    attData: "",
    areasInspectedMain: "Food",
    areasInspectedSub: "Source",
    areasInspected: "Gallery",
    evidenceFound: "PEDI202012123",
    sampleResult: "Other Document Name.pdf",
    docReviewed: "File Description",
    controlMeasures: "control measures 1",
    reInspectionDate: "12/03/2021",
    comments: "comments 1",
  },
  {
    id: "3",
    attUid: "sys",
    attSeq: "6",
    sscecId: "SSCEC20201220123",
    attData: "",
    areasInspectedMain: "Water",
    areasInspectedSub: "Storage",
    areasInspected: "Gallery",
    evidenceFound: "PEDI202012123",
    sampleResult: "Other Document Name.pdf",
    docReviewed: "File Description",
    controlMeasures: "Control measures 2",
    reInspectionDate: "12/03/2021",
    comments: "Verified",
  },
];
