//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.21 at 09:24:47 AM SGT 
//


package com.dsv.edi.xml.DSV_StatusMessage_v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.dsv.edi.xml.DSV_StatusMessage_v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DSVStatusMessage_QNAME = new QName("http://edi.dsv.com/XML/DSV_StatusMessage_v1.xsd", "DSV_StatusMessage");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dsv.edi.xml.DSV_StatusMessage_v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DangerousGoods }
     * 
     */
    public DangerousGoods createDangerousGoods() {
        return new DangerousGoods();
    }

    /**
     * Create an instance of {@link DSVStatusMessage }
     * 
     */
    public DSVStatusMessage createDSVStatusMessage() {
        return new DSVStatusMessage();
    }

    /**
     * Create an instance of {@link ShipmentId }
     * 
     */
    public ShipmentId createShipmentId() {
        return new ShipmentId();
    }

    /**
     * Create an instance of {@link DimensionsList }
     * 
     */
    public DimensionsList createDimensionsList() {
        return new DimensionsList();
    }

    /**
     * Create an instance of {@link ControlTotalList }
     * 
     */
    public ControlTotalList createControlTotalList() {
        return new ControlTotalList();
    }

    /**
     * Create an instance of {@link TransportServiceList }
     * 
     */
    public TransportServiceList createTransportServiceList() {
        return new TransportServiceList();
    }

    /**
     * Create an instance of {@link HandlingInstructions }
     * 
     */
    public HandlingInstructions createHandlingInstructions() {
        return new HandlingInstructions();
    }

    /**
     * Create an instance of {@link ShipmentStatus }
     * 
     */
    public ShipmentStatus createShipmentStatus() {
        return new ShipmentStatus();
    }

    /**
     * Create an instance of {@link EquipmentUnit }
     * 
     */
    public EquipmentUnit createEquipmentUnit() {
        return new EquipmentUnit();
    }

    /**
     * Create an instance of {@link GoodsItemList }
     * 
     */
    public GoodsItemList createGoodsItemList() {
        return new GoodsItemList();
    }

    /**
     * Create an instance of {@link MonetaryAmountList }
     * 
     */
    public MonetaryAmountList createMonetaryAmountList() {
        return new MonetaryAmountList();
    }

    /**
     * Create an instance of {@link LocationList }
     * 
     */
    public LocationList createLocationList() {
        return new LocationList();
    }

    /**
     * Create an instance of {@link ReferenceGroup }
     * 
     */
    public ReferenceGroup createReferenceGroup() {
        return new ReferenceGroup();
    }

    /**
     * Create an instance of {@link EquipmentUnitsList }
     * 
     */
    public EquipmentUnitsList createEquipmentUnitsList() {
        return new EquipmentUnitsList();
    }

    /**
     * Create an instance of {@link DangerousGoodsDetailList }
     * 
     */
    public DangerousGoodsDetailList createDangerousGoodsDetailList() {
        return new DangerousGoodsDetailList();
    }

    /**
     * Create an instance of {@link PackageIds }
     * 
     */
    public PackageIds createPackageIds() {
        return new PackageIds();
    }

    /**
     * Create an instance of {@link GoodsItem }
     * 
     */
    public GoodsItem createGoodsItem() {
        return new GoodsItem();
    }

    /**
     * Create an instance of {@link StatusDetailslist }
     * 
     */
    public StatusDetailslist createStatusDetailslist() {
        return new StatusDetailslist();
    }

    /**
     * Create an instance of {@link TransportStageList }
     * 
     */
    public TransportStageList createTransportStageList() {
        return new TransportStageList();
    }

    /**
     * Create an instance of {@link SealList }
     * 
     */
    public SealList createSealList() {
        return new SealList();
    }

    /**
     * Create an instance of {@link Shipment }
     * 
     */
    public Shipment createShipment() {
        return new Shipment();
    }

    /**
     * Create an instance of {@link DangerousGoodsDetail }
     * 
     */
    public DangerousGoodsDetail createDangerousGoodsDetail() {
        return new DangerousGoodsDetail();
    }

    /**
     * Create an instance of {@link PartiesList }
     * 
     */
    public PartiesList createPartiesList() {
        return new PartiesList();
    }

    /**
     * Create an instance of {@link TransportStage }
     * 
     */
    public TransportStage createTransportStage() {
        return new TransportStage();
    }

    /**
     * Create an instance of {@link ShipmentList }
     * 
     */
    public ShipmentList createShipmentList() {
        return new ShipmentList();
    }

    /**
     * Create an instance of {@link DateList }
     * 
     */
    public DateList createDateList() {
        return new DateList();
    }

    /**
     * Create an instance of {@link PartyList }
     * 
     */
    public PartyList createPartyList() {
        return new PartyList();
    }

    /**
     * Create an instance of {@link ReferenceGroupList }
     * 
     */
    public ReferenceGroupList createReferenceGroupList() {
        return new ReferenceGroupList();
    }

    /**
     * Create an instance of {@link FreeTextList }
     * 
     */
    public FreeTextList createFreeTextList() {
        return new FreeTextList();
    }

    /**
     * Create an instance of {@link ProductIdsList }
     * 
     */
    public ProductIdsList createProductIdsList() {
        return new ProductIdsList();
    }

    /**
     * Create an instance of {@link MeasurementsList }
     * 
     */
    public MeasurementsList createMeasurementsList() {
        return new MeasurementsList();
    }

    /**
     * Create an instance of {@link Measurement }
     * 
     */
    public Measurement createMeasurement() {
        return new Measurement();
    }

    /**
     * Create an instance of {@link AllowanceOrCharge }
     * 
     */
    public AllowanceOrCharge createAllowanceOrCharge() {
        return new AllowanceOrCharge();
    }

    /**
     * Create an instance of {@link PaymentInstruction }
     * 
     */
    public PaymentInstruction createPaymentInstruction() {
        return new PaymentInstruction();
    }

    /**
     * Create an instance of {@link ProductId }
     * 
     */
    public ProductId createProductId() {
        return new ProductId();
    }

    /**
     * Create an instance of {@link Tax }
     * 
     */
    public Tax createTax() {
        return new Tax();
    }

    /**
     * Create an instance of {@link PaymentTerms }
     * 
     */
    public PaymentTerms createPaymentTerms() {
        return new PaymentTerms();
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link Marks }
     * 
     */
    public Marks createMarks() {
        return new Marks();
    }

    /**
     * Create an instance of {@link EquipmentType }
     * 
     */
    public EquipmentType createEquipmentType() {
        return new EquipmentType();
    }

    /**
     * Create an instance of {@link ItemDescription }
     * 
     */
    public ItemDescription createItemDescription() {
        return new ItemDescription();
    }

    /**
     * Create an instance of {@link GovernmentalRequirements }
     * 
     */
    public GovernmentalRequirements createGovernmentalRequirements() {
        return new GovernmentalRequirements();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link HandlingInstruction }
     * 
     */
    public HandlingInstruction createHandlingInstruction() {
        return new HandlingInstruction();
    }

    /**
     * Create an instance of {@link Currency }
     * 
     */
    public Currency createCurrency() {
        return new Currency();
    }

    /**
     * Create an instance of {@link FinancialInstitution }
     * 
     */
    public FinancialInstitution createFinancialInstitution() {
        return new FinancialInstitution();
    }

    /**
     * Create an instance of {@link Stage }
     * 
     */
    public Stage createStage() {
        return new Stage();
    }

    /**
     * Create an instance of {@link TransportMovement }
     * 
     */
    public TransportMovement createTransportMovement() {
        return new TransportMovement();
    }

    /**
     * Create an instance of {@link LocationIdentification }
     * 
     */
    public LocationIdentification createLocationIdentification() {
        return new LocationIdentification();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link GoodsIdentity }
     * 
     */
    public GoodsIdentity createGoodsIdentity() {
        return new GoodsIdentity();
    }

    /**
     * Create an instance of {@link MonetaryAmount }
     * 
     */
    public MonetaryAmount createMonetaryAmount() {
        return new MonetaryAmount();
    }

    /**
     * Create an instance of {@link InvoiceLine }
     * 
     */
    public InvoiceLine createInvoiceLine() {
        return new InvoiceLine();
    }

    /**
     * Create an instance of {@link Milestone }
     * 
     */
    public Milestone createMilestone() {
        return new Milestone();
    }

    /**
     * Create an instance of {@link Reference }
     * 
     */
    public Reference createReference() {
        return new Reference();
    }

    /**
     * Create an instance of {@link Charge }
     * 
     */
    public Charge createCharge() {
        return new Charge();
    }

    /**
     * Create an instance of {@link Terms }
     * 
     */
    public Terms createTerms() {
        return new Terms();
    }

    /**
     * Create an instance of {@link Quantity }
     * 
     */
    public Quantity createQuantity() {
        return new Quantity();
    }

    /**
     * Create an instance of {@link Dimension }
     * 
     */
    public Dimension createDimension() {
        return new Dimension();
    }

    /**
     * Create an instance of {@link GoodsPlacementIds }
     * 
     */
    public GoodsPlacementIds createGoodsPlacementIds() {
        return new GoodsPlacementIds();
    }

    /**
     * Create an instance of {@link RangeDetails }
     * 
     */
    public RangeDetails createRangeDetails() {
        return new RangeDetails();
    }

    /**
     * Create an instance of {@link Date }
     * 
     */
    public Date createDate() {
        return new Date();
    }

    /**
     * Create an instance of {@link Contact }
     * 
     */
    public Contact createContact() {
        return new Contact();
    }

    /**
     * Create an instance of {@link FreeText }
     * 
     */
    public FreeText createFreeText() {
        return new FreeText();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link TransportService }
     * 
     */
    public TransportService createTransportService() {
        return new TransportService();
    }

    /**
     * Create an instance of {@link ControlTotal }
     * 
     */
    public ControlTotal createControlTotal() {
        return new ControlTotal();
    }

    /**
     * Create an instance of {@link PackageId }
     * 
     */
    public PackageId createPackageId() {
        return new PackageId();
    }

    /**
     * Create an instance of {@link Seal }
     * 
     */
    public Seal createSeal() {
        return new Seal();
    }

    /**
     * Create an instance of {@link Package }
     * 
     */
    public Package createPackage() {
        return new Package();
    }

    /**
     * Create an instance of {@link PartyDetails }
     * 
     */
    public PartyDetails createPartyDetails() {
        return new PartyDetails();
    }

    /**
     * Create an instance of {@link TemperatureControl }
     * 
     */
    public TemperatureControl createTemperatureControl() {
        return new TemperatureControl();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link DangerousGoods.FlashPointTemperature }
     * 
     */
    public DangerousGoods.FlashPointTemperature createDangerousGoodsFlashPointTemperature() {
        return new DangerousGoods.FlashPointTemperature();
    }

    /**
     * Create an instance of {@link DangerousGoods.Labels }
     * 
     */
    public DangerousGoods.Labels createDangerousGoodsLabels() {
        return new DangerousGoods.Labels();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DSVStatusMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://edi.dsv.com/XML/DSV_StatusMessage_v1.xsd", name = "DSV_StatusMessage")
    public JAXBElement<DSVStatusMessage> createDSVStatusMessage(DSVStatusMessage value) {
        return new JAXBElement<DSVStatusMessage>(_DSVStatusMessage_QNAME, DSVStatusMessage.class, null, value);
    }

}
