//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.21 at 09:24:47 AM SGT 
//


package com.dsv.edi.xml.DSV_StatusMessage_v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Shipment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Shipment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ShipmentId" type="{http://edi.dsv.com/XML/ShipmentStatus_v1.xsd}ShipmentId"/>
 *         &lt;element name="ControlTotals" type="{http://edi.dsv.com/XML/ShipmentStatus_v1.xsd}ControlTotalList" minOccurs="0"/>
 *         &lt;element name="StatusDetails" type="{http://edi.dsv.com/XML/ShipmentStatus_v1.xsd}StatusDetailslist" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Shipment", namespace = "http://edi.dsv.com/XML/ShipmentStatus_v1.xsd", propOrder = {
    "shipmentId",
    "controlTotals",
    "statusDetails"
})
public class Shipment {

    @XmlElement(name = "ShipmentId", required = true)
    protected ShipmentId shipmentId;
    @XmlElement(name = "ControlTotals")
    protected ControlTotalList controlTotals;
    @XmlElement(name = "StatusDetails")
    protected List<StatusDetailslist> statusDetails;

    /**
     * Gets the value of the shipmentId property.
     * 
     * @return
     *     possible object is
     *     {@link ShipmentId }
     *     
     */
    public ShipmentId getShipmentId() {
        return shipmentId;
    }

    /**
     * Sets the value of the shipmentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipmentId }
     *     
     */
    public void setShipmentId(ShipmentId value) {
        this.shipmentId = value;
    }

    /**
     * Gets the value of the controlTotals property.
     * 
     * @return
     *     possible object is
     *     {@link ControlTotalList }
     *     
     */
    public ControlTotalList getControlTotals() {
        return controlTotals;
    }

    /**
     * Sets the value of the controlTotals property.
     * 
     * @param value
     *     allowed object is
     *     {@link ControlTotalList }
     *     
     */
    public void setControlTotals(ControlTotalList value) {
        this.controlTotals = value;
    }

    /**
     * Gets the value of the statusDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the statusDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStatusDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StatusDetailslist }
     * 
     * 
     */
    public List<StatusDetailslist> getStatusDetails() {
        if (statusDetails == null) {
            statusDetails = new ArrayList<StatusDetailslist>();
        }
        return this.statusDetails;
    }

}
