//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.21 at 09:24:47 AM SGT 
//


package com.dsv.edi.xml.DSV_StatusMessage_v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ShipmentStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ShipmentStatus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Dates" type="{http://edi.dsv.com/XML/ShipmentStatus_v1.xsd}DateList" minOccurs="0"/>
 *         &lt;element name="TransportServices" type="{http://edi.dsv.com/XML/ShipmentStatus_v1.xsd}TransportServiceList" minOccurs="0"/>
 *         &lt;element name="Parties" type="{http://edi.dsv.com/XML/ShipmentStatus_v1.xsd}PartiesList" minOccurs="0"/>
 *         &lt;element name="References" type="{http://edi.dsv.com/XML/ShipmentStatus_v1.xsd}ReferenceGroupList" minOccurs="0"/>
 *         &lt;element name="Locations" type="{http://edi.dsv.com/XML/ShipmentStatus_v1.xsd}LocationList" minOccurs="0"/>
 *         &lt;element name="EquipmentUnits" type="{http://edi.dsv.com/XML/ShipmentStatus_v1.xsd}EquipmentUnitsList" minOccurs="0"/>
 *         &lt;element name="Shipments" type="{http://edi.dsv.com/XML/ShipmentStatus_v1.xsd}ShipmentList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShipmentStatus", namespace = "http://edi.dsv.com/XML/ShipmentStatus_v1.xsd", propOrder = {
    "dates",
    "transportServices",
    "parties",
    "references",
    "locations",
    "equipmentUnits",
    "shipments"
})
public class ShipmentStatus {

    @XmlElement(name = "Dates")
    protected DateList dates;
    @XmlElement(name = "TransportServices")
    protected TransportServiceList transportServices;
    @XmlElement(name = "Parties")
    protected PartiesList parties;
    @XmlElement(name = "References")
    protected ReferenceGroupList references;
    @XmlElement(name = "Locations")
    protected LocationList locations;
    @XmlElement(name = "EquipmentUnits")
    protected EquipmentUnitsList equipmentUnits;
    @XmlElement(name = "Shipments")
    protected ShipmentList shipments;

    /**
     * Gets the value of the dates property.
     * 
     * @return
     *     possible object is
     *     {@link DateList }
     *     
     */
    public DateList getDates() {
        return dates;
    }

    /**
     * Sets the value of the dates property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateList }
     *     
     */
    public void setDates(DateList value) {
        this.dates = value;
    }

    /**
     * Gets the value of the transportServices property.
     * 
     * @return
     *     possible object is
     *     {@link TransportServiceList }
     *     
     */
    public TransportServiceList getTransportServices() {
        return transportServices;
    }

    /**
     * Sets the value of the transportServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransportServiceList }
     *     
     */
    public void setTransportServices(TransportServiceList value) {
        this.transportServices = value;
    }

    /**
     * Gets the value of the parties property.
     * 
     * @return
     *     possible object is
     *     {@link PartiesList }
     *     
     */
    public PartiesList getParties() {
        return parties;
    }

    /**
     * Sets the value of the parties property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartiesList }
     *     
     */
    public void setParties(PartiesList value) {
        this.parties = value;
    }

    /**
     * Gets the value of the references property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceGroupList }
     *     
     */
    public ReferenceGroupList getReferences() {
        return references;
    }

    /**
     * Sets the value of the references property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceGroupList }
     *     
     */
    public void setReferences(ReferenceGroupList value) {
        this.references = value;
    }

    /**
     * Gets the value of the locations property.
     * 
     * @return
     *     possible object is
     *     {@link LocationList }
     *     
     */
    public LocationList getLocations() {
        return locations;
    }

    /**
     * Sets the value of the locations property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationList }
     *     
     */
    public void setLocations(LocationList value) {
        this.locations = value;
    }

    /**
     * Gets the value of the equipmentUnits property.
     * 
     * @return
     *     possible object is
     *     {@link EquipmentUnitsList }
     *     
     */
    public EquipmentUnitsList getEquipmentUnits() {
        return equipmentUnits;
    }

    /**
     * Sets the value of the equipmentUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link EquipmentUnitsList }
     *     
     */
    public void setEquipmentUnits(EquipmentUnitsList value) {
        this.equipmentUnits = value;
    }

    /**
     * Gets the value of the shipments property.
     * 
     * @return
     *     possible object is
     *     {@link ShipmentList }
     *     
     */
    public ShipmentList getShipments() {
        return shipments;
    }

    /**
     * Sets the value of the shipments property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipmentList }
     *     
     */
    public void setShipments(ShipmentList value) {
        this.shipments = value;
    }

}
