//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.21 at 09:24:47 AM SGT 
//


package com.dsv.edi.xml.DSV_StatusMessage_v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StatusDetailslist complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StatusDetailslist">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Status" type="{http://edi.dsv.com/XML/SharedElements_v1.xsd}Status" minOccurs="0"/>
 *         &lt;element name="References" type="{http://edi.dsv.com/XML/ShipmentStatus_v1.xsd}ReferenceGroupList" minOccurs="0"/>
 *         &lt;element name="Dates" type="{http://edi.dsv.com/XML/ShipmentStatus_v1.xsd}DateList" minOccurs="0"/>
 *         &lt;element name="FreeTextData" type="{http://edi.dsv.com/XML/ShipmentStatus_v1.xsd}FreeTextList" minOccurs="0"/>
 *         &lt;element name="Parties" type="{http://edi.dsv.com/XML/ShipmentStatus_v1.xsd}PartiesList" minOccurs="0"/>
 *         &lt;element name="Locations" type="{http://edi.dsv.com/XML/ShipmentStatus_v1.xsd}LocationList" minOccurs="0"/>
 *         &lt;element name="TransportStages" type="{http://edi.dsv.com/XML/ShipmentStatus_v1.xsd}TransportStageList" minOccurs="0"/>
 *         &lt;element name="GoodsItems" type="{http://edi.dsv.com/XML/ShipmentStatus_v1.xsd}GoodsItemList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StatusDetailslist", namespace = "http://edi.dsv.com/XML/ShipmentStatus_v1.xsd", propOrder = {
    "status",
    "references",
    "dates",
    "freeTextData",
    "parties",
    "locations",
    "transportStages",
    "goodsItems"
})
public class StatusDetailslist {

    @XmlElement(name = "Status")
    protected Status status;
    @XmlElement(name = "References")
    protected ReferenceGroupList references;
    @XmlElement(name = "Dates")
    protected DateList dates;
    @XmlElement(name = "FreeTextData")
    protected FreeTextList freeTextData;
    @XmlElement(name = "Parties")
    protected PartiesList parties;
    @XmlElement(name = "Locations")
    protected LocationList locations;
    @XmlElement(name = "TransportStages")
    protected TransportStageList transportStages;
    @XmlElement(name = "GoodsItems")
    protected GoodsItemList goodsItems;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Status }
     *     
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Status }
     *     
     */
    public void setStatus(Status value) {
        this.status = value;
    }

    /**
     * Gets the value of the references property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceGroupList }
     *     
     */
    public ReferenceGroupList getReferences() {
        return references;
    }

    /**
     * Sets the value of the references property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceGroupList }
     *     
     */
    public void setReferences(ReferenceGroupList value) {
        this.references = value;
    }

    /**
     * Gets the value of the dates property.
     * 
     * @return
     *     possible object is
     *     {@link DateList }
     *     
     */
    public DateList getDates() {
        return dates;
    }

    /**
     * Sets the value of the dates property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateList }
     *     
     */
    public void setDates(DateList value) {
        this.dates = value;
    }

    /**
     * Gets the value of the freeTextData property.
     * 
     * @return
     *     possible object is
     *     {@link FreeTextList }
     *     
     */
    public FreeTextList getFreeTextData() {
        return freeTextData;
    }

    /**
     * Sets the value of the freeTextData property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreeTextList }
     *     
     */
    public void setFreeTextData(FreeTextList value) {
        this.freeTextData = value;
    }

    /**
     * Gets the value of the parties property.
     * 
     * @return
     *     possible object is
     *     {@link PartiesList }
     *     
     */
    public PartiesList getParties() {
        return parties;
    }

    /**
     * Sets the value of the parties property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartiesList }
     *     
     */
    public void setParties(PartiesList value) {
        this.parties = value;
    }

    /**
     * Gets the value of the locations property.
     * 
     * @return
     *     possible object is
     *     {@link LocationList }
     *     
     */
    public LocationList getLocations() {
        return locations;
    }

    /**
     * Sets the value of the locations property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationList }
     *     
     */
    public void setLocations(LocationList value) {
        this.locations = value;
    }

    /**
     * Gets the value of the transportStages property.
     * 
     * @return
     *     possible object is
     *     {@link TransportStageList }
     *     
     */
    public TransportStageList getTransportStages() {
        return transportStages;
    }

    /**
     * Sets the value of the transportStages property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransportStageList }
     *     
     */
    public void setTransportStages(TransportStageList value) {
        this.transportStages = value;
    }

    /**
     * Gets the value of the goodsItems property.
     * 
     * @return
     *     possible object is
     *     {@link GoodsItemList }
     *     
     */
    public GoodsItemList getGoodsItems() {
        return goodsItems;
    }

    /**
     * Sets the value of the goodsItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link GoodsItemList }
     *     
     */
    public void setGoodsItems(GoodsItemList value) {
        this.goodsItems = value;
    }

}
